### ISSUE TITLE
Add `typicode/hotel` project

### ISSUE THREAD

**Issue by typicode** [michaelrambeau/bestofjs#10]
https://github.com/typicode/hotel
Makes it easy to access local dev servers

**Comment by michaelrambeau** [comment]
Hello again, I am adding `hotel` project, too.
About tagging the project, can you see something more appropriate than `Server CLI` => http://bestof.js.org/tags/cli ?

**Comment by michaelrambeau** [comment]
Hello @typicode ,
"hotel" project is online too.
Just one question: why did you put the gif URL in the project `description` rather than using the `URL` field ? So far I have never seen URLs used in descriptions and because of that it's not rendered correctly.

![image](https://cloud.githubusercontent.com/assets/5546996/19206347/2bee877a-8d23-11e6-92f5-1e22c73d4c30.png)

Thank you for your support!

**Comment by michaelrambeau** [comment]
Closing for now, even if I did not have the answer to my question 😢 .

**Comment by typicode** [comment]
Hi,

Sincerely sorrry, it's just that, sometimes, I don't have time to reply right away, so I postpone and can forget to do it later :/... so let me fix that now! :)

> About tagging the project, can you see something more appropriate than Server CLI

Hard question, and I don't really know myself. It can be seen as a process manager, dev tool, etc...

On JavaScripting they have this https://www.javascripting.com/development-aids/. Maybe you can take inspiration from it.

> why did you put the gif URL in the project description rather than using the URL field ? 

I've removed it but since hotel can be complicated to explain with just words, I wanted to make it easier for people sharing it on social networks to include the GIF if they wanted too.

**Comment by michaelrambeau** [comment]
Hello @typicode , no problem at all, thank you for your answer.
I may miss something but why not put the GIF url in the repo `Website` field ?

That field:

![image](https://cloud.githubusercontent.com/assets/5546996/19824477/ce0df4c2-9daa-11e6-8cd0-a412f470c7eb.png)

**Comment by typicode** [comment]
You're right :). Actually, I chose to put it in `description` because it wasn't really a website and also when putting in `website` it doesn't appear in `<title/>`, so if, for example, you use a social sharing extension the link to the GIF won't be picked.
