### ISSUE TITLE
Encore platform

### ISSUE THREAD

**Issue by skiabox** [michaelrambeau/bestofjs#1002]
**Please briefly describe the project you'd like to add to _Best of JS_?**
TypeScript backend framework for robust and type-safe applications

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/encoredev/encore

**Before submitting the request to add a new project, please check the following points:**

- [ x] The project is related to the web platform or Node.js
- [ x] The source code is on GitHub and project has more than 100 stars on GitHub
- [ x] The project has thorough documentation in English
- [ x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Backend-as-a-Service

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @skiabox thank you for the suggestion, `Encore` is available on _Best of JS_:

https://bestofjs.org/projects/encore

It seems to be a very powerful solution to build applications with "end to end type safety", do you know why we have not heard of it before?
