### ISSUE TITLE
I have more interesting projects

### ISSUE THREAD

**Issue by jcubic** [michaelrambeau/bestofjs#1003]
It seems that one of my project is in bestofjs, got notification from Ahrefs about link to my website:

https://bestofjs.org/projects/tagger

I have few more interesting projects:

* [Sysend](https://github.com/jcubic/sysend.js/) - for sending messages between open tabs/windows. Searched all the tags didn't find any that would fit. Proposal: communication (into same category you can fit [Comlink](https://bestofjs.org/projects/comlink) and [Socket.io](https://bestofjs.org/projects/socketio))
* [wayne](https://github.com/jcubic/wayne) service worker library that have similar API as express.js and allow creating pure in browser HTTP endpoints. (TAG: [Service Worker](https://bestofjs.org/projects?tags=serviceworker) and [routing](https://bestofjs.org/projects?tags=routing))
* [jQuery Terminal](https://github.com/jcubic/jquery.terminal) a library (or more like a framework) that allow to add terminal interface to websites. (TAG: [Plugin / form widget](https://bestofjs.org/projects?tags=plugin))

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**Comment by michaelrambeau** [comment]
Hello Jakub @jcubic thank you for having noticed, I added `Tagger` a few days ago indeed 😄 

OK I will add these 3 projects, stay tuned!

**Comment by michaelrambeau** [comment]
Hello Jakub @jcubic not one, not two but three projects from you on today's home page! 

Please check, thank you in advance for your feedback.

![image](https://github.com/user-attachments/assets/893f3a7e-66eb-44a7-99f9-8a8b78ba1680)

You can search for `jcubic` too 😄 

![image](https://github.com/user-attachments/assets/89439ea7-6d56-4fe7-800d-0963ceb641af)
`

**Comment by jcubic** [comment]
Awesome, thanks.

One note that some of those project get more hits from CDN. This is especially true for Wayne, from the beginning the README that is the only documentation, suggested to use jsDelivr. I only recently added [tutorial on FreeCodeCamp how to use it with Vite](https://www.freecodecamp.org/news/how-to-create-a-rest-api-without-a-server/), so now it get little bit more downloads.
