### ISSUE TITLE
I'd like to propose my project OpenGlobus for you database. Check it out, please.

### ISSUE THREAD

**Issue by Zemledelec** [michaelrambeau/bestofjs#1005]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Open-source JavaScript library for visualizing in 3D high-precision virtual globes and various geospatial data, such as terrain, 3d objects, satellite imagery date etc.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/openglobus/openglobus

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
3D WebGL Maps

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
GIS

**Comment by michaelrambeau** [comment]
Hello Michael @Zemledelec thank you for the suggestion, `OpenGlobus` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @Zemledelec `OpenGlobus` is available on _Best of JS_, please check:

https://bestofjs.org/projects/openglobus

About the tagging, does a new tag called `Geospatial` make sense? Can you see other projects from _Best of JS_ that should be tagged too?

I'm thinking about these projects:

- Turf
- KeplerGL
- L7
- Geolib

Thank you in advance for the feedback!

**Comment by michaelrambeau** [comment]
Hello @Zemledelec a new tag `Geospatial` has been added: https://bestofjs.org/projects?tags=geospatial

Let me know if I'm missing other projects from _Best of JS_, thank you!

![image](https://github.com/user-attachments/assets/69f09c88-211a-44c3-8b27-f98978b212d0)

**Comment by Zemledelec** [comment]
Great news @michaelrambeau! Thank you! 
Geospatial sounds reasonable for the projects. 
Probably JSTS also geospatial.
