### ISSUE TITLE
Add doks

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#1006]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Everything you need to build a stellar documentation website. Fast, accessible, and easy to use.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/thuliteio/doks

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Documentation

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by xeusteerapat** [comment]
Hmmmm, it's just a theme for Thulite, which has already been added to the website. BTW, has the project changed its name from Hyas? 🤔

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat for the recommendation.

The weird thing is that Doks (2.1k stars) is much popular than Thulite (348), both being from the same org.

According to [this commit](https://github.com/thuliteio/thulite/commit/944b1a6aadaf57d55b7b9106dc12020111960e23) it changed from Hyas to Thulite indeed, I'm going to rename it in _Best of JS_.

**Comment by michaelrambeau** [comment]
Dock is available on _Best of JS_: https://bestofjs.org/projects/doks

Hyas was renamed: https://bestofjs.org/projects/thulite

Thank you for the information!
