### ISSUE TITLE
Flyon UI Tailwind CSS Components

### ISSUE THREAD

**Issue by CodeByOmm** [michaelrambeau/bestofjs#1010]
**The Easiest Components Library For Tailwind CSS.**

**https://github.com/themeselection/flyonui**

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**TailwindCSS, CSS Toolkit**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @CodeByOmm thank you for the suggestion, `FlyonUI` is available on _Best of JS_, please check:

https://bestofjs.org/projects/flyonui
