### ISSUE TITLE
Update OrbitDB

### ISSUE THREAD

**Issue by haydenyoung** [michaelrambeau/bestofjs#1017]
We are listed on your site but the npmjs project appears to be the old project name.

OrbitDB is now on npmjs as https://www.npmjs.com/package/@orbitdb/core.

**Comment by michaelrambeau** [comment]
Hello @haydenyoung thank you for the information, data has been updated, please check https://bestofjs.org/projects/orbitdb

![image](https://github.com/user-attachments/assets/157bd9b1-ad65-436f-a095-6e8f94cc826a)

**Comment by haydenyoung** [comment]
@michaelrambeau thanks for updating so quickly. Looks great.
