### ISSUE TITLE
add typescript-rest

### ISSUE THREAD

**Issue by creadicted** [michaelrambeau/bestofjs#102]
[Typescript-Rest](https://github.com/thiagobustamante/typescript-rest) is a lightweight annotation-based expressjs extension for typescript. It can be used to define APIs using ES7 decorators and generate documentation based on [typescript-rest-swagger](https://github.com/thiagobustamante/typescript-rest#swagger)

**Comment by michaelrambeau** [comment]
@creadicted  Hello Konrad.
Thank you for the suggestion, the project will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello Konrad @creadicted 
It's online, check the `Express` tag: https://bestof.js.org/tags/express

Thank you for your feedback!
