### ISSUE TITLE
react-horizontal-scrolling-menu

### ISSUE THREAD

**Issue by asmyshlyaev177** [michaelrambeau/bestofjs#1020]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Horizontal scrolling menu component for React, modular and highly cusomizable.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
React, component, scrolling, slider, menu

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @asmyshlyaev177 thank you for the suggestion, `React horizontal scrolling menu` is available on _Best of JS_, please check.

https://bestofjs.org/projects/react-horizontal-scrolling-menu
