### ISSUE TITLE
Update tags for virtua

### ISSUE THREAD

**Issue by inokawa** [michaelrambeau/bestofjs#1021]
Hi, I'm the author of https://bestofjs.org/projects/virtua . We achieved stable support for Svelte so I've requested to update the tags.

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Virtual list (current)
React (current)
Scrolling (current)
Vue (current)
Solid (current)
Svelte (new)

**Comment by michaelrambeau** [comment]
Hello @inokawa it's nice to see devs from Japan 😄 !

The `Svelte` tag was added, please check:

![image](https://github.com/user-attachments/assets/16f9c388-5980-4441-b1c9-7c4a2444db8d)

**Comment by inokawa** [comment]
@michaelrambeau 
Looks good. Thanks!
