### ISSUE TITLE
New project: Colyseus

### ISSUE THREAD

**Issue by endel** [michaelrambeau/bestofjs#1022]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Multiplayer Framework for Node.js

Colyseus is an open-source framework for making real-time networked games. It plays nicely with a variety of front-end frameworks such as Phaser, React, Vue, KAPLAY, etc.

It offers room-based system, unique binary realtime state-synchronization, and a number of tools to speed-up and guide developers in the process of making their own multiplayer games.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/colyseus/colyseus

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Node.js framework
- Authentication / Authorization
- Real-time
- Full-stack framework
- Websocket
- Self-Hosted
- Game engine

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Game development (not necessarily a game _engine_)

**Comment by michaelrambeau** [comment]
Hello Endel @endel thank you for the suggestion, `Colyseus` was added to _Best of JS_:

https://bestofjs.org/projects/colyseus
