### ISSUE TITLE
Florr.io Project

### ISSUE THREAD

**Issue by cat2d2** [michaelrambeau/bestofjs#1024]
**Please briefly describe the project you'd like to add to _Best of JS_:**
A vast collection of scripts related to the game [florr.io](https://florr.io). It includes a clone, several user-enhancing things, and scripts for other clones of the game.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
The repository is [https://github.com/cat2d2/florr.io](https://github.com/cat2d2/florr.io).

**Before submitting the request to add a new project, please check the following points:**

- [ ✅ ] The project is related to the web platform or Node.js 
> Check directory `chinese-anthos` for how it relates to Node. 
- [ ✅ ] The source code is on GitHub and project has more than 10 stars on GitHub
- [ ✅ ] The project has thorough documentation in English
- [✅ ] The project is not deprecated and actively maintained
Daily commits.
**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Vue, Canvas
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
User Script(s)

I hope you take my project into consideration 😸 
### Although only being >3 days old, it already has 121 clones and 10,000+ views (as of this writing).
![Commit history](https://github.com/user-attachments/assets/1284eb51-0057-47b3-aadd-2af26b262e87)
![Clones](https://github.com/user-attachments/assets/4a131be5-5d9d-43b3-b8fe-669dac5d2f3a)

**Comment by michaelrambeau** [comment]
Hello @cat2d2 thank you for the suggestion.
We don't plan to include projects related to "game scripts" in _Best of JS_ for now but you'd be notified if the situation changes.
Thank you for your understanding and good luck with the promotion of your project!

**Comment by cat2d2** [comment]
> Hello @cat2d2 thank you for the suggestion. We don't plan to include projects related to "game scripts" in _Best of JS_ for now but you'd be notified if the situation changes. Thank you for your understanding and good luck with the promotion of your project!

In the directory chinese-anthos there is a 2D canvas game made from scratch.
