### ISSUE TITLE
new category

### ISSUE THREAD

**Issue by pelikhan** [michaelrambeau/bestofjs#1029]
With LLM/AI/GenAI technology rising, would you consider adding a new category for anything GenAI related?

**Comment by michaelrambeau** [comment]
Hello @pelikhan thank you for the feedback!

There are already 2 tags `AI` and `Machine Learning`:

- https://bestofjs.org/projects?tags=ai
- https://bestofjs.org/projects?tags=ml
 
Do you think a more specific tag `LLM` would be useful?

**Comment by pelikhan** [comment]
Ha right... LLMs are a newish kind of ML but unclear it warrants a new category. It might get more SEO hits though as AI has become very generic.
