### ISSUE TITLE
Add more responsive table projects

### ISSUE THREAD

**Issue by miksh7** [michaelrambeau/bestofjs#103]
It would be nice to have more responsive table projects like
https://github.com/DataTables/DataTables
https://github.com/fooplugins/FooTable
etc

**Comment by michaelrambeau** [comment]
Hello @miksh7 , thank you for the feedback.
The 2 projects you mentioned will be available on bestof.js.org very soon, under the `Table` tag:
https://bestof.js.org/tags/table

**Comment by michaelrambeau** [comment]
Hello @miksh7 
The 2 projects are online, check the `Table` tag: https://bestof.js.org/tags/table
Thank you for your feedback!
