### ISSUE TITLE
state-in-url

### ISSUE THREAD

**Issue by asmyshlyaev177** [michaelrambeau/bestofjs#1030]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Few hooks to store user data in browser's search params, can store complex nested objects while preserving types, like JSON but in URL. Support Next.js, React-router, and hooks for pure JS.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/asmyshlyaev177/state-in-url

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
React, Next.js, state management, routing, query params (can add this tag)

**Comment by michaelrambeau** [comment]
Thank you @asmyshlyaev177 I have noticed that project when you submitted the previous request because I'm interesting in the topic 😄

**Comment by michaelrambeau** [comment]
@asmyshlyaev177 `state-in-url` is available on _Best of JS_, please check:

https://bestofjs.org/projects/state-in-url

**Comment by asmyshlyaev177** [comment]
@michaelrambeau Awesome! Thank you.

Dumb question - does Readme updating automatically or is it manual process?

**Comment by asmyshlyaev177** [comment]
Completed. 😃
