### ISSUE TITLE
Add Ant Design X

### ISSUE THREAD

**Issue by afc163** [michaelrambeau/bestofjs#1034]
**Please briefly describe the project you'd like to add to _Best of JS_?**

@ant-design/x is an advanced AI component library focusing on the React ecosystem, aiming to simplify the development process of integrating artificial intelligence. Our library includes highly customized AI components, allowing developers to easily integrate conversational AI into their applications. In addition to rich UI components, @ant-design/x also provides a package of API solutions, supporting developers to directly access existing AI services through token authentication, seamlessly connecting with AI conversations and interactions. Whether you are building intelligent chat applications, enhancing user interaction experience, or accelerating the integration of AI capabilities, @ant-design/x is the ideal partner for React developers to enter the AI world.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/ant-design/x

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- [React](https://bestofjs.org/projects?tags=react)
- [Component library](https://bestofjs.org/projects?tags=component)
- [Design System](https://bestofjs.org/projects?tags=design-system)
- [AI](https://bestofjs.org/projects?tags=ai)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @afc163 it's been a long time 😄 👋 

Ant Design X will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Do you know what is the link to the documentation in English?

These URL both open the documentation in Japanese, is there a bug?

- https://x.ant.design/docs/spec/introduce
- https://x.ant.design/docs/spec/introduce-cn

**Comment by afc163** [comment]
It is Chinese, not Japanese.

The translation is still in progress.

**Comment by michaelrambeau** [comment]
Oh sorry my bad, I wanted to say "Chinese" but I said Japanese just because I'm used to (I live in Japan), it's a mistake 😅

**Comment by michaelrambeau** [comment]
@afc163 thank you for your patience 😄 

`Ant Design X` is available on _Best of JS_: https://bestofjs.org/projects/ant-design-x
