### ISSUE TITLE
@lazarv/react-server

### ISSUE THREAD

**Issue by lazarv** [michaelrambeau/bestofjs#1035]
**Please briefly describe the project you'd like to add to _Best of JS_?**
`@lazarv/react-server` is a React meta-framework using the Vite 6 Environment API, including support for React Server Components, server functions, streaming, static site generation, file-system based routing, micro-frontends using RSC Delegation, Node.js cluster mode and more.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/lazarv/react-server

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
react rsc vite fullstack ssg microfrontend

**Comment by michaelrambeau** [comment]
Hello Viktor @lazarv thank you for the recommendation!

`react-server` is available on _Best of JS_, please check: https://bestofjs.org/projects/react-server

**Comment by lazarv** [comment]
Awesome, thanks @michaelrambeau!
