### ISSUE TITLE
Add Redux-observable

### ISSUE THREAD

**Issue by codebex** [michaelrambeau/bestofjs#105]
Suggestion: Redux-Observable

> RxJS middleware for action side effects in Redux using "Epics" 

`https://redux-observable.js.org`

`https://github.com/redux-observable/redux-observable`

I think it could be tagged as _redux_ and _functional programming_ .

**Comment by michaelrambeau** [comment]
Hello @alaindm 
Thank you for the suggestion, `redux-observable` will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello @alaindm 
`redux-observable` project is available on bestof.js.org.

 Check here: https://bestof.js.org/tags/redux
