### ISSUE TITLE
Add bootstrap-vue

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#106]
Hi there,

I believe this project should be included into the [Vue](https://bestof.js.org/tags/vue) category :)

Boostrap-vue: https://github.com/bootstrap-vue/bootstrap-vue

Thanks for this great website that I check every single day!

**Comment by michaelrambeau** [comment]
Hello @Atinux ,
Thank you for the suggestion and for your kind words!
`bootstrap-vue` will be available in bestof.js.org very soon.

By the way,`nuxt`project is doing well, it was one of the hottest project, 2 days ago, good job!

![image](https://user-images.githubusercontent.com/5546996/29643060-6cde1f5e-88a7-11e7-9ae5-b80546bd61dd.png)

As one of the main actors of the JavaScript scene, your feedback is very valuable.

Just an idea: wouldn't it be nice if bestof.js.org could deliver a more customized experience by automatically showing "your" projects (the projets you contribute to, I mean) ?

Now, if you are logged-in, you can bookmark project that will be displayed in the page called "MY PROJECTS". But maybe we could add a section "THE PROJECTS I CONTIBUTE TO".

Well it's just an idea, I don't know if it makes sense...

**Comment by atinux** [comment]
Thank you for your fast answer and your kind words @michaelrambeau 

Actually I believe that `MY PROJECTS` is enough since I can add the projects I contribute to inside my projects :-)

**Comment by michaelrambeau** [comment]
Hello again @Atinux 
`bootstrap-vue` is available on bestof.js.org, under the following tags: `Vue` and `Component Toolkit`.

Check here for example: https://bestof.js.org/tags/component
