### ISSUE TITLE
Rythm.js

### ISSUE THREAD

**Issue by acailly** [michaelrambeau/bestofjs#107]
Hi,

[Rythm.js](https://okazari.github.io/Rythm.js/) is a nice lib that make your page dance in **rythm** with the music.

It's getting some traction recently (+73 stars today)

**Comment by michaelrambeau** [comment]
Hello Antoine @acailly 
Thank you for the suggestion, the project will be available on bestof.js.org vey soon.

By the way, make all HTML elements in a page move according to the rhythm of a given music is a fun concept, but can you imagine what could be built using this concept?

**Comment by Okazari** [comment]
Hello ! Creator of Rythm.js here.
To be totally honest, this library have no real usecase at the moment (and it's almost scaring how much people like it even if it doesn't fit any of their usecase :smile: ). I had some suggestion on hacker news 

> Still, it's an interesting library, and has its uses on certain niche sites (or for easter eggs).

> Plenty of muscicians and DJs have blogs and also it wouldn't be out of place on a site like Soundcloud, if used sparingly.

It is currently used on my company website beside a Konami code. I just hope someone will find some real use case in the future.

**Comment by michaelrambeau** [comment]
Hello Benjamin @Okazari 
No problem at all.
Thank you for your great job and congratulations for the buzz around your project!
It will be available under the `Audio` tag. I will tell you when it's online.

**Comment by michaelrambeau** [comment]
Hello again Benjamin @Okazari and Antoine @acailly ,
Not only your project is available on bestof.js.org but also it's the project number 1 today!
Congratulations!

![image](https://user-images.githubusercontent.com/5546996/30239179-d0a8bec6-9591-11e7-9d33-879557c4cdfa.png)

**Comment by Okazari** [comment]
Thanks ! The hype is out of control 👍 (+1200star within 3days)

**Comment by michaelrambeau** [comment]
Great @Okazari , teach me how to create the hype around my projects 😄  !
