### ISSUE TITLE
Add Lad and Lass

### ISSUE THREAD

**Issue by niftylettuce** [michaelrambeau/bestofjs#108]
https://lad.js.org and https://lass.js.org

**Comment by michaelrambeau** [comment]
Hello @niftylettuce , thank you for the suggestions.

The 2 projects will be available on bestof.js.org very soon.

Just to be sure I make no mistake about the right tags to choose, could you confirm the following points?

* `lass` is a boilerplate that can be used to create a new node.js package. I guess it's only for `backend` packages, it's not one of these countless frontend boilderplates (see this tag https://bestof.js.org/tags/boilerplate)
* `lad` is a node.js project, built from lass, that can be used to create either an API server or a full "monolith" web application (by monolith I mean a single web application that manages backend logic **and** also renders the views, sending html page to the clients)

Bonus question: I wonder why the 2 names are so close and where do the 2 cute characters come from!
Thank you in advance for your feedback.

**Comment by michaelrambeau** [comment]
Hello @niftylettuce ,
Lad and Lass projects are both available on bestof.js.org
But I'm still waiting for your feedback 😄  !
Thank you in advance!

**Comment by michaelrambeau** [comment]
Hello @niftylettuce 
Here are the numbers of stars added on GitHub over the last 30 days, on average:

* Lad: +0.8 stars/day
* Lass +1.3 stars /day

Closing the issue but feel free to contact me at any time if you have feedback about bestof.js.org!

**Comment by niftylettuce** [comment]
@michaelrambeau thank you and apologies for not getting back sooner, I was very focused on work.  Looks great to me, and thank you for sharing the stats!  Once stable release is out I'm sure those star numbers will jump quite a bit 😆
