### ISSUE TITLE
Elm (elm-compiler)

### ISSUE THREAD

**Issue by patrickstubner** [michaelrambeau/bestofjs#109]
Even if it is not a JS Framework, It would fit into the group of UI Frameworks.
And it would be interesting, how the momentum of this UI focused language evolves.

**Comment by michaelrambeau** [comment]
Hello @patrickstubner ,
Thank you for the suggestion.
It's not JavaScript but I guess it compiles to JavaScript, and as you said it would be interesting to check its evolution over the time.
Maybe it could be classified under the `compilers` tags too.
About the GitHub project itself, which one is the more appropriate to add to bestof.js.org, I guess it's this one: https://github.com/elm-lang/elm-compiler ?

**Comment by patrickstubner** [comment]
Yep, that's right.
It is a ML-Style pure functional Language that compiles to JS.
In JS land terms it could be explained as a combination of React, Redux, Immutablejs, (Flux or TypeScript) that is all together combined in a very well designed language.
Just to be clear, it dos not use these libraries, it is just one of several library combination that in JS land would come "close" Elm.

**Comment by michaelrambeau** [comment]
Thank you Patrick @patrickstubner 
`elm-compiler` is available on bestof.js.org under `Functional programming` and `Compiler` tags.

Check here for example:
https://bestof.js.org/tags/compiler
