### ISSUE TITLE
Add `electron-userland/electron-builder` project

### ISSUE THREAD

**Issue by develar** [michaelrambeau/bestofjs#11]
https://github.com/electron-userland/electron-builder
Stars trend :)

**Comment by michaelrambeau** [comment]
Hello @develar !
Thank you, I have added that project, it will be available in 48 hours (because the application needs at least 2 daily snapshots of Github stars to display trends). Be patient!

**Comment by michaelrambeau** [comment]
It's online, number 4 in the `Desktop app` category, thank you for support!

http://bestof.js.org/tags/desktop

![image](https://cloud.githubusercontent.com/assets/5546996/19206376/7c3ec88e-8d23-11e6-8a6b-cf4ee8c7f340.png)
