### ISSUE TITLE
loading-bar.js

### ISSUE THREAD

**Issue by zbryikt** [michaelrambeau/bestofjs#110]
[loading-bar.js](https://github.com/loadingio/loading-bar/) is an open-sourced  javascript library to do progress animation with SVG, built by loading.io.

It's highly customizable and provides some presets to start with. You can find documentation and live demo [here](https://loading.io/progress/).

**Comment by michaelrambeau** [comment]
Hello @zbryikt 
Thank you for the suggestion, the project will be available on bestof.js.org very soon.
By the way, do you know if it's available on npm?

**Comment by zbryikt** [comment]
@michaelrambeau thanks! not yet on npm, but there is already an issue for that, so it will be on npm soon :)

**Comment by michaelrambeau** [comment]
Hello @zbryikt,
`loading-bar.js` is available on bestof.js.org, check here:
http://bestofjs.surge.sh/tags/progress-bar
