### ISSUE TITLE
Maker.js

### ISSUE THREAD

**Issue by danmarshall** [michaelrambeau/bestofjs#111]
Hello, I just found BestOfJs and it is really cool! Thanks for creating it.

I would like to add Maker.js - http://maker.js.org/

May I also ask how tags are added to projects:
* Are tags manually curated, crowd sourced, or computed? 
* Can a project have more than one tag?

**Comment by michaelrambeau** [comment]
Hello Dan @danmarshall thank you very much for your feedback and your kind words!
`maker.js` will be available on bestof.js.org very soon.
So far **tags** are manually created and projects are manually tagged, there is no automatic process even if we could access GitHub "topics".
To improve bestof.js.org, any suggestion is welcome.
Some projects have multiple tags.

About the 2 projects you mentioned, we could create a new tag called `CAD`, does it make sense?
Or is there an other word that makes more sense for the majority of people who check bestof.js.org?
In addition, maybe a new tag called `geometry` makes sense too?

I'm not familiar at all with the CAD world, this is why I'm asking, thank you for your input!

**Comment by danmarshall** [comment]
I think CAD is pretty good! I would also like to add Maker.js to existing tags: SVG & Drawing.

**Comment by michaelrambeau** [comment]
Hello Dan @danmarshall 
It's online, check the new tag `CAD`: https://bestof.js.org/tags/cad

**Comment by danmarshall** [comment]
Awesome, thank you Michael!
