### ISSUE TITLE
OpenJSCAD

### ISSUE THREAD

**Issue by danmarshall** [michaelrambeau/bestofjs#112]
https://openjscad.org/
Programmatic 3D modeling

**Comment by michaelrambeau** [comment]
Hello again Dan @danmarshall 
`OpenJSCAD` will be available very soon on bestof.js.org.

It could be tagged under `3D`, `WebGL` and `CAD` tags, would it be OK?

**Comment by danmarshall** [comment]
Those are perfect, thanks!

**Comment by danmarshall** [comment]
@z3dev do you have any suggestions how to tag OpenJSCAD for BestOfJS ?

**Comment by z3dev** [comment]
The last release was to enable NODEJS.

**Comment by z3dev** [comment]
Also, we have renamed ourselves, bringing together several layers and libraries under on organization, called JSCAD. (Short names are awesome). So, maybe this should become JSCAD.

https://github.com/jscad

let me know if the components should be listed separately.

**Comment by michaelrambeau** [comment]
Hello again Dan @danmarshall 
It's online too!
https://bestof.js.org/tags/cad

**Comment by danmarshall** [comment]
Looks good to me :)

**Comment by z3dev** [comment]
Thanks!

**Comment by kaosat-dev** [comment]
Thanks ! :)
