### ISSUE TITLE
Tag Opentype.js with Typography

### ISSUE THREAD

**Issue by danmarshall** [michaelrambeau/bestofjs#113]
Hi Michael, I see you already have Opentype.js under the **font** tag. I think it should also have the **typography** tag. Thanks!

**Comment by michaelrambeau** [comment]
OK Dan, it will be online in 24 hours.
Thank you!

**Comment by michaelrambeau** [comment]
@danmarshall The tag has been added, check here:
https://bestof.js.org/tags/typo
