### ISSUE TITLE
Links for general computer science questions ( every-programmer-should-know )

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#115]
https://github.com/mr-mig/every-programmer-should-know

**Comment by michaelrambeau** [comment]
Hello @davojta ,
Thank you for the recommendation.
My first reaction was that `every-programmer-should-know` project is not directly related to JavaScript or web development in general.
But there is a category called `meta - project list` in best.of.js with the `Awesome` project, that is a bit similar (it's basically an aggregation of links, gathered in simple Markdown files).
And I checked the content of `every-programmer-should-know`, there is lot of interesting things related to web development.
So `every-programmer-should-know` will be added to best.of.js, under the `meta - project list` tag, does ti make sense for you?
Thank you in advance for your feedback.

**Comment by michaelrambeau** [comment]
Hello @davojta ,
`every-programmer-should-know` project is available on bestof.js.org and it's one of the hottest projects right now, check online.
It was the project number 3 yesterday and today too.
Thank you for your feedback!

**Comment by davojta** [comment]
@michaelrambeau Thank you for your support! meta - project list is the perfect tag for that project!
