### ISSUE TITLE
Add Vuebar

### ISSUE THREAD

**Issue by DominikSerafin** [michaelrambeau/bestofjs#116]
Vuebar is pretty neat Vue.js ecosystem library that makes possible to have custom scrollbars with native scrolling behavior. Created and maintained by me.

Website: [github.serafin.io/vuebar](https://github.serafin.io/vuebar/)

GitHub: [github.com/DominikSerafin/vuebar](https://github.com/DominikSerafin/vuebar)

NPM: [www.npmjs.com/package/vuebar](https://www.npmjs.com/package/vuebar)

**Comment by michaelrambeau** [comment]
Hello Dominik @DominikSerafin ,
Thank you for the suggestion, `vuebar` project will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello Dominik @DominikSerafin 
`vuebar` is available on Best of JS!
Check `Vue` and `Scrolling` tags:
https://bestof.js.org/tags/scrolling

Thank you for your feedback!

**Comment by DominikSerafin** [comment]
Awesome, thank you!
