### ISSUE TITLE
Add SproutCore Project 

### ISSUE THREAD

**Issue by mauritslamers** [michaelrambeau/bestofjs#117]
Yes, it is a bit old, but it is still very much alive.

**Comment by michaelrambeau** [comment]
Hello @mauritslamers 
Whaaaat, a UI framework I have never heard of it before, I cannot believe that!

Thank you for the suggestion,  https://github.com/sproutcore/sproutcore project will be added very soon!

**Comment by mauritslamers** [comment]
Ember had to get its ideas from somewhere ;-)

**Comment by michaelrambeau** [comment]
Hello @mauritslamers 
It's online, check the `UI Framework` tag: https://bestof.js.org/tags/framework

**Comment by michaelrambeau** [comment]
Hello @mauritslamers 
Just to confirm, checking the numbers from bestof.js.org, the project is not "super trendy" indeed, it has exactly the same numbers of stars than one week ago, it lost a star one day but it got one star an other day.
