### ISSUE TITLE
Add loki

### ISSUE THREAD

**Issue by klippx** [michaelrambeau/bestofjs#118]
Visual Regression Testing for Storybook

https://github.com/oblador/loki

Very good tool if you have stories and want to use those to generate screenshots and verify vs baseline. Supports a number of platforms such as ios, android, chrome for desktop/ios

**Comment by michaelrambeau** [comment]
Hello @klippx 
Thank you for that suggestion too, `loki` project will be available very soon!

I guess there is nothing to do with an other project called `LokiJS` on https://bestof.js.org ?
http://lokijs.org/

**Comment by klippx** [comment]
No, that is something completely different. Just a naming collision.

**Comment by michaelrambeau** [comment]
OK @klippx , it's funny that the `Loki` creator picked the same name as a pretty popular JavaScript project on GitHub (3.6k stars, +2.5 stars par day over the last 12 months).

I wonder how to name them in Best of JS, maybe like this:

* https://loki.js.org/ => "Loki for Storybook" (your one 😄 )
* http://lokijs.org/ => "LokiJS" (the document oriented database)

Would it be OK?

**Comment by michaelrambeau** [comment]
Hello @klippx 
It's online!
Just search for `loki` in the search bar and you will find it... and the other `LokiJS` project too! 😄 

That's why I think we could rename it `Loki for Stotybook ` in https://bestof.js.org/ maybe, if you don't mind.
Again, thank you for your feedback!

**Comment by klippx** [comment]
👍  Thanks!
