### ISSUE TITLE
Add sagui

### ISSUE THREAD

**Issue by klippx** [michaelrambeau/bestofjs#119]
Sagui is the single development dependency that provides the tooling required to build, test and develop modern JavaScript applications.

https://github.com/saguijs/sagui

This is a very nice and powerful tool to get started with a new js project in 0 time, setting up all the tedious boilerplate that can take hours or even a day in a snap.

**Comment by michaelrambeau** [comment]
Hello @klippx 
Thank you for the suggestion, `sagui` project will be available very soon.
It will be classified under the `Scaffoldling - Generator` tag, would it be OK?

I wonder if Sagui can be used for any front-end project or if it's tight to a specific library. The README.md mentions React as an example but it seems you can use any npm package, is it true?

**Comment by pirelenito** [comment]
Thanks for the suggestion @klippx ❤️

I'm one of the developers behind Sagui. Conceptually it is very similar to `create-react-app` in that it is both a "scaffolding" and a "dependency", handling build, development and testing concerns of your application. So maybe the categories could be:

- Building tool
- Boilerplate

What do you think?

Btw, awesome project @michaelrambeau! And thanks for considering Sagui 🐒

**Comment by michaelrambeau** [comment]
Hello @pirelenito 
Thank you for your support, I'm more than happy to add nice projects suggested by users and contributors!
About `sagui`, OK, it will be available under those tags.
Nice logo by the way!

**Comment by michaelrambeau** [comment]
@klippx @pirelenito 
It's online!

Check one of these tags:
* https://bestof.js.org/tags/boilerplate
* https://bestof.js.org/tags/build

Thank you for your feedback!

**Comment by klippx** [comment]
Thanks! 👍

**Comment by pirelenito** [comment]
Thank you! ❤️
