### ISSUE TITLE
Add mappersmith

### ISSUE THREAD

**Issue by klippx** [michaelrambeau/bestofjs#120]
https://github.com/tulios/mappersmith

Mappersmith is a powerful library for building API clients, isomorphic since it works both in node backend and frontend. It is powerful since it wraps a number of gateways (including fetch), has support for middlewares and has a number of interesting optional built in middlewares available, among other basic auth and error handling.

It is promise based and with it's resource like syntax it makes API code very easy to reason about. 

Other than all that it has built in support for testing all your requests and mocking those. You can also choose your gateway - xhr, http and fetch.

**Comment by michaelrambeau** [comment]
Thank you again Mathias @klippx !
It will available be very soon.

FYI new projects added to Best of JS are available online after 48 hours because we need at least the number of stars on GitHub from 2 different days, in order to display the "daily trends".

**Comment by michaelrambeau** [comment]
Hello Mathias @klippx 
It's online, check the `http` tag: https://bestof.js.org/tags/http

Thank you again for all the suggestions!

**Comment by klippx** [comment]
Great, thanks! 👍
