### ISSUE TITLE
Add node-api-boilerplate

### ISSUE THREAD

**Issue by talyssonoc** [michaelrambeau/bestofjs#121]
node-api-boilerplate is a well documented boilerplate for Node apps based on DDD/clean-architecture focused on codebase scalability and separation of concerns.

Repository: https://github.com/talyssonoc/node-api-boilerplate
Documentation: https://github.com/talyssonoc/node-api-boilerplate/wiki

**Comment by michaelrambeau** [comment]
Hello @talyssonoc,
Thank you for the suggestion, `node-api-boilerplate` project will be available on https://bestof.js.org/ very soon.

**Comment by michaelrambeau** [comment]
Hello @talyssonoc ,
`node-api-boilerplate` project is now available, check the `Boilerplate` tag:

https://bestof.js.org/tags/boilerplate

Thank you for your feedback!

**Comment by talyssonoc** [comment]
Thanks, @michaelrambeau! 😄
