### ISSUE TITLE
Add loglevel

### ISSUE THREAD

**Issue by pimterry** [michaelrambeau/bestofjs#122]
Loglevel is a minimal lightweight logging framework for JS, with nearly 3 million downloads a month:

https://www.npmjs.com/package/loglevel
https://github.com/pimterry/loglevel

**Comment by michaelrambeau** [comment]
Hello Tim @pimterry ,
Thank you for the suggestion, `loglevel` project will be available on https://bestof.js.org/ very soon!

**Comment by michaelrambeau** [comment]
Hello Tim @pimterry 
`loglevel` project is now available, check the `Logging` tag:
https://bestof.js.org/tags/log

Thank you for your feedback!
