### ISSUE TITLE
Custom Scrollbar projects

### ISSUE THREAD

**Issue by miksh7** [michaelrambeau/bestofjs#124]
Hi, i'd suggest to add a few projects implementing a custom scrollbar into Scrolling folder

- https://github.com/utatti/perfect-scrollbar
- https://github.com/inuyaksa/jquery.nicescroll

**Comment by michaelrambeau** [comment]
Hello @miksh7 
Thank you for the suggestions, these 2 projects will be available very soon on bestof.js.org.

**Comment by davojta** [comment]
@michaelrambeau  Here are some more libs - https://github.com/malihu/malihu-custom-scrollbar-plugin
and old famous https://github.com/vitch/jScrollPane

**Comment by michaelrambeau** [comment]
@davojta Maybe we should create a separate app called "Best of Scrolling" 😆  !

**Comment by davojta** [comment]
@michaelrambeau it's good to have the best js parts in one place )

**Comment by michaelrambeau** [comment]
@davojta I was checking the projects, they seem a bit old, compared of what we have now, I'm not sure we really need them in Best of JavaScript, given the fact that jQuery is less used than before.

* `jScrollPane` has been built 2 years ago (https://github.com/vitch/jScrollPane/tree/master/script)
* `malihu-custom-scrollbar-plugin` last commit was one year ago

But I may be wrong, it's just an opinion, there is no accurate metrics about how to select projects that appear on bestof.js.org... so just confirm that you really want them and they will be added 😄 ! Thank you for your understanding!

**Comment by davojta** [comment]
malihu-custom-scrollbar-plugin is okey (it works perfert for it purpose - as more and more project dont use custom scrollbars at all)
jScrollPane is quite old, i agree so we can ignore it and dont add to best.of.js )

**Comment by miksh7** [comment]
maybe worth considering those ones too
http://blog.dynamicdrive.com/5-brilliant-ways-to-lazy-load-images-for-faster-page-loads

**Comment by davojta** [comment]
@miksh7 do you use that technics on production ? i think the lazy load for images too trivial )
We some kind of image lazyloading with django on production but 4 years ago and i dont sure about modern solution in the topic )

**Comment by miksh7** [comment]
ops sorry, wrong link, ignore please

**Comment by michaelrambeau** [comment]
@miksh7 About image loaders, you can find several solutions under the `Resource Loader` tag: https://bestof.js.org/tags/load

@davojta One of the modern solutions is this library: http://callmecavs.com/layzr.js/
Now the hottest project is the category is: https://github.com/ApoorvSaxena/lozad.js

**Comment by michaelrambeau** [comment]
@miksh7 The 2 projects you suggested are available on bestof.js.org, check the `scrolling` tag:
https://bestof.js.org/tags/scrolling
Thank you for checking!
