### ISSUE TITLE
Recommend Azat Mardan into hall of fame

### ISSUE THREAD

**Issue by azat-co** [michaelrambeau/bestofjs#125]
![screenshot 2017-10-20 12 21 22](https://user-images.githubusercontent.com/1137314/31838335-35598e1c-b591-11e7-9299-30abf064d26f.png)

**Comment by azat-co** [comment]
tags: react, node, javascript, aws, crypto, react-native, backbone, express

**Comment by michaelrambeau** [comment]
Hello Azat @azat-co ,
You will be inducted into the _JavaScript Hall of Fame_ in less than 24 hours (when the project is rebuilt), be patient!
Sorry for having you missed you so far, thank you for your understanding.

**Comment by michaelrambeau** [comment]
Hello Azat @azat-co 
I'm happy to announce that you were inducted to the _JavaScript Hall of Fame_, congratulations! 🎉 

https://bestof.js.org/hall-of-fame/

As a member of the Hall of Fame, any feedback about Best of JavaScript application would be very valuable!
Or just giving a star to https://github.com/michaelrambeau/bestofjs-webui repo would make me very proud! 😄 
Have a great week, thank you!

**Comment by azat-co** [comment]
@michaelrambeau thanks!
