### ISSUE TITLE
Add Practical Node to list of free books

### ISSUE THREAD

**Issue by azat-co** [michaelrambeau/bestofjs#126]
https://github.com/azat-co/practicalnode

**Comment by michaelrambeau** [comment]
Hello again @azat-co ,
`Pratical Node` project will be available on bestof.js.org very soon, thank you for the suggestion!

**Comment by michaelrambeau** [comment]
Hello again Azat @azat-co ,
`Practical Node` project is available on bestof.js.org, check one of these tags: 

* `Learning resource` =>  https://bestof.js.org/tags/learning
*  `Book` => https://bestof.js.org/tags/book (screenshot below)

Once again, thank you for your feedback!

![image](https://user-images.githubusercontent.com/5546996/31867542-9858e930-b7cc-11e7-85d4-8a225fb1ad3d.png)
