### ISSUE TITLE
add Ilya Kantor to Hall of Fame

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#128]
https://github.com/iliakan Ilya Kantor is educator in Russian speaking world, creator of the most popular Russian speaking website about javascript and most complete Russian lessons for js - https://learn.javascript.ru/ . He has great influence on js community for Russian-speaking people.

And also author of https://github.com/iliakan/javascript-tutorial-en

**Comment by michaelrambeau** [comment]
Thank you very much @davojta !
We need more international presence in the JavaScript Hall of Fame 🌐  !
I will let you know when the Hall of Fame page is updated.

**Comment by michaelrambeau** [comment]
@davojta Please let Ilya Kantor 🇷🇺  know that he has been inducted to the *JavaScript Hall of Fame*!

https://bestof.js.org/hall-of-fame

@iliakan Welcome to the JavaScript Hall of Fame, any feedback about *Best of JavaScript* is welcome!

**Comment by iliakan** [comment]
@davojta @michaelrambeau thanks! I wonder why the newer English version of the tutorial is not mentioned :)
https://javascript.info

**Comment by davojta** [comment]
@iliakan actually javascript.info is added in the next issue - https://github.com/michaelrambeau/bestofjs/issues/129

**Comment by davojta** [comment]
@iliakan or do you mean that we need to give link to https://javascript.info near your name in hall of fame ?

**Comment by iliakan** [comment]
Yes, guess for many readers it would be more relevant than .ru
thank you

**Comment by davojta** [comment]
@michaelrambeau could we change the website for Ilya Kantor?

**Comment by iliakan** [comment]
Both websites are actual, they are just Russian and English versions of the tutorial.

**Comment by michaelrambeau** [comment]
@davojta @iliakan Actually, the website is the one displayed in the user's GitHub profile: https://github.com/iliakan

![image](https://user-images.githubusercontent.com/5546996/31886742-9864e41a-b830-11e7-9c65-3a96027c3895.png)

If you update it, the _Hall of Fame_ page will be automatically updated 24 hours later.

**Comment by michaelrambeau** [comment]
@iliakan Thank you for having updated your profile on GitHub, the _JavaScript Hall of Fame_ page has just been rebuilt.

Let me know if you have any feedback about `Best of JavaScript` application, as a member of the Hall of Fame, your point of view is very important to me! 😄
