### ISSUE TITLE
One more js tutorial )

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#129]
https://github.com/iliakan/javascript-tutorial-en

**Comment by michaelrambeau** [comment]
Thank you for that link too, @davojta !
The `Modern JavaScript Tutorial` project will be available on bestof.js.org in 48 hours, classified under the `Learning` tag.

**Comment by michaelrambeau** [comment]
@davojta @iliakan The `Modern JavaScript Tutorial` project is available on _Best of JavaScript_.

Check the `Learning Resource` tag: https://bestof.js.org/tags/learning

Thank you!
