### ISSUE TITLE
Add `postlight/lux` project

### ISSUE THREAD

**Issue by papa-zakari** [michaelrambeau/bestofjs#13]
https://github.com/postlight/lux
This project is an MVC style framework for building a JSON API with Node.js.

**Comment by michaelrambeau** [comment]
Hello @zacharygolba , I have added Lux framework project, it will be available in 48 hours, be patient.

I am really interested in solutions to build easily REST API with node.js, I tried solutions like FeathersJS (the one I prefer right now) or Loopback. See the contenders here: http://bestof.js.org/tags/api.

So I'd like to know how Lux deals with database and models, is there a system of plugins to connect to any database (MongoDB for example), or is there a database by default ?
Thank you!

**Comment by papa-zakari** [comment]
Awesome, thanks for adding Lux to bestofjs! 😃

Lux wraps [`knex`](http://knexjs.org/) to create a custom ORM that supports a number of DBMSs. Currently we do not support MongoDB but it is something we are looking into for future releases. You can find a few examples of what a Lux model looks like [here](https://github.com/postlight/lux/tree/master/examples/social-network/app/models). Also, if your interested in the schema building aspect of models, checkout these [migration examples](https://github.com/postlight/lux/tree/master/examples/social-network/db/migrate).

**Comment by michaelrambeau** [comment]
Thank you for the anwser, "lux framework" project can be found on bestof.js.org!
http://bestof.js.org/tags/nodejs-framework
Also I added `knex`ORM because it's a popular ORL for sql databases.
