### ISSUE TITLE
Add Cypress.io and WallabyJS

### ISSUE THREAD

**Issue by Sharlaan** [michaelrambeau/bestofjs#130]
[Cypress.io](https://www.cypress.io/) Awesome next-gen e2e testing tool, (still in beta)

[Wallaby.js](https://wallabyjs.com/) Commercial Unit testing tool

**Comment by michaelrambeau** [comment]
Hello Raphaël @Sharlaan 
Thank you for the recommendations, `Cypress` project will be available under the `Testing` and `Browser automation` tags very soon.
_Best of JavaScript_ only stores open source projects on GitHub so I don't think we can include Wallaby.js project, let me know if it makes sense, thank you for your understanding!

**Comment by michaelrambeau** [comment]
Hello Raphaël @Sharlaan 
It's online, could you please check?
https://bestof.js.org/tags/test
Thank you!
