### ISSUE TITLE
Add ant-design-pro

### ISSUE THREAD

**Issue by afc163** [michaelrambeau/bestofjs#132]
http://github.com/ant-design/ant-design-pro

**Comment by michaelrambeau** [comment]
Hello @afc163 
Thank you for the recommandation, `ant-design-pro` project will be available very soon on bestof.js.org.

**Comment by michaelrambeau** [comment]
Hello @afc163 
It's online, and it's the project number 2 today!

![image](https://user-images.githubusercontent.com/5546996/32352140-4c648d28-c063-11e7-8008-f6d2bd18b51f.png)

**Comment by afc163** [comment]
Thank you! @michaelrambeau
