### ISSUE TITLE
Add Dockly - Node.js CLI tool for managing Containers 

### ISSUE THREAD

**Issue by lirantal** [michaelrambeau/bestofjs#133]
Hi,

Author of [Dockly](https://github.com/lirantal/dockly) here, suggesting to add it to Server CLI section of bestof.js.org. 

![](https://cloud.githubusercontent.com/assets/316371/25682867/c5212216-3027-11e7-8f36-72d38516d2af.gif)

**Comment by michaelrambeau** [comment]
Hello @lirantal 
Thank you for the recommendation.
`Dockly` project will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
@lirantal `Dockly` project is available on bestof.js.org: https://bestof.js.org/tags/cli
