### ISSUE TITLE
Add wretch

### ISSUE THREAD

**Issue by elbywan** [michaelrambeau/bestofjs#134]
[Wretch](https://github.com/elbywan/wretch) is a tiny http client wrapped around the fetch API which has gained some traction recently.

I was wondering if you would consider adding it under the [http](https://bestof.js.org/tags/http/) tag ?

(links : [github](https://github.com/elbywan/wretch), [npm](https://www.npmjs.com/package/wretch))

Thanks !

**Comment by michaelrambeau** [comment]
Hello Julien @elbywan,
Thank you for the recommendation, `Wretch` will be online very soon.
By the way, did you know that there was already a project from you in bestof.js.org: `Bosket`, good job!
Let me know if you have any feedback about the application, thank you!

**Comment by elbywan** [comment]
Hi Michael,

> Thank you for the recommendation, Wretch will be online very soon. 

Great, many thanks !

>By the way, did you know that there was already a project from you in bestof.js.org: Bosket, good job!

To be honest that's how I came upon bestofjs (a referral link) 😉.

>Let me know if you have any feedback about the application, thank you!

I have no special feedback the website is very clean and intuitive, keep up the good work !

**Comment by michaelrambeau** [comment]
@elbywan Just to confirm, `Wretch` project is available: https://bestof.js.org/tags/http

Thank you for your kind words!
