### ISSUE TITLE
nodebestpractices - community node.js practices 

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#135]
https://github.com/i0natan/nodebestpractices

**Comment by michaelrambeau** [comment]
Hello @davojta 
`Node.js Best Practices` is available on bestof.js.org and it's today's number one project!

![image](https://user-images.githubusercontent.com/5546996/32921493-2b3499c2-cb71-11e7-8ac9-a10c89c42f59.png)
