### ISSUE TITLE
tech-interview-handbook - good interview aggregation resource )

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#138]
https://github.com/yangshun/tech-interview-handbook

**Comment by davojta** [comment]
Its for meta tag

**Comment by michaelrambeau** [comment]
OK @davojta thank you, it's coming soon!

**Comment by michaelrambeau** [comment]
Hello @davojta,
it's online, check the `Learning` tag: https://bestof.js.org/tags/learning
