### ISSUE TITLE
Add `angular/angular` project

### ISSUE THREAD

**Issue by rafaellyra** [michaelrambeau/bestofjs#14]
https://github.com/angular/angular
angular2!

**Comment by michaelrambeau** [comment]
@rafaellyra Thank you very much, I totally missed the fact that Angular2 was in a different repository, shame on me!
I am adding it, it will be online in 48 hours, because the application needs at least 2 daily "snapshots" of Github stars in order to show tendencies.

**Comment by michaelrambeau** [comment]
@rafaellyra Angular2 is available on bestof.js.org, at last!
Check the list here: http://bestof.js.org/tags/framework
(number 5 on the list)
