### ISSUE TITLE
colebemis/feather - open source icons with MIT license

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#140]
https://github.com/colebemis/feather

**Comment by michaelrambeau** [comment]
Hello @davojta 
Thank you, but I think that project is already on bestof.js.org.

Search for `feather` or check here: https://bestof.js.org/projects/feather

Can you confirm?

**Comment by davojta** [comment]
Oh, seems i missed it when was verifing on best of js.
