### ISSUE TITLE
Koalerplate - A simple Koa 2 boilerplate for API's using ES6.

### ISSUE THREAD

**Issue by dbalas** [michaelrambeau/bestofjs#141]
Hello, 
I'm the author of https://github.com/dbalas/koalerplate/releases.
I would love it if you could add it :)

Thank you

**Comment by michaelrambeau** [comment]
Hello Daniel @dbalas,
Your project will be available on bestof.js.org very soon, thank you for the recommendation!

**Comment by michaelrambeau** [comment]
Hello Daniel @dbalas , it's live check here: https://bestof.js.org/tags/boilerplate

Any feedback is welcome, thank you!

**Comment by dbalas** [comment]
Thank you @michaelrambeau !
