### ISSUE TITLE
Add Shaka Player

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#142]
[Shaka Player](https://github.com/google/shaka-player) - JavaScript player library / DASH client / MSE-EME player.

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Thank you for the recommendation, `Shaka Player` project will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
It's online, check the `Video` tag: https://bestof.js.org/tags/video
Thank you, any feedback is welcome!
