### ISSUE TITLE
Add clappr

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#143]
Hello Michael,
I use [clappr](https://github.com/clappr/clappr) in a couple of projects. It's a good video player.

**Comment by michaelrambeau** [comment]
Thank you Denis @gamtiq, 
`clappr` project will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
@gamtiq It's online, check the `Video` tag: https://bestof.js.org/tags/video/
