### ISSUE TITLE
Add TypeIt, the most versatile animated typing utility on the planet.

### ISSUE THREAD

**Issue by alexmacarthur** [michaelrambeau/bestofjs#144]
https://typeitjs.com/

TypeIt is the most versatile JavaScript utility on the planet for creating dynamic, realistic typewriter text effects. With simple, straightforward configuration, it allows you to type single or multiple strings that break lines, delete & replace each other, and it even handles strings that contain HTML.

For more advanced, controlled typing effects, TypeIt comes with companion functions that can be chained to control your typing down to a single character, enabling you to type an dynamic narrative, with complete control over speed changes, line breaks, deletions, and pauses.

**Comment by michaelrambeau** [comment]
Hello @alexmacarthur 
Thank you for the suggestion, `TypeIt` project will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello @alexmacarthur 
`TypeIt` project is available on bestof.js.org, check here: https://bestof.js.org/tags/animation
Thank you for your feedback!
