### ISSUE TITLE
Add Lottie

### ISSUE THREAD

**Issue by bluehat974** [michaelrambeau/bestofjs#146]
> Lottie is a mobile library for Android and iOS that parses Adobe After Effects animations exported as json with Bodymovin and renders them natively on mobile and on the web!

Documentation and Entry Point on Lottie project
http://airbnb.io/lottie/
https://github.com/airbnb/lottie

Subprojects
https://github.com/airbnb/lottie-android
https://github.com/airbnb/lottie-ios
https://github.com/airbnb/lottie-react-native
https://github.com/airbnb/lottie-web

https://github.com/chenqingspring/react-lottie
https://github.com/chenqingspring/ng-lottie
https://github.com/chenqingspring/vue-lottie

**Comment by michaelrambeau** [comment]
@bluehat974  Thank you for the recommendation.
`Lottie` will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello @bluehat974  It's online, check the `Animation` tag: 
https://bestof.js.org/tags/animation

Any feedback is welcome!
