### ISSUE TITLE
Add Platform.js

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#147]
https://github.com/bestiejs/platform.js

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Thank you, `Platform.js` will be available om bestof.js.org very soon.
It will be classified under the `Browser compatibility` tag, unless you see a more appropriate tag?
https://bestof.js.org/tags/compatibility

**Comment by gamtiq** [comment]
Hello Michael,
I suppose `Browser compatibility` tag is appropriate. Maybe it is worth also to add `Environment` tag.

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
It's online, check here: https://bestof.js.org/tags/compatibility
Thank you for this recommendation (the third from you 😄 )
