### ISSUE TITLE
Add 30 seconds of code

### ISSUE THREAD

**Issue by Chalarangelo** [michaelrambeau/bestofjs#149]
It's a learning resource/library of snippets for people to use, share and learn: https://github.com/Chalarangelo/30-seconds-of-code

**Comment by michaelrambeau** [comment]
Hello Angelos @Chalarangelo 
Thank you for the recommendation, `30 seconds of code` project will be available on bestof.js.org very soon.
`mini.css` project is doing well by the way, already 2 K stars, good job!

**Comment by Chalarangelo** [comment]
Thanks @michaelrambeau for the support and the quick reply! 👍

**Comment by michaelrambeau** [comment]
Hello Angelos @Chalarangelo ,
Not only `30 seconds of code` is availalble on bestof.js.org but also it's the hottest project today, by far!
+1.5 K stars in 24 hours, how did you do that? Teach me! 😄 
Congratulations!

![image](https://user-images.githubusercontent.com/5546996/33964687-9aa313f2-e09c-11e7-938c-5bebfa7ffc5d.png)

**Comment by Chalarangelo** [comment]
Hey @michaelrambeau, thanks for adding 30 seconds of code to bestofjs. To be honest, I have no clue how it got so big so fast, but I'm really happy to see so many people interested and actively participating in its development. 😄
