### ISSUE TITLE
Add wenk

### ISSUE THREAD

**Issue by tiaanduplessis** [michaelrambeau/bestofjs#150]
https://github.com/tiaanduplessis/wenk

**Comment by michaelrambeau** [comment]
Hello Tiaan @tiaanduplessis,
Thank you for the recommendation, `Wenk` project will be online very soon.

**Comment by michaelrambeau** [comment]
Hello Tiaan @tiaanduplessis ,
It's online, check the `Tooltip` tag, thank you!
https://bestof.js.org/tags/tooltip

**Comment by tiaanduplessis** [comment]
Thanks 😄
