### ISSUE TITLE
Grant

### ISSUE THREAD

**Issue by simov** [michaelrambeau/bestofjs#151]
:wave: 

I would like to add my OAuth middleware for Express, Koa and Hapi called [Grant](https://github.com/simov/grant). 

It's similar to Passport, but it covers only the OAuth server side login flow. However it's super easy to use and designed to support any OAuth provider with no application logic required. Currently the 'officially' supported providers are 172 in total, pretty much whatever you can think of :)

You can play around with the middleware [here](https://grant.outofindex.com/). It's a simple but really powerful application showcasing the design goal of the module - login with any number of providers without application logic required, only JSON configuration.

**Comment by michaelrambeau** [comment]
Hello @simov 
Thank you for the recommendation, `Grant` project will be available on bestof.js.org very soon!

**Comment by michaelrambeau** [comment]
Hello @simov 
It's online, check here: https://bestof.js.org/tags/auth
Thank you for your feedback!
