### ISSUE TITLE
Add TSLint

### ISSUE THREAD

**Issue by bdpartridge** [michaelrambeau/bestofjs#154]
TSLint is a linter that's widely used by TypeScript developers.

https://github.com/palantir/tslint

**Comment by michaelrambeau** [comment]
Hello @bdpartridge 
Thank you for the recommendation, `TSLint` will be online very soon.

**Comment by michaelrambeau** [comment]
Hello @bdpartridge 
It's online, check the `Linter` tag: https://bestof.js.org/tags/lint
Thank you for the feedback!

**Comment by bdpartridge** [comment]
Thanks @michaelrambeau for adding that so quickly!
