### ISSUE TITLE
ADD storybook to tag Angular

### ISSUE THREAD

**Issue by ndelangen** [michaelrambeau/bestofjs#155]
Storybook supports Angular 4+ from version 3.3 onwards. 

Would love to have it featured within the Angular tag page!

**Comment by michaelrambeau** [comment]
Hello Norbert @ndelangen 
Storybook also support Angular, that's great, it will be updated very soon.

**Comment by michaelrambeau** [comment]
Hello Norbert @ndelangen, it's done!

![image](https://user-images.githubusercontent.com/5546996/34452688-d1d53d52-ed88-11e7-9122-5a476f575f83.png)

**Comment by ndelangen** [comment]
Thanks!!
