### ISSUE TITLE
Add RockJS Framework

### ISSUE THREAD

**Issue by w3core** [michaelrambeau/bestofjs#156]
The trusty framework for old school guys!

RockJS is a minimalistic, high-performance and intuitive single-page application vanila framework.

https://rock.js.org

**Comment by michaelrambeau** [comment]
Hello Max @w3core,
I checked quickly the documentation: the PHP command line, the Eclipse IDE... you're right, it's really for old school guys! 😆 
In the other hand, it looks pretty modern with features like lazy loading, precaching, the component approach... and I like the focus on performance.
So `RockJS` will be available on bestof.js.org very soon.
But there are a lot of contenders in the `UI Framework` category, you will have to fight to survive, be warned 😄 !

**Comment by w3core** [comment]
Thank you Michael.I'm really happy to be presented on your site.

**Comment by michaelrambeau** [comment]
Hello Max @w3core 
`RockJS` is available on bestof.js.org, check the `UI Framework` tag: https://bestof.js.org/tags/framework/
