### ISSUE TITLE
Request for addition of Gijgo

### ISSUE THREAD

**Issue by atatanasov** [michaelrambeau/bestofjs#157]
Could you add my library to your website as UI Framework
github repository: https://github.com/atatanasov/gijgo
website: http://gijgo.com/

**Comment by michaelrambeau** [comment]
Hello @atatanasov 
Thank you for the suggestion, `Gijgo` project will be available on bestof.js.org very soon.
It will be classified under the `Plugin and form widget` tag but not under `UI Frameworks` tag, that means something a bit different in the context of bestof.js.org, if you don't mind.

**Comment by atatanasov** [comment]
Ok. Sounds good. Thank you!

**Comment by michaelrambeau** [comment]
@atatanasov It's online, check here: https://bestof.js.org/tags/plugin
Thank you!

**Comment by atatanasov** [comment]
Thank you.
