### ISSUE TITLE
Add Vue-Meta

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#158]
Hi there 👋 

Could you add [vue-meta](https://github.com/declandewet/vue-meta)?

It's a project recommended by Vue.js itself to handle meta tags for any web application :)

Have a great day!

**Comment by michaelrambeau** [comment]
Hello Sébastien @Atinux it's good to hear from you!
Thank you for the recommendation, `vue-meta` will be available very soon.

FYI, we are going to release very soon the 2017 edition of "Rising Stars" https://risingstars2016.js.org/ and I can tell you that your `Nuxt` project will be featured!
And in addition, there will be a French version too (dans la langue de Molière, si, si !).
Stay tuned my friend!

**Comment by atinux** [comment]
Hey @michaelrambeau 

Thank you, I feel honoured to be part of the 2017 Rising Stars :)

I recommend all my friend to visit Best of JS, and I visit it everyday since! In French too, this is great, if you need any help, ping me :-)

**Comment by atinux** [comment]
BTW @michaelrambeau, we just released Nuxt.js 1.0! https://medium.com/@nuxt_js/nuxt-js-1-0-is-out-bab1af459972

😄

**Comment by michaelrambeau** [comment]
Hello Sébastien @Atinux
It's online, check the `Vue` tag: https://bestof.js.org/tags/vue

By the way, `Nuxt` project is number 5 today, good job!

**Comment by atinux** [comment]
Great job on https://risingstars.js.org/2017/en/ @michaelrambeau, you rock :)

I noticed here (https://risingstars.js.org/2017/en/#section-ssg) that you mentation Next.js that can be used as static generator, but Nuxt.js does too and it was before Next.js does it actually :)

**Comment by michaelrambeau** [comment]
@Atinux Thank you!
About the Rising Stars, I'm going fix the content, it will be online in a few minutes.

By the way, it's an open source project, so if you want to change something, whether it's the English or the French version, do not hesitate! 😄
