### ISSUE TITLE
Add Scala.js

### ISSUE THREAD

**Issue by sjrd** [michaelrambeau/bestofjs#160]
Scala.js is the Scala to JavaScript compiler. It is increasingly popular, especially among developers/companies using Scala on the back-end. It currently has 3.2k stars on GitHub (https://github.com/scala-js/scala-js), which is at least comparable to some of the other languages in the [Compiler tag](https://bestof.js.org/tags/compiler), such as Elm and PureScript.

Would you consider adding it?

Repo: https://github.com/scala-js/scala-js
Tags: compiler

**Comment by michaelrambeau** [comment]
Thank you for the recommendation @sjrd.
`Scala.js` project will be available on bestof.js.org very soon.

**Comment by sjrd** [comment]
Thank you!

**Comment by michaelrambeau** [comment]
@sjrd It's online, check here https://bestof.js.org/tags/compiler

**Comment by sjrd** [comment]
Nice, thanks!
