### ISSUE TITLE
Request for adding Caporal

### ISSUE THREAD

**Issue by mattallty** [michaelrambeau/bestofjs#161]
Hi there, here is my request to add Caporal.js: https://github.com/mattallty/Caporal.js

thanks ! :)
Matthias

**Comment by mattallty** [comment]
already in your list, my bad :)

**Comment by michaelrambeau** [comment]
Hello @mattallty is there something wrong with the search engine of bestof.js.org?

... because it's the second time someone asks me to add a project that already belongs to _Best of JS_ 😄
