### ISSUE TITLE
Add middy

### ISSUE THREAD

**Issue by lmammino** [michaelrambeau/bestofjs#162]
🛵 The stylish Node.js middleware engine for AWS Lambda

https://middy.js.org

**Comment by michaelrambeau** [comment]
Hello @lmammino 
Thank you for the suggestion, it's online, check here: https://bestof.js.org/tags/microservice

Do you think a new tag called `Middlewares` could be useful in _Best of JS_, and can you see other great projects from _Best of JS_ that should be tagged `Middlewares`?
Thank you for your feedback!

**Comment by lmammino** [comment]
Hello @michaelrambeau, thanks a million for adding Middy 😉 
Regarding the middlewares tag it would definitely make sense as there might be many other frameworks (mostly web frameworks) that can fit in this tag very nicely.

Anyway, I think a `serverless` category would be way more interesting, especially considering that serverless is gaining a lot of traction lately and a lot of open source libraries (many in JS) are popping up every day.

**Comment by michaelrambeau** [comment]
@lmammino Sorry to ask you more questions, could you tell me how `Serveless` projects would be different from `Microservices` projects, giving me some examples?
All `Serverless` projects tags could be tagged `Microservices` but the opposite is not right because `Microservices` is a more general concept than `Serverless`, is it right?

Among _Best of JS_ projects, the following projects could be tagged "serverless":

* http://www.serverless.com/ (of course!)
* https://claudiajs.com/
* https://stdlib.com/

Can you see other projects?
Thank you for your help!

**Comment by lmammino** [comment]
No bother for the question, i am happy to help.

I think serverless is a separate concept from microservices. There's definitely an intersection between the two (as you can build microservices with a serverless approach) but I would think of them as 2 broadly different concepts.

Serverless is a paradigm in which the developer does not have to worry about provisioning the server infrastructure and make it high available as they rely on third party services offered by cloud providers. 

Serverless cloud providers generally provide services that serve as abstractions over the infrastructure covering different layers (compute, storage, networking, user management, etc.).

All this services are generally pay-per-use, which means you don't pay for idle.

In the category `serverless` i would put all the project that are focused on supporting this paradigm.

Some good examples of serverless JavaScript projects might be [the serverless framework](https://serverless.com) and similar alternatives such as [dawson](https://github.com/dawson-org/dawson-cli).

Another good resource to have a feeling of potential serverless projects for this repository might be https://github.com/anaibol/awesome-serverless

**Comment by michaelrambeau** [comment]
Hello @lmammino 
Thank you very much for the explanations.

The `Serverless` tag has been created: https://bestof.js.org/tags/serverless

I will check all the links, don't hesitate to contact us anytime you find something interesting that should be featured in _Best of JS_.

**Comment by lmammino** [comment]
Great :) thanks!
