### ISSUE TITLE
Request for adding nanogallery2

### ISSUE THREAD

**Issue by Kris-B** [michaelrambeau/bestofjs#164]
Hi @michaelrambeau 

[nanogallery2 ](https://github.com/nanostudio-org/nanogallery2) is an image/video gallery
maybe for the `image viewer` tag?

**Comment by michaelrambeau** [comment]
Hello @Kris-B 
Thank you for the suggestion, it's online, check here: https://bestof.js.org/tags/viewer

**Comment by Kris-B** [comment]
merci @michaelrambeau :smirk:
