### ISSUE TITLE
react-native-typography

### ISSUE THREAD

**Issue by hectahertz** [michaelrambeau/bestofjs#165]
Hi Michael, cool project! 😄

I thought you might want to include this library, it helps with handling typography in React Native:
https://github.com/hectahertz/react-native-typography

Thanks for the creating this! 👏🏻

**Comment by michaelrambeau** [comment]
Hello Hector @hectahertz 
OK it's coming soon.

Thank you for the kind words!

**Comment by michaelrambeau** [comment]
Hello Hector @hectahertz 
It's online, check here: https://bestof.js.org/tags/typo
Thank you for your feedback!

**Comment by hectahertz** [comment]
Awesome, thanks!
