### ISSUE TITLE
Add verdaccio npm registry

### ISSUE THREAD

**Issue by juanpicado** [michaelrambeau/bestofjs#166]
:) I think it deserves to be present here.

https://github.com/verdaccio/verdaccio

**Comment by michaelrambeau** [comment]
Hello @juanpicado 
Thank you for the recommendation, it will be available on _Best of JS_ very soon.

**Comment by juanpicado** [comment]
Thanks !!! 🎉

**Comment by michaelrambeau** [comment]
Hello @juanpicado 
It's online, check here: https://bestof.js.org/tags/package
Thank you for your feedback!

**Comment by juanpicado** [comment]
It's great @michaelrambeau thanks so much !
