### ISSUE TITLE
Add altair GraphQL IDE

### ISSUE THREAD

**Issue by imolorhe** [michaelrambeau/bestofjs#167]
Altair. GraphQL IDE for development.

https://altair.sirmuel.design/
https://github.com/imolorhe/altair

**Comment by michaelrambeau** [comment]
Hello Samuel @imolorhe 
Thank you for the recommendation, `Altair` project will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @imolorhe 
It's online, check here: https://bestof.js.org/tags/graphql
Thank you for your feedback!
