### ISSUE TITLE
Add GraphQL IO

### ISSUE THREAD

**Issue by nihilor** [michaelrambeau/bestofjs#168]
Add [GraphQL IO](http://graphql-io.com/). It's a realtime framework for GraphQL and extremely easy to use. Every GraphQL query can be switched to a realtime subscription simply by using `.subscribe()` instead of `.query()`.

Official website: [http://graphql-io.com/](http://graphql-io.com/)

**Comment by michaelrambeau** [comment]
Thank you @nihilor, it will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @nihilor 
It's online, check here: https://bestof.js.org/tags/graphql
Thank you for your feedback!
