### ISSUE TITLE
Add `rmurphey/js-assessment` project

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#17]
https://github.com/rmurphey/js-assessment
Javascript exercises for beginner education

**Comment by michaelrambeau** [comment]
@davojta OK I am adding that too.
Great because the project owner is also member of the JavaScript Hall of Fame http://bestof.js.org/hof !

**Comment by michaelrambeau** [comment]
The project is available on bestof.js.org!
http://bestof.js.org/tags/doc
