### ISSUE TITLE
Add AnyChart (Charts)

### ISSUE THREAD

**Issue by andreykh1985** [michaelrambeau/bestofjs#171]
https://github.com/AnyChart/AnyChart

**Comment by michaelrambeau** [comment]
Hello @andreykh1985 
Thank you for the suggestion, it will be available on _Best of JS_ very soon.
Just in case, do you know if there is a relation between [GraphicJS](https://github.com/AnyChart/GraphicsJS) (already available) and AnyChart? Both projects are from the same org.

**Comment by michaelrambeau** [comment]
Hello @andreykh1985 
`AnyChart` project is available on _Best of JS_, please check here: https://bestof.js.org/tags/chart
