### ISSUE TITLE
Add 30 seconds of CSS 

### ISSUE THREAD

**Issue by Chalarangelo** [michaelrambeau/bestofjs#172]
It's a learning resource/library of HTML/CSS snippets for people to use, share and learn (inspired by my 30 seconds of code project): https://github.com/atomiks/30-seconds-of-css

**Comment by michaelrambeau** [comment]
Hello Angelos @Chalarangelo 
Thank you for the suggestion.
`30 seconds of CSS` project will be available on _Best of JS_ in 48 hours, be patient!

**Comment by michaelrambeau** [comment]
Hello Angelos @Chalarangelo  it's online, please check here https://bestof.js.org/tags/learning or search for `30 seconds`.

![image](https://user-images.githubusercontent.com/5546996/36898517-81828cc2-1e5e-11e8-80f5-0628a1740a09.png)

Thank you!
