### ISSUE TITLE
Add Stimulus by Basecamp

### ISSUE THREAD

**Issue by aliakakis** [michaelrambeau/bestofjs#173]
Hello I love your site. Can you please add https://stimulusjs.org/ :-)

**Comment by michaelrambeau** [comment]
Hello @aliakakis 
Thank you for the recommendation.
`Stimulus` project will be online very soon.

**Comment by michaelrambeau** [comment]
Hello @aliakakis 
Thank you for the recommendation.
`Stimulus` project will be online very soon.

**Comment by michaelrambeau** [comment]
@aliakakis it's online, check here: https://bestof.js.org/tags/framework

**Comment by aliakakis** [comment]
Checked it yesterday :-D Thank you for the prompt reply.
