### ISSUE TITLE
Recommend SpeakingURL

### ISSUE THREAD

**Issue by pid** [michaelrambeau/bestofjs#174]
https://github.com/pid/speakingurl

Yes, I'm the author ;-)

**Comment by michaelrambeau** [comment]
Hello @pid 
Thank you for the recommendation.
Do you you know how that project could be tagged in _Best of JS_ ?
Maybe `i18n` https://bestof.js.org/tags/i18n ? 
I'm not very inspired about the right tag, please help me 😄 !

**Comment by pid** [comment]
Hi,
my recommendations:
string, URL, i18n

**Comment by michaelrambeau** [comment]
Hello @pid 
`SpeakingURL` project is available on _Best of JS_.
Check here for example: https://bestof.js.org/tags/string
