### ISSUE TITLE
NGXS

### ISSUE THREAD

**Issue by skiabox** [michaelrambeau/bestofjs#175]
NGXS is a state management pattern + library for Angular

https://github.com/amcdnl/ngxs

**Comment by michaelrambeau** [comment]
Hello @skiabox , 
Thank you for the recommendation, `NGXS` project will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
@skiabox  `NGXS` project is available here: https://bestof.js.org/tags/state
