### ISSUE TITLE
Add FilePond

### ISSUE THREAD

**Issue by rikschennink** [michaelrambeau/bestofjs#176]
Hi! Love the site, looks great and is very fast as well. Will you add [FilePond](https://github.com/pqina/filepond) to the list?

It also has adapters for jQuery, Vue and React:
- https://github.com/pqina/jquery-filepond
- https://github.com/pqina/react-filepond
- https://github.com/pqina/vue-filepond

**Comment by michaelrambeau** [comment]
Hello Rik @rikschennink 
Thank you for your kind words
`Filepond` project will be available very soon in `Best of JS`.

**Comment by rikschennink** [comment]
That is awesome @michaelrambeau!

**Comment by michaelrambeau** [comment]
@rikschennink It's online, check here: https://bestof.js.org/tags/upload

**Comment by rikschennink** [comment]
Thanks @michaelrambeau :)
