### ISSUE TITLE
Add webdash

### ISSUE THREAD

**Issue by jadjoubran** [michaelrambeau/bestofjs#177]
Hey Michael!
I'd like to suggest [webdash](https://webdash.xyz)
github [repo](https://github.com/jadjoubran/webdash)
Webdash is a customizable web dashboard
![webdash](https://user-images.githubusercontent.com/2265232/38014971-ff1a4224-3272-11e8-8afc-a25a8fbf0e4c.jpeg)

**Comment by michaelrambeau** [comment]
Hello Jad @jadjoubran, thank you for the recommendation, it will be online very soon.

**Comment by michaelrambeau** [comment]
Hello @jadjoubran it's online, check here: https://bestof.js.org/tags/dashboard

**Comment by jadjoubran** [comment]
Thanks!
