### ISSUE TITLE
Noty

### ISSUE THREAD

**Issue by evenfrost** [michaelrambeau/bestofjs#178]
[Noty](https://github.com/needim/noty) is a great notification library, which is good addition to https://bestof.js.org/tags/notify.

**Comment by michaelrambeau** [comment]
Thank you @evenfrost for the recommendation, it will be online very soon.

**Comment by michaelrambeau** [comment]
Hello @evenfrost, it's online, check here: https://bestof.js.org/tags/notify

**Comment by evenfrost** [comment]
Great, thank you!
