### ISSUE TITLE
Add React Native Expo Boilerplate

### ISSUE THREAD

**Issue by boadude** [michaelrambeau/bestofjs#179]
React-Native-Expo-Starter will help you to start your fresh new React Native project with Expo using the best practices to accelerate you coding.

- Ready to build with Expo.
- NativeBase integration. Best UI Kit for React Native.
- Domain-Driven file structure.
- Best configurations for VSCode.
- Module Resolver for fixing Relative Paths.
- Best Linting configurations and complements.
- Ready to work with Prettier, Eslint integrations and best practices.
- Redux, Redux-thunk and Redux-persist for manage state.

Repository: https://github.com/boadude/React-Native-Expo-Starter

**Comment by michaelrambeau** [comment]
Hello @boadude , it's online, check here https://bestof.js.org/tags/boilerplate
