### ISSUE TITLE
Add Egg.js

### ISSUE THREAD

**Issue by char8x** [michaelrambeau/bestofjs#180]
Hi Michael
I'd like to suggest [Egg](https://github.com/eggjs/egg)
It's born for building enterprise application and framework with Node.js & Koa.
Official website: https://eggjs.org/en/index.html

**Comment by michaelrambeau** [comment]
Hello @charles8xu, it's online, check here https://bestof.js.org/tags/nodejs-framework

**Comment by char8x** [comment]
Thanks!
