### ISSUE TITLE
Add colors.js

### ISSUE THREAD

**Issue by DABH** [michaelrambeau/bestofjs#181]
I'd like to suggest adding https://github.com/Marak/colors.js , a small Node.js utility for colorizing text that has been around for years and become ingrained in a number of other "best of" projects.  Projects that use `colors` include `winston`, `karma`, etc. -- over 10k dependents and 3k stars on GitHub.  Thanks for your consideration!

**Comment by michaelrambeau** [comment]
Thank you @DABH, it will be available on _Best of JavaScript_ very soon.

It will be under the tag called `Server CLI`, like `Chalk` library (the most popular project with the same goal, I think)

**Comment by michaelrambeau** [comment]
@DABH it's online, check here: https://bestof.js.org/tags/cli
