### ISSUE TITLE
Add The JavaScript Way book

### ISSUE THREAD

**Issue by bpesquet** [michaelrambeau/bestofjs#182]
Hi,
The JavaScript Way is an entry-level book for learning modern JavaScript, first published in August 2017. It's available for free at https://github.com/bpesquet/thejsway.
Thanks in advance.

**Comment by michaelrambeau** [comment]
Hello Baptiste @bpesquet , thank you for the recommendation, `The JavaScript way` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Baptiste @bpesquet , it's online, check here https://bestof.js.org/tags/book.
Thank you for your feedback!

**Comment by bpesquet** [comment]
Thank you too!
