### ISSUE TITLE
Consider adding Ringo

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#183]
https://ringojs.org/

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Thank you for the suggestion, I didn't know about that, could you give more feedback about what makes Ringo project great?
Is it a way to integrate easily server-side JavaScript with an existing backend written in Java?
And then, how would you "tag" such a project in _Best of JavaScript_, I can't find any similar project.
Thank you for your help!

**Comment by gamtiq** [comment]
Hello Michael,

I suppose Java interoperability is the main feature of Ringo. In other aspects it seems to be quite similar to Node.js.
Regarding to tag I think appropriate variants are "platform", "engine", "runtime" or "server-side".

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq,
Thank you for the information,  a new tag called `runtime` has been created and `RingoJS` is available on _Best of JS_, check here: https://bestof.js.org/tags/runtime

![image](https://user-images.githubusercontent.com/5546996/39840343-18e30f9c-541a-11e8-8e1a-4153e96f035d.png)
