### ISSUE TITLE
two webgl libs: regl and TWGL

### ISSUE THREAD

**Issue by wojdyr** [michaelrambeau/bestofjs#184]
I'd like to propose two entries in the 3D/WebGL tags:

- https://github.com/regl-project/regl
- https://github.com/greggman/twgl.js

Thanks for maintaining this awesome project!

**Comment by michaelrambeau** [comment]
Hello Marcin @wojdyr,
Thank you for the suggestion, both projects will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
@wojdyr The 2 projects are available on _Best of JavaScript_, check here:
https://bestof.js.org/tags/webgl

Thank you for your feedback!

**Comment by wojdyr** [comment]
Thank you Michael!
