### ISSUE TITLE
Add mocker-data-generator

### ISSUE THREAD

**Issue by danibram** [michaelrambeau/bestofjs#186]
I'd like to suggest adding [https://github.com/danibram/mocker-data-generator](https://github.com/danibram/mocker-data-generator), its a simplified way to generate masive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.

Thank you for the consideration!

**Comment by michaelrambeau** [comment]
Hello Daniel @danibram 
Thank you for the suggestion, the project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Daniel @danibram ,
It's online, check here: https://bestofjs.org/tags/random

**Comment by danibram** [comment]
thanks!
