### ISSUE TITLE
Add `NaturalIntelligence/anumargak` project

### ISSUE THREAD

**Issue by amitguptagwl** [michaelrambeau/bestofjs#187]
https://github.com/NaturalIntelligence/anumargak

Anumargak is fastest node js based web router. And it is the only router which can differentiate similar and same URLs. Eg

`\this\is\:age([0-9]+)` and `\this\is\:name([a-zA-Z]+)`

**Comment by michaelrambeau** [comment]
Hello Amit @amitguptagwl, thank you for the recommandation, it will be available very soon.

It's your second submission after `Stubmatic` project, it's nice to see you again 😄 

How things are going for your project ?

**Comment by amitguptagwl** [comment]
This is actually my 3rd submission. :smile: 

Things are going pretty good. I've developed many more projects like [nimn](http://nimn.in) but unfortunately I'm failing to bring them in everyone's attention.

Thanks for asking.

**Comment by michaelrambeau** [comment]
Oh right, it will be your 3rd project on _Best of JavaScript_, I forgot about `fast-xml-parser`, sorry!

**Comment by amitguptagwl** [comment]
You're so kind. Thanks to make bestof.js.org

**Comment by michaelrambeau** [comment]
Hello Amit @amitguptagwl 
It's online, check here: https://bestofjs.org/tags/routing
See you next time!

**Comment by amitguptagwl** [comment]
Many thanks @michaelrambeau
