### ISSUE TITLE
Add Theia

### ISSUE THREAD

**Issue by akosyakov** [michaelrambeau/bestofjs#188]
Theia is a cloud & desktop IDE framework implemented in TypeScript.

http://theia-ide.org/
https://github.com/theia-ide/theia
https://hub.docker.com/r/theiaide/theia/

**Comment by michaelrambeau** [comment]
Thank you Anton @akosyakov 
It will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Helllo Anton @akosyakov , it's online, check "IDE" tag:
https://bestofjs.org/tags/ide

Thank you for your feedback!
