### ISSUE TITLE
Add request: Reclare

### ISSUE THREAD

**Issue by oguzgelal** [michaelrambeau/bestofjs#189]
Hey, I'm the author of Reclare. Reclare is a declarative state and logic management library.
https://github.com/reclarejs/reclare

**Comment by michaelrambeau** [comment]
Hello Oguz @oguzgelal 
Thank you for the recommendation!
Actually `Reclare` is already available on _Best of JavaScript_, check the "State Management" tag:
https://bestofjs.org/tags/state

Thank you for your feedback!

**Comment by oguzgelal** [comment]
Oh awesome @michaelrambeau, thank you!
