### ISSUE TITLE
Add project : anticore

### ISSUE THREAD

**Issue by Lcfvs** [michaelrambeau/bestofjs#192]
anticore is a generic living DOM library to simplify your client code, like with its easiest middleware manager for AJAX requests. 

https://github.com/Lcfvs/anticore

;)

**Comment by michaelrambeau** [comment]
Hello @Lcfvs ,
Thank you for the suggestion.
I've checked and I have to confess that I'm struggling to understand the scope of the library, I think you should improve the documentation, if possible.

Starting with the project description:

> A generic living DOM library to simplify your client code, like with its easiest middleware manager for AJAX requests. 

What means "living"? it's not a dead library, it's still under active development, I guess?  

And then that "its easiest middleware manager" example, it means the easiest way to handle AJAX requests in the world? But I could not find any explanation about that feature.

As a developer, when I check a new project, I want to understand the context first, the big picture, for example:

* is `anticore` an alternative to jQuery? 
* Is it similar or [Umbrella](https://umbrellajs.com/)?
* What's the main benefit of using it?
* What are the highlighted patterns?

I couldn't find a documentation that mentions all available functions, I can jump from README.md to README.md but the documents don't explain what the function do.

It would be nice to get a complete documentation with explanations and example, like here, for example:
https://umbrellajs.com/documentation

The available documentation https://lcfvs.github.io/anticore/ seems to be a draft: no styling at all, it's fine, but you should explain what's the purpose of every example, it looks like a testing page you did for yourself more than a documentation you want to share with the rest of the world.

About the code itself, I noticed you import the functions like this in the README.md

```js
import { append } from 'anticore/dom/tree/append'
import { remove } from 'anticore/dom/tree/remove'
import { replace } from 'anticore/dom/tree/replace'
```

In addition, it would be nice to be able to import everything from a single `import` statement, taking advantage of the "named" exports.

```js
import { append, remove, replace } from 'anticore/dom/tree'
```

It would be even better to be able to impoty any function from a single entry point.


Sorry for this long feedback, I can see you put a lot of effort in this project (118 releases... wow!).

Let me know if my feedback makes sense, I may have missed a lot of points, thank you for your understanding!

Merci et bon courage! 😄

**Comment by Lcfvs** [comment]
Hi @michaelrambeau,

Merci beaucoup pour ce feedback. :P 

It's a living library, means designed to evolve, a few like the HTML5 Living Standard. 

About the doc improvements, I will. I'm just running out of time, for the moment, between the projects of my clients, mines and my suite of PHP libraries. But, again, I will, this request is perhaps a bit too hasty.

About the anticore's goal, at it's beginning, anticore was only a front-end expressjs, where the routes are the query selectors and the retrieved object is and element, in place of a request object.

With the time, I added a lot of DOM utils and anticore begins to be a jQuery alternative, which only packs (using a webpack or any other packager) what we really use, based on separated imports and offer a very simple way to deal with DOM AJAX contents.

How simple ? We don't have to build the AJAX requests (it's why you don't see some AJAX code), anticore do them automatically, based on form/anchors. We have only to define what we want to do with the fetched nodes.

Furthermore, it really changes your code design/rereading, there is no callbacks/promises to fetch-and-treat, it simplify the server errors management, ...

If you start a new project, I invite you to just test it or check the demos code to see what it changes and the few code needed.

About the single entry point, it's a few concept-killer, because anticore is thought to be big, really big, embedding a lot of generic features, shareable between projects, but we don't want to have all of that in our dist package, it isn't ? ;)

If some things aren't clear, don't hesitate to let me know.

**Comment by michaelrambeau** [comment]
Hello again @Lcfvs,
Thank you for the answers, what you described is interesting, but how someone who has never heard about that is supposed to know if it's not written in the documentation?

For example, I may have missed it, but where do you explain that concept:

> We don't have to build the AJAX requests (it's why you don't see some AJAX code), anticore do them automatically, based on form/anchors

Do you see what I mean? How other developers react when you show them this repo, I guess they feel lost like me? (And I guarantee you that I spend a lot of time on GitHub 😄 )

That's why I requested a better documentation, at least a complete README.md that starts by explaining the big picture, the goal, your motivation, the problem you try to solve and then give more details, listing the available features...

I think the documentation is as much important as the features themselves.
You spent so much time and energy on your project, it really deserves a better documentation :) it's how your project will get traction among other developers, look at other succesful projects.

Do you think you could make the documentation look better? Thank you again!

**Comment by michaelrambeau** [comment]
Closing the issue  because from now only projects with more than 50 stars are eligible.
It may change in the future if we find a way to make the selection process automatic.
Thank you for your understanding!

**Comment by Lcfvs** [comment]
No problem, we are currently working on a full doc & tutorials...

See you soon ;)
