### ISSUE TITLE
Would you add my project to bestofjs?

### ISSUE THREAD

**Issue by mbrn** [michaelrambeau/bestofjs#193]
https://github.com/mbrn/material-table 

it is a datatable based on react, material-ui components.

**Comment by michaelrambeau** [comment]
Hello Mehmet @mbrn ,

Thank you for the suggestion, `material-table` will be available on _Best of JavaScript_ very soon.

**Comment by mbrn** [comment]
Hello @michaelrambeau,

Thanks.

**Comment by michaelrambeau** [comment]
Hello @mbrn 
It's online, check here: https://bestofjs.org/tags/table

**Comment by mbrn** [comment]
Thank you @michaelrambeau
