### ISSUE TITLE
Update package info

### ISSUE THREAD

**Issue by tricoder42** [michaelrambeau/bestofjs#195]
Hi,
I can't figure out how to update package info at the website.

In this project: https://bestofjs.org/projects/jslingui, could you please change npm package to `@lingui/react` (`lingui-react` was obsolete few months ago) and change the name to `LinguiJS` (I'm rolling out new name gradually to be consistent with js ecosystem)?

Thanks a lot!

**Comment by michaelrambeau** [comment]
Hello @tricoder42 
OK, it will be fixed the next time the site is rebuilt, in 24 hours.
I will confirm when it's online, stay tuned!

**Comment by michaelrambeau** [comment]
Hello @tricoder42 
The project page has been updated, please check here: https://bestofjs.org/tags/i18n
Thank you!

**Comment by tricoder42** [comment]
Thank you very much!
