### ISSUE TITLE
Add react-admin

### ISSUE THREAD

**Issue by fzaninotto** [michaelrambeau/bestofjs#196]
Hi, I suggest adding react-admin (https://github.com/marmelab/react-admin) to your database. With more than 5k stars, it's a reasonably popular library to figure out in your list ;)

Cheers,

François (co-creator of react-admin)

**Comment by michaelrambeau** [comment]
Hello François @fzaninotto 

Thank you for the suggestion, `react-admin` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @fzaninotto 
It's online, check here: https://bestofjs.org/tags/dashboard

On _Best of JavaScript_, `ng-admin` project is doing well by the way.
Thank you for your feedback!

**Comment by fzaninotto** [comment]
Thanks a lot for adding it!
