### ISSUE TITLE
Add cellx

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#197]
https://github.com/Riim/cellx

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Thank you for the suggestion.

I was checking the Benchmark in the README.md and I was wondering why it mentions frameworks like _Knockout_ but not _Vue.js_ or _Angular_, and libraries like _Reactive.js_ but not _Rx.js_ or _Bacon.js_ that are far much popular and implement the reactive pattern too, if I understand correctly.

Do you now the authors or have you used this library?
Thank you for your feedback!

**Comment by gamtiq** [comment]
Hello Michael,

I don’t know the author of cellx and haven’t used the library in real projects.
A couple of my personal suppositions regarding the benchmark.
Knockout has concept of [observables](https://knockoutjs.com/documentation/observables.html) (has dedicated API) so in some extent can be used as reactive programming library. In contrast to Knockout, Angular nor Vue doesn’t have similar concept or API.
Concerning Rx.js or Bacon.js I suppose that their absence in benchmark is a wish of the author to show cellx to the best advantage. But I should note that both Rx.js and Bacon.js are more complex libraries considering their API and size.

**Comment by michaelrambeau** [comment]
Thank you Denis @gamtiq `cellx` project will be available in _Best of JavaScript_ very soon.

So far the concept of "Reactive Programming" was more or less covered by the tag called [Streams](https://bestofjs.org/tags/stream) but I'm going to add a new tag, more specific, called "Reactive Programming" that would include the following projects:

* cellx (coming soon!)
* Kefir (coming soon too, it was not tracked by _Best of JavaScript_)
* RxJS
* BaconJS
* xstream
* most
* Marble.js
* Knockout
* Ractive.js
* Mobx

Does it make sense? Can you see other projects from _Best of JavaScript_ that belong to this category? (some other UI frameworks maybe?)

Thank you for your help!

**Comment by gamtiq** [comment]
Hello Michael,


> Does it make sense?

I think the new proposed tag "Reactive Programming" will be useful for users of _Best of JavaScript_.

> Can you see other projects from Best of JavaScript that belong to this category?

At the moment I don’t see any appropriate projects from _Best of JavaScript_ besides mentioned that can be tagged by "Reactive Programming".

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
OK, `cellx` project and the new tag `Reactive programming` are available on _Best of JavaScript_.

Could you check here: https://bestofjs.org/tags/reactive

Thank you again!
