### ISSUE TITLE
Add `Ben Lesh` to Wall of Fame

### ISSUE THREAD

**Issue by MrGWest** [michaelrambeau/bestofjs#198]
Big name in RxJS and Angular.

**Comment by michaelrambeau** [comment]
Hello @MrGWest 
Thank you for the suggestion, Ben Lesh has been inducted into the JavaScript Hall of Fame!

![image](https://user-images.githubusercontent.com/5546996/46766336-aa9d1600-cd1c-11e8-9599-aac84ca9ddbb.png)
