### ISSUE TITLE
Suggestion: add fast-check in testing category

### ISSUE THREAD

**Issue by dubzzz** [michaelrambeau/bestofjs#199]
fast-check is a property based testing framework for JavaScript

**Comment by michaelrambeau** [comment]
Hello Nicolas @dubzzz
Thank you for the suggestion.
`fast-check` project will be available on _Best of JavaScript_ very soon.

Just a question: the project description says:

> Property based testing framework for JavaScript **(like QuickCheck)**...

But I can't find any reference to "QuickCheck" in the README.md... so what is QuickCheck?
(maybe you could add a link about that in the project README.md)

Sorry for my ignorance! 😄

**Comment by dubzzz** [comment]
Hi @michaelrambeau,

Good catch, I think I will add a quick note on what is QuickCheck.

In a nutshell, QuickCheck is a framework written in haskell. It introduced the idea of property based testing.

Most of the time people looking for such frameworks are either searching for 'QuickCheck in JavaScript' or 'Property based testing in JavaScript'.

For more details, I published a medium article explaining the philosophy - https://medium.com/criteo-labs/introduction-to-property-based-testing-f5236229d237

Thanks a lot ;)

**Comment by michaelrambeau** [comment]
Thank you for the explanation Nicolas @dubzzz.

**Breaking News**: `fast-check` projet is available on _Best of JavaScript_, check the "Testing" tag!

https://bestofjs.org/tags/test?page=2

**Comment by dubzzz** [comment]
Thanks a lot ;)
