### ISSUE TITLE
Add `mozilla/popcorn-js` project

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#20]
https://github.com/mozilla/popcorn-js
Framework for creating rich media \ multimedia pages from Mozilla

**Comment by michaelrambeau** [comment]
Hello @davojta ! Thank you for the suggestion.
Do you think the project is still maintened ? Last commit is 16 months ago (June 2015) !
Or do you think it's better / different than projects from here: http://bestof.js.org/tags/audio-video (like video.js for example)
Thank you for your feedback in advance!

**Comment by davojta** [comment]
@michaelrambeau Video.js is awesome, but popcorn.js is about different. Popcorn is more like library for creating multi \ cross media interactive pages then just player. But seems  it abandoned since i used it last time (near 1-2 year ago ). So we can skip it as we are creating the best of stuff

**Comment by michaelrambeau** [comment]
OK, Thank you very much for your feedback!
