### ISSUE TITLE
I recommend Chris Nwamba

### ISSUE THREAD

**Issue by cjustinobi** [michaelrambeau/bestofjs#200]
I think Chris Nwamba should be on the list of  Hall Of Fame having seen his tremendous impact on the JavaScript community.

He had authored two books: [hands on next](https://www.honext.io/) and [Typescript for Angular Developers](https://www.packtpub.com/web-development/typescript-angular-developers)

Chris is great at his game in terms of community building. He co-organizes the largest Africa Developer community forLoop Africa, Angular Nigeria, Frontstack etc.

Codebeast deserves the spot.

**Comment by michaelrambeau** [comment]
Hello Justin @Cejowisz ,

Thank you for the recommendation, Christian Nwamba will be in the _JavaScript Hall of Fame_ in a few hours.

**Comment by michaelrambeau** [comment]
Christian Nwamba is now a member of the official _JavaScript Hall of Fame_!

![image](https://user-images.githubusercontent.com/5546996/48809576-79c2ee80-ed68-11e8-8a29-e584621cb603.png)

**Comment by cjustinobi** [comment]
Thanks  @michaelrambeau
