### ISSUE TITLE
Add Webix UI components framework

### ISSUE THREAD

**Issue by dandv** [michaelrambeau/bestofjs#201]
[Webix](https://webix.com/) is a responsive UI components library aimed at making admin apps very simple to write (see the [playground demo](https://snippet.webix.com/basic)). It has [60+ widgets](https://webix.com/widget/datatable/), from the simple (accordion, carousel, menus etc.) up to data tables, tree tables, treemaps and others.

![Webix screenshot](https://i.stack.imgur.com/DixaM.png)

Funding comes from a commercial edition with some advanced widgets (Pivot, Scheduler, Kanban, org chart etc.). The [GPL3 edition](http://webix.com/licenses/) [allows commercial use](http://forum.webix.com/discussion/2114/webix-gpl-as-ui-on-commercial-server) and lets non-GPL applications using Webix keep their license, e.g. MIT, via a [license exemption for FLOSS](http://forum.webix.com/discussion/4023/does-an-open-source-app-that-uses-webix-have-to-become-gpl-licensed).

Webix [integrates](https://blog.webix.com/uis-components-with-react-framework/) with React, Vue, Angular, and jQuery.

[Wikipedia](https://en.wikipedia.org/wiki/Webix) • [GitHub](https://github.com/webix-hub) • [Admin dashboard demo](http://webix.com/demos/admin-app/) • [Demos](http://webix.com/demos) • [Widget samples](http://docs.webix.com/samples)

**Comment by michaelrambeau** [comment]
Hello Dan @dandv 
Thank you for the recommendation.
Just to confirm, is the following link correct?
https://github.com/webix-hub/webix

I'm asking because _Best of JavaScript_ tracks only open-source projects available on GitHub.
That's why "ExtJS" is not tracked for example (unless I'm mistaken or if things have since last time I checked).

Thank you in advance for your feedback!

**Comment by dandv** [comment]
Correct, that's the link to their GitHub repo. I think Webix is an amazing UI components toolkit, that could benefit from more exposure!

**Comment by michaelrambeau** [comment]
Thank you @dandv `Webix UI` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @dandv
`Webix UI` is available on _Best of JavaScript_, check the `Component Toolkit` tag for example:

https://bestofjs.org/tags/component

Thank you again for your feedback!
