### ISSUE TITLE
Update dojo reference

### ISSUE THREAD

**Issue by dylans** [michaelrambeau/bestofjs#202]
The project listed at https://bestofjs.org/projects/dojo , @dojo/core , has been replaced by @dojo/framework, http://github.com/dojo/framework.

**Comment by michaelrambeau** [comment]
Thank you Dylan, that will be fixed very soon.

**Comment by michaelrambeau** [comment]
Hello Dylan @dylans 

`Dojo` GitHub repo has been fixed.

Could you check again? (checking the `UI framework` tag for example: https://bestofjs.org/tags/framework)

**Comment by dylans** [comment]
Thanks @michaelrambeau... it looks mostly correct except under the section titled package which seems to still refer to @dojo/core and version 2.0.0 instead of @dojo/framework and version 4.0.0.

**Comment by michaelrambeau** [comment]
@dylans Sorry for the miss about the NPM package section.

The site has just been rebuilt, taking into account `@dojo/framework`, could you check again?

![image](https://user-images.githubusercontent.com/5546996/48984834-4a372c00-f144-11e8-8489-85434b80c4b7.png)

**Comment by dylans** [comment]
Looks great, thanks!
