### ISSUE TITLE
Add ant-design-landing

### ISSUE THREAD

**Issue by jljsj33** [michaelrambeau/bestofjs#204]
https://github.com/ant-design/ant-design-landing

**Comment by michaelrambeau** [comment]
Hello @jljsj33 
Thank you for the suggestion.
If my understanding is correct, _Ant Design Landing_ is an online tool to generate landing pages from templates, made with _Ant Design_ components?
It seems the [online editor](https://landing.ant.design/edit/) is only available in Chinese?

**Comment by jljsj33** [comment]
I am translating, temporarily closing.
