### ISSUE TITLE
Add `Atinux` user to the Hall of Fame

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#207]
It's me, I have seen this on https://bestofjs.org/hall-of-fame

![screenshot 2018-12-24 at 15 14 29](https://user-images.githubusercontent.com/904724/50401409-acf50500-078e-11e9-94b5-6155a5e77a94.png)

So I am taking my chance 😄

**Comment by michaelrambeau** [comment]
Hello Sébastien @Atinux 
That's a very good idea, you will be inducted to the official _JavaScript Hall of Fame_ in less than 24 hours.
🎄  Joyeux Noël chez toi !

**Comment by atinux** [comment]
Thank you :)
Merci et joyeux Noel à toi aussi !

**Comment by michaelrambeau** [comment]
Congratulations @Atinux,
You are now a member of the _Hall of Fame_!

<img width="948" alt="image" src="https://user-images.githubusercontent.com/5546996/50436911-39d4c580-092b-11e9-81f1-bc44f1a67b6f.png">

**Comment by atinux** [comment]
<3

**Comment by michaelrambeau** [comment]
Hello Sébastien @Atinux !
As a member of the JavaScript Hall of Fame your opinion is really important ;)

Before we release officially the _2018 JavaScript Rising Stars_ do you have any feedback? https://risingstars.js.org/2018/en

And then, when the project is ready to launch (next week), it would be great if you could mention the project since _Nuxt_ is doing really well!

**Comment by atinux** [comment]
Hey @michaelrambeau 

Thank you for asking, I am really happy to see Nuxt in the rising stars <3

One thing is about the Static Sites generator, actually Nuxt.js is also a static site generator the same as VuePress or GridSome (see https://docs.google.com/spreadsheets/d/1SrerEcQKeMcwtbLonhnmlV4nuPBzNJ_MYFZPM3tRvRI/edit#gid=0), a lot of people uses `nuxt generate` before deploying their Nuxt static websites :)
Actually, nuxtjs.org has been static generated and hosted on Netlify so we don't have any node.js server.

**Comment by atinux** [comment]
About the icon, could you use the svg one? https://s3.amazonaws.com/media-p.slid.es/uploads/9256/images/5490030/nuxt.svg

**Comment by michaelrambeau** [comment]
Hello again @Atinux thank you for the feedback!

`Static Site Generator` tag has been added to both `Next.js` and `Nuxt` projects:

* Best of JavaScript: https://bestofjs.org/tags/ssg
* Rising Stars: https://risingstars.js.org/2018/en/#section-ssg

The project icon has been updated, using the svg file.
