### ISSUE TITLE
Add vant

### ISSUE THREAD

**Issue by chenjiahan** [michaelrambeau/bestofjs#208]
Lightweight Mobile UI Components built on Vue.
https://github.com/youzan/vant

**Comment by michaelrambeau** [comment]
Hello @chenjiahan 
Thank you for the suggestion, `vant` project will be available on _Best of JavaScript_ very soon.

**Comment by chenjiahan** [comment]
Thank you 😊

**Comment by michaelrambeau** [comment]
Hello @chenjiahan 
`Vant` project is available on _Best of JavaScript_, check the `Vue` tag: https://bestofjs.org/tags/vue

**Comment by chenjiahan** [comment]
👍Very efficient
