### ISSUE TITLE
Add hotkeys

### ISSUE THREAD

**Issue by jaywcjlove** [michaelrambeau/bestofjs#209]
[hotkeys.js](https://git.io/hotkeys.js) : ➷ A robust Javascript library for capturing keyboard input. It has no dependencies.

**Comment by michaelrambeau** [comment]
Hello @jaywcjlove 

Thank you for the suggestion but `hotkeys.js` is already available on _Best of JavaScript_!

Check here: https://bestofjs.org/tags/keyboard

I wonder why you couldn't find it, is there something wrong with the search engine? 🤔

**Comment by jaywcjlove** [comment]
@michaelrambeau I found out, my mistake. thx!
