### ISSUE TITLE
Add `mozilla/pdf.js` project

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#21]
https://github.com/mozilla/pdf.js
Lib to render pdf in browser

**Comment by michaelrambeau** [comment]
Thank you @davojta , I am adding a new tag called`pdf` in the application, with that project.

**Comment by michaelrambeau** [comment]
Also, I am adding this project: https://github.com/MrRio/jsPDF 
Let me know if you know a better tool to generate pdf (so that https://github.com/mozilla/pdf.js will not be the only project with the `pdf` tag).

**Comment by michaelrambeau** [comment]
it's online!
http://bestof.js.org/tags/pdf

![image](https://cloud.githubusercontent.com/assets/5546996/19288942/5f91454a-9043-11e6-83e8-80c92dfbfbe6.png)
