### ISSUE TITLE
Add `kireerik/refo` project

### ISSUE THREAD

**Issue by kireerik** [michaelrambeau/bestofjs#210]
https://github.com/kireerik/refo

**Comment by michaelrambeau** [comment]
Hello @kireerik 
It's a bit difficult to understand what is the purpose of the project, I had trouble finding the running demo link, I guess it's this one: https://kireerik.github.io/refo/resume/ and I find the instructions to get started confusing.

It seems that your project `refo` is able to build a webpage from a JSON file (this one? https://github.com/kireerik/refo/blob/c6e14deaeb993044b25145994786dea85cf14eb4/example/asset/resume/data.json) but I think it should be documented.
Sorry if I missed something about the documentation, I may have missed something obvious.

Also maybe it would be simpler to use `refo` if it was a package published on NPM?

So It would be great if you could improve these points, thank you for your understanding!

**Comment by kireerik** [comment]
Hi @michaelrambeau

The link to the "running" demo is here within the example folder (https://github.com/kireerik/refo/tree/master/example#refo-example): https://kireerik.github.io/refo/
It is hosted from this folder: https://github.com/kireerik/refo/tree/master/docs

Do you find the instructions confusing to get started with the [Refo Example](https://github.com/kireerik/refo/tree/master/example) or with [Refo](https://github.com/kireerik/refo#usage) it self?

This is not a built-in feature, but yes the example does that too. It is really flexible. You can do anything you can do with Node.js.
The example is not the simplest example possible.

`Refo` is a package on NPM as you can see here: https://github.com/kireerik/refo#packages
Currently Refo has 9 package published on npm.

**Comment by michaelrambeau** [comment]
Hello @kireerik 
Thank you for the explanation and sorry for the late reply.
In order to limit the numbers of projects included in _Best of JavaScript_ , from now, only projects with more than 50 stars are eligible.
To be able to show more projects (including yours!), the application needs a different architecture, now all the 1500 projects are loaded from a single JSON file when the application starts, it does not scale very well.
Sorry for this news, and thank you for the energy you put in _Refo_ project!

**Comment by kireerik** [comment]
Thank you!

Is this still the case?

I have updated the project.

Can you check it again?:
- https://github.com/kireerik/refo

**Comment by michaelrambeau** [comment]
Hello @kireerik long time no see 😄 

Yes, there is still the same condition (actually it's 100 stars according to the issue template).
To get there, I'd say try to promote your project, explaining what problems if solves, especially compared to solutions like Astro (that I like very much) and other contenders from the "Static Site" category.

Good luck!

**Comment by kireerik** [comment]
Yes, I am working on the promotion. Did you checked the description in the readme?

Astro is good. Actually, I used Astro for Refo, but recently I moved it to use [dynohot](https://github.com/braidnetworks/dynohot) (hot module reloader for Node.js) (before Astro I used [sidorares/hot-module-replacement](https://github.com/sidorares/hot-module-replacement) (very similar to dynohot) (more information: https://github.com/braidnetworks/dynohot/issues/6#issuecomment-1960504443)).

I think if you like Astro then you will like Refo as well. Maybe even more.
Refo is fully Node.js based. So there is no need for adopting new concepts like Astro templates. We can just use Node.js modules and the result and how it works is similar, but with no limitations. Astro has a couple.

Maybe you can try the Refo template? I am curious how you would like it.

> By the way I have another repository (#91). That one has 100+ stars, but I can't find it on Best of JS currently.
