### ISSUE TITLE
Add omniclone to bestofjs

### ISSUE THREAD

**Issue by jfet97** [michaelrambeau/bestofjs#212]
Hi, yesterday I was on github trending with this project and I'd like to see it on bestofjs.
Starting from nothing the project reached more than 100 stars in one day :D

It allows objects deep cloning and supports lot of stuff :)

Link: https://github.com/jfet97/omniclone
Test: https://npm.runkit.com/omniclone

**Comment by michaelrambeau** [comment]
Hello Andrea @jfet97 

Thank you for the recommendation and congratulations for the success of that library!

`omniclone` will be available on _Best of JavaScript_ very soon, under the `JSON` tag.

**Comment by jfet97** [comment]
Thanks :D

I don't know if `JSON` is the most appropriate tag, but I honestly do not know what else to choose so I trust you ;)

Best Regards

**Comment by michaelrambeau** [comment]
You're totally right Andrea @jfet97 , JavaScript objects are more complex than JSON, it's not appropriate.

Maybe we could tag under "Data structure"? https://bestofjs.org/tags/data-structure

Or what we need is a new tag "Object manipulation"... 🤔 

Thank you for helping me with this difficult question!

**Comment by jfet97** [comment]
Yes maybe `Data structure` is more appropriate.

What about `Object manipulation`? Mhhh...mine is not properly an object manipulation because the source remains untouched, but in a more general sense it could be seen as an object manipulation.

**Comment by michaelrambeau** [comment]
Hello Andrea @jfet97 

`Omniclone` is available on _Best of JavaScript_, check here: https://bestofjs.org/projects/omniclone

The discussion about the tagging is still open of course 😄 !

**Comment by jfet97** [comment]
Nice thanks :D
