### ISSUE TITLE
add `ant-design-vue` project 

### ISSUE THREAD

**Issue by tangjinzhou** [michaelrambeau/bestofjs#213]
https://github.com/vueComponent/ant-design-vue
An enterprise-class UI components based on Ant Design and Vue.
Thank you!

**Comment by michaelrambeau** [comment]
Thank you @tangjinzhou for the recommendation!

_Ant Design Vue_ will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @tangjinzhou ,

`Ant Design Vue` is available on _Best of JavaScript_, check here: https://bestofjs.org/tags/component

Thank you!

**Comment by tangjinzhou** [comment]
Thank you for doing that so soon! @michaelrambeau
