### ISSUE TITLE
Add rrweb to bestofjs

### ISSUE THREAD

**Issue by Yuyz0112** [michaelrambeau/bestofjs#214]
https://github.com/rrweb-io/rrweb
rrweb is a tool for recording and replaying users' interactions on the web.

**Comment by michaelrambeau** [comment]
Hello @Yuyz0112 thank you for the recommendation.

`rrweb` will be available on _Best of JavaScript_ very soon, under the following tags:

* "Debugging": https://bestofjs.org/tags/debug
* "Browser Automation": https://bestofjs.org/tags/auto

Let me know if the tagging is correct, thank you!

**Comment by Yuyz0112** [comment]
Yes it is.

**Comment by michaelrambeau** [comment]
Hello @Yuyz0112 
`rrweb` is available on _Best of JavaScript_, check here: https://bestofjs.org/tags/debug
Thank you!

**Comment by Yuyz0112** [comment]
Thanks! Feel free to close this issue.

**Comment by poozhu** [comment]
npm url for this project  
https://www.npmjs.com/package/rrweb
