### ISSUE TITLE
Add Accounts.js

### ISSUE THREAD

**Issue by SachaG** [michaelrambeau/bestofjs#215]
Suggested for the Authentication category: https://github.com/accounts-js/accounts

**Comment by michaelrambeau** [comment]
Thank you @SachaG it will be available on _Best of JavaScript_ very soon.

But what's that logo 😆 ?

![image](https://user-images.githubusercontent.com/5546996/51241257-c588c180-19c0-11e9-8776-6d8f3ce62c3f.png)

**Comment by michaelrambeau** [comment]
Hello @SachaG , `accounts.js` is available on _Best of JavaScript_, check here: 

https://bestofjs.org/tags/auth

But they still have that weird dragon on their website!

**Comment by SachaG** [comment]
haha, cc @TimMikeladze
