### ISSUE TITLE
Add machinelearn.js

### ISSUE THREAD

**Issue by JasonShin** [michaelrambeau/bestofjs#216]
Please add it under Machine Learning tag =) https://github.com/machinelearnjs/machinelearnjs

**Comment by michaelrambeau** [comment]
Hello Jason @JasonShin 
Thank you for the recommendation, `machinelearn.js` project will be available on _Best of JavaScript_ very soon.

**Comment by JasonShin** [comment]
Can you also add a new tag called "statistics" and add machinelearn.js under `machine-learning` and `statistics`?

**Comment by devjiro76** [comment]
Kalimdor is really super very powerful crazy project.

**Comment by michaelrambeau** [comment]
Hello again Jason @JasonShin 

About the new `statistics` tag, besides this project https://bestofjs.org/projects/simple-statistics can you see other projects that should be tagged under the same tag? (whether they are already tracked by _Best of JavaScript_ or not)

@devjiro76 sorry I couln't find the project you mentioned.

**Comment by JasonShin** [comment]
@michaelrambeau I think mathjs can be tagged with `statistics` as well http://mathjs.org/docs/reference/functions.html#statistics-functions

**Comment by michaelrambeau** [comment]
Hello Jason @JasonShin `machinelearn.js` is available on _Best of JavaScript_, check here:

https://bestofjs.org/tags/stats

Thank you!
