### ISSUE TITLE
Add Slonik

### ISSUE THREAD

**Issue by gajus** [michaelrambeau/bestofjs#218]
* https://github.com/gajus/slonik
* https://medium.com/@gajus/processing-large-volumes-of-data-safely-and-fast-using-node-js-and-postgresql-6aa62392cadb

**Comment by michaelrambeau** [comment]
Hello @gajus 
Thank you for the recommendation, `Slonik` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @gajus 
`Slonik` project is available on _Best of JavaScript_, check here for example: https://bestofjs.org/tags/db
Thank you for your feedback!
