### ISSUE TITLE
goober

### ISSUE THREAD

**Issue by cristianbote** [michaelrambeau/bestofjs#220]
Not sure how this works, but goober might be a great candidate to be added.

**Comment by michaelrambeau** [comment]
Hello Cristian @cristianbote 
So you want to compete in the [CSS-in-JavaScript](https://bestofjs.org/tags/css-in-js) category with https://github.com/cristianbote/goober project?
No problem 😄 !
Thank you for the recommendation, `Goober` project will be available on _Best of JavaScript_ very soon.

**Comment by cristianbote** [comment]
Hey Michael,

Thanks! 🎉

Yeah, 😄 let's say it's not competing but rather a different take on it 🙌.

Also, sorry for the sparse details from the issue. I've added it from my phone and I had the feeling that it's not an actual issue but rather something else. I was wrong 😄.

Anyway, you are doing a great job! So, thank you again!

**Comment by michaelrambeau** [comment]
Hello Christian @cristianbote ,
Thank you for your kind words!

`Goober` project is available on _Best of JavaScript_, check here: https://bestofjs.org/tags/css-in-js
