### ISSUE TITLE
Add Inputmask

### ISSUE THREAD

**Issue by ramijarrar** [michaelrambeau/bestofjs#222]
For "Plugin & form widget" category: https://github.com/RobinHerbots/Inputmask

**Comment by michaelrambeau** [comment]
Hello Rami @ramijarrar 
Thank you for the suggestion.
`Inputmask` project will be available on _Best of JavaScript_ very soon.

Do you think we should add  a more specific category called "Input Mask" to gather similar projects:

* Text Mask
* imaskjs
* RIFM
* Cleave.js (the one that was the hottest over the last weeks)

Thank you for your feedback!

**Comment by michaelrambeau** [comment]
Hello Rami @ramijarrar 
`Inputmask` project is available on _Best of JavaScript_.

Check the new category "Input Mask": https://bestofjs.org/tags/mask

Thank you in advance!

![image](https://user-images.githubusercontent.com/5546996/55044172-95266900-507c-11e9-8242-c726f954e9af.png)
