### ISSUE TITLE
Mark hybrids as a UI Framework

### ISSUE THREAD

**Issue by smalluban** [michaelrambeau/bestofjs#223]
Thanks for adding [hybrids](https://github.com/hybridsjs/hybrids) to the list! I would like to ask for marking the library with UI framework tag. I was looking for an option for that, but there is none, so I assume that it has to be done through the issue.

**Comment by michaelrambeau** [comment]
Hello Dominik @smalluban , thank you for reaching us.
There is no way to let users add tags indeed,  it's something that should be improved.
`Hybrids` project will be tagged under "UI framework", I will tell you when it's online, in less than 12 hours.
Feel free to suggest anything about _Best of JavaScript_.
Thank you for your feedback!

**Comment by smalluban** [comment]
👍Great, thanks!

**Comment by michaelrambeau** [comment]
Hello Dominik @smalluban ,
It's online, please check here: https://bestofjs.org/tags/framework
Thank you!

**Comment by smalluban** [comment]
Working :)
