### ISSUE TITLE
Add Revact

### ISSUE THREAD

**Issue by PxyUp** [michaelrambeau/bestofjs#226]
Super fast framework with a component, router supports, and reactive from box. https://github.com/PxyUp/Revact

**Comment by michaelrambeau** [comment]
Hello Yuriy @PxyUp 
Thank you for the suggestion, `Revact` will be available on _Best of JavaScript_ very soon.

Just to be sure, you have just changed the name of the project on GitHub? (before the repo was  https://github.com/PxyUp/FastDom ?)

**Comment by PxyUp** [comment]
Hello, yes, was not consistent naming and provided functional. @michaelrambeau

**Comment by michaelrambeau** [comment]
Hello @PxyUp 
`Revact` project is available on _Best of JavaScript_.

 Check here: https://bestofjs.org/tags/framework

**Comment by PxyUp** [comment]
Thanks you @michaelrambeau
