### ISSUE TITLE
Add laconia

### ISSUE THREAD

**Issue by ceilfors** [michaelrambeau/bestofjs#227]
Source: https://github.com/laconiajs/laconia
Website: https://laconiajs.io/
Relevant news: https://twitter.com/hashtag/laconiajs
Tags suggestion: Node.js framework, Serverless

**Comment by michaelrambeau** [comment]
Hello Wisen @ceilfors 
Thank you for the suggestion.
_Laconia_ project is available on _Best of JavaScript_, check here: https://bestofjs.org/tags/serverless

**Comment by ceilfors** [comment]
Thank you @michaelrambeau! :)
