### ISSUE TITLE
Add awesome-notifications

### ISSUE THREAD

**Issue by f3oall** [michaelrambeau/bestofjs#228]
Source: https://github.com/f3oall/awesome-notifications
Website: https://f3oall.github.io/awesome-notifications/
Docs: https://f3oall.github.io/awesome-notifications/docs
Tags suggestion: notification, popup, modal window, toast, modal dialog, async

Thanks!

**Comment by michaelrambeau** [comment]
Hello David @f3oall 
Thank you for the suggestion.
`awesome notifications` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello David @f3oall , it's online, check here: https://bestofjs.org/tags/notify

Thank you for your feedback!

**Comment by f3oall** [comment]
Great, thanks again!
