### ISSUE TITLE
Add scramjet

### ISSUE THREAD

**Issue by MichalCz** [michaelrambeau/bestofjs#229]
Scramjet is a fast, simple, open source functional reactive programming framework bringing easiness of map/filter/reduce to node.js native streams.

https://www.scramjet.org/
https://github.com/signicode/scramjet
https://www.npmjs.com/package/scramjet

**Comment by michaelrambeau** [comment]
Hello @MichalCz 
Thank you for the suggestion, `Scramjet` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @MichalCz 
`Scramjet` is available on _Best of JavaScript_, please check here: https://bestofjs.org/tags/stream

Thank you for your feedback!

**Comment by MichalCz** [comment]
Thanks, I see it on the site already. :)
