### ISSUE TITLE
Add `SlexAxton/Jed` project

### ISSUE THREAD

**Issue by davojta** [michaelrambeau/bestofjs#23]
https://github.com/SlexAxton/Jed
i18n lib for po files

**Comment by michaelrambeau** [comment]
Hello @davojta thank you I am adding the project and I am creating a tag called `i18n`.

**Comment by davojta** [comment]
[Format.JS](http://bestof.js.org/projects/formatjs/readme) is also should be under that tag

**Comment by michaelrambeau** [comment]
Hello @davojta , OK it's online => http://bestof.js.org/search/i18n

![image](https://cloud.githubusercontent.com/assets/5546996/19405623/af6d4992-92b4-11e6-9d88-e192dd8d1335.png)
