### ISSUE TITLE
Tuna.js

### ISSUE THREAD

**Issue by Theodeus** [michaelrambeau/bestofjs#230]
Tuna, the web audio effects library, should be in there! 🐟 🐟 🐟 

https://github.com/Theodeus/tuna

**Comment by michaelrambeau** [comment]
Hello Oskar @Theodeus 
Thank you for the suggestion.
`Tuna.js` will be available on _Best of JavaScript_ very soon because we need more big fishes!

**Comment by michaelrambeau** [comment]
Hello Oskar @Theodeus 
It's online, please check here: https://bestofjs.org/tags/audio
Thank you for your feedback!
