### ISSUE TITLE
Add `log-process-errors`

### ISSUE THREAD

**Issue by ehmicky** [michaelrambeau/bestofjs#232]
`log-process-errors`: https://github.com/ehmicky/log-process-errors

This library improves how Node.js handles process errors, such as uncaught exceptions, unhandled promises, warnings, etc. It: 
  - shows extra information and stack traces
  - enables remote logging
  - allows unit testing those errors
  - can silent some errors conditionally
  - pretty-print those errors

As far as I know, this is currently the only library specifically dealing with enhancing Node.js process errors.

Thanks!

**Comment by michaelrambeau** [comment]
Hello @ehmicky 
Thank you for the recommendation, `log-process-errors` will be available on _Best of JavaScript_ very soon.

**Comment by ehmicky** [comment]
@michaelrambeau thanks!

**Comment by michaelrambeau** [comment]
Hello @ehmicky 

`log-process-errors` is available on _Best of JavaScript_, please check here:

https://bestofjs.org/tags/log

Thank you for the two suggestions of project you made!

**Comment by ehmicky** [comment]
Thanks again!
