### ISSUE TITLE
Add `consola` to Loggers

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#233]
Hey @michaelrambeau 

I hope you're doing well :)

I believe [consola](https://github.com/nuxt/consola) can be part of BestOfJS on the https://bestofjs.org/tags/log page :)

**Comment by michaelrambeau** [comment]
Hello Sébastien @Atinux 

I'm always super happy when you reach us 😄 .

Thank you for the suggestion, you think perfectly right.

`Consola` project is coming very soon.

**Comment by michaelrambeau** [comment]
Hello Sébastien @Atinux

`Consola` project is available on _Best of JavaScript_, check here: https://bestofjs.org/tags/log

Thank you, and feel free to suggest anything related to the Vue.js community!

**Comment by atinux** [comment]
Thanks @michaelrambeau :)
