### ISSUE TITLE
Add DOMPurify

### ISSUE THREAD

**Issue by ramijarrar** [michaelrambeau/bestofjs#234]
For "HTML & text parsing" or "Validation" category (or perhaps even something new specifically for sanitisation): https://github.com/cure53/DOMPurify

**Comment by michaelrambeau** [comment]
Hello Rami @ramijarrar 

Thank you for the suggestion, `DOMPurify` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Rami @ramijarrar 
It's online, please check here: https://bestofjs.org/tags/parsing
Thank you in advance!
