### ISSUE TITLE
react-id-swiper

### ISSUE THREAD

**Issue by kidjp85** [michaelrambeau/bestofjs#235]
A library to use idangerous Swiper as a ReactJs component which allows Swiper's modules custom build

http://kidjp85.github.io/react-id-swiper/

**Comment by michaelrambeau** [comment]
Hello Asher @kidjp85 

Thank you for the recommendation, it will be available on _Best of JavaScript_ very soon.

Just a remark about the project description: I don't understand very well what means "which allows Swiper's modules custom build". Maybe you could be more explicit in the documentation and/or remove it from the project description.

**Comment by michaelrambeau** [comment]
Hello Asher @kidjp85 
It's online, please check here: https://bestofjs.org/tags/nav
Thank you!
