### ISSUE TITLE
Add reSolve - full stack CQRS/ES framework

### ISSUE THREAD

**Issue by superroma** [michaelrambeau/bestofjs#236]
name: reSolve
description: Full stack CQRS, DDD, Event Sourcing framework for Node.js
repo: https://github.com/reimagined/resolve

It is free and open source.

Add it to https://bestofjs.org/tags/fullstack

**Comment by michaelrambeau** [comment]
Hello Roman @superroma 
Thank you for the suggestion, `reSolve` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Roman @superroma 
It's online, please check here: https://bestofjs.org/tags/fullstack
Thank you for your feedback!
