### ISSUE TITLE
Add Embla Carousel

### ISSUE THREAD

**Issue by davidjerleke** [michaelrambeau/bestofjs#237]
A physics simulated JavaScript carousel: https://github.com/davidcetinkaya/embla-carousel.

**Comment by michaelrambeau** [comment]
Hello David @davidcetinkaya 
Thank you for the suggestion.
For now we accept only projects with more than 50 stars.
Sorry, I know that good projects like yours don't have a lot of stars at the beginning.
We are working on a new architecture that would allow more projects to be tracked by _Best of JavaScript_, so this undocumented threshold may change soon and I will contact you when the situation change.
Thank you for your understanding!

**Comment by davidjerleke** [comment]
Hi Michael @michaelrambeau ,
I understand. Thank you for your prompt response.

If you think my project is good and want to support it, I'd very much appreciate if you gave it a star =).
Thanks in advance!

**Comment by michaelrambeau** [comment]
Hello David @davidcetinkaya , OK you're good at business 😄 , I'm starring your repo!

I was checking your project, I could not find in the documentation how to set up the "Previous" and the "Next" buttons, sorry if I'm missing something.

I suppose I have to create by myself a button and bind the `onClick` event to `embla.next()` method?

Maybe you could provide a basic example (with the bare minimum about styling) using https://codepen.io/ for example, so that users can see quickly the markup, the CSS and the JS code needed to get an example working?

**Comment by davidjerleke** [comment]
Hi Michael @michaelrambeau,

Thank you very much 😄. Well, people don't tend to take the time to check your work out if you don't promote it, and don't have a significant amount of stars already.

You've got a great point, thanks for the feedback. I really appreciate it!
If you don't mind you're very welcome to open an issue about what you just mentioned. And you're correct about **how to do it**, you should bind **embla.next()** to an element node:

```javascript
// Trivial example
const myNextButton = document.getElementById('embla-next-button')
myNextButton.addEventListener('click', embla.next, false)
```

Again, thank you :slightly_smiling_face:!

**Comment by michaelrambeau** [comment]
Thank you too, David, OK, I will create an issue.

I think now I understand the concept of `Embla`: it provides the building blocks to let you create the slider that fits your needs, it's up to the user to provide the styling.

I like this flexible approach!

**Comment by davidjerleke** [comment]
Spot on 🙂. Amazing, thank you Michael!

**Comment by davidjerleke** [comment]
Hi Michael @michaelrambeau,

I’m glad to announce that Embla Carousel is now a repository with > 50 (stars) ⭐️. That means that we can proceed with this issue right?

Thanks in advance 🙂!

**Comment by michaelrambeau** [comment]
@davidcetinkaya That's a great news David, you are a champion!

`Embla Carousel` is coming very soon, be patient!

**Comment by davidjerleke** [comment]
Thank you Michael @michaelrambeau 😃.

The issue we talked about regarding a full example of code [here](https://github.com/davidcetinkaya/embla-carousel/issues/8) is awaiting your feedback and I’ve replied to you.

This is not to rush you! Just a friendly reminder in case you’ve missed it ☺️.

**Comment by michaelrambeau** [comment]
@davidcetinkaya My bad David, I missed your update.

So thank you for the useful reminder, I'm going to check.

**Comment by michaelrambeau** [comment]
@davidcetinkaya Hello again David!

It's online, welcome to _Best of JavaScript_ family! 
Check here: https://bestofjs.org/tags/nav

By the way I think a more specific tag should be created.
Now it's classified under: `Menu - navigation - slider`.

Which tag name makes more sense: `Slider` or `Carousel`?

**Comment by davidjerleke** [comment]
Thanks a lot Michael @michaelrambeau, that's great news 😊!

It seems like most of the sliders/carousels are tagged with `Menu - navigation - slider` so maybe that's a good tag to get some exposure?

Or is it possible/does it make sense to add multiple tags 🤔?

Again, thanks for your efforts. I really appreciate it (I starred ⭐️ your [bestofjs](https://github.com/bestofjs/bestofjs-webui) project)!

**Comment by michaelrambeau** [comment]
@davidcetinkaya Thank you for your kind words David!

When I said the tagging could be improved, it's not only for your project, it's for all projects in this category that should be split into different categories, I think.

So don't worry about exposure 😄 , I just want to make good carousel libraries like yours easier to find!

And yes, multiples tags is possible, we can create as many tags as we want.

**Comment by davidjerleke** [comment]
Hello again Michael @michaelrambeau,

Ah, I see 😃.
What about the following tags: `carousel`, `slider`, `slideshow`?

**Comment by michaelrambeau** [comment]
@davidcetinkaya Actually, instead of creating 3 tags I think we should implement the concept of "alias" for tags because sometimes the same concept has different names, it depends on people... but you want to find the appropriate libraries whether you search for "carousels" or "sliders".

Anyway, thank you David for your feedback, I will keep you up-to-date about this question of tagging.

**Comment by davidjerleke** [comment]
@michaelrambeau That’s very true. Any person searching for either `slider`, `slideshow` or `carousel` is probably looking for the same thing, more or less 🙂.
I think your suggestion makes a lot of sense Michael, thanks for keeping me in the loop 👍🏻.

Time to close this issue since it's **done**?

Who knows, maybe I'll be back when the [React Version of Embla Carousel](https://github.com/davidcetinkaya/embla-carousel-react) has reached > 50 stars 😉.
