### ISSUE TITLE
Add Frontity - Framework to build super fast WordPress themes using React.

### ISSUE THREAD

**Issue by Poliuk** [michaelrambeau/bestofjs#239]
Hello @michaelrambeau 

We'd like to recommend Frontity for the bestofjs site. 

**Name:** Frontity
**Description:** Free and open source framework to build super fast WordPress themes using React.
**Tags:** CMS, React, 
**Repo:** [github.com/frontity/frontity](https://github.com/frontity/frontity) (100 ⭐️ )
**Official site:** [Frontity.org](https://frontity.org)

Thanks!

**Comment by michaelrambeau** [comment]
Hello Pablo @Poliuk 
Thank you for the recommendation, `Frontify` project will be available in _Best of JavaScript_ very soon.

**Comment by Poliuk** [comment]
@michaelrambeau Great! Just make sure to use the right name `Frontity` not _Frontify_ :)

**Comment by michaelrambeau** [comment]
@Poliuk Oups sorry for the typo Pablo!

I confirm `Frontity` will be available on _Best of JavaScript_ in 24 hours, stay tuned!

**Comment by michaelrambeau** [comment]
Hello Pablo @Poliuk 
It's online, please check here: https://bestofjs.org/tags/cms

Thank you for your feedback!
