### ISSUE TITLE
add Event Sourcing tag to Wolkenkit

### ISSUE THREAD

**Issue by purefun** [michaelrambeau/bestofjs#240]
as #236, There is another Event Sourcing framework

https://github.com/thenativeweb/wolkenkit

**Comment by michaelrambeau** [comment]
Hello @cdnil 
Thank you for your suggestion but Wolkenkit is already tracked by _Best of JavaScript_, can you see it? https://bestofjs.org/tags/fullstack

I wonder if something could be improved to make it easier to find 🤔 .
Thank you for your feedback!

**Comment by purefun** [comment]
@michaelrambeau 

ReSolve can be found by search term `event sourcing`, but Wolkenkit can't. I think just add the tag for it. Thank you.

https://bestofjs.org/search/event%20sourcing

**Comment by michaelrambeau** [comment]
OK @cdnil, a tag `Event Sourcing` will be added to _Best of JavaScript_, stay tuned!

**Comment by michaelrambeau** [comment]
@cdnil A new tag has been added to _Best of JavaScript_, please check here: 

https://bestofjs.org/tags/event-sourcing

![image](https://user-images.githubusercontent.com/5546996/57975236-1efd0d80-7a00-11e9-88f1-92e73692aed8.png)
