### ISSUE TITLE
add Grade

### ISSUE THREAD

**Issue by purefun** [michaelrambeau/bestofjs#241]
> This JavaScript library produces complementary gradients generated from the top 2 dominant colours in supplied images.

https://github.com/benhowdle89/grade

tag: Image View?

**Comment by michaelrambeau** [comment]
Thank you again @cdnil 
`Grade.js` wlll be available on _Best of JavaScript_ very soon, under the following tags:

* Colors
* Image processing
* Canvas

**Comment by michaelrambeau** [comment]
Hello @cdnil 

It's online, please check here for example: https://bestofjs.org/tags/color

Thank you!
