### ISSUE TITLE
Add Mevn-CLI to Best of JS

### ISSUE THREAD

**Issue by coder9604** [michaelrambeau/bestofjs#242]
@michaelrambeau https://www.github.com/jamesgeorge007 is the author of [Mevn-CLI](https://github.com/madlabsinc/mevn-cli), a scaffolding tool centred around the goals to make Developers productive especially those who are starting out. He is a Full Stack JavaScript Developer and also pretty active in the open source community. 
Considering the potential that this scaffolding tool has I think it is good to have him on the list :smile:

**Comment by michaelrambeau** [comment]
Hello @coder9604 
Thank you for the suggestion.

About James George, before inducting him to the Hall of Fame, let's wait until he becomes a little more famous in the community, if you don't mind. I can't find any evidence about the fact that he's a well known library author, writer, blogger or speaker... unless I miss something.

However, `MEVN` may be an interesting project to add to _Best of JavaScript_.
What do you think, should we track `MEVN` in _Best of JavaScript_?

Thank you for your understanding!

**Comment by coder9604** [comment]
@michaelrambeau 
> However, MEVN may be an interesting project to add to Best of JavaScript.

Oh that would be great!
Docs: https://mevn.madhacks.co
Repo: https://github.com/madlabsinc/mevn-cli

**Comment by michaelrambeau** [comment]
Hello @coder9604 
It's online, check here for example: https://bestofjs.org/tags/scaffolding
Thank you!

**Comment by coder9604** [comment]
@michaelrambeau It would be great if the name was `Mevn CLI` instead of `Mevn`.

**Comment by michaelrambeau** [comment]
Hello again @coder9604 
OK, the project's name has been fixed.
Could you please check if it's OK: https://bestofjs.org/projects/mevn-cli
Thank you for your feedback!

**Comment by coder9604** [comment]
@michaelrambeau Yeah LGTM :+1: 
Also, do consider leaving a :star: to the repository as well as sharing it within your Dev community :smile:

**Comment by coder9604** [comment]
@michaelrambeau Yeah LGTM :+1: 
Also, do consider leaving a :star: to the repository as well as sharing it within your Dev community :smile:

**Comment by michaelrambeau** [comment]
Thank you @coder9604 but I'm not allowed to star repos otherwise people would tell me I'm biased, I should be a fair referee! 😆 

Seriously I'm not really in the Vue.js world, this is why I can not really check the project.
If I ever go back to the Vue.js world, I would check carefully.

Thank you for your understanding, let me know if you have any feedback about _Best of JavaScript_!
