### ISSUE TITLE
jExcel

### ISSUE THREAD

**Issue by pphod** [michaelrambeau/bestofjs#243]
Hi, I would like to suggest jExcel - The javascript spreadsheet.
https://github.com/paulhodel/jexcel
https://bossanova.uk/jexcel

**Comment by michaelrambeau** [comment]
Hello Paul @paulhodel 
Thank you for the suggestion, `jExcel`will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Paul @paulhodel 
It's online, could you please check here: https://bestofjs.org/tags/table
Thank you!
