### ISSUE TITLE
Add jtools

### ISSUE THREAD

**Issue by pphod** [michaelrambeau/bestofjs#244]
https://bossanova.uk/jtools

**Comment by michaelrambeau** [comment]
Hello again Paul @paulhodel
Thank you for that suggestion too.

For now we only track projects with more than 50 stars.
This limit may change in the next future when we change the architecture of the application to make it more flexible.

Sorry for this answer, we keep an eye on your project and we will contact you when the situation changes.
Thank you for your understanding!

**Comment by pphod** [comment]
Thanks, the repository has 78 stars. Could you please reconsider? ;)

**Comment by michaelrambeau** [comment]
OK Paul @paulhodel `jTools` project will be available on _Best of JavaScript_ very soon!

By the way, I noticed a small typo in the project description, you entered `ligthtweight`, I think it should be `lightweight`.

**Comment by pphod** [comment]
Brilliant! I have fixed the description, thanks for that. ;)

**Comment by michaelrambeau** [comment]
Hello Paul @paulhodel ,
It's online, check here please: https://bestofjs.org/tags/plugin
Thank you for your feedback!
