### ISSUE TITLE
Tourguide.js

### ISSUE THREAD

**Issue by PhilippeTrounev** [michaelrambeau/bestofjs#245]
Hi there, 
Tourguide.js is a simple open source product tours library. We posted it a couple of weeks ago in JS sub reddit and got a 100 stars. Let me know if you have any feedback :) 

https://github.com/LikaloLLC/tourguide.js

**Comment by michaelrambeau** [comment]
Hello Philippe @PhilippeTrounev 
Thank you for the recommendation, `Tourguide.js` will be available on _Best of JavaScript_ very soon.

Are you ready for the Finals? 🏀 😄

**Comment by PhilippeTrounev** [comment]
Hi Mike. Yes!! Still can't believe raptors made it 🏀🏀🏀🏀🥇

**Comment by michaelrambeau** [comment]
Hello Philippe @PhilippeTrounev 
It's online, please check: https://bestofjs.org/tags/presentation

This year Finals will be epic, this is my only prediction, good luck!

**Comment by PhilippeTrounev** [comment]
Thank you :) It looks great! 

Yes we are in for some amazing games. Go Raptors! 🥇 :P

**Comment by michaelrambeau** [comment]
@PhilippeTrounev What an atmosphere! I can't wait for Game 2.
