### ISSUE TITLE
Add Guillaume Chau in the Hall of Fame

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#246]
Hey :)

I believe that Guillaume Chau (@Akryum) should be part of the all of fame, he is core team member of Vue.js and is creating fantastic projects around it :)

**Comment by michaelrambeau** [comment]
Thank you for that suggestion too!

**Comment by michaelrambeau** [comment]
Hello again Sébastien, please welcome Guillaume Chau to the _JavaScript Hall of Fame_!

**Comment by atinux** [comment]
Awesome, thanks @michaelrambeau
