### ISSUE TITLE
Add Eduardo San Martin Morote to the Hall of Fame

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#247]
Hey again :)

I also believe that Eduardo San Martin Morote (@posva) should be part of the JS Hall of Fame, core team of Vue.js and main maintainer on Vue-Router & VueFire :)

**Comment by michaelrambeau** [comment]
@Atinux Great, thank you Sébastien, Eduardo will be a member of the _Hall of Fame_ very soon.

By the way, I keep thinking that this _Hall of Fame_ page should be improved, it's becoming crowded, it needs a pagination and a search feature.

The members could be split using a system of tags, maybe:

* Lib authors
* Speakers
* Authors
* Pionneers
* ... other ideas?

I'm sharing my thoughts just in case you have any feedback

**Comment by michaelrambeau** [comment]
Hello Sébastien @Atinux ,
Eduardo San Martin Morote is now a member of the _JavaScript Hall of Fame_.

@posva Eduardo, don't forget to update your resume! 😄

**Comment by posva** [comment]
Thank you! I will not forget 😆
