### ISSUE TITLE
Add Scene.js

### ISSUE THREAD

**Issue by daybrush** [michaelrambeau/bestofjs#248]
Scene.js is JavaScript & CSS timeline-based animation library

Can I register this library?

tag: Animation

https://github.com/daybrush/scenejs

**Comment by michaelrambeau** [comment]
Hello @daybrush 
Thank you for the suggestion, `Scene.js` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @daybrush 
It's online, please check here: https://bestofjs.org/tags/animation
Thank you for your feedback!

**Comment by daybrush** [comment]
@michaelrambeau

I checked. Thank you for adding for the library.
