### ISSUE TITLE
Add Misskey

### ISSUE THREAD

**Issue by JLKM** [michaelrambeau/bestofjs#249]
[Misskey](https://github.com/syuilo/misskey) is an awesome Fediverse-project - heavily based on Vue.js.

**Comment by michaelrambeau** [comment]
Hello @JLKM 
Thank you for the suggestion but the project seems to be a bit out of the scope of _Best of JavaScript_: provide the best components to build applications with the JavaScript eco-system.

I can see the project is made with Vue.js, it has a lot of activity but _Best of JavaScript_ does not really track "real world applications" (at least for now, there is no "real world" tag).

Thank you for your understanding, we will reconsider this question if we extend the scope of _Best of JavaScript_.
