### ISSUE TITLE
Add `airyland/vux` project

### ISSUE THREAD

**Issue by airyland** [michaelrambeau/bestofjs#25]
https://github.com/airyland/vux
UI Components based on Vue

**Comment by michaelrambeau** [comment]
Hello @airyland , thank you for the link.
OK I am adding `vux` project, it will be online in 48 hours, be patient!

**Comment by michaelrambeau** [comment]
Hello @airyland , `vux` project can be found on bestof.js.org

http://bestof.js.org/tags/vue

![image](https://cloud.githubusercontent.com/assets/5546996/19664169/2ec7b002-9a7a-11e6-8d75-17f17f071358.png)

**Comment by airyland** [comment]
:heart:
