### ISSUE TITLE
Add jsstore

### ISSUE THREAD

**Issue by ujjwalguptaofficial** [michaelrambeau/bestofjs#250]
JsStore is an IndexedDB Wrapper. It makes IndexedDB super easy with its SQL like apis. 

Doc link - http://jsstore.net/
Github - https://github.com/ujjwalguptaofficial/JsStore

**Comment by michaelrambeau** [comment]
Hello Ujjwal @ujjwalguptaofficial 
Thank you for the suggestion, _JsStore_ will be available in _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @ujjwalguptaofficial 
It's online, could you please check here: https://bestofjs.org/tags/db

Now it's tagged `Database`, which is a very generic category that contains projects related to data storage: databse ORM and clients, wrappers around browser storage like your project...

I wonder if you had any idea about how we could split this category into more meaningful tags.

Thank you for your feedback!

**Comment by ujjwalguptaofficial** [comment]
works for me. Thanks.

**Comment by ujjwalguptaofficial** [comment]
Hi @michaelrambeau 

Regarding this 
> I wonder if you had any idea about how we could split this category into more meaningful tags.

Its a database technology but its a browser based technology and categorizing this along with server database like mongodb is not a good idea. Could you create seperate tags "browser storage" ?

Browser storage seems more meaningful for me. Let me know.

**Comment by michaelrambeau** [comment]
Hello @ujjwalguptaofficial 

Here is the new category called "Browser storage": https://bestofjs.org/tags/browser-storage

Let me know if it makes sense for you, thank you!

![image](https://user-images.githubusercontent.com/5546996/59720201-3a567500-9259-11e9-91ed-d42e350583f9.png)

**Comment by ujjwalguptaofficial** [comment]
awesome, thanks!.
