### ISSUE TITLE
Add FoalTS

### ISSUE THREAD

**Issue by eltrollado** [michaelrambeau/bestofjs#251]
Foal is node framework similar to Nest. I think they deserve more attention.
https://github.com/FoalTS/foal

**Comment by michaelrambeau** [comment]
Hello @eltrollado 
Thank you for the suggestion, `FoalTS` will be available on _Best of JavaScript_ very soon!

**Comment by michaelrambeau** [comment]
Hello @eltrollado 
It's online, please check here: https://bestofjs.org/tags/nodejs-framework
Thank you for your feedback!
