### ISSUE TITLE
add simpleParallax

### ISSUE THREAD

**Issue by geosigno** [michaelrambeau/bestofjs#252]
Hi there,

I'd like to see [simpleParallax](https://github.com/geosigno/simpleParallax) on bestofjs :)

Thanks.

**Comment by michaelrambeau** [comment]
Hello @geosigno 

Thank you for the recommendation.

`simpleParallax` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Geoffrey @geosigno 
It's online, please check here: https://bestofjs.org/tags/scrolling
Thank you for your feedback!
