### ISSUE TITLE
Consider adding Zebkit

### ISSUE THREAD

**Issue by markvx** [michaelrambeau/bestofjs#253]
Zebkit - HTML5 Canvas based UI framework

Repo: https://github.com/barmalei/zebkit
Online Demos: http://zebkit.org/

**Comment by michaelrambeau** [comment]
Hello @markvx 
Thank you for the recommendation, `Zebkit` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @markvx 
It's online, please check here: https://bestofjs.org/tags/framework
Thank you!
