### ISSUE TITLE
Add react-top-loading-bar

### ISSUE THREAD

**Issue by klendi** [michaelrambeau/bestofjs#254]
Hi I want to add my component. It's a highly customisable youtube-like ajax loader.
https://github.com/klendi/react-top-loading-bar

**Comment by michaelrambeau** [comment]
Hello @klendi 
Thank you for the recommandation, `react-top-loading-bar` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @klendi 
It's online, check here please: https://bestofjs.org/tags/progress-bar
Thank you!
