### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by artyprog** [michaelrambeau/bestofjs#255]
I would like to recommend Isiah Meadows , the main maintener of the awesome framework MithrilJS

Regards

**Comment by michaelrambeau** [comment]
Hello @artyprog , thank you for the recommendation.
Given the fact that all other members have at least 100 followers on GitHub, let's wait a little more before inducting Isiah to the _Hall of Fame_, if you don't mind.

Talking about Hall of Fame, it's interesting that his bio mentions [here](https://www.isiahmeadows.com/about/) that he was named after the great Isiah Thomas 🏀 !
