### ISSUE TITLE
Add Flicking

### ISSUE THREAD

**Issue by daybrush** [michaelrambeau/bestofjs#256]
https://github.com/naver/egjs-flicking

Reliable, flexible and extendable carousel used by 30 million people everyday. 
* Easy-to-use infinite carousel(slider).
*  Every options are compatible with each others.
*  Except for mutual exclusive options (like circular and bound).
*  Provides various scroll movement types that you can choose.
*  Ready-to-use plugins you can grab right away.
*  Supports all major frameworks(Angular, React, Vue).

Tag: React, Angular, Vue, Menu-Navigation-Slider

**Comment by michaelrambeau** [comment]
Hello @daybrush 
Thank you for the recommendation, `Flicking` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @daybrush 
It's online, check here: https://bestofjs.org/tags/nav
Thank you for your feedback!

**Comment by daybrush** [comment]
@michaelrambeau 

Thank you. I checked registration.
