### ISSUE TITLE
Add moveable

### ISSUE THREAD

**Issue by daybrush** [michaelrambeau/bestofjs#258]
Moveable is Draggable, Resizable, Scalable, Rotatable.

https://github.com/daybrush/moveable

Tags: React, Drag and drop, Gesture - Touch

**Comment by michaelrambeau** [comment]
Hello @daybrush 

Thank you for the suggestion, `moveable` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @daybrush 
Congratulations, now you have 2 projects on _Best of JavaScript_!

![image](https://user-images.githubusercontent.com/5546996/61495088-f0e17d00-a9f2-11e9-94bb-51fc43b6e0e2.png)

**Comment by daybrush** [comment]
@michaelrambeau 

I checked the registration. Thank you. :)
