### ISSUE TITLE
Add Smashtest

### ISSUE THREAD

**Issue by stepaniukm** [michaelrambeau/bestofjs#259]
Simple but powerful e2e testing kit

https://smashtest.io/
https://github.com/smashtestio/smashtest

**Comment by michaelrambeau** [comment]
Hello @Stepek123 
Thank you for the suggestion, `Smashtest` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @Stepek123 
It's online, check the [Browser Automation](https://bestofjs.org/tags/auto) tag for example.
Thank you!

**Comment by stepaniukm** [comment]
Thanks @michaelrambeau for rapid response :1st_place_medal:
