### ISSUE TITLE
Add react-to-print

### ISSUE THREAD

**Issue by codesignist** [michaelrambeau/bestofjs#260]
https://github.com/gregnb/react-to-print

- [x] The project is related to the web platform and/or Node.js
Web platform
- [x] The project has more than 50 stars on GitHub
275 stars
- [x] The project has a thorough documentation
It has nice [readme file](https://github.com/gregnb/react-to-print/blob/master/README.md)
- [x] The project is not deprecated and still maintained
Last update 30 July 2019 (10 hours ago)

**Comment by michaelrambeau** [comment]
Hello @codesignist,
Thank you for the suggestion, `ReactToPrint` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @codesignist !
It's online, under the tag "React".
Can you see an other tag we could use for this project?

There is a tag called [Typography](https://bestofjs.org/tags/typo) but I don't think it's really appropriate.
So a new tag "Print" would be better, for "React To Print" and for this project too: https://bestofjs.org/projects/gutenberg
Any suggestion is welcome, thank you!

**Comment by codesignist** [comment]
Hello @michaelrambeau,

I agree with you. **Typography** is not appropriate and **Print** would be better.

Thank you.

**Comment by michaelrambeau** [comment]
Alright @codesignist I'm adding a new tag, stay tuned!

**Comment by michaelrambeau** [comment]
Hello again @codesignist !
A new tag has been created, please check here: https://bestofjs.org/tags/print
Thank you!

**Comment by codesignist** [comment]
Hello @michaelrambeau,
Thank you.
