### ISSUE TITLE
Add Frontless.JS

### ISSUE THREAD

**Issue by nesterow** [michaelrambeau/bestofjs#261]
A Node.JS stack for building isomorphic applications with [Riot.JS](https://github.com/riot/riot) and [Feathers.JS](https://docs.feathersjs.com)

https://frontless.js.org/
https://github.com/nesterow/frontless

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Anton @nesterow 
Thank you for the recommandation, `Frontless` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Anton @nesterow 
It's available, could you check here for example: https://bestofjs.org/tags/nodejs-framework
Maybe the tag "Fullstack" would be appropriate too.
Thank you in advance!

**Comment by nesterow** [comment]
@michaelrambeau Thank you! Yes, it is a full-stack library. I avoid calling it framework, because it glues a stack of technologies that came out to work nicely together (feathers, riot, turbolinks, express). Fullstack stack would sound funny ;).

**Comment by michaelrambeau** [comment]
Alright @nesterow I'm not changing the tags assigned to the project.

Feel free to suggest anything about _Best of JavaScript_, thank you for your support!

**Comment by nesterow** [comment]
Thank you!
