### ISSUE TITLE
add RedGL

### ISSUE THREAD

**Issue by redcamel** [michaelrambeau/bestofjs#262]
WebGL library
github - https://github.com/redcamel/RedGL2

**Comment by michaelrambeau** [comment]
Hello @redcamel 

Thank you for the suggestion.
The README.md is not very clear, would it be possible to write documentation in English about the library, for example:

- what is its purpose, 
- how it's different from other WebGL libraries (see the competitors here: https://bestofjs.org/tags/webgl)
- how to use  it

Thank you for your understanding!

**Comment by redcamel** [comment]
@michaelrambeau 
Thank you for answer.
I'm trying to write a more specific document.
