### ISSUE TITLE
Please add 'React Hook Form'

### ISSUE THREAD

**Issue by codebex** [michaelrambeau/bestofjs#264]
https://react-hook-form.com/
https://github.com/bluebill1049/react-hook-form

**Comment by michaelrambeau** [comment]
Hello Alain @alaindm 
Thank you for the suggestion, `React Hook Form` project will be available very soon.

**Comment by michaelrambeau** [comment]
Hello Alain @alaindm 
It's online, please check here: https://bestofjs.org/tags/form
Thank you for your feedback!
