### ISSUE TITLE
Tanner Linsley

### ISSUE THREAD

**Issue by tannerlinsley** [michaelrambeau/bestofjs#265]
The JavaScript Hall of Fame gathers the greatest developers, authors and speakers of the JavaScript community.

Before submitting the request to add a new member, check the following points:

- [x] The member has a GitHub profile with more than 500 followers
- [x] The member is renowned for her/his writings, talks or projects

[tannerlinsley](https://github.com/tannerlinsley)

**Comment by michaelrambeau** [comment]
Hello Tanner @tannerlinsley 
Thank you, you will be inducted to the _JavaScript Hall of Fame_ very soon!

By the way, did you know that [Weekly Best of JavaScript](https://weekly.bestofjs.org/) is made with _React Static_, one of your great projects?

This is an other reason why you should be a member of the _Hall of Fame_!

**Comment by tannerlinsley** [comment]
Woah! That's awesome! Thanks for using it :)

I've recently moved on from React Static and am focusing my time on React Table and React Charts now. You should check them out.

Thanks again!

**Comment by michaelrambeau** [comment]
Thank you for your feedback @tannerlinsley 

`React Table` is already tracked by _Best of JavaScript_ but not https://github.com/tannerlinsley/react-charts

Do you want it to be added to _Best of JavaScript_? Maybe better to wait for the official release?

> React Charts is currently in beta!

**Comment by tannerlinsley** [comment]
Yeah, let’s wait til I can make it stable.

**Comment by michaelrambeau** [comment]
Hello Tanner @tannerlinsley 
Congratulations, you have been inducted to the _JavaScript Hall of Fame_!

Check here: https://bestofjs.org/hall-of-fame

Sorry for now there is no search filter or anything to help navigate through the 151 members, it's something that should be improved.

If you have any feedback about _Best of JavaScript_ (how it could be more useful, a feature you'd like to see?), your point of view as a _Hall of Famer_ is very valuable, of course!

**Comment by michaelrambeau** [comment]
Hello Tanner @tannerlinsley, just a quick update:
Do you know that _React Table_ is the project number one today? Congratulations!

![image](https://user-images.githubusercontent.com/5546996/64914187-c6a90300-d788-11e9-8bf7-0fdda09746ae.png)
