### ISSUE TITLE
Please add Redux Logger 

### ISSUE THREAD

**Issue by LukeLogRocket** [michaelrambeau/bestofjs#266]
Love the site! Suggestion to add Redux Logger - https://github.com/LogRocket/redux-logger

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [ Yes ] The project is related to the web platform and/or Node.js
- [ 4,736 ] The project has more than 50 stars on GitHub
- [ Yes ] The project has a thorough documentation
- [ Yes ] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello @LukeLogRocket 
Thank you for the suggestion, _Redux Logger_ will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @LukeLogRocket 
It's online, could you please check here:
https://bestofjs.org/tags/redux

Thank you for your feedback!
