### ISSUE TITLE
request to add dmxus, a [working] js library for controlling dmx lighting fixtures

### ISSUE THREAD

**Issue by michael-hamilton** [michaelrambeau/bestofjs#267]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [*] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [*] The project has a thorough documentation
- [*] The project is not deprecated and still maintained

https://github.com/michael-hamilton/dmxus

**Comment by michaelrambeau** [comment]
Hello Michael @michael-hamilton 
Thank you for the suggestion.
Unfortunately we accept only projects with more than 50 stars, for now, but this limit may be change soon.

About the "thorough" documentation, I think you could provide some context in the README.md file.
I had no idea about what was "DMX", Wikipedia tells me that it's the name of "an American rapper and actor. " but I think your DMX is not the same!

So I looked up what was a [lighting console](https://en.wikipedia.org/wiki/Lighting_control_console), I suppose that somehow it can be controlled by something you plug to the USB port of your computer?

Sorry for my ignorance and thank you for your understanding!

**Comment by michael-hamilton** [comment]
Hi Michael,

Thanks for your insight! This is a new project of mine, and it comes from a need I had after finding that there is only 1 other somewhat popular library like this on NPM, but it unfortunately isn’t maintained and does not work correctly. I will certainly take your notes into consideration with the documentation. If the restriction on GitHub stars changes, I’d hope this could be added!

-Mike

**Comment by michaelrambeau** [comment]
Thank you @michael-hamilton 
By the way, do you know how a project like yours could be tagged in _Best of JavaScript_?
There is a category called "IoT" but I don't think it's relevant (unless the devices you handle are connected to the Internet?)
"Lighting console" seems too restrictive.
"Controller" makes developers think about controllers from the MVC pattern.
"USB controlled" or "USB"?
The best I can see is "Hardware" but it's very generic.
