### ISSUE TITLE
Add DeskApp Bootstrap 4 admin template.

### ISSUE THREAD

**Issue by dropways** [michaelrambeau/bestofjs#268]
Suggestion to add DeskApp admin --  https://github.com/dropways/deskapp

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [yes ] The project is related to the web platform and/or Node.js
- [79 ] The project has more than 50 stars on GitHub
- [ yes] The project has a thorough documentation
- [ yes] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Ankit @dropways 

About the documentation, I couldn't find it, where are instructions about how to install it, how to start it, how to use it?

Sorry if I miss something obvious but I don't understand what is the purpose of the project, how it works. I can see a lot of PHP files and huge JavaScript files here https://github.com/dropways/deskapp/tree/master/vendors/scripts

To me the project looks like an extension for an existing CMS written in PHP, that requires no build process (hence the huge JS file committed in the source?)... but it's just an assumption.

One more thing: the demo on Heroku does not work:

```
An error occurred in the application and your page could not be served.
If you are the application owner, check your logs for details.
```

Thank you for your understanding!
