### ISSUE TITLE
Add `helion3/inspire-tree` project

### ISSUE THREAD

**Issue by viveleroi** [michaelrambeau/bestofjs#27]
https://github.com/helion3/inspire-tree
A great UI tree library.

**Comment by michaelrambeau** [comment]
Hello @viveleroi ,
Thank you, I have added `inspire-tree` project, it will be online in 48 hours because the application needs 2 daily snapshots of Github stars to show tendencies.
Be patient!

**Comment by michaelrambeau** [comment]
Hello @viveleroi , it's online, under the tag `Plugin - form widget`, check here http://bestof.js.org/tags/plugin or search for `tree` http://bestof.js.org/search/tree
