### ISSUE TITLE
Add openid-client

### ISSUE THREAD

**Issue by panva** [michaelrambeau/bestofjs#271]
> OpenID Certified™ Relying Party (RP, Client) implementation with wide feature coverage including optional specifications for Node.js.

https://github.com/panva/node-openid-client

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Filip @panva
Thank you for the recommendation, `openid-client`  will be available on _Best of JavaScript_ very soon.
Note that we already track an other project from you: `oidc-provider`: https://bestofjs.org/projects/oidc-provider

It will be available under the tag "Authentication": https://bestofjs.org/tags/auth

**Comment by michaelrambeau** [comment]
Hello Filip @panva 
It's online, could you please check here: https://bestofjs.org/tags/auth

Let me know if you think about great projects missing in the `Authentication` category, thank you!

**Comment by panva** [comment]
@michaelrambeau thanks!
