### ISSUE TITLE
Appwrite - New Open Source Backend Server for Frontend Apps

### ISSUE THREAD

**Issue by eldadfux** [michaelrambeau/bestofjs#273]
- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

Appwrite is a backend server for frontend apps, that is packaged as a docker container. Appwrite mission is to help frontend developers by reducing the time it takes to build a new web project.

![Appwrite Dashboard](https://appwrite.io/images/github.png)

Appwrite provides REST APIs and tools that abstract common and repetitive tasks across software projects. Between the different APIs and tools, you can find an authentication, storage, users and database APIs and tools for managing recurring tasks, webhooks and API keys.

The project has only been published last week and the community response has been amazing.

Appwrite Website:
https://appwrite.io

Appwrite Docs:
https://appwrite.io/docs

Appwrite Github Repo:
https://github.com/appwrite/appwrite

**Comment by michaelrambeau** [comment]
Hello Eldad!
Sorry for the late reply.
Thank you for the recommendation, Appwrite project will be available in _Best of JavaScript_ very soon, under the tag `Node.js framework`.

**Comment by michaelrambeau** [comment]
Hello again @eldadfux 
I was checking the project, actually the backend seems to be a PHP server, not a Node.js server, am I correct?
So I don't think it can be tagged under the "Node.js frameworks" category.
Let me know if I missed something, thank you in advance!
