### ISSUE TITLE
add `react-simple-animate` project

### ISSUE THREAD

**Issue by bluebill1049** [michaelrambeau/bestofjs#274]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

https://react-simple-animate.now.sh

**Comment by bluebill1049** [comment]
thanks for considering ❤️

**Comment by michaelrambeau** [comment]
Hello Bill @bluebill1049 
Thank you for the suggestion, `react-simple-animate` will be available on _Best of JavaScript_ very soon.

**Comment by bluebill1049** [comment]
thanks very much @michaelrambeau 🙏

**Comment by michaelrambeau** [comment]
Hello Bill @bluebill1049 
It's online, please check here for example: https://bestofjs.org/tags/animation/trending/today
Or just search for `bluebill`:

![image](https://user-images.githubusercontent.com/5546996/64928076-0b4aa200-d84e-11e9-8345-be9c9eeea33d.png)


Did you know there was an other project from you already tracked by _Best of JavaScript_? 😃

**Comment by bluebill1049** [comment]
thanks so much, @michaelrambeau for maintaining this website and add the project.
