### ISSUE TITLE
Add Factor Platform 

### ISSUE THREAD

**Issue by arpowers** [michaelrambeau/bestofjs#275]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

---

- https://factor.dev
- https://github.com/fiction-com/factor

<img width="1657" alt="Screen Shot 2019-09-15 at 12 04 23 PM" src="https://user-images.githubusercontent.com/308134/64925647-18fe1a00-d7b1-11e9-9d48-74c8b5f3f74a.png">

**Comment by michaelrambeau** [comment]
Hello Andrew @arpowers 
Thank you for the suggestion, `Factor` project will be available _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Andrew @arpowers 
It's online, could you please check?
Let me know if the tagging makes sense, thank you!

**Comment by arpowers** [comment]
@michaelrambeau thank you for the fast turnaround. Looks good, as far as tagging not sure if a MEVN tag makes sense, but otherwise looks good. 

Now it's time to continue working and level up in your leaderboard haha

**Comment by michaelrambeau** [comment]
Thank you @arpowers 
Rather than a MEVN tag, since we have already the E (`Express`) and the V (`Vue.js`), I think a tag `MongoDB` would make more sense.
About the leaderboard you mentioned, you got +7 stars in 1 day, that's a good start!
