### ISSUE TITLE
 Ornamentum: lightweight, feature-rich, highly configurable, Angular Data Grid

### ISSUE THREAD

**Issue by sachin-nanayakkara** [michaelrambeau/bestofjs#277]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

  Link :- https://github.com/yohangz/ornamentum
  website :- https://ornamentum.app/

**Comment by michaelrambeau** [comment]
Hello @SACHINnANYAKKARA 
Thank you for the suggestion, `Ornamentum` project will be available on _Best of JavaScript_ very soon.

**Comment by sachin-nanayakkara** [comment]
@michaelrambeau  thanks :)

**Comment by michaelrambeau** [comment]
Hello @SACHINnANYAKKARA 
It's online, check the `table` tag for example: https://bestofjs.org/tags/table
Thank you for your feedback!
