### ISSUE TITLE
Add `css-camera` project

### ISSUE THREAD

**Issue by WoodNeck** [michaelrambeau/bestofjs#278]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

---

Hello, thanks for the great work managing this awesome website.

css-camera is a helper library to handle CSS 3d transform easily.

Repo: https://github.com/WoodNeck/css-camera
Docs: https://woodneck.github.io/css-camera/release/latest/docs/index.html
Demo: https://woodneck.github.io/css-camera/
Tag: 3D

**Comment by michaelrambeau** [comment]
Hello @WoodNeck 
Thank you for the recommendation, `CSS Camera` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @WoodNeck 
It's online, check here: https://bestofjs.org/tags/3d
Thank you for your kind words! 😄

**Comment by WoodNeck** [comment]
Great! Thanks for your effort, @michaelrambeau !
