### ISSUE TITLE
react-smooth-range-input + react-flip-numbers

### ISSUE THREAD

**Issue by bluebill1049** [michaelrambeau/bestofjs#279]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

Could you please include the following react components?

https://github.com/bluebill1049/react-smooth-range-input

https://github.com/bluebill1049/react-flip-numbers

**Comment by michaelrambeau** [comment]
Hello @bluebill1049 
You really want all your projects to be tracked by _Best of JavaScript_? 😆 
OK, both projects will be available on Best of JavaScript very soon!

**Comment by bluebill1049** [comment]
hahaha Yes, 100% I visit the website daily, it's nice to get my open source projects there. ❤️

**Comment by michaelrambeau** [comment]
That's great! Thank you for your support.
I may ask you to test some new features as a beta-tester, if you don't mind.

**Comment by bluebill1049** [comment]
would love to :)

**Comment by michaelrambeau** [comment]
Hello @bluebill1049 
The 2 projects you submitted are online!

If you have some time, could I ask to you give me some feedback about the next version of _Best of JavaScript_ I'm preparing right now?
More details here: https://github.com/bestofjs/bestofjs-webui/issues/75#issuecomment-535726927

Thank you in advance!

**Comment by bluebill1049** [comment]
cool thanks very much, I will take a look tmr :)

**Comment by bluebill1049** [comment]
nvm I am looking at it now hehe
