### ISSUE TITLE
Add `FountainJS/generator-fountain-webapp` project

### ISSUE THREAD

**Issue by Swiip** [michaelrambeau/bestofjs#28]
https://github.com/FountainJS/generator-fountain-webapp
Rich yeoman generator for React and Angular

**Comment by michaelrambeau** [comment]
Hello @Swiip ,
Thank you, I am adding the project to bestof.js.org, it will be available in 48 hours.

**Comment by Swiip** [comment]
Thanks ;)

**Comment by michaelrambeau** [comment]
Hello @Swiip , the project is online, as you can see here => http://bestof.js.org/tags/scaffolding

I was not sure about how to tag the project.
There was already a tag called `React boilerplate` (http://bestof.js.org/projects/tags/react-template) but your project is more generic, so I created a new tag called `Scaffolding - generator`, let me know if it makes sense for you.

![image](https://cloud.githubusercontent.com/assets/5546996/20118202/038774a8-a647-11e6-88e8-27bdb7a7cd49.png)

**Comment by Swiip** [comment]
Seems perfect to me, thanks.
