### ISSUE TITLE
add 'cerebral/overmind' project

### ISSUE THREAD

**Issue by devhero** [michaelrambeau/bestofjs#280]
I suggest the state management library [overmindjs](https://github.com/cerebral/overmind)

It's defined as the 'spiritual successor' of [cerebraljs](https://github.com/cerebral/cerebral) from the same author.

It's growing up fast and has a very detailed and updated documentation.

**Comment by michaelrambeau** [comment]
Hello Andrea @devhero 
Thank you for the suggestion, we need more _spiritual_ things in this application, I totally agree!

**Comment by michaelrambeau** [comment]
Hello Andrea @devhero , it's online, please check here: 

https://bestofjs.org/tags/state

Thank you for your feedback!

**Comment by devhero** [comment]
Thanks to you, best-of-js a very useful and inspiring website!

**Comment by michaelrambeau** [comment]
Thank you Andrea @devhero for your kind words!

May I ask you feedback about the _Next_ version of _Best of JavaScript_?

Details here: https://github.com/bestofjs/bestofjs-webui/issues/75#issuecomment-535726927

Let me know if you like it or not 😃
