### ISSUE TITLE
update @panva/jose

### ISSUE THREAD

**Issue by panva** [michaelrambeau/bestofjs#281]
Hello @michaelrambeau 

could you please update `@panva/jose`? It's now called just `jose`, both the project and package names, repository stays the same.

Thank you.

**Comment by michaelrambeau** [comment]
Hello Filip @panva 
No, problem, I'm doing that, the site data will be rebuilt in 24 hours.
Meanwhile, if you have some time, could I ask you to check the next version of _Best of JavaScript_ we are working on?
I remember we talked about the tags. So it's not about what you suggested but it's about a new search feature to combine several tags and keywords.

https://github.com/bestofjs/bestofjs-webui/issues/75#issuecomment-535726927

Thank you for your feedback in advance!

**Comment by michaelrambeau** [comment]
Hello Fikip @panva 
It's done, could you please check again?

In the _Next_ version of _Best of JavaScript_, if you search for `panva`, results would be displayed like this:

![image](https://user-images.githubusercontent.com/5546996/66082996-57177e00-e5a6-11e9-862d-6ba6350ee015.png)

**Comment by panva** [comment]
Thank you!
