### ISSUE TITLE
Add wwayne/react-tooltip

### ISSUE THREAD

**Issue by evark** [michaelrambeau/bestofjs#282]
It is popular and active project.

**Comment by michaelrambeau** [comment]
Hello @evark 
Thank you for the suggestion, `React Tooltip` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @evark 
It's online. please check here: https://bestofjs.org/tags/tooltip
Thank you for your feedback!
