### ISSUE TITLE
Please add little-state-machine 

### ISSUE THREAD

**Issue by bluebill1049** [michaelrambeau/bestofjs#283]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

https://github.com/bluebill1049/little-state-machine

**Comment by michaelrambeau** [comment]
Hello Bill @bluebill1049 
Thank you, `Little State Machine` will be available on Best of JavaScript very soon!

Following a previous discussion about the "Next" version of _Best of JavaScript_,  I improved the search engine, now related tags are displayed when you select a tag.

So, for example, if you select the `Form` tag, you will be able to **refine the search** by selecting `React` for example.

![image](https://user-images.githubusercontent.com/5546996/66733447-8e393980-ee9a-11e9-96a4-4a91b2a4bebe.png)

Check here: https://next--bestofjs.netlify.com/projects?tags=form&sort=weekly
Let me know what you think, thank you again!

**Comment by bluebill1049** [comment]
Wow that’s awesome! Looks good too and love those status :)

**Comment by michaelrambeau** [comment]
Hello Bill @bluebill1049 
`Little State Machine` is available on _Best of JavaScript_.

Check here: https://bestofjs.org/tags/state-machine

**Comment by bluebill1049** [comment]
amazing! thank you
