### ISSUE TITLE
recommend a JS project called zzllrr Mather, which is a holistic web App for Math 

### ISSUE THREAD

**Issue by zzllrr** [michaelrambeau/bestofjs#284]
https://github.com/zzllrr/mather

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello @zzllrr 
Thank you for the suggestion.
I wonder if there is documentation available in English?
I checked quickly but I couldn't find instructions about how to use the application
Thank you for your understanding!
