### ISSUE TITLE
Add taskforcesh/bullmq

### ISSUE THREAD

**Issue by purefun** [michaelrambeau/bestofjs#285]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

Project: https://github.com/taskforcesh/bullmq

- [x] The project is related to the web platform and/or Node.js
- [ ] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

I think the project will get more than 50 stars very soon. ;)
It's the next major version of [OptimalBits/bull](https://bestofjs.org/projects/bull)

**Comment by michaelrambeau** [comment]
Hello @shape-ideas 
Thank you for the suggestion, `BullMQ` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @shape-ideas 
It's online, please check here: https://bestofjs.org/projects?tags=queue
Thank you in advance for your feedback!

**Comment by purefun** [comment]
Thanks
