### ISSUE TITLE
react-grid-layout

### ISSUE THREAD

**Issue by arturcarvalho** [michaelrambeau/bestofjs#286]
All checks seem good. 

Could fit with tags "grid" and "drag and drop": https://github.com/STRML/react-grid-layout

**Comment by michaelrambeau** [comment]
Hello Arthur @arturcarvalho 
Thank you for the suggestion, `React-Grid-Layout` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @arturcarvalho 

It's online, please check here: https://bestofjs.org/projects?tags=layout

By the way, we have recently released a brand new search engine, now you can combine 2 tags, for example `React` + `Layout` => https://bestofjs.org/projects?tags=layout&tags=react

 Let me know if you like it or not, thank you in advance!

**Comment by arturcarvalho** [comment]
Perfect! 😃 I've used the search, it works really well.

Just curious, how do you find the projects? I usually google + list the stuff in state of js before doing proofs of concept.

Keep up the great work!

**Comment by michaelrambeau** [comment]
Hello @arturcarvalho 
Thank you for your feedback.
To find new projects to add, I often check:

- JavaScript newsletters
- projects starred by GitHub users I follow
- the daily trends on GitHub

It's not perfect of course, some great projects may be missing.

The goal of _Best of JavaScript_ is to avoid having to look up on Google or GitHub when you want to check a given project or when you want to get an overview for a given topic (like "CSS in JS", that was the topic I was checking right now!)

**Comment by arturcarvalho** [comment]
Hi @michaelrambeau.

I see, the projects are curated by you and the github stats are automatically updated. Pretty nice.
(Facebook is going to release their "css in js" project soon, so that's another one for you to keep an eye on 😉 )

**Comment by michaelrambeau** [comment]
Yes @arturcarvalho the project list is "curated".

After a certain period of time, projects can "decay" and are no more included in the list (if there is no commit for one year and nobody has added a star in one year, it usually means the project is no more relevant, for example).

Of course feel to suggest any idea to improve the concept, I'd like to make the process more automatic.

I'm really curious about the project you mentioned, please send me the link!

**Comment by arturcarvalho** [comment]
IMO the concept seems pretty good as it is. 

Initially I thought it was automated. For instance, if some scheduled job you had would detect a new project that broke some kind of threshold (e.g. the project passed 500 stars + changes during last year) you would include it automatically. A sort of google rank for npm projects.

The trade-off would be smaller projects that wouldn't trigger the threshold to be included.

There was a talk during reactconf by https://twitter.com/frankyan about the fb css in js. Their css in js solution has some interesting ideas that maybe nobody else has implemented, but there's nothing official yet.

**Comment by michaelrambeau** [comment]
Thank you your ideas and for the link Arthur @arturcarvalho 

Besides the trade-off you mentioned, there is no official API to check the number of stars at a given time.
So I decided to track the numbers of stars by myself, every day.
But I cannot track all existing projects on GitHub ("the egg and the chicken" problem)

There is also the problem of tagging the projects. I don't find tags from NPM or "topics" from GitHub really relevant sometimes, finding and maintaining tags that make sense is part of my workflow.

However this problem is less critical now that tags can be filtered with the new autocomplete feature.

**Comment by arturcarvalho** [comment]
I wasn't aware of those limitations. I thought it would be possible to query all the repos on github with the graphqpl api or maybe from npm.

But yeah, even with that automated, tagging with still remain a problem.
