### ISSUE TITLE
Add joe223/tiny-swiper

### ISSUE THREAD

**Issue by joe223** [michaelrambeau/bestofjs#287]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello @joe223 
Thank you for the suggestion, `Tiny-Swiper` will be available on _Best of JavaScript_ very soon.

**Comment by joe223** [comment]
That great ！ I'm looking forward to it.

**Comment by michaelrambeau** [comment]
Hello @joe223 

It's online, please check here: https://bestofjs.org/projects?tags=slider&sort=daily

By the way, we have recently released a brand new search engine (more details: https://github.com/bestofjs/bestofjs-webui/issues/75), let me know if you like it or not, thank you in advance!

**Comment by joe223** [comment]
Thanks
