### ISSUE TITLE
Add bbc/sqs-consumer

### ISSUE THREAD

**Issue by purefun** [michaelrambeau/bestofjs#288]
https://github.com/BBC/sqs-consumer

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello @shape-ideas 
Thank you for the recommendation.
`sqs-consumer` will be available on _Best of JavaScript_ very soon.
And I didn't know that BBC was into open-source code, it's good to know.

**Comment by purefun** [comment]
Thanks

**Comment by michaelrambeau** [comment]
Hello @shape-ideas 
It's online, please check here: https://bestofjs.org/projects?tags=queue
Thank you for your feedback!
