### ISSUE TITLE
I recommend Mark Text

### ISSUE THREAD

**Issue by Jocs** [michaelrambeau/bestofjs#289]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

### Introduction

[Mark Text](https://github.com/marktext/marktext) is a simple and elegant open-source markdown editor that focused on speed and usability.

And it available for Linux, macOS and Windows.

### Features

- Realtime preview (WYSIWYG) and a clean and simple interface to get a distraction-free writing experience.
- Support CommonMark Spec and GitHub Flavored Markdown Spec.
- Markdown extensions such as math expressions (KaTeX), front matter and emojis.
- Support paragraphs and inline style shortcuts to improve your writing efficiency.
- Output HTML and PDF files.
- Various themes: Cadmium Light, Material Dark etc.
- Various editing modes: Source Code mode, Typewriter mode, Focus mode.

**Comment by michaelrambeau** [comment]
Hello @Jocs 
Thank you for the recommendation.
The project looks great, the only problem is that so far _Best of JavaScript_ does not track that kind of productivity application, we don't have a tag "Markdown Editor".
We have a tag called "Markdown" but it means libraries that can be used to handle markdown content.

However, we have a category "IDE" that also contains several desktop applications.
What do you think, should we create a new tag "Markdown editor app"?

Such a tag would include:

- MarkText
- [BoostNote](https://github.com/BoostIO/Boostnote)
- [Notable](https://github.com/notable/notable)
- Other projects?

[Typora](https://typora.io) would not be included because it's not an open-source project.

Thank you in advance for your feedback!

**Comment by Jocs** [comment]
Thank you very much for your quick reply. I think it belongs to `markdown`, also belongs to the `markdown editor app`, can it have multiple labels at the same time?

**Comment by michaelrambeau** [comment]
Hello @Jocs 

Yes, a project can have multiple tags, this is why we have released a new search engine last week (see https://github.com/bestofjs/bestofjs-webui/issues/75)

So you think we need a tag such as "Markdown Editor App", it makes sense to you?

It will be created and it will include the 3 projects I mentioned (MarkText, BoostNote and Notable), if you are OK?

**Comment by Jocs** [comment]
>It will be created and it will include the 3 projects I mentioned (MarkText, BoostNote and Notable), if you are OK?

@michaelrambeau I think `Markdown Editor App` is OK. :+1:

**Comment by michaelrambeau** [comment]
OK @Jocs the 3 projects will be available on Best of JavaScript very soon.

**Comment by Jocs** [comment]
@michaelrambeau Thanks!

**Comment by michaelrambeau** [comment]
Hello @Jocs 
It's online, please check here: https://bestofjs.org/projects?tags=md-editor-app
Thank you for your feedback!

![image](https://user-images.githubusercontent.com/5546996/67642378-76f45480-f94e-11e9-8c2f-b0b41ca90ab8.png)

**Comment by Jocs** [comment]
@michaelrambeau Thanks for your work, I have one question, how can I see the history of DAILY TRENDS?

**Comment by michaelrambeau** [comment]
I think you're talking about that calendar view:

![image](https://user-images.githubusercontent.com/5546996/67644003-c3489000-f960-11e9-8068-1004371df56f.png)


We store daily trends data by ourselves, for all the projects we track in _Best of JavaScript_ but there is no official API to access data.

Your project has just been added so it will take time to fill all the little of squares of the calendar. But it will be updated every day with a new little square... so be patient 😄

**Comment by Jocs** [comment]
Thank you very much for your patience. Bestofjs is a very good project. I really like this project.

**Comment by michaelrambeau** [comment]
@Jocs Thank you for your kind words!
