### ISSUE TITLE
Add `js-cookie/js-cookie` project

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [michaelrambeau/bestofjs#29]
https://github.com/js-cookie/js-cookie
The most popular library for handling cookies in the browser

**Comment by michaelrambeau** [comment]
Hello @FagnerMartinsBrack ,
Thank you, I am adding `js-cookie` :cookie: project to bestof.js.org.
It will be online in 48 hours.

it's interesting that a library that only deals with cookies already required more than 500 commits!
I guess that's the price for doing things the right way ;) (and I guess dealing with browser quirks is a pain!)

**Comment by FagnerMartinsBrack** [comment]
This project is the same [jquery-cookie](http://plugins.jquery.com/cookie/) but was born when we decided to remove jQuery as a hard dependency. It was one of the first 8 jquery plugins at the time jQuery was on Google Code. It is currently in a very good stability state, after all it's 9 years of development!

There's not much regarding browser quirks since it can easily support up to IE 6 without much effort. It is mostly about documenting how cookies work in the browsers and serve as a single source of truth through an efficient abstraction based mostly on docs that [eases the impact of abstraction leaks](https://medium.com/@fagnerbrack/repairing-the-leaky-abstraction-e726baab91b5) instead of having a lot of low-level information scattered through the internet.

**Comment by michaelrambeau** [comment]
Thank you very much the explanation, that's great!
I will let you know when it's online.

**Comment by FagnerMartinsBrack** [comment]
I edited the comment above, I was saying " it can easily support up to IE 8" but I meant " it can easily support up to IE 6".

**Comment by michaelrambeau** [comment]
Hello @FagnerMartinsBrack , it's online, number 6 of the `utils` tag: http://bestof.js.org/tags/util

By the way, let me know if you have a better idea about how to classify those `utils` libraries, thank you!

**Comment by FagnerMartinsBrack** [comment]
> By the way, let me know if you have a better idea about how to classify those utils libraries, thank you!

My suggestion would be to organize all those `utils` in feature tags. Utils tend to become too generic and contain a lot of stuff, just like we build the "others" folder in our personal file system where we fill it with things we never know it's there :D

js-cookie could be on "cookie" tag, Lodash in "Functional Programming" along with Ramda and similar libs, clipboard.js on "clipboard", "Underscore on Functional Programming" too, etc.

**Comment by FagnerMartinsBrack** [comment]
You can also have a definition of `library` vs `framework` and tag as such, but from a user perspective it's easier to find through feature tags instead.

**Comment by michaelrambeau** [comment]
Thank you, I will try to move toward the 'feature tags' approach indeed
