### ISSUE TITLE
Add react-charty

### ISSUE THREAD

**Issue by 99ff00** [michaelrambeau/bestofjs#290]
A data viz library that can be used with React or stand-alone:
https://github.com/99ff00/react-charty

- [x] The project is related to the web platform and/or Node.js
- [ ] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Aleksandr @99ff00
Thank you for the suggestion.
For the moment, _Best of JavaScript_ only tracks projects with more than 50 stars, I guess `react-charty` will reach this threshold very soon.
By the way your avatar background color perfectly matches your username, this is amazing, I've never seen that before, good job!

**Comment by 99ff00** [comment]
> By the way your avatar background color perfectly matches your username, this is amazing, I've never seen that before, good job!

🤣I'm glad someone finally noticed.
