### ISSUE TITLE
Recommend G2

### ISSUE THREAD

**Issue by afc163** [michaelrambeau/bestofjs#291]
https://github.com/antvis/g2

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello @afc163 , it's been a long time 😄 !

Thank you for the suggestion, `G2` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @afc163 it's online, please check here: https://bestofjs.org/projects?tags=chart

Thank you for your feedback!
