### ISSUE TITLE
Kingly - state machine library

### ISSUE THREAD

**Issue by brucou** [michaelrambeau/bestofjs#292]
Repository: https://github.com/brucou/kingly
Documentation: https://brucou.github.io/documentation/
Should figure here: https://bestofjs.org/projects?tags=state-machine&sort=last-commit

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello @brucou 
Thank you for the suggestion, `Kingly` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @brucou 
It's online, please check here: https://bestofjs.org/projects?tags=state-machine
Thank you for your feedback!

**Comment by brucou** [comment]
It is amazing, thanks!!

On 11/24/19, Michael Rambeau <notifications@github.com> wrote:
> Hello @brucou
> It's online, please check here:
> https://bestofjs.org/projects?tags=state-machine
> Thank you for your feedback!
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/michaelrambeau/bestofjs/issues/292#issuecomment-557930166


-- 
---

**Comment by brucou** [comment]
@michaelrambeau , one small thing I noticed, the project's page for Kingly (https://brucou.github.io/documentation/) is missing from the bestofjs site.

**Comment by michaelrambeau** [comment]
Hello @brucou it's missing because you have not set up the project's "Website" on GitHub.

It's just after the project's description, for example:

![image](https://user-images.githubusercontent.com/5546996/71314628-0c175380-248f-11ea-8a14-bdcb1970b698.png)

Could you update it on GitHub, and then _Best of JavaScript_ will automatically pick it up?

**Comment by brucou** [comment]
oh wow, I did not know that. hanks, it is now done

On 12/21/19, Michael Rambeau <notifications@github.com> wrote:
> Hello @brucou it's missing because you have not set up the project's
> "Website" on GitHub.
>
> It's just after the project's description, for example:
>
> ![image](https://user-images.githubusercontent.com/5546996/71314628-0c175380-248f-11ea-8a14-bdcb1970b698.png)
>
> Could you update it on GitHub, and then _Best of JavaScript_ will
> automatically pick it up?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/michaelrambeau/bestofjs/issues/292#issuecomment-568217504


-- 
---
