### ISSUE TITLE
neo.mjs - The webworkers driven UI framework

### ISSUE THREAD

**Issue by mrsunshine** [michaelrambeau/bestofjs#293]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

Added neo.mjs to the list of frameworks.
neo.mjs is a webworker driven UI framework using ES8
https://github.com/neomjs/neo

**Comment by michaelrambeau** [comment]
Hello Nils @mrsunshine ☀️ 
Thank you for the recommendation.
I'm curious about the history of the project, the README.md says "3720 commits in total", and the copyright is from 2015... is it based on an other project?
When do the official released is planned?

**Comment by mrsunshine** [comment]
Hi @michaelrambeau,
The guys (Tobi and Rich) started developing it back in 2015. The code was previously on a privat gitlab repo and was recently moved to github to make it public and open source (MIT). First public (beta) release was on last Saturday (23.11.). To get more contributors and momentum on the framework I try to spread  word. Thats why I created the PR on your Repo :-).
If you need more detailed infos I happily connect you with Tobias @tobiu (https://github.com/tobiu) one of the framework core developers.

Sunny ☀️ 😎 greetings 

Nils

**Comment by michaelrambeau** [comment]
Hello Nils @mrsunshine 
It's online, could you please check here, for example: https://bestofjs.org/projects?tags=webworker
Thank you!

**Comment by mrsunshine** [comment]
Perfect! Thanks a lot @michaelrambeau
