### ISSUE TITLE
Suggestion: n8n

### ISSUE THREAD

**Issue by janober** [michaelrambeau/bestofjs#299]
I want to suggest to add my project n8n which is a free easily extendable self hostable workflow automation tool.

Website: https://n8n.io
Github: https://github.com/n8n-io/n8n
npm: https://www.npmjs.com/package/n8n

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Jan @janober 
Thank you for the recommendation, n8n project looks great.

How do you think the project could be tagged in _Best of JavaScript_, we don't have similar projects (I think). Should we create a tag called "Workflow" or can you see something more generic? Can you see other projects that should be tagged under this new tag?

Thank you for your help!

**Comment by janober** [comment]
Hello @michaelrambeau,
great to hear that it looks interesting!
I checked now all the tags and did not find anything matching either. The only ones I did find which could qualify as it can also be done with n8n would be: Bot, Data fetching

Apart from that possible tags could be: Automation, No-code, Workflow

**Comment by michaelrambeau** [comment]
Hello Jan @janober 
It's online, could you please check?
https://bestofjs.org/projects?tags=workflow

A new tag called "Workflow automation" has been created, let me know if you about other great projects that should be added to this category.

By the way, when you said you checked all the tags, it must have been difficult for you because there is no page that lists all the available tags, it's a feature that will be available very soon, I may ask you to check, if you don't mind.

**Comment by janober** [comment]
Thanks a lot, looks good!

About other projects. The only other one which allows doing something similar and uses JavaScript would be https://nodered.org/ even though it would be more low level and they describe themself as low-code programming.

Checking all the tags was actually not that difficult. I simply clicked in the search box on the top and then it displays all the 163 which apparently exist currently. Sure can then check it out once it is ready.

**Comment by janober** [comment]
Ok close the issue as it got added. Thanks!

**Comment by michaelrambeau** [comment]
Hello @janober 
I forgot to ping you sorry, we have released the "Tags" page I mentioned in the thread.
https://bestofjs.org/tags

About "Node-RED", it's on _Best of JavaScript_, but it's under the tag "IoT".
https://bestofjs.org/projects?tags=iot
Do you think it should be also tagged "Workflow automation", like `n8n` project?
Thank you for your help!

**Comment by janober** [comment]
Ah cool just checked it. Yes, the tags-page will be very helpful.

Yes, IoT is definitely the best tag for them but workflow automation is also possible with them up to some degree so adding it is probably not wrong.

**Comment by michaelrambeau** [comment]
Thank you for the advice Jan! @janober 

You are in good company now: https://bestofjs.org/projects?tags=workflow

![image](https://user-images.githubusercontent.com/5546996/71605364-a6704900-2bab-11ea-8d7c-46e188ae1ffa.png)
