### ISSUE TITLE
Add `ElemeFE/element` project

### ISSUE THREAD

**Issue by otabekgb** [michaelrambeau/bestofjs#30]
https://github.com/ElemeFE/element
Frontend UI framework for VUE 2

**Comment by michaelrambeau** [comment]
Hello @otabekgb , thank you, I am adding the project, it will be available online in 48 hours.

Is there a documentation page in English ?

**Comment by otabekgb** [comment]
I couldn't find one except readme page at github. I checked the website by translating with google chrome.

**Comment by otabekgb** [comment]
Its already translated to English:
http://element.eleme.io/#/en-US

**Comment by michaelrambeau** [comment]
Thank you @otabekgb .

`Element` project is available on http://bestof.js.org/ and it's today's number 3 project!

![image](https://cloud.githubusercontent.com/assets/5546996/20367251/12991644-ac92-11e6-89bf-2a3b8fb71d8d.png)

**Comment by michaelrambeau** [comment]
@otabekgb ...and today, `Element` is the number one, congratulations! 🎉
