### ISSUE TITLE
Recommendation: MSAL.js

### ISSUE THREAD

**Issue by jasonnutter** [michaelrambeau/bestofjs#300]
> The Microsoft Authentication Library for JavaScript enables client-side JavaScript web applications, running in a web browser, to authenticate users using Azure AD for work and school accounts (AAD), Microsoft personal accounts (MSA), and social identity providers like Facebook, Google, LinkedIn, Microsoft accounts, etc. through Azure AD B2C service. It also enables your app to get tokens to access Microsoft Cloud services such as Microsoft Graph.

Github: https://github.com/AzureAD/microsoft-authentication-library-for-js
npm: https://www.npmjs.com/package/msal
Docs: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-javascript

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Jason @jasonnutter 
Thank you for the recommendation.

The project looks great but the only problem is that for now we don't track projects related to authentication online services.
If we include MSAL.js, we should track libraries like Auth0.js too (it was requested in the past #45 ) and create a new tag I guess.

What do you think, should we track these projects and what would be the right tags: `authentication` and `serverless`? A new one?

Thank you for your help!

**Comment by jasonnutter** [comment]
@michaelrambeau Personally, yes, I would say you should track authentication libraries like MSAL.js (and others like Auth0, Hello.js, etc.).

As far as tags, I would use the existing `auth` tag (`serverless` isn't relevant here).

Thanks!

**Comment by michaelrambeau** [comment]
Hello Jason @jasonnutter 
OK, the 3 following projects will be available on _Best of JavaScript_ very soon:

- `MSAL.js`
- `auth0`
- `hello.js`

**Comment by michaelrambeau** [comment]
Hello Jason @jasonnutter 
The 3 projects have been added, could you check here: https://bestofjs.org/projects?tags=auth
Thank you for your feedback!

**Comment by jasonnutter** [comment]
@michaelrambeau Looks great, thanks!
