### ISSUE TITLE
Add Airframe

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#301]
Site: http://airframe.webkom.co/
GitHub repo of React version: https://github.com/0wczar/airframe-react

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Thank you for the suggestion Denis @gamtiq 
It will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Happy new year 2020 Denis! @gamtiq 

It's online, please check here: https://bestofjs.org/projects?tags=dashboard

**Comment by gamtiq** [comment]
Happy New Year, Michael!
Thank you!
