### ISSUE TITLE
react-diagrams

### ISSUE THREAD

**Issue by arturcarvalho** [michaelrambeau/bestofjs#302]
Hi there,

Couldn't find this one and seems an interesting project:
https://github.com/projectstorm/react-diagrams

Maybe this one would be a good fit to add to best of JS.

Cheers

**Comment by michaelrambeau** [comment]
Hello Artur @arturcarvalho 
Thank you for the recommendation, it will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
@arturcarvalho  Happy new year 2020 Artur!
It's online, please check the charting tag: https://bestofjs.org/projects?tags=chart

Maybe, in addition of "charting", a more specific tag like "diagram" (or flowchart?) would be useful, what do you think?

**Comment by arturcarvalho** [comment]
> 
> 
> @arturcarvalho Happy new year 2020 Artur!
> It's online, please check the charting tag: https://bestofjs.org/projects?tags=chart
> 
> Maybe, in addition of "charting", a more specific tag like "diagram" (or flowchart?) would be useful, what do you think?

@michaelrambeau Happy New Year 2020 Michael! :)

Great, thanks! A diagram tag would be great, it's always nice searching and seeing that there's a related tag. For flowchart or diagram I'm not sure. Diagram seems better to me, but I suppose that's my natural tendency to look for diagram.

**Comment by michaelrambeau** [comment]
Hello Artur @arturcarvalho 
I forgot to tell you that now we have a tag called "Diagram / Flow chart":
https://bestofjs.org/projects?tags=diagram

Sorry for the very late reply, let me know if it makes sense, thank you!

**Comment by arturcarvalho** [comment]
Hi Michael @michaelrambeau 

That's great! Thanks for doing this. The site and the mailing list are really nice and a great way to keep up with stuff that's trending.

**Comment by michaelrambeau** [comment]
Thank you for your support Artur!
