### ISSUE TITLE
Add JSON Editor

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#303]
https://github.com/josdejong/jsoneditor

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
It's available on _Best of JavaScript_ under the 2 following tags:

- `JSON` https://bestofjs.org/projects?tags=json
- `Syntax Highlighting` https://bestofjs.org/projects?tags=highlight

Thank you for your feedback!
