### ISSUE TITLE
Add TypeGraphQL to Best of JavaScript

### ISSUE THREAD

**Issue by MichalLytek** [michaelrambeau/bestofjs#304]
I would like to propose a project called TypeGraphQL, which is a modern framework for GraphQL API in Node.js. It is also used by NestJS as a code-first approach for builing GraphQL schemas.

Website: https://typegraphql.ml/
GitHub: https://github.com/MichalLytek/type-graphql

I've checked the following points:
- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Michal @MichalLytek 
That looks great, thank you very much for the suggestion.
It will be available on _Best of JavaScript_ very soon.

**Comment by MichalLytek** [comment]
I can see it now on the website 🎉 Thanks!

![image](https://user-images.githubusercontent.com/10618781/72604574-6fc05f80-391b-11ea-83ca-37ce9a99120d.png)

It's a bit sad for me that it would be a no. 7 rising star for GraphQL in 2019 (+2442⭐️) 😞 
https://risingstars.js.org/2019/en/#section-graphql

**Comment by michaelrambeau** [comment]
Hello Michal @MichalLytek 
Yes it's live, I forgot to tell you.
And about Rising Stars, it only handles projects tracked in 2019, that's right, I'm sorry!
