### ISSUE TITLE
Add Flyd

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#305]
https://github.com/paldepind/flyd

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq ,
Thank you for the recommendation.
Just to confirm, the repo project is still active? it seems the package was published 2 years ago on NPM: https://www.npmjs.com/package/flyd

**Comment by gamtiq** [comment]
Hello Michael,
Sorry, I missed that the last version of Flyd was published in July of 2018.
Maybe you are right and currently the project is not in active development.
You are free not to add Flyd into Best of JS and to close the issue.

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
I trust your judgement so _Flyd_ has been added to _Best of JavaScript_ 😃 

Please check here: https://now--bestofjs.netlify.com/projects?tags=reactive
