### ISSUE TITLE
Add `r37r0m0d3l/consono`

### ISSUE THREAD

**Issue by r37r0m0d3l** [michaelrambeau/bestofjs#306]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

Project: https://consono.js.org/

- [x] The project is related to the web platform and/or Node.js
- [ ] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

Project surpasses 2.6K downloads and keep growing. But it looks like people just use it and doesn't bother to give any stars 😒.

**Comment by michaelrambeau** [comment]
Hello Anton @r37r0m0d3l 
Thank you for the recommendation.
Unfortunately the application only tracks projects with more than 50 stars on GitHub, I know this is not fair for new projects or nice projects like yours that didn't get signs of appreciation from users.

I keep an eye on your project and I will let you know if the system changes (ideally projects tracked by Best of JavaScript should be the results of an automatic curation?).
Sorry and thank you for your understanding!
