### ISSUE TITLE
Fullcalendar

### ISSUE THREAD

**Issue by AhnafCodes** [michaelrambeau/bestofjs#307]
[Fullcalendar](https://fullcalendar.io/) 
 https://github.com/fullcalendar/fullcalendar
 https://www.npmjs.com/package/fullcalendar

- [x] The project is related to the web platform and/or Node.js
- [x]  The project has more than 10,000 stars on GitHub
- [x]  The project has a thorough documentation
- [x]  The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello @AhnafCodes 
Thank you for the recommendation, it's online, please check here: https://bestofjs.org/projects?tags=date
Thank you!
