### ISSUE TITLE
Add Oleksii Trekhleb to the Hall of Fame

### ISSUE THREAD

**Issue by YaninaTrekhleb** [michaelrambeau/bestofjs#308]
I recommend to add Oleksii Trekhleb (https://github.com/trekhleb) to the list. He is the author of JavaScript Algorithms repository https://github.com/trekhleb/javascript-algorithms. 

Before submitting the request to add a new member, check the following points:

- [x] The member has a GitHub profile with more than 500 followers
- [x] The member is renowned for her/his writings, talks or projects

**Comment by michaelrambeau** [comment]
Thank you for the recommendation @YaninaTrekhleb 
Oleksii Trekhleb has been inducted to the JavaScript Hall of Fame, please check here:

https://bestofjs.org/hall-of-fame
