### ISSUE TITLE
Add emoji-button

### ISSUE THREAD

**Issue by joeattardi** [michaelrambeau/bestofjs#309]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [X] The project is related to the web platform and/or Node.js
- [X] The project has more than 50 stars on GitHub
- [X] The project has a thorough documentation
- [X] The project is not deprecated and still maintained

GitHub repository: https://github.com/joeattardi/emoji-button

**Comment by michaelrambeau** [comment]
Hello Joe @joeattardi 
Thank you for the recommendation.
So far we have only 2 projects related to emojis: https://bestofjs.org/projects?query=emoji
We definitively need more projects in this awesome category 😄 !
It will be online very soon.

**Comment by michaelrambeau** [comment]
One more thing Joe @joeattardi 
The link after the repo's description opens this page http://emoji-button.js.org/ that does not work right now (2020-02-19 8:45 AM Japan time)

**Comment by joeattardi** [comment]
Yes, sorry about that. I am currently in the process of switching over to a `js.org` subdomain. I just submitted it this afternoon, it should hopefully be working again in a few hours, or by tomorrow at the latest I hope.

Thanks!

**Comment by joeattardi** [comment]
The site is working now, I just checked. Thanks again!

**Comment by michaelrambeau** [comment]
Hello joe @joeattardi 
It's online, could you please check here: https://bestofjs.org/projects?tags=emoji
Thank you!

**Comment by joeattardi** [comment]
Looks great! Thank you so much!
