### ISSUE TITLE
Add `shohan4556/jolly-jumper` project

### ISSUE THREAD

**Issue by shohan4556** [michaelrambeau/bestofjs#31]
https://github.com/shohan4556/jolly-jumper
A fun game made in PhaserJs

**Comment by michaelrambeau** [comment]
Hello, thank you for your suggestion.
Unfortunately, bestof.js.org is only about tools and documentation to help developers "build amazing web applications".
There is a category "Game Engine" http://bestof.js.org/projects/tags/game but we don't store game projects, at least for now.
Things may change in the future and your game will be added if we decide to create something like "bestofgames.js.org".
Thank you for your understanding!
