### ISSUE TITLE
Add Eruda

### ISSUE THREAD

**Issue by surunzi** [michaelrambeau/bestofjs#310]
https://github.com/liriliri/eruda

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Thank you for that suggestion too, @surunzi  it will be available on Best of JavaScript very soon.

**Comment by michaelrambeau** [comment]
Hello again @surunzi 
`eruda` project is available on _Best of JavaScript_, check here for example:
https://bestofjs.org/projects?tags=debug&sort=newest

By the way, we have just released a new homepage, let us know what you think when you have time.
