### ISSUE TITLE
Add Licia

### ISSUE THREAD

**Issue by surunzi** [michaelrambeau/bestofjs#311]
https://github.com/liriliri/licia

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello @surunzi,
Thank you for the suggestion, Licia will be availalble on Best of JavaScript very soon.

**Comment by michaelrambeau** [comment]
Hello @surunzi 
It's online, please check here for example: https://bestofjs.org/projects?tags=util&sort=newest
