### ISSUE TITLE
Add phin

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#312]
https://github.com/ethanent/phin

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform and/or Node.js
- [x] The project has more than 50 stars on GitHub
- [x] The project has a thorough documentation
- [x] The project is not deprecated and still maintained

**Comment by michaelrambeau** [comment]
Hello @gamtiq 
Thank you for the suggestion, I guess it's a new contender for this tag: https://bestofjs.org/projects?tags=http

Since you are a long-time _Best of JavaScript_ super user, can I ask you what you think about the latest changes to the home page? (details: https://github.com/bestofjs/bestofjs-webui/issues/86#issuecomment-599790988)

**Comment by gamtiq** [comment]
Sure, I've added [comment](https://github.com/bestofjs/bestofjs-webui/issues/86#issuecomment-600320149).

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq , it's online!
And now you can see the latest addition to _Best of JavaScript_ right from the top page, what do you think, is "Newest Projects / Latest additions to _Best of JavaScript_" easy to understand?
Even if it's not really a "new" project in the case of that project, let me know if you think about a better wording.

![image](https://user-images.githubusercontent.com/5546996/77015282-b3852300-69b7-11ea-96c5-e063490a1697.png)

Note: if you click on "View all newest projects" you can see ALL the projects, from the latest addition to the first one (React, in 2015!).

Thank you for your feedback, again!

**Comment by gamtiq** [comment]
That's great!

> what do you think, is "Newest Projects / Latest additions to Best of JavaScript" easy to understand?

I suppose it is ok.
I'm not sure it is better wording, but instead of "Newest Projects" I would suggest to consider "Recently added projects".

> Note: if you click on "View all newest projects" you can see ALL the projects, from the latest addition to the first one (React, in 2015!).

It's cool feature!
