### ISSUE TITLE
Appwrite

### ISSUE THREAD

**Issue by eldadfux** [michaelrambeau/bestofjs#313]
https://github.com/appwrite/appwrite
Appwrite is an end-to-end backend server for web, native and mobile developers. 🚀

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js (web)
- [x] The project has more than 100 stars on GitHub (2.2k)
- [x] The project has a thorough documentation in English (https://appwrite.io/docs)
- [x] The project is not deprecated and actively maintained (yes)

How would this project be tagged?
Serverless, Database, Image processing, Authentication, Microservices, File system, File upload

**Comment by michaelrambeau** [comment]
Hello Eldad @eldadfux 
I don't know if you remember but you posted an issue a long time ago https://github.com/michaelrambeau/bestofjs/issues/273 but you have not replied to my question 😢 .

Thank you in advance for your answer!

**Comment by eldadfux** [comment]
Ohh 😟so sorry, probably missed it between too many notifications 😓.

The project is not a node.js framework as it is actually an HTTP server interacting with web based apps (js or node) over a REST API (soon with GraphQL too).

I think the best category for is probably serverless or "backend as a service". Other tags that might fit as mentioned above could be: Database, Image processing, Authentication, Microservices, File system, File upload

**Comment by michaelrambeau** [comment]
No problem Eldad @eldadfux !
About your request, the problem is that _Best of JavaScript_ does not track such projects, we only track back-end projects that run on Node.js.
Otherwise there are a lot of projects that we should track (like e-commerce platform that run on PHP too, even if the front-end is in JavaScript).
If the scope of _Best of JavaScript_ change, we can reconsider your request of course.
Let me know if I missed anything.
Thank you for your understanding!

**Comment by eldadfux** [comment]
Yeh I get it, but this is a product that is aimed for JS developers not backend developers. The core language has no meaning for the end developers as they only interact and integrate with Appwrite using and HTTP API or the dedicated JS SDK (https://github.com/appwrite/sdk-for-js). This is not a CMS or a Ecommerce project. It is a backend as a service, similar to Firebase or Parse.

**Comment by michaelrambeau** [comment]
Thank you for the explanation Eldad, we will re-consider your request when we extend the scope of _Best of JavaScript_ and accept backend projects written in any language, I've just made a similar answer for a project written in C#.
Thank you again for your understanding!
