### ISSUE TITLE
Add game-of-life

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#314]
Project [game-of-life](https://github.com/TroyTae/game-of-life) is an implementation and playground of Conway's game of life. 

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Canvas, WebGL, Playground)

**Comment by TroyTae** [comment]
Oh It seems  necessary stars are increased..?

**Comment by ghost** [comment]
Oh I saw 50 or more stars are needed before 😅 
But It seems  necessary stars are increased..?

**Comment by michaelrambeau** [comment]
Hello @TroyTae 
Thank you for the suggestion.
Sorry, now _Best of JavaScript_ does not really track games so I don't know how "Game of life" could be tagged.
The _playground_ tag means "project to test components in isolation", maybe we should find a better way to avoid any confusion.

**Comment by ghost** [comment]
Hello @michaelrambeau 
How about "Side project" or "Toy project"?

**Comment by michaelrambeau** [comment]
Hello @TroyTae 
The main reason why we don't track toy projects is the current architecture of the application: a list of **all** projects tracked by _Best of JavaScript_ is loaded when the application starts, it's a single JSON file of more than 1500 projects so it can't grow indefinitely, we have to make some choices and introducing a category like "toy projects" would open the door for a lot of similar projects, I think
However, we are thinking about a different structure, with a real server that could respond to user requests in real-time, it would offer more flexibility.
Or we may change our point of view if your project gets a lot of traction.
So stay tuned, and thank you for your understanding!

**Comment by ghost** [comment]
@michaelrambeau 
I understood :)
I'll think about more specific category of my project.
And I hope real server is coming soon 👍
