### ISSUE TITLE
Add textlint

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#315]
https://textlint.github.io/
Before submitting the request to add a new project, please check the following points:

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has a thorough documentation in English
- [X] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
Linter, Markdown
Maybe also new tag should be added: Text processing

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
OK, it's coming soon.
Note: we have a category called `HTML and text parsing` that is similar to the "Text processing" you're asking, I think?
https://bestofjs.org/projects?tags=parsing
Or maybe I should rename it "Text processing", it would make more sense?

**Comment by gamtiq** [comment]
Hello Michael,
I checked `HTML and text parsing` category page and didn't include the tag because corresponding projects mostly relate to parsing and HTML. Which is not the main case/purpose for textlint (imho).
I doubt that `HTML and text parsing` tag should be renamed. The tag specifies quite standalone and useful set of projects. But the tag doesn't cover all text processing projects like in the case with textlint.
So I would suggest to add new tag `Text processing` and maybe mark with it some projects listed on `HTML and text parsing` page (for example, `unified` and `retext` are good candidates for that I think).

**Comment by michaelrambeau** [comment]
OK @gamtiq `Textlint` is available on _Best of JavaScript_.

A new tag `Text processing` has been added: https://bestofjs.org/projects?tags=text-processing

Thank you for your feedback, as always!
