### ISSUE TITLE
SapphireDb

### ISSUE THREAD

**Issue by morrisjdev** [michaelrambeau/bestofjs#316]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
angular, database, websocket

Urls:
[https://github.com/SapphireDb/SapphireDb](https://github.com/SapphireDb/SapphireDb)
[https://sapphire-db.com/](https://sapphire-db.com/)

Description:

SapphireDb is a self-hosted, easy to use realtime database for Asp.Net Core and EF Core.

It creates a generic API you can easily use with different clients to effortlessly create applications with realtime data synchronization.
SapphireDb should serve as a self hosted alternative to firebase realtime database and firestore on top of .Net.

Check out the documentation for more details: [Documentation](https://sapphire-db.com/)

**Comment by michaelrambeau** [comment]
Hello Morris @morrisjdev 
Thank you for the suggestion.
Unfortunately _Best of JavaScript_ only tracks backend projects written in a flavor of JavaScript, for now.
Of course we would re-consider your request if we changed the scope of the application introducing a tag like "Backend in other languages".
Sorry, I made a similar response for an other request https://github.com/michaelrambeau/bestofjs/issues/313 about a backend that is interesting too.
Thank you for your understanding!

**Comment by morrisjdev** [comment]
Ok thank you for your explanation. Do you think it makes sense to add [https://github.com/SapphireDb/sapphiredb-js](https://github.com/SapphireDb/sapphiredb-js) instead?

**Comment by michaelrambeau** [comment]
Hello @morrisjdev 
For now, to avoid tracking too many projects (mainly because of the single JSON file loaded when the application starts), we limit the list to projects with more than 100 stars on GitHub but this limit could change in the future when we change the architecture of the application, bringing a real server to respond to user requests.
Sorry and again thank you for your understanding!
