### ISSUE TITLE
Add Crank.js

### ISSUE THREAD

**Issue by AndreLeria** [michaelrambeau/bestofjs#317]
https://github.com/bikeshaving/crank
https://crank.js.org/

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
UI Framework

**Comment by michaelrambeau** [comment]
Hello André @AndreLeria 
Thank you for the suggestion.
I'm reading the introduction post https://crank.js.org/blog/introducing-crank, it's very interesting!
`Crank.js` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello André @AndreLeria 
Not only _Crank.js_ is available on Best of JavaScript, but also it's the hottest project today!

![image](https://user-images.githubusercontent.com/5546996/79677512-2b4fa300-822d-11ea-901d-07662ea3eee4.png)
