### ISSUE TITLE
Kong/swrv

### ISSUE THREAD

**Issue by darrenjennings** [michaelrambeau/bestofjs#318]
https://github.com/Kong/swrv

---

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?
Data fetching, Vue, Caching

**Comment by michaelrambeau** [comment]
Hello Darren @darrenjennings 
Thank you for the suggestion, `swrv` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Darren @darrenjennings 
`swrv` is available on _Best of JavaScript_
Thank you in advance for your feedback!
