### ISSUE TITLE
Add UI-Router

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#319]
https://ui-router.github.io/
Repository of UI-Router for React: https://github.com/ui-router/react/

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
Routing

**Comment by michaelrambeau** [comment]
Thank you Denis @gamtiq it will be available very soon!

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
`UI-Router` is available on _Best of JavaScript_, check here: https://bestofjs.org/projects?tags=routing
