### ISSUE TITLE
Add `json-schema-faker/json-schema-faker` project

### ISSUE THREAD

**Issue by pateketrueke** [michaelrambeau/bestofjs#32]
https://github.com/json-schema-faker/json-schema-faker
I'm confident that JSON-Schema can help us on development and testing, until now wasn't there a tool for it.

**Comment by michaelrambeau** [comment]
Hello @pateketrueke, thank you for the suggestion.
I am adding `json-schema-faker` to bestof.js.org, it will be online in 48 hours.
I think I will tag it under a new tag, something like "Random generator" or just "Random data". 
I can also use the existing tag `Form validation` => http://bestof.js.org/tags/validation
Does it make sense, what do you think ?

**Comment by pateketrueke** [comment]
Good question, for me it can be tagged also under "Testing tools", e.g. its output can be used for render stuff and test UI things.

Also under "Data" and "Scaffolding - generator" may be?

I think JSON is by itself a big topic, consider this: https://github.com/burningtree/awesome-json

**Comment by michaelrambeau** [comment]
Thank you, I will do that. "Scaffolding" was more about "scaffolding a whole (web or node.js) application".
I should split the "Data" into several tags because it the word "data", just by itself, is ambiguous (I was lazy when I created this tag!).
I will check the awesome list you sent me, I may find other projects to add.
Thank you, I will keep you updated!

**Comment by michaelrambeau** [comment]
Hello @pateketrueke , `json-schema-faker` project is on bestof.js.org, as you can see here: http://bestof.js.org/tags/json

![image](https://cloud.githubusercontent.com/assets/5546996/21280752/371c61f0-c42b-11e6-8aa7-be9da36537fb.png)

I created 2 new tags:
* `JSON`
* `Random`

It's also available under `Testing tools` tag.

FYI I split the tag formerly called `Data` into `Data fetching` and `State management`.

Let me know if you have any feedback about the application, thank you!
