### ISSUE TITLE
Add Hyphen

### ISSUE THREAD

**Issue by ytiurin** [michaelrambeau/bestofjs#321]
https://github.com/ytiurin/hyphen

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
Typography

**Comment by michaelrambeau** [comment]
Hello Eugene @ytiurin 
Thank you for the suggestion, _Hyphen_ will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Eugene @ytiurin 
_Hyphen_ project is available on _Best of JavaScript_.
Thank you in advance for your feedback!
