### ISSUE TITLE
Add Selecto

### ISSUE THREAD

**Issue by daybrush** [michaelrambeau/bestofjs#322]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

https://github.com/daybrush/selecto

Before submitting the request to add a new project, please check the following points:

- [V] The project is related to the web platform or Node.js
- [V] The project has more than 100 stars on GitHub
- [V] The project has a thorough documentation in English
- [V] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
* Drag and drop
* Gesture - touch

**Comment by michaelrambeau** [comment]
Hello @daybrush 
Long time no see 😄 !
OK `Selecto` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello @daybrush 
It's online, could you please check?
You know have 3 different projects on _Best of JavaScript_, good job!
Let me know if you have any feedback about the application, thank you!

![image](https://user-images.githubusercontent.com/5546996/81510811-bd8c2800-934f-11ea-9931-49ed3504a94d.png)

**Comment by daybrush** [comment]
@michaelrambeau 

Thank you :)

It's good!
