### ISSUE TITLE
Add camaro

### ISSUE THREAD

**Issue by tuananh** [michaelrambeau/bestofjs#324]
https://github.com/tuananh/camaro

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
XML

**Comment by michaelrambeau** [comment]
Hello Tuan Anh @tuananh 
OK, thank you for the recommendation, `camaro` project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Tuan Anh, @tuananh 
It's online, check here for example: https://bestofjs.org/projects?tags=xml&sort=daily
Thank you in advance for your feedback!
