### ISSUE TITLE
https://github.com/glennfaison/mtn-momo

### ISSUE THREAD

**Issue by glennfaison** [michaelrambeau/bestofjs#325]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

**Comment by michaelrambeau** [comment]
Hello @glennfaison 
Thank you for the suggestion.
For now, such API wrappers are not really in the scope of _Best of JavaScript_ but we may re-consider your suggestion when we change the architecture of the application.
Sorry and thank you for your understanding!
