### ISSUE TITLE
Prisma

### ISSUE THREAD

**Issue by 2color** [michaelrambeau/bestofjs#326]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
- Data fetching
- Database

Project: https://github.com/prisma/prisma

**Comment by michaelrambeau** [comment]
Hello Daniek @2color ,
Thank you for the recommendation, _Prisma_ project will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Daniel @2color 
Prisma is available on _Best of JavaScript_, thank you in advance for your feedback!
