### ISSUE TITLE
Please add react-carousel

### ISSUE THREAD

**Issue by RobertHebel** [michaelrambeau/bestofjs#327]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

https://github.com/brainhubeu/react-carousel
https://brainhubeu.github.io/react-carousel

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
React, Slider

**Comment by michaelrambeau** [comment]
Hello Robert @RobertHebel 
Thank you for the suggestion, React Carousel will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Robert @RobertHebel 
It's online, check the "Recently Added Projects" section on the homepage, thank you for your feedback

**Comment by RobertHebel** [comment]
Thank you ;)
