### ISSUE TITLE
react-visual-editor

### ISSUE THREAD

**Issue by anye931123** [michaelrambeau/bestofjs#328]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [ ] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
- web-design
- react
- drag-drop

Project: https://github.com/brick-design/react-visual-editor

**Comment by michaelrambeau** [comment]
Hello @anye931123 
Thank you for the suggestion, it looks very interesting but we accept only projects with documentation in English, for now.
Is there any plan to add some documentation in English?
Thank you for your understanding!
