### ISSUE TITLE
Dokz

### ISSUE THREAD

**Issue by remorses** [michaelrambeau/bestofjs#329]
Dokz is a documentation site generator based on Nextjs and MDX
https://github.com/remorses/dokz
https://dokz.site

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has a thorough documentation in English
- [X] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
- React
- Documentation Generator
- Nextjs

**Comment by michaelrambeau** [comment]
Hello @remorses Tommaso!
Thank you for the recommendation, `Dokz` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
@remorses Hello Tommaso
Thank you for your patience, it's online, please check here: https://bestofjs.org/projects?tags=doc

**Comment by remorses** [comment]
Thank you, bestofjs is really an awesome website
