### ISSUE TITLE
Add paseto

### ISSUE THREAD

**Issue by panva** [michaelrambeau/bestofjs#330]
> PASETO (Platform-Agnostic SEcurity TOkens) for Node.js with minimal dependencies

https://github.com/panva/paseto

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

Stars are steadily getting there.

> How would this project be tagged?

I guess same as `jose` - Authentication

**Comment by michaelrambeau** [comment]
Hello Filip @panva 
Long time no see!
OK _Paseto_ will be available on Best of JavaScript very soon.

**Comment by michaelrambeau** [comment]
Hello Filip @panva , it's online, please check here https://bestofjs.org/projects?tags=auth

Now that you have 4 projects on _Best of JavaScript_ would you be interesting in adding a badge on the README.md, that provides data about the trends? More details here: https://github.com/bestofjs/bestofjs-webui/issues/79

**Comment by panva** [comment]
@michaelrambeau thanks for adding the project. I’ll pass on the badge, there are none cluttering my readmes atm. 

Thank you!
