### ISSUE TITLE
Toastify-JS

### ISSUE THREAD

**Issue by apvarun** [michaelrambeau/bestofjs#332]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

- Notification
- Utils

Project: https://github.com/apvarun/toastify-js
Demo: https://apvarun.github.io/toastify-js/

**Comment by michaelrambeau** [comment]
Hello Varun @apvarun ,
Thank you for the suggestion, _Toastify_ will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Varun,
It's online, please check _Best of JS_ homepage.
Thank you for your feedback!

**Comment by apvarun** [comment]
Thanks for letting me know 🙌 @michaelrambeau
