### ISSUE TITLE
Whenipress -  A gorgeous, simple, tiny JavaScript package to add keyboard bindings into your application.

### ISSUE THREAD

**Issue by lukeraymonddowning** [michaelrambeau/bestofjs#333]
Hullo!

I created a small open source JS package yesterday that makes it super easy to register key bindings in websites and applications. It already has over 250 stars, so I wondered if I could suggest it here?

Many thanks,
Luke Downing

**Comment by michaelrambeau** [comment]
@lukeraymonddowning Hello Luke!
Thank you for the suggestion, `whenipress` will be available on _Best of JavaScript_ very soon.

**Comment by michaelrambeau** [comment]
Hello Luke @lukeraymonddowning 
It's online, please check here for example: https://bestofjs.org/projects?tags=keyboard
Thank you in advance for your feedback!
