### ISSUE TITLE
@monaco-editor/react

### ISSUE THREAD

**Issue by suren-atoyan** [michaelrambeau/bestofjs#334]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

- monaco editor
- monaco editor react
- code editor

[Github](https://github.com/suren-atoyan/monaco-react)
[Demo](https://monaco-react.surenatoyan.com/)

**Comment by michaelrambeau** [comment]
Hello Suren @suren-atoyan 
Thank you for the suggestion, it will be available on _Best of JS_ very soon.
I guess we should add the orginal Monaco editor too: https://github.com/Microsoft/monaco-editor since your project is a wrapper to integrate the Monaco editor as a React component, if I understand well?

**Comment by suren-atoyan** [comment]
Hello @michaelrambeau.

Thank you 🎉 

I totally agree with you. If we are going to add a wrapper for React the original also should be there 🙂

**Comment by michaelrambeau** [comment]
Hello Suren @suren-atoyan it's online, check the home page or go to https://bestofjs.org/projects?tags=highlight

Thank you in advance for your feedback!

**Comment by suren-atoyan** [comment]
Thank you @michaelrambeau. The idea of your app is great; I am sure it will become well known in the near future.

One more thing: you've marked `monaco` and `monaco-react` with `Syntax highlighting` tag, in my opinion, it would be better to have `editor` or `code editor` tag and mark them with that, I think `Syntax highlighting` is not the best characteristic for them, at least as a first characteristic.

**Comment by michaelrambeau** [comment]
Thank you for your comment Suren @suren-atoyan 
We have already a tag called `IDE`: https://bestofjs.org/projects?tags=ide with projects like VS Code, Atom. Bracket...
Do you think we should create a tag called `Code Editor` since an IDE is a concept a bit different (`Code Editor` could be seen a subset of `IDE`?)
Thank you for your help!

**Comment by suren-atoyan** [comment]
[The definition](https://en.wikipedia.org/wiki/Integrated_development_environment) of IDE (Integrated development environment) says that it is a toolchain, which includes code editor, build tool, debugger, etc. So, we can say that somehow code editor is a substance of IDE. Nowadays, sometimes, they overlap with each other in different aspects, so, it becomes hard to distinguish them, but I suggest be guided by the definitions of those tools given by their creators. I mean to say, the official webpage of [Monaco](https://microsoft.github.io/monaco-editor/) says that it is a code editor. According to that, I assume the best idea is to call monaco `code editor`.

P.S. In my opinion, it's a really hard task to choose the right tag-set to be able to cover all possible applications out there.

But I believe that it's doable 🙂

**Comment by michaelrambeau** [comment]
Thank you for the clarification @suren-atoyan 
So let's create a tag called `Code Editor` and preserve the `IDE` tag.
Besides the 2 Monaco projects, which projects from `Syntax Highlighting` should have the tag `Code Editor`?

I thought about removing the tag `Syntax Highlighting` but it may be useful for some very specific projects like "Pretty Diff" or "Highlight.js".

**Comment by suren-atoyan** [comment]
I agree with you, it would be better to have all of them (`code editor`, `IDE`, `Syntax Highlighting`).

From the current list of `Syntax Highlighting` tag, I definitely see 4 projects that more correspond to `code editor` tag: they are `monaco`, `monaco-react`, `codeMirror`, `Ace`. It's written in the first lines of their official pages.

**Comment by michaelrambeau** [comment]
Alright @suren-atoyan it's done, please check here: https://bestofjs.org/projects?tags=code-editor

![image](https://user-images.githubusercontent.com/5546996/87224863-c33fd180-c3c3-11ea-9837-eb915ec558e1.png)

Thank you again for your feedback!

**Comment by suren-atoyan** [comment]
That looks great!

You are welcome 🙂
