### ISSUE TITLE
GuideChimp - Interactive guided product tours

### ISSUE THREAD

**Issue by r-brown** [michaelrambeau/bestofjs#335]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

Repo: https://github.com/Labs64/GuideChimp

How would this project be tagged? (_Pick one or several existing tags_)

- guided tour
- product tour
- beacons
- user onboarding
- product adoption

**Comment by michaelrambeau** [comment]
Hello @r-brown , thank you for the suggestion.
We have a tag called "Presentation" that is too much generic I think: https://bestofjs.org/projects?tags=presentation
What about creating a new tag called "Tour" that would include the following projects:

- IntroJS
- Driver.js
- Sheperd
- Chardin
- and GuideChimp of course!

Can you see any other popular projects that we should track?
Thank you for your help!

**Comment by r-brown** [comment]
Hello @michaelrambeau - this sounds good - let's use _Tour_ as a tag here.

UPD  / Suggestion: or might be even _Tours & Guides_ as a tag name?

**Comment by michaelrambeau** [comment]
Hello @r-brown 
It's online, please check here: https://bestofjs.org/projects?tags=tour

The tag was called `Tour / Guide` to be consistent with other tag names that use the singular form usually but I'm not sure what is the best, maybe I should use the plural form for all tags instead.

![image](https://user-images.githubusercontent.com/5546996/89090936-026cab80-d3e1-11ea-9ecc-47eb40ae90e3.png)

**Comment by r-brown** [comment]
Hello @michaelrambeau that's awesome - thanks!
In regards to singular vs. plural - indeed I saw more plural titles, especially on the catalogue websites.

**Comment by r-brown** [comment]
Hello @michaelrambeau,
Would it be difficult to replace Labs64 logo on the GuideChimp entry using one of the GuideChimp logos?
Images can be found here: https://github.com/Labs64/GuideChimp/tree/master/docs/img

e.g.
this one https://github.com/Labs64/GuideChimp/blob/master/docs/img/guidechimp-logo-notext.png

**Comment by michaelrambeau** [comment]
Hello @r-brown 
It's possible but we need a **SVG** file (not an exported image like the ones you shared) that contain only the logo (without the wording), similar to this one: https://github.com/Labs64/GuideChimp/blob/master/docs/img/guidechimp-icon-64x64.png

Could you send me the SVG file?

**Comment by r-brown** [comment]
Hi @michaelrambeau PFB the SVG version of the GuideChimp logo
https://github.com/Labs64/GuideChimp/blob/master/docs/img/guidechimp-logo-notext.svg

**Comment by michaelrambeau** [comment]
Hello @r-brown 
Done, please check again.
The file you provided was big (50 kB!) so I compressed it as much as possible but I couldn't get something smaller than 8 kB: https://github.com/bestofjs/bestofjs-webui/blob/master/public/logos/guidechimp.svg
Considering the simple shape and colors of the logo, it shouldn't be bigger than 2 kB I think, let me know if you have a better file.
