### ISSUE TITLE
alosaur - Deno web framework with many decorators

### ISSUE THREAD

**Issue by borisliu** [michaelrambeau/bestofjs#336]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

Repo: https://github.com/alosaur/alosaur

How would this project be tagged? (_Pick one or several existing tags_)
Deno
Web Framework

**Comment by michaelrambeau** [comment]
Hello Boris @borisliu 
Thank you for the suggestion.
About Deno, so far the only project _Best of JS_ tracks is Deno itself but I think it would be nice to track the most important projects of the Deno eco-system from now.

**Comment by michaelrambeau** [comment]
Hello Boris @borisliu 
A new tag called `Deno` has been created, please check here: https://bestofjs.org/projects?tags=deno

Thank you for your feedback!

**Comment by borisliu** [comment]
Thanks a lot!
