### ISSUE TITLE
Fomantic-UI 

### ISSUE THREAD

**Issue by d-akara** [michaelrambeau/bestofjs#337]
https://github.com/fomantic/Fomantic-UI

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
CSS Toolkit

**Comment by michaelrambeau** [comment]
Hello again Chad @dakaraphi 
_Fomantic-UI_ will be available on _Best of JS_ very soon, thank you!

I wonder if you know about the status of Semantic-UI?
It seems that the latest release was almost 2 years to go.
Can Fomantic-UI be considered as its successor?

**Comment by d-akara** [comment]
Seems the maintainer of Semantic-UI has been unavailable for 2 years now.
Fomantic-UI forked to continue development of semantic.  They state that if the maintainer ever returns their intention is to merge back into semantic.

**Comment by michaelrambeau** [comment]
Hello Chad @dakaraphi 
Thank you for the explanation!
It's online, check here: https://bestofjs.org/projects?tags=css-lib
