### ISSUE TITLE
Rename Huncwot

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#338]
Hello  Michael,

[Huncwot](https://bestofjs.org/projects/huncwot) is renamed to [Kretes](https://kretes.dev/).

**Comment by michaelrambeau** [comment]
Hello @gamtiq it's good to hear from you 😄 !

Good catch, it will be renamed.

About the tagging, now it's tagged "Node.js framework" but I don't think it's correct, it introduces itself as a "programming environment", have you a suggestion?

**Comment by gamtiq** [comment]
Michael,

I agree that "Node.js framework" isn't very appropriate tag for Kretes. But I think the tag may be saved because Kretes is sort of framework and based on Node.js.
Regarding another/alternative tags I suppose the following variants should be considered:
- [Full-stack framework](https://bestofjs.org/projects?tags=fullstack) (Kretes somewhat resembles Meteor);
- [IDE](https://bestofjs.org/projects?tags=ide) (because Kretes is "built on top of Visual Studio Code");
- web framework (as stated on Kretes' landing page: "It combines a web framework with an editor...");
- TypeScript (because "Kretes is a programming environment for TypeScript applications").

**Comment by michaelrambeau** [comment]
Sorry for the late reply @gamtiq I forgot to say the project was renamed.

I think we could add the tag "Full-stack framework" indeed, maybe _GraphQL_ and _Web Assembly_ too.
