### ISSUE TITLE
Add crypto-js

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#339]
https://github.com/brix/crypto-js

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
`Utils`

**Comment by michaelrambeau** [comment]
Hello @gamtiq Denis
Thank you for the suggestion!
We alaready have https://bestofjs.org/projects?tags=crypto-currency but it's very specific (maybe `blockchain` would be more appropriate), so what about creating a new tag called `crypto` for this project (and for the other project you suggested)?
Among the existing projects we track, can you see other projects that should be tagged `crypto`?

**Comment by gamtiq** [comment]
Hello Michael,
I agree that new `crypto` tag is appropriate for `crypto-js` and `forge`.
I've not found any project listed on _Best Of JavaScript_ that also can be tagged by `crypto` tag. Maybe [GUN](https://bestofjs.org/projects/gun) but I'm not sure.

**Comment by michaelrambeau** [comment]
Thank you for the feedback Denis, it's online, check here: https://bestofjs.org/projects?tags=crypto
