### ISSUE TITLE
Add forge

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#340]
https://github.com/digitalbazaar/forge

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
`Utils`

**Comment by michaelrambeau** [comment]
Thank you Denis, check my comment here: https://github.com/michaelrambeau/bestofjs/issues/339#issuecomment-689537320

**Comment by michaelrambeau** [comment]
@gamtiq It's online, check the new tag `Crypto`: https://bestofjs.org/projects?tags=crypto
