### ISSUE TITLE
Add jsPlumb

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#341]
https://github.com/jsplumb/jsplumb

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

`Diagram / Flow chart`

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq , thank you for the suggestion.

The [doc site](https://jsplumbtoolkit.com/) has pages with "free trial" and "purchase" buttons, can you confirm about the status of the project?
I can see they have both "community" and "toolkit" (commercial) edition, I suppose the "community edition" could be added to _Best of JS_?

**Comment by gamtiq** [comment]
Hello Michael,

Yes, they have the commercial edition. The mentioned GitHub repository is for the community edition. I agree that exactly the community edition should be added.
By the way, there is separated doc site for the community edition: https://docs.jsplumbtoolkit.com/community/current/index.html

**Comment by michaelrambeau** [comment]
Thank you Denis, then I will link the project to that link (instead of the default one).

**Comment by michaelrambeau** [comment]
@gamtiq it's online Denis: https://bestofjs.org/projects?tags=diagram

Thank you as always!
