### ISSUE TITLE
awesomplete

### ISSUE THREAD

**Issue by frederikhors** [michaelrambeau/bestofjs#342]
What about adding the amazing https://github.com/LeaVerou/awesomplete?

**Comment by michaelrambeau** [comment]
Hello @frederikhors thank you for the suggestion!

OK, if it's amazing, it deserves to be on _Best of JS_. `Awesomplete` will be available very soon!

**Comment by michaelrambeau** [comment]
Hello @frederikhors it's online, check here for example: https://bestofjs.org/projects?tags=autocomplete
