### ISSUE TITLE
mailgo

### ISSUE THREAD

**Issue by manzinello** [michaelrambeau/bestofjs#343]
https://mailgo.dev
https://github.com/manzinello/mailgo

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has a thorough documentation in English
- [X] The project is not deprecated and actively maintained

`Package - dependency`, `Accessibility`, `Modal`, `Email`

**Comment by michaelrambeau** [comment]
Hello @manzinello 
Thank you for the suggestion, `Mailgo` is now available on _Best of JS_, check here for example:
https://bestofjs.org/projects?tags=email
