### ISSUE TITLE
Add TypeScript utility types libraries

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#344]
Hello Michael,

I suppose it would be great to add the following libraries related to TypeScript:
* https://github.com/sindresorhus/type-fest
* https://github.com/andnp/SimplyTyped
* https://github.com/millsp/ts-toolbelt
* https://github.com/piotrwitek/utility-types

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

Types, Utils

**Comment by michaelrambeau** [comment]
Thank you Denis @gamtiq the 4 projects will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 

It's online, please check here: https://bestofjs.org/projects?tags=types
