### ISSUE TITLE
Vue Flow Form form generator

### ISSUE THREAD

**Issue by EkaterinaVu** [michaelrambeau/bestofjs#345]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

GitHub link: https://github.com/ditdot-dev/vue-flow-form

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
Form, Vue

**Comment by michaelrambeau** [comment]
Thank you @EkaterinaVu for the suggestion.

`Vue Flow Form` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @EkaterinaVu `Vue Flow Form` is available on _Best of JS_.

Please check here for example: https://bestofjs.org/projects?tags=form

Thank you for your feedback!
