### ISSUE TITLE
Recommend an open source project

### ISSUE THREAD

**Issue by dream-num** [michaelrambeau/bestofjs#346]
Luckysheet is an online spreadsheet like excel that is powerful, simple to configure, and completely open source.

https://github.com/mengshukeji/Luckysheet/

**Comment by dream-num** [comment]
tags: Spreadsheet, Table

**Comment by michaelrambeau** [comment]
Hello @mengshukeji 
Thank you for the recommendation, `Luckysheet` is available on _Best of JS_.
And it's today's project number 1, congratulations! 🎉 

![image](https://user-images.githubusercontent.com/5546996/96049316-cfe83000-0eb2-11eb-8a16-bed5b1bfa5a9.png)
