### ISSUE TITLE
add klap

### ISSUE THREAD

**Issue by osdevisnot** [michaelrambeau/bestofjs#347]
https://github.com/osdevisnot/klap

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
- Module - bundler
- Building tool

**Comment by michaelrambeau** [comment]
Hello @osdevisnot 
Thank you for the recommendation!
`Klap` is available on _Best of JS_, please check here: https://bestofjs.org/projects?tags=build

**Comment by michaelrambeau** [comment]
@osdevisnot I've just realized I made a typo in the name ("Kalp"), I'm sorry, I'm fixing...

**Comment by osdevisnot** [comment]
Thank you so much @michaelrambeau

**Comment by michaelrambeau** [comment]
The typo has been fixed, thank you for your patience!
