### ISSUE TITLE
add oak - A middleware framework for Deno's net server

### ISSUE THREAD

**Issue by borisliu** [michaelrambeau/bestofjs#348]
https://github.com/oakserver/oak

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
deno

**Comment by michaelrambeau** [comment]
Hello Boris @borisliu 
Thank you for the suggestion!

It's online, please check here:
https://bestofjs.org/projects?tags=deno
