### ISSUE TITLE
Lucia.js

### ISSUE THREAD

**Issue by aidenybai** [michaelrambeau/bestofjs#349]
https://github.com/aidenybai/lucia

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
- UI Framework
- DOM manipulation
- State management

**Comment by michaelrambeau** [comment]
Hello Aiden @aidenybai 
Thank you for the recommendation, `Lucia` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Aiden @aidenybai it's online, please check here:

https://bestofjs.org/projects?sort=newest

Thank you in advance for your feedback!
