### ISSUE TITLE
Add `marcosmoura/vue-material` project

### ISSUE THREAD

**Issue by dautushenka** [michaelrambeau/bestofjs#35]
https://github.com/marcosmoura/vue-material
Vue Material is lightweight framework built exactly according to the Material Design specs.

**Comment by michaelrambeau** [comment]
Thank you @dautushenka , I am adding it and it will be available under the "Material Design" and "Vue components" tags very soon.

**Comment by michaelrambeau** [comment]
@dautushenka 
Hello Denis, it's online, check here and http://bestof.js.org/tags/vue and here http://bestof.js.org/projects/tags/material

Let me know if you have any feedback about the application, thank you for your 3 contributions!
