### ISSUE TITLE
notistack

### ISSUE THREAD

**Issue by arturcarvalho** [michaelrambeau/bestofjs#350]
Hello there,

I found this project, notistack mentioned on the Material-UI docs. I'd say it's on the `Notification` category:
[notistack](https://github.com/iamhosseindhv/notistack)

**Comment by michaelrambeau** [comment]
Hello Artur @arturcarvalho 
Thank you for the recommendation, `Notistack` will be available on _Best of JS_ very soon.

**Comment by arturcarvalho** [comment]
Great, thanks Michael =)

**Comment by michaelrambeau** [comment]
Hello Artur @arturcarvalho it's online, please check here: https://bestofjs.org/projects?tags=notify

Thank you for your feedback!

**Comment by arturcarvalho** [comment]
Hello Michael. Looks great, thank you!
