### ISSUE TITLE
add react-tracked

### ISSUE THREAD

**Issue by codebex** [michaelrambeau/bestofjs#351]
I suggest the addition of react-tracked, under the tags "state management" and "react".

[github](https://github.com/dai-shi/react-tracked)
[website](https://react-tracked.js.org/)

**Comment by michaelrambeau** [comment]
Hello Alain @alaindm,
Thank you for the recommendation, we never have enough of state managements solutions for React 😆 .
`React Tracked` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Alain @alaindm 
Done, please check the `State management` tag for example: https://bestofjs.org/projects?tags=state
Thank you in advance for your feedback!
