### ISSUE TITLE
Add tsParticles

### ISSUE THREAD

**Issue by matteobruni** [michaelrambeau/bestofjs#352]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

Animation, Canvas, React, Vue, Angular

The project is here: https://github.com/matteobruni/tsparticles

**Comment by michaelrambeau** [comment]
Hello Matteo @matteobruni 
Thank you for the recommendation, `tsParticles` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Matteo @matteobruni 
Done, please check here: https://bestofjs.org/projects?tags=animation
Thank you in advance for your feedback!

**Comment by matteobruni** [comment]
Awesome! Thank you very much!
