### ISSUE TITLE
Add FFCreator

### ISSUE THREAD

**Issue by fantasticsoul** [michaelrambeau/bestofjs#353]
https://github.com/tnfe/FFCreator

**Comment by michaelrambeau** [comment]
Hello again @fantasticsoul 
Thank you for the recommendation, `FFCreator` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @fantasticsoul it's online, please check here: https://bestofjs.org/projects?tags=video

Thank you in advance for your feedback!
