### ISSUE TITLE
Add concent

### ISSUE THREAD

**Issue by fantasticsoul** [michaelrambeau/bestofjs#354]
[concent](https://github.com/concentjs/concent), a state management that tailored for react, it is simple、predictable、progressive and efficient.

**Comment by michaelrambeau** [comment]
Hello @fantasticsoul 
Thank you for the recommendation.
Is there any English version of the documentation? https://concentjs.github.io/concent-doc/ ?

**Comment by fantasticsoul** [comment]
> Hello @fantasticsoul
> Thank you for the recommendation.
> Is there any English version of the documentation? https://concentjs.github.io/concent-doc/ ?

Thank you so much, we will be writing English documents in the near future.
here is a very simple one: https://concentjs.github.io/concent-doc/en/

**Comment by michaelrambeau** [comment]
Thank you @fantasticsoul !
`Concent` project is now available on _Best of JS_, check here for example: 
https://bestofjs.org/projects?tags=state&tags=react
