### ISSUE TITLE
Add react-intersection-observer

### ISSUE THREAD

**Issue by thebuilder** [michaelrambeau/bestofjs#355]
Hey, I'd like to suggest adding https://github.com/thebuilder/react-intersection-observer to the list.
It's React implementation around the important IntersectionObserver API, and it's seeing a lot of traction these days. It's part of the [Vercel Commerce](https://github.com/vercel/commerce) bolierplate, and also used on the new [Tailwind CSS](https://github.com/tailwindlabs/tailwindcss.com) website. With 1.2 million downloads each month, it's an important part of a lot of projects.

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has a thorough documentation in English
- [X] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
`React`, `Scrolling`, `Performance Optimization`

**Comment by michaelrambeau** [comment]
Hello Daniel @thebuilder 
Thank you for the recommendation and for the background, `react-intersection-observer` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Daniel @thebuilder 
It's online, please check here: https://bestofjs.org/projects?tags=scrolling

About the tagging, I made the tag "Performance Optimization" a bit more specific, limiting the scope to the tooling to measure/improve web performances but the boundary is a bit blurry, it's not easy to tag things properly...

Let me know if it makes sense, or if you see new tags we should add to _Best of JS_, thank you!
