### ISSUE TITLE
Add ChatUI

### ISSUE THREAD

**Issue by akai** [michaelrambeau/bestofjs#356]
https://github.com/alibaba/ChatUI

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
`React`, `UI Framework`,  `Mobile`, `Component Toolkit`

**Comment by michaelrambeau** [comment]
Hello @akai thank you for the recommendation.
Is the documentation web site https://chatui.io/ available in English?
