### ISSUE TITLE
CanvasXpress

### ISSUE THREAD

**Issue by neuhausi** [michaelrambeau/bestofjs#357]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has a thorough documentation in English
- [X] The project is not deprecated and actively maintained

How would this project be tagged? (javascript, r, visualization, analytics, network, reproducible-research, bioinformatics, genomics, chart)

https://www.canvasxpress.org/

**Comment by michaelrambeau** [comment]
Hello @neuhausi 
Thank you for the recommendation.
Is it an open source project, I cannot find the link to GitHub?
The only GitHub repo I found is written in `R`, not in JavaScript, I don't understand where is the JavaScript code that run the data visualization in the browser... sorry if I missed something obvious! 😅
