### ISSUE TITLE
Add Tiny Slider

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#358]
https://github.com/ganlanyuan/tiny-slider

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

Slider, Carousel

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Thank you for the recommendation, `Tiny Slider` will be available on _Best of JS_ very soon.

About the tagging, sometimes I think we need "aliases": different ways to call the same thing.
For example `Slider` and `Carousel` mean the same thing but it's called `Slider` on _Best of JS_ (even if slider can also mean something like a "range" component in other contexts, it's not the best example)

From the search bar, it could be fine to be able to find https://bestofjs.org/projects?tags=slider from both "slider" and "carousel" keywords, what do you think?

**Comment by gamtiq** [comment]
Yes, I totally agree that tag aliases would be useful.
And `Slider` is a good candidate for such feature because as you mentioned slider can mean different kinds of components. And as a result some people may miss that carousels are related and grouped to `Slider` tag.

**Comment by michaelrambeau** [comment]
_Tiny Slider_ is available on _Best of JS_, thank you Denis @gamtiq !
