### ISSUE TITLE
Add wmr

### ISSUE THREAD

**Issue by cristianbote** [michaelrambeau/bestofjs#359]
https://github.com/preactjs/wmr

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
ssg, preact, react, universal, prefetch, prerender

**Comment by michaelrambeau** [comment]
Hello Cristian @cristianbote 
Thank you for the recommendation, `wmr` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Cristian @cristianbote 
`wmr` is available on _Best of JS_ and it's the hottest project of the day!

**Comment by cristianbote** [comment]
🙏  thank you @michaelrambeau! Much appreciate it!
