### ISSUE TITLE
Add `kazupon/vue-i18n` project

### ISSUE THREAD

**Issue by dautushenka** [michaelrambeau/bestofjs#36]
https://github.com/kazupon/vue-i18n
Internationalization plugin for Vue.js

**Comment by michaelrambeau** [comment]
Thank you @dautushenka for that 3rd suggestion, I'am adding the project under the following tags:

* `Vue components`
* `i18n`

**Comment by michaelrambeau** [comment]
It's online, check here => http://bestof.js.org/tags/vue or http://bestof.js.org/projects/tags/i18n

Thank you for your support!
