### ISSUE TITLE
Add Actionhero

### ISSUE THREAD

**Issue by evantahler** [michaelrambeau/bestofjs#360]
www.Actionherojs.com

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? 
* Node.JS framework
* Real Time
* Game Engine

**Comment by michaelrambeau** [comment]
Hello Evan @evantahler 
Thank you for the recommendation.
More than ever, the world in 2020 needs action heroes 😄 
_Actionherojs_ will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Evan @evantahler it's online please check _Best of JS_ homepage.
Thank you in advance for your feedback!

**Comment by evantahler** [comment]
Thank you!
