### ISSUE TITLE
Add Node Resque

### ISSUE THREAD

**Issue by evantahler** [michaelrambeau/bestofjs#361]
https://github.com/actionhero/node-resque

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?
* Queue

**Comment by michaelrambeau** [comment]
Thank you again Evan @evantahler `node-resque` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Evan @evantahler 
Done, could you please check here for example? https://bestofjs.org/projects?tags=queue
Thank you for your feedback!

**Comment by evantahler** [comment]
That looks great! I think the Actionhero Star is the best choice for a logo... one day we'll get a special [logo just for the project](https://github.com/actionhero/node-resque/issues/306)
