### ISSUE TITLE
Adding Web Test Runner

### ISSUE THREAD

**Issue by daKmoR** [michaelrambeau/bestofjs#362]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

- Name: Web Test Runner
- Npm: @web/test-runner
- Github: https://github.com/modernweb-dev/web/tree/master/packages/test-runner
- Description: Test runner for browser-based testing and debugging
- Homepage: https://modern-web.dev/docs/test-runner/overview/
- Tags: Testing

**Comment by michaelrambeau** [comment]
Hello Thomas @daKmoR 
Thank you for the recommendation, `Web Test Runner` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Thomas @daKmoR 
`Web Test Runner` is available on _Best of JS_.
Thank you in advance for your feedback!
