### ISSUE TITLE
Add Volta

### ISSUE THREAD

**Issue by charlespierce** [michaelrambeau/bestofjs#363]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has a thorough documentation in English
- [X] The project is not deprecated and actively maintained

How would this project be tagged? (CLI, Dev tool, Node version management)

https://volta.sh
https://github.com/volta-cli/volta

**Comment by michaelrambeau** [comment]
Hello Charles @charlespierce 
Done, please check _Best of JS_ home page.
Thank you in advance for your feedback!
