### ISSUE TITLE
Fix InfiniteGrid

### ISSUE THREAD

**Issue by daybrush** [michaelrambeau/bestofjs#364]
Hi. We are the egjs team managing infinitegrid.

If infinitegrid is currently registered, can you add tags?

https://github.com/naver/egjs-infinitegrid

https://bestofjs.org/projects/infinite-grid

---

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

* Layout
* React
* Angular
* Vue
* Svelte

**Comment by michaelrambeau** [comment]
Hello @daybrush 
OK, it's done, check here: https://bestofjs.org/projects/infinite-grid
Thank you for your feedback!
