### ISSUE TITLE
Request to add OpenUI5 as UI framework

### ISSUE THREAD

**Issue by petermuessig** [michaelrambeau/bestofjs#365]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
`UI Framework`

You can find more information about OpenUI5 here: https://openui5.org/ or directly on GH here: https://github.com/SAP/openui5

I also reached out to hello@stateofjs.com - maybe you received this request also directly from Sacha Greif via mail.

Thanks so much...

**Comment by michaelrambeau** [comment]
Hello Peter @petermuessig 
Thank you for the recommendation.
Yes, I got the message from Sacha too!
OK `OpenUI5` will be available on _Best of JS_ very soon.

**Comment by petermuessig** [comment]
Hi Michael @michaelrambeau ,
thanks so much for adding `OpenUI5` that quick to _Best of JS_. 👍

**Comment by petermuessig** [comment]
If you need anything from me: logo, some description, ... please let me know. I am happy to help...

**Comment by michaelrambeau** [comment]
Hello Peter @petermuessig 
`OpenUI5` is available on _Best of JS_.
About the logo, if you want we could replace the default one (the avatar of the GitHub org) by a customized SVG file that would include the logo only (without the wording), this is what we do for the "featured" projects, visible in the right sidebar of the top page.

**Comment by petermuessig** [comment]
Hi Michael @michaelrambeau , 
great, I can see it already. Yes, indeed - replacing the logo would be great. How can I provide the SVG to you? I attached it as ZIP right now as SVGs can't be attached. Thanks...

[B.svg.zip](https://github.com/michaelrambeau/bestofjs/files/5714763/B.svg.zip)

**Comment by michaelrambeau** [comment]
Thank you Peter @petermuessig I will set up the logo.

The best way to share it? SVG being just code, like this is perfect 😄 

```html
<svg viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
  <clipPath id="a">
    <path d="M244.4 0s0 20.8 54.4 53.9C404.4 118 404 176.9 404 189.2c0 52.4-54.5 86.3-79.9 58.9 0 0 24.9-18.4 24.9-46.8 0 0-18.2 12-27.8 14 0 0 12.5-21.9 6.7-60.4 0 0-10 19.5-41.8 35.2 0 0 12.4-27.7.8-54.2 0 0 2.5 33.1-73 68.3s-52.1 70.4-52.1 70.4 15-16 40.5-4.7c34.5 15.1 20.6 76-34.9 76-54 0-89.5-58.8-89.5-104.7 0-19 2-53.9 36.3-92.2 27.3-30.6 61-46.7 68.1-80.5C145 103.2 77.6 125.8 37.6 185c-36 53.2-24.3 123.6-17.9 145.3A238.2 238.2 0 00248 500c131.5 0 239.5-105.2 239.5-236.7C487.4 64.2 298 43 244.4 0zm-31.8 243.7c-4 1-7.9-.7-14.3-2.7-6-1.8-8-1.5-8-1.5a101.6 101.6 0 0112.6-7.2c6.4-3 11.8-3.1 14.3 2.7 1.7 3.9-1.3 8-4.6 8.7z"/>
  </clipPath>
  <linearGradient id="b" gradientUnits="userSpaceOnUse" x1="368" x2="134.4" y1="468.1" y2="63.5">
    <stop offset="0" stop-color="#146cd0"/>
    <stop offset="1" stop-color="#0fa1ea"/>
  </linearGradient>
  <g clip-path="url(#a)">
    <path d="M244.4 0s0 20.8 54.4 53.9C404.4 118 404 176.9 404 189.2c0 52.4-54.5 86.3-79.9 58.9 0 0 24.9-18.4 24.9-46.8 0 0-18.2 12-27.8 14 0 0 12.5-21.9 6.7-60.4 0 0-10 19.5-41.8 35.2 0 0 12.4-27.7.8-54.2 0 0 2.5 33.1-73 68.3s-52.1 70.4-52.1 70.4 15-16 40.5-4.7c34.5 15.1 20.6 76-34.9 76-54 0-89.5-58.8-89.5-104.7 0-19 2-53.9 36.3-92.2 27.3-30.6 61-46.7 68.1-80.5C145 103.2 77.6 125.8 37.6 185c-36 53.2-24.3 123.6-17.9 145.3A238.2 238.2 0 00248 500c131.5 0 239.5-105.2 239.5-236.7C487.4 64.2 298 43 244.4 0z" fill="url(#b)"/>
    <g fill="#07c1f2">
      <path d="M230.8 248.7C272.8 227 286 190 286 190s12.5-27.8.9-54.3c0 0 2.4 33.1-73 68.4s-52.3 70.4-52.3 70.4a33 33 0 0115.2-7.9c12.5-3.3 32-6.7 53.9-18z" opacity=".6"/>
      <path d="M233 264c32.3 0 69.8-15 88.4-48.7a73.7 73.7 0 006.8-21.8c2-12.8 2.2-22.3-.2-39.6 0 0-6.1 17.2-41.9 36.1-13 6.9-29.6 13.7-51.6 20.4-85.2 25.9-72.7 64.2-72.7 64.2 13.4-8.9 13.5-10.6 71.1-10.6z" opacity=".4"/>
      <path d="M233 264c29.7 0 70.2 1.7 91.3-16 12.9-10.8 24.6-25.1 24.9-46.9 0 0-17.7 11.7-27.8 14.2a225 225 0 01-62.4 7.4c-78.4-4.4-97.2 51.8-97.2 51.8 10.8-9.9 24-10.5 71.1-10.5z" opacity=".2"/>
      <path d="M230.8 248.7C272.8 227 286 190 286 190c-13 6.8-29.6 13.7-51.6 20.4-85.2 25.8-72.7 64.1-72.7 64.1a33 33 0 0115.2-7.9c12.4-3.3 31.9-6.7 53.8-18z" opacity=".4"/>
      <path d="M177 266.7c12.4-3.3 32-6.7 53.8-18a122.3 122.3 0 0033.8-25.7c-1.9 0-3.8 0-5.6-.2-78.4-4.4-97.2 51.8-97.2 51.8a30.4 30.4 0 0112-7l3.2-.9z"/>
      <path d="M487.4 263.3a235 235 0 00-20-99.5c1.2 3.6 25.3 79-35.1 139.3-34.5 34.5-93 46.4-140.2 8.7 0 0 6 94.6-106 108.6-73.3 9-130.8-37.5-155.8-97-17.4-41.2-19-88.7.9-128C3 247.2 13.7 310 19.7 330.3A238.2 238.2 0 00248 500c131.5 0 239.5-105.2 239.5-236.7z" opacity=".4"/>
      <path d="M463.2 367.1c-12.4 3.4-109.8 26.5-171.1-55.3 0 0 28.5 110.9-93 183.2a238.5 238.5 0 0048.8 5 240 240 0 00215.3-132.9z" opacity=".6"/>
      <path d="M410.3 437.2C334.3 398 292 311.9 292 311.9c34 82.7 19.3 147.2 4 183.3a240.2 240.2 0 00114.3-58z" opacity=".7"/>
    </g>
  </g>
</svg>

```

**Comment by petermuessig** [comment]
🤦 - you are so right, @michaelrambeau ... 😄 

Thanks! BTW: do you know how _StateOfJS_ refers to the _BestOfJS_ data? Right now, I still don't see OpenUI5 being listed in the Front-end frameworks?

**Comment by michaelrambeau** [comment]
No problem at all, I have a secret passion in my life, gather as many logos as possible, they are like my Pokemons 😅 

Right now, the link between _State of JS_ and _Best of JS_ data is not dynamic and I think Sacha does not want to update the list to avoid changing the rules of the game while the survey is still open but I'm going to ask him again.

**Comment by petermuessig** [comment]
Ok, thanks for the info and thanks for asking Sacha. At least, for next year we can use it... 😃 

Really appreciate your time to add OpenUI5 and UI5 Web Components to _Best of JS_! 

Regarding your passion, just fyi: 
  * some logo guidelines + downloads incl. 3d icon models to print: https://openui5.org/guidelines/
  * here a video of our logo evolution: https://www.youtube.com/watch?v=c0NehCRNZoY 
  * some classic UI5 logos for you: [ClassicUI5Logos.zip](https://github.com/michaelrambeau/bestofjs/files/5715552/ClassicUI5Logos.zip)

**Comment by michaelrambeau** [comment]
Thank you Peter for taking project logos seriously, I checked all of them, they look good! 

Somehow they remind me the Firefox logo even if a fox and a phoenix can't be mistaken 😆

**Comment by petermuessig** [comment]
It is indeed a Phoenix. We started the OpenUI5 project end of 2008 with the Codename "Phoenix"... 😃 

A colleague of mine has recently written a blog post about our history: https://blogs.sap.com/2020/11/04/a-brief-history-of-openui5-and-sapui5/

But for the logos of the projects on Best of JS, please use the SVGs I sent you initially.

**Comment by michaelrambeau** [comment]
Hello Peter, @petermuessig  it's online, please check _Best of JS_ top page!

![image](https://user-images.githubusercontent.com/5546996/102675031-49fea300-41db-11eb-9631-c6dc3e2c9bf6.png)

**Comment by petermuessig** [comment]
Perfect, looks great! Thanks Michael @michaelrambeau 👍
