### ISSUE TITLE
Suggestion: add Docusaurus in SSG category

### ISSUE THREAD

**Issue by lex111** [michaelrambeau/bestofjs#367]
Docusaurus is actually a static site generator.

- https://v2.docusaurus.io/
- https://bestofjs.org/projects/docusaurus

**Comment by michaelrambeau** [comment]
Hello Alexey @lex111 
It's fixed, check here please: https://bestofjs.org/projects?tags=ssg

Let us know if we miss other good "SSG", thank you!

**Comment by lex111** [comment]
@michaelrambeau thanks!
