### ISSUE TITLE
Add Element Plus

### ISSUE THREAD

**Issue by zazzaz** [michaelrambeau/bestofjs#368]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
Vue Component Toolkit

https://github.com/element-plus/element-plus
https://element-plus.org/#/en-US
Element Plus is a Vue.js 3.0 UI Library made by Element team. 

Check the relationship with Element UI
https://github.com/ElemeFE/element/blob/dev/README.md
https://bestofjs.org/projects/element

>Element will stay with Vue 2.x
> For Vue 3.0, we recommend using Element Plus from the same team

**Comment by michaelrambeau** [comment]
Hello @zazzaz 
Thank you for the suggestion, `Element Plus` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @zazzaz 
It's online, please check here for example: https://bestofjs.org/projects?tags=component&tags=vue
Thank you for your feedback!

**Comment by zazzaz** [comment]
cool THX
