### ISSUE TITLE
MandarineTS. A minimalist, decorator-driven, MVC, typescript framework for Deno

### ISSUE THREAD

**Issue by borisliu** [michaelrambeau/bestofjs#369]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
Deno

**Comment by borisliu** [comment]
Repo: https://github.com/mandarineorg/mandarinets

**Comment by michaelrambeau** [comment]
Hello @borisliu 
Thank you for the recommendation, `MandarineTS` is available on _Best of JS_.
It's currently displayed as `Mandarinets` but it will be fixed soon.
