### ISSUE TITLE
Add `pagekit/vue-resource` project

### ISSUE THREAD

**Issue by dautushenka** [michaelrambeau/bestofjs#37]
https://github.com/pagekit/vue-resource
The plugin for Vue.js provides services for making web requests and handle responses

**Comment by michaelrambeau** [comment]
Thank you @dautushenka for that suggestion too, I'am adding the project under the following tags:

* `Vue components`
* `Ajax - http`

**Comment by michaelrambeau** [comment]
It's online, check here => http://bestof.js.org/tags/vue

Thank you for your support!
