### ISSUE TITLE
Swiper - add Angular tag

### ISSUE THREAD

**Issue by vltansky** [michaelrambeau/bestofjs#370]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has a thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

Its existing repo on bestofjs - just need to add an Angular label, as now swiper has official angular support.
Also I'd suggest adding nolimits4web (Vladimir Kharlampidi) to the hall of fame he is the author of swiper (25k stars) and framework7 (15k stars) with 2.4k followers.

**Comment by michaelrambeau** [comment]
Hello Vlad @vltansky 
Thank you, I added the missing tags, could you check here: https://bestofjs.org/projects/swiper

OK for `nolimits4web`, Vladimir will be inducted to the official _Hall of Fame_ very soon!

**Comment by vltansky** [comment]
@michaelrambeau its there :) Thanks.

**Comment by michaelrambeau** [comment]
@vltansky Vladimir Kharlampidi has been inducted to the _Hall of Fame_!

I also added Andrey Sitnik https://github.com/ai FYI.

![image](https://user-images.githubusercontent.com/5546996/105916118-dec6ad00-6073-11eb-9b4c-64652d38a4af.png)

**Comment by vltansky** [comment]
awesome thanks!
