### ISSUE TITLE
Please add Nullstack

### ISSUE THREAD

**Issue by Mortaro** [michaelrambeau/bestofjs#372]
https://nullstack.app/

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

- Full-stack framework
- Isomorphic
- Static site generator
- Prerender
- Reactive programming

**Comment by michaelrambeau** [comment]
Hello Christian @Mortaro 
Thank you for the recommendation, `Nullstack` project is available on _Best of JS_, please check!

**Comment by Mortaro** [comment]
Thanks a lot 💖
