### ISSUE TITLE
Please add FlaReact

### ISSUE THREAD

**Issue by tx0c** [michaelrambeau/bestofjs#373]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

1. https://flareact.com/ Flareact is an edge-rendered React framework built for Cloudflare Workers.
2. https://github.com/flareact/flareact

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

1. `flareact` `react` `webworker` `ssr` `edge-rendered React framework` `serverless`
2. `Server-Side Rendering` `Edge-Side Rendering`

**Comment by michaelrambeau** [comment]
Hello @tx0c thank you for the recommendation, `Flareact` is available on _Best of JS_, please check!

**Comment by tx0c** [comment]
https://bestofjs.org/projects/flareact

**Comment by tx0c** [comment]
https://bestofjs.org/projects/flareact
