### ISSUE TITLE
Vue dynamic form component

### ISSUE THREAD

**Issue by xaboy** [michaelrambeau/bestofjs#374]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

GitHub link: [https://github.com/xaboy/form-create](https://github.com/xaboy/form-create)

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
Form, Vue

**Comment by michaelrambeau** [comment]
Hello @xaboy 

Thank you for the suggestion, `form-create` is now available on _Best of JS_, please check!
