### ISSUE TITLE
Eta JS Template Engine

### ISSUE THREAD

**Issue by shadowtime2000** [michaelrambeau/bestofjs#375]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

1. [eta.js.org](https://eta.js.org)
2. [eta-dev/eta](https://github.com/eta-dev/eta)

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
template engine

**Comment by michaelrambeau** [comment]
Hello @shadowtime2000 thank you for the recommendation, `Eta` is available on _Best of JS_, please check!

https://bestofjs.org/projects?tags=template

**Comment by shadowtime2000** [comment]
@michaelrambeau Great! I guess I will close this
