### ISSUE TITLE
Add NPM for tailwindcss

### ISSUE THREAD

**Issue by Goom11** [michaelrambeau/bestofjs#376]
https://bestofjs.org/projects/tailwind-css

https://www.npmjs.com/package/tailwindcss

**Comment by Goom11** [comment]
Not sure if there's a way for me to do this myself, hence the issue

**Comment by michaelrambeau** [comment]
Hello Aman @Goom11 
Thank you, NPM package data has been added, could you check? 

https://bestofjs.org/projects/tailwind-css

![image](https://user-images.githubusercontent.com/5546996/111234670-68d1d180-8632-11eb-8659-9a0433331808.png)

**Comment by Goom11** [comment]
Works!
