### ISSUE TITLE
Please add labelmake

### ISSUE THREAD

**Issue by hand-dot** [michaelrambeau/bestofjs#377]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

https://github.com/hand-dot/labelmake

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
PDF

**Comment by michaelrambeau** [comment]
Hello @hand-dot thank you for the suggestion, `labelmake` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello @hand-dot 
`labelmake` is now available in _Best of JS_, please check the `PDF` tag for example:

https://bestofjs.org/projects?tags=pdf

Thank you for your feedback!

**Comment by hand-dot** [comment]
Thank you!
