### ISSUE TITLE
react-i18next

### ISSUE THREAD

**Issue by adrai** [michaelrambeau/bestofjs#378]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? i18n and react

**Comment by michaelrambeau** [comment]
Hello Adriano @adrai 
Thank you for the suggestion, you didn't include the link but I guess it's this project: https://www.i18next.com/
It's already tracked by _Best of JS_: https://bestofjs.org/projects/i18next but maybe we should add the tag `React` if there is a React implementation available?
Thank you in advance for your explanations!

**Comment by adrai** [comment]
https://react.i18next.com
https://github.com/i18next/react-i18next

react-i18next is a specific framework for react based on i18next

**Comment by michaelrambeau** [comment]
Thank you Adriano, OK, understood, `react-i18next` will be available on _Best of JS_ very soon.

**Comment by adrai** [comment]
awesome, thx

**Comment by michaelrambeau** [comment]
Hello Adriano @adrai 
It's online, please check here for example: https://bestofjs.org/projects?tags=i18n

Thank you in advance for your feedback!

**Comment by adrai** [comment]
looks good 👍
