### ISSUE TITLE
Add PatternFly

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#379]
https://www.patternfly.org
https://github.com/patternfly/patternfly-react

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

Component Toolkit, React

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
It's good to see you back here 😄 !
Thank you for the suggestion, it will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
`PatternFly` is available on _Best of JS_, thank you Denis @gamtiq !
