### ISSUE TITLE
Add `monterail/vue-multiselect` project

### ISSUE THREAD

**Issue by shentao** [michaelrambeau/bestofjs#38]
https://github.com/monterail/vue-multiselect
Universal select/multiselect/tagging component for Vue.js

**Comment by michaelrambeau** [comment]
Thank you very much for the suggestion, it will be soon online.

**Comment by shentao** [comment]
Thanks! :)

**Comment by michaelrambeau** [comment]
It's online, thank you for your contribution!

http://bestof.js.org/tags/vue
