### ISSUE TITLE
Add Collections

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#380]
https://github.com/montagejs/collections

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

Data structure

**Comment by michaelrambeau** [comment]
`Collections` is available on _Best of JS_, thank you Denis @gamtiq 
Check the "Data structure" tag:
https://bestofjs.org/projects?tags=data-structure
