### ISSUE TITLE
Why Did You Render

### ISSUE THREAD

**Issue by vzaidman** [michaelrambeau/bestofjs#381]
The library monkey patches React to notify you about avoidable React re-renders.

GitHub link: https://github.com/welldone-software/why-did-you-render

Before submitting the request to add a new project, please check the following points:

- [ v ] The project is related to the web platform or Node.js
- [ v ] The project has more than 100 stars on GitHub
- [ v ] The project has thorough documentation in English
- [ v ] The project is not deprecated and actively maintained

How would this project be tagged? React, Performance

**Comment by michaelrambeau** [comment]
Hello Vitali @vzaidman 
Thank you for the recommendation, it will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Vitali @vzaidman 
It's online, please check here: https://bestofjs.org/projects?tags=performance

Thank you in advance!
