### ISSUE TITLE
Add Fontsource

### ISSUE THREAD

**Issue by ayuhito** [michaelrambeau/bestofjs#382]
https://github.com/fontsource/fontsource

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? 
Font

Appreciate the time taken to review this. :)

**Comment by michaelrambeau** [comment]
Hello @DecliningLotus 
Thank you for the suggestion, `Fontsource` will be available on _Best of JS_ very soon.

Remark: the website https://fontsource.org/ is not linked to the repo, I found it by browsing the org page on GitHub, could you update the repo?

**Comment by ayuhito** [comment]
Done. I hadn't added it since I've been rebuilding the entire website and wanted to wait for that.

**Comment by michaelrambeau** [comment]
Hello @DecliningLotus 
`Fontsource` is available on _Best of JS_ and I can tell you it's doing well!

Thank you for your patience!

![image](https://user-images.githubusercontent.com/5546996/114141781-04faaa00-994d-11eb-8bce-bc4dc389dade.png)
