### ISSUE TITLE
PenEditor

### ISSUE THREAD

**Issue by jojowwbb** [michaelrambeau/bestofjs#383]
Simple Online Code Editor! Support Rect, HTML, CSS, Javascript | PenEditor

PenEditor is a simple HTML / CSS / JS code editor, works online in real-time, and out of the box! PenEditor.js is an open-source online HTML / CSS / JavaScript code editor (Code Playground) inspired by Codepen.io.

Feature

-   [x] HTML/CSS/JS code editing
-   [x] Code formatting
-   [x] HTML editor supports emmet
-   [x] Code hint
-   [x] Sublime shortcut keys
-   [x] Simple console(log,error,info,warn)
-   [x] Built-in babel
-   [x] Built-in react, no need to quote separately
-   [x] Download HTML save
-   [x] works online in real-time

**Comment by michaelrambeau** [comment]
Hello @jojowwbb 
Thank you for the suggestion, I suppose it's this project: https://github.com/jojowwbb/PenEditor
It does not match the "requirement" of 100 stars but I guess you will reach the bar soon and `PenEditor` would be added to _Best of JS_.

**Comment by jojowwbb** [comment]
all right！and so on

**Comment by michaelrambeau** [comment]
Hello @jojowwbb 
`Pen Editor` is now available on _Best of JS_!
Please check here: https://bestofjs.org/projects?tags=code-editor

Thank you for your patience!
