### ISSUE TITLE
Add Mnemonist

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#384]
https://github.com/yomguithereal/mnemonist

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

Data structure

**Comment by michaelrambeau** [comment]
Thank you Denis, it's coming soon!

**Comment by michaelrambeau** [comment]
Done, please check https://bestofjs.org/projects?tags=data-structure

Thank you Denis @gamtiq , as always!
