### ISSUE TITLE
Add Graphology

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#385]
https://github.com/graphology/graphology

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

Data structure

**Comment by michaelrambeau** [comment]
https://yomguithereal.github.io/mnemonist/

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq it's online, please check here: https://bestofjs.org/projects?tags=data-structure
