### ISSUE TITLE
Consider Sandhands for Data Validation

### ISSUE THREAD

**Issue by L1lith** [michaelrambeau/bestofjs#387]
[https://github.com/L1lith/Sandhands](https://github.com/L1lith/Sandhands)
I'm aware the project doesn't have 100 stars, but I have been developing over 200 test cases and improving the code architecture for several years now, and I believe the project has reached a mature state.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
testing (type validation can be useful during testing to do things like validate exports or function returns etc), real-time, functional-programming, express (this library has express support out of the box), utils, possibly authentication (for validating JSON form data in auth flows), types (capable of performing advanced run-time type checking which isn't possible with precompiled type checking like typescript), data structure

**Comment by michaelrambeau** [comment]
Hello @L1lith thank you for the recommendation.
It's a hard dilemma, this rule of the 100 stars is there just to avoid irrelevant requests but I totally understand that it makes non sense because the quality of the projects is not related to their popularity.

I have to find a way to keep the list curated while being fair with everybody... if you had any idea to solve this issue, let me know, the best would be an automatic system that would scan thousands of projects and promote the best ones based on some criteria maybe, instead of the current list of about 1500 projects...

**Comment by L1lith** [comment]
Thanks for the consideration, and I understand. I think this is a problem not just with your list but with the NPM ecosystem in general. 

I think lots of blog posts & other articles document malicious NPM packages may be more common than we realize. It's very possible for open-source developers who create completely clean code to introduce malicious code to their users due to the sometimes enormous dependency trees.

In my opinion it would be worth creating a curated list of libraries that have been studied with extensive scrutiny. Something like this could possibly be integrated with some cli tool to basically make it only possible to install packages within the list of libraries. We could achieve this level of scrutiny through a number of measures, but I think there are some basic measures that would make it inherently more difficult for malware to be published.

1. Integrated Build Environments
There's an uncomfortable dilemma when I publish my library to my users. It's basically that I'm using an uglifier to minimize file sizes before deploying the code to my users, but that makes it much more difficult for a human or a machine to really understand what the code is doing. I do not put malware in my code or my deployments, but it would be very easy to publish a different version of the application to my github than the one I deploy to NPM (which is obscured and practically unreadable). To counter this, we could seek to create integration between the package managing service and the developers, to where they could setup their rollup or their webpack environments and supply their source code, then the package manager could automatically build the library before it's published to the users. This would allow both humans and automated approaches to better read the source code and inspect it for malware. Additionally, the packages could be published on NPM under some kind of private [organization](https://docs.npmjs.com/organizations).

Rollup, webpack, and their plugins would all need to be whitelisted packages as well. Allowing un-whitelisted plugins could allow malware to be injected after the source code is scanned.

2. AI Based Code Scanning
I think creating an AI to scan packages' source code automatically would be necessary as it won't be realistic to read through every update of every library. Having human readable code with realistic variable names means that it will be more difficult to fool an AI about the purpose of the code (just as it would make it more difficult for a human, as variable names carry context and intention). Uglified code could be automatically detected and cause the build process to fail.

3. Package Sandboxing
One of the biggest problems with packages is that they're simply too powerful by default. They have access to shell, the FS, the network, and more. This can lead to rootkits, privilege escalation, and various other issues. Most packages have no need for these kinds of capabilities, and realistically should need permission from the developer, sort of like app permissions on android devices. I haven't looked into it extensively but I believe [Deno](https://www.infoworld.com/article/3518888/nodejs-rival-deno-emphasizes-security.html) may be addressing this issue. 

I realized this might be out of the scope of this project or your intentions but if you are interested I think these measures could revolutionize some of the biggest problems of the NPM Ecosystem. 

4. Fluff Reduction 
Another great benefit about whitelisting is that we can keep a lot of the abandoned, unfinished, and otherwise non-production ready libraries out of the ecosystem. This will greatly reduce the number of overall packages, which to me is a good thing. 

When there's a hoard of packages and I just want to know what's the simplest way to clone an object, it is overwhelming the number of packages there are. Looking at this page [https://www.npmjs.com/search?q=clone](https://www.npmjs.com/search?q=clone) for example you can see there's a broad ranges of choices. The first package worked very well for me, but there's also [this package](https://www.npmjs.com/package/lodash.clonedeep) which seems rather pointless and hasn't been updated in 5 years. While I do think there is a case to be made that there should be multiple solutions to the same problem, I think that trimming off the fluff from the environment could help developers avoid implementing a library only to find out does a very poor job and having to go back and install another package. Although things like micro versions of libraries I think are very cool.

This also has the added benefit of increasing the odds of libraries having shared dependencies, thus reducing dependency sizes


Conclusion
Considering the size of your massive list (which I think is great that someone's making the effort to sift through that many projects), I think it could be great to migrate to possibly some kind of CLI integrated solution, and take a garden wall approach to the package ecosystem. Additionally, I think this is a great deal of work and would probably require a group effort of developers, and studying existing solutions like Deno and other things could be very useful too.

**Comment by michaelrambeau** [comment]
@L1lith  Thank you very much for sharing your ideas, that's really interesting.
The "fluff reduction" you mentioned is the reason why I started the project in 2015, I wanted to provide a clear overview of the landscape by providing a list of projects carefully picked and classified under "tags" that make sense.
The project has reached a kind of limit, it's time to make evolve the concept and you are 100% right, migrating toward an automated solution would be great.
I like that idea of AI based code scanning.
Ideally the system should be able to scan projects from GitHub (possibly by checking some specific "social" media sources) by itself, picking the "candidates" that could be accepted/rejected as I suppose a human action would needed at the end to double-check and ensure a consistent tagging.

Meanwhile I wonder if we could ask a "committee of experts" to validate projects that are don't match the usual criteria of popularity.
You could be the first member... and of course that means that you could "accept" the project "Sandhands".
I'm not overwhelmed by requests to add projects on _Best of JS_ so it should not be a very demanding job!

**Comment by L1lith** [comment]
@michaelrambeau sorry for the late response, I have been thinking about this project. I have devised another way we could greatly reduce the amount of pollution in the ecosystem without being excessively strict about the completeness stage. All libraries could first automatically published in the "Alpha" stage. As libraries become more mature they could apply for the "beta" and maybe a "mature" state. Each phase could be progressively more heavily scrutinized. This would be useful when browsing for packages, as you could filter and/or sort the packages by their maturity stage. This would also prevent developers from being discouraged from sharing packages before they're production ready (there's no harm in a immature package that's appropriately labeled, and supporting these libraries could stoke innovation). Additionally, The package ecosystem could have an integrated comment and rating features. 

Adding community ratings and feedback could allow for a lot more conversation between developers and users, and can allow users to estimate the quality of a package by it's star rating. This is very similar to how most app stores have opportunities for feedback, and it has the added benefit of allowing the package search results to be listed more organically. There's plenty of non-functional packages with a name short enough they get installed anyways only to waste developer's time.

I would be happy to be part of the community of experts :) I am continuing to think about this problem and how we can best devise a robust and comprehensive solution. It might be a good idea to create a new repo and we could discuss this further there and potentially invite some additional experts once we've got a decent looking project proposal.

EDIT: A sweet feature would be to automatically add "ghost tags" to libraries based on what people search for the most when using it. For example a library might be missing a critical keyword "sanitation", and so internally we could incorporate these keywords in the search results automatically based on it's recent search keyword history. As a developer it's a pain needing to make big keywords list and still not being sure if you've gotten everything.

EDIT2: We could also add an audit command similar to `npm audit` that would allow you to see things like complains about installed packages or packages installed with low trustability (based on maturity, reports, stars, etc)

**Comment by michaelrambeau** [comment]
Hello @L1lith 
This time, it's my turn to apologize for being late.
Thank you again for the insights.
So I've changed the "rules of the game" to consider that we can have exceptions to the number of stars requirement if the project is considered as "good enough" by a committee of experts.
So for now, it's just a manual process, I need to spend time on this issue.

To add more complexity to the scope, the problem is not limited about finding projects to **add**, there is also the question of when projects have to be **removed**, when they become deprecated.
I try to spend time checking some keywords like "not maintained, deprecated" and so on but it's not enough.
A good indicator is the date of last commit, if a project has no recent commit (within 1 year) and if its number of stars added within 1 year is less than a threshold (+100 stars/year), it's removed.

Back to the initial request: `Sandhands` is now available on _Best of JS_, congratulations! 😄 

Please check here for example: 
https://bestofjs.org/projects?tags=validation
The tags I picked are `Validation` and `Express` because the other ones you suggested mean something a bit different in the context of _Best of JS_, let me know if it makes sense.

![image](https://user-images.githubusercontent.com/5546996/119056972-965a4300-ba06-11eb-9df7-aa927b83db0b.png)


Thank you again!

**Comment by L1lith** [comment]
@michaelrambeau Thank you for accepting my package, and yes no worries about the tags, I was just trying to suggest as many as possible so you could select which ones you think best fit. It made my morning the other day waking up to see a few extra stars on the repo 😊

I am still interested in working with you on the ecosystem issues. I do agree with you that commit history would be a good indicator of a project being abandoned but I don't think it would be universally true (some mature packages might serve a limited purpose and be very mature). I still think adding some form of community feedback within the bestofjs could be useful (this would also help know when a project is abandoned or broken, as it may receive lower ratings since a particular update was released, though potentially you could do this kind of analytics using the star count). I'm probably a little busy at the moment but when I get the time I think there should be more time put into some kind of CLI tool that supports a garden-wall approach to the package ecosystem (bestofjs could be one configurable provider). 

Also there could definitely be an automated backend for package scanning for best of JS (though this could be made open source and migrated into the cli, but that could make avoiding it that much easier). It could also be good to integrate with NPMs vulnerability reporting system in order to take immediate action on packages when necessary (like taking down malicious packages or warning devs and users of the risk)

I'm also still wanting to help inspect other peoples packages too, maybe we could just flag repos with insufficient stars and then their approval can wait until x percent of the committee has  approved the project and commented on the issue?

Edit: Also if a project with insufficient stars is deemed unready to be submitted to best of js it could be good if the experts left some constructive criticism in order to help the developer improve their project to a mature state. Also, I am currently developing a course for coding beginners, it could be among the first of the projects to be reviewed by the board. Did you have anyone else in mind that would be interested in participating in it?

**Comment by michaelrambeau** [comment]
Hello @L1lith  thank you again for all your ideas!

Yes, I have a friend @mvila, the creator of a new full stack framework to build web applications called [Layr](https://layrjs.com/) who is interested in the idea.
Actually since we are all busy with different things we could start with a very simple idea and see if it works:

- The board could be made of the members of _Best of JS_ organization on GitHub (I'd invite you, of course, if you are OK with the concept).
- When people submit requests through the issues in the GitHub repo, we check and vote by applying emojis 👍 or 👎 . I know that anyone on GitHub can add emojis but we can check who reacted.
- Once we have voted, we apply a tag "Approved" or "Rejected" to make the decision clear.
- In the comments, we could explain the reason of the rejection.

It's very basic and manual but since we don't have a lot of requests, it could work I think?

I would make the process explicit in the issue template used to "suggest new projects".

**Comment by L1lith** [comment]
@michaelrambeau Sure that sounds good 👍 I just made a PR for the issue template [here](https://github.com/michaelrambeau/bestofjs/pull/396). Feel free to invite me

**Comment by michaelrambeau** [comment]
OK @L1lith you have been invited to the GitHub org.

We have a pretty quiet Slack team, I can invite you if are interested, for more direct communication.

**Comment by L1lith** [comment]
@michaelrambeau I don't think i ever figured out how to find the link to accept the invite, do you need to send it to me? Also I'm not on slack much but I do have discord (if not I can get Slack)

**Comment by michaelrambeau** [comment]
Hello @L1lith sorry I missed your message.
I have just re-sent the invitation, maybe you could see it from here: https://github.com/orgs/bestofjs/people ?

I have opened a Discord space here: https://discord.com/channels/820216739706830868
...but I have `0` experience with Discord, any advice is welcome!

Also, we have a candidate to check! https://github.com/michaelrambeau/bestofjs/issues/397

**Comment by L1lith** [comment]
@michaelrambeau I closed this issue but I just temporarily re-opened it because I realized you sent me an invalid invite. You gotta send me an invite link not a link to the server's channel (right click the server icon and click the invite button)

**Comment by michaelrambeau** [comment]
Hello @L1lith here is the link: https://discord.gg/DcaNhE23

But be warned: a guy invited all his friends and now the default channel is full of crap...
I will have to clean later but for now I'm waiting for the storm to pass...

_Human nature_ 🎵
