### ISSUE TITLE
Add `icebob/vue-form-generator` project

### ISSUE THREAD

**Issue by icebob** [michaelrambeau/bestofjs#39]
https://github.com/icebob/vue-form-generator
This is a powerful form-generator for VueJS

**Comment by michaelrambeau** [comment]
Thank you very much for the suggestion, it will be soon online.

**Comment by michaelrambeau** [comment]
It's online!

http://bestof.js.org/projects/tags/vue

**Comment by icebob** [comment]
Thanks!
