### ISSUE TITLE
Add Paperclip

### ISSUE THREAD

**Issue by crcn** [michaelrambeau/bestofjs#390]
I'd like to add Paperclip! https://paperclip.dev/

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)

- Templating
- React

**Comment by michaelrambeau** [comment]
Hello Craig @crcn 
Thank you for the suggestion, `Paperclip` is now available on _Best of JS_, could you please check here?
https://bestofjs.org/projects?tags=playground

**Comment by crcn** [comment]
Thanks for including that! I think the only tag that I'd add would be `template` since it's a template language that compiles down to React code. The playground is an extra thing specific to Paperclip to help developers build UIs faster.

**Comment by michaelrambeau** [comment]
Hello Craig @crcn 
Thank you for the feedback, you're right, I will fix the tagging.
I wonder if we need a new tag in the application, something about "visual UI builder" and/or "visual testing/regression"... can you see a new tag we could create (and some other projects that should be classified under this new tag?)

**Comment by crcn** [comment]
No problem! `visual ui builder` sounds like a useful tag. Off the top of my head, here are some additional libraries that I think could fit under it (just from a quick Google search):

- https://grapesjs.com/
- https://github.com/builderio/builder (they also have  DSL for this called [jsx-lite](https://github.com/builderio/jsx-lite))
- https://github.com/premieroctet/openchakra

I'd imagine more tools like this will be coming too since visual development is becoming a popular idea (again!).

`visual regression testing` is a bit tougher - couldn't find many libraries that do this, and libraries that _do_ exist are plugins for either Chromatic, or Percy. Both of those services also contain links to libraries that they support, so it seems a bit redundant to also include them in Bestofjs. What do you think?

**Comment by michaelrambeau** [comment]
Thank you very much for the information @crcn 

A tag called  `Visual Editor` would make sense to you? It's a bit a more generic than `Visual UI Builder` as it could include any visual tool that generates code, whether it's about generating UI or not (similar to the "low code" trend too).

We could have Node-RED in this category: https://bestofjs.org/projects/node-red

And I would include GrapeJS too: https://bestofjs.org/projects/grapejs

I will add to _Best of JS_ the 2 other projects you mentioned: OpenChakra and Builder.

Note: we also have a CMS tag: https://bestofjs.org/projects?tags=cms it may include some projects that could be tagged `Visual Editor`.

Thank you again, I take this question of tagging very seriously!

When you said that visual programing is becoming popular again, does it mean you were a Visual Basic programmer in a previous life 😄? I feel less lonely suddenly!

**Comment by crcn** [comment]
> A tag called Visual Editor would make sense to you? It's a bit a more generic than Visual UI Builder as it could include any visual tool that generates code, whether it's about generating UI or not (similar to the "low code" trend too).

Yeah good call, something a bit more generic is probably better.

> Thank you again, I take this question of tagging very seriously!

No problemo! Thanks for setting up BestofJS! It's an awesome resource.

> [...] does it mean you were a Visual Basic programmer in a previous life 

Flex and Flash! I did dabble with Visual Basic a long time ago, not enough to be proficient though. Man those were some fun days...

**Comment by michaelrambeau** [comment]
Hello again Craig @crcn 
Actually, we already had a tag called "Visual Programming", so I simply assigned this tag to some projects already tracked by _Best of JS_, please check here:

https://bestofjs.org/projects?tags=visual-programming

Also your project has now the `templating` tag

![image](https://user-images.githubusercontent.com/5546996/119581591-d1d98080-bdfd-11eb-94fa-1ef4e3fdf8e0.png)

Sorry if it sounds like "bikeshedding", between "Visual Programming" and "Visual Editor" let me know which is one is the most appropriate, and I will make you the unofficial "owner" of the tag 👑 😄 !

The 2 "new" projects will be available in 24 hours, stay tuned!

**Comment by michaelrambeau** [comment]
Hello Craig @crcn 
`OpenChakra` and `Builder` projects are now available under the new tag "Visual programming".
Thank you for checking, again!
