### ISSUE TITLE
Add rescript to BestOfJs

### ISSUE THREAD

**Issue by vtrofin** [michaelrambeau/bestofjs#391]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.
As the title suggests, i think Best of Javascript might benefit from adding [rescript](https://github.com/rescript-lang/rescript-compiler) to the list.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (_Pick one or several existing tags_)
Compiler, Types

**Comment by michaelrambeau** [comment]
Hello Victor @vtrofin 
It's good to see you here, my friend 😄 !
Thank you for the suggestion, `ReScript` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Victor @vtrofin ,
The good news: it's online, check here: https://bestofjs.org/projects?tags=compiler
The bad news: it has lost one star! (which is very uncommon for newly added projects)

![image](https://user-images.githubusercontent.com/5546996/118202115-2b53be00-b494-11eb-9913-fc56a77c9607.png)

**Comment by vtrofin** [comment]
Thank you very much @michaelrambeau!
