### ISSUE TITLE
Add Scrawl-canvas to Best of JavaScript

### ISSUE THREAD

**Issue by KaliedaRik** [michaelrambeau/bestofjs#392]
GitHub: https://github.com/KaliedaRik/Scrawl-canvas
NPM: https://www.npmjs.com/package/scrawl-canvas

How would this project be tagged? (_Pick one or several existing tags_)
Canvas, Animation

**Comment by michaelrambeau** [comment]
Hello Rik @KaliedaRik 
Thank you for the suggestion, `Scrawl-canvas` is now available on _Best of JS_, please check: https://bestofjs.org/projects?tags=canvas

Thank you in advance for your feedback!

**Comment by KaliedaRik** [comment]
Many thanks for actioning my request. And best wishes for your work on this project!
