### ISSUE TITLE
Add `perspective` and `regular-table`

### ISSUE THREAD

**Issue by texodus** [michaelrambeau/bestofjs#393]
Interested in adding [`perspective`](https://perspective.finos.org/)  [(github)](https://github.com/finos/perspective/) (Recommend tags `Charting`, `Analytics`) and [`regular-table`](https://github.com/jpmorganchase/regular-table) (Is there something like a `Datagrid` tag?)?  Both projects independently meet the critera:

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**Comment by michaelrambeau** [comment]
Hello Andrew @texodus 

Thank you for both recommendations, the projects will be available on _Best of JS_ very soon.

About `regular-table` project, we have a tag called `Table`: https://bestofjs.org/projects?tags=table

I wonder if we need kind of aliases for some tags, to help user find what they are looking for.

For example `Datagrid` could be an alias to `Table` (even if the concepts are not the same).
An other example is the "Slider" tag that is often called "Carousel": https://bestofjs.org/projects?tags=slider

Thank you for your feedback!

**Comment by michaelrambeau** [comment]
Hello Andrew @texodus 
Both projects are available on _Best of JS_, please check!
Thank you in advance for your feedback!

![image](https://user-images.githubusercontent.com/5546996/119244342-a448c900-bbaa-11eb-8aaa-cf437644e60e.png)

**Comment by texodus** [comment]
`Table` is a great tag - I completely missed that one.  Thanks for the resolution and the great project!
