### ISSUE TITLE
Add Structurae

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#394]
Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?
Data structure

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Done, please check here: https://bestofjs.org/projects?tags=data-structure
Thank you, as always!
