### ISSUE TITLE
Add Canvacord to Best of JS

### ISSUE THREAD

**Issue by scientific-dev** [michaelrambeau/bestofjs#397]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.
**URL:** https://github.com/DevSnowflake/canvacord

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
- Image processing
- Image viewer
- Canvas

**Comment by michaelrambeau** [comment]
Hello @Scientific-Guy thank you for the suggestion.
It seems there is a dead link here: https://canvacord.js.org/#/docs/main/v5/class/Leaver 

![image](https://user-images.githubusercontent.com/5546996/121770916-2a9f6c00-cba7-11eb-8b2f-13085ba8c452.png)

Could you fix that?

Then, I'm curious about `Canvacord` but I know nothing about Discord, so I have a naive question: I can see it can be used to generate images from a template image and some data, I suppose image are rendered in the a `canvas` elements, but what is the link with Discord?

Thank you for your feedback!

**Comment by scientific-dev** [comment]
The fact is that i am not the original creator of Canvacord. I am just a fan of it. I guess anyone can add any project to the bestofjs to it right? You can read about canvacord in the documentation. You can check up the original repo https://github.com/DevSnowflake/canvacord. And any complaints regarding it can be complainted there by creating an issue over there.

**Comment by michaelrambeau** [comment]
Hello @Scientific-Guy thank you for the reply.
Sorry I thought you were the main maintainer of the project.
Of course, anyone can suggest a new project and this is why I wanted to know what is the use case of the library, why you are a fan, what makes the project great, because I could not understand the link with Discord when I checked the documentation.

An other reason is that I was asked to open a Discord server so I'd like to understand how people (and especially developers) use Discord: https://discord.gg/DcaNhE23

Thank you again for your feedback!

**Comment by scientific-dev** [comment]
> Hello @Scientific-Guy thank you for the reply.
> Sorry I thought you were the main maintainer of the project.
> Of course, anyone can suggest a new project and this is why I wanted to know what is the use case of the library, why you are a fan, what makes the project great, because I could not understand the link with Discord when I checked the documentation.
> 
> An other reason is that I was asked to open a Discord server so I'd like to understand how people (and especially developers) use Discord: https://discord.gg/DcaNhE23
> 
> Thank you again for your feedback!

Yeah well here, Canvacord is nothing but just a wrapper to create awesome image styles using canvas example like blurring image, blurring it, coloring it, etc without making us to mess with large codes. It was very useful since i was beginner back in the time. But now i use canvas but this project would be very useful for beginners. 

And discord here lets to interact with other developers like i cannot chat with other developers in github or do a voice chat. So i use discord to interact and discuss over there. But mostly in discord there are discord bot developers. Still there are people like web developers, app developers, and some organization who hires developers.

**Comment by michaelrambeau** [comment]
Thank you for the feedback @Scientific-Guy 
I used to be a scientific guy so I want to make all scientific guys happy 😄 
`Canvacord` will be available on _Best of JS_ very soon (well unless I got rejections votes from the committee!)

**Comment by scientific-dev** [comment]
Thank you :)

**Comment by L1lith** [comment]
I noticed a few issues with the project. I've open issues on the original repo here:
[Issue 1: \[BUG\] Fails to install on Windows 10](https://github.com/DevSnowflake/canvacord/issues/96)
[Issue 2: \[Feature Request\] Use a bundling service](https://github.com/DevSnowflake/canvacord/issues/97)

I would like to do more research into the project but I'm a little busy at the moment

**Comment by sujalgoel** [comment]
[Issue 1](https://github.com/DevSnowflake/canvacord/issues/96) can be resolved by following this [method](https://github.com/DevSnowflake/canvacord/issues/96#issuecomment-860452728).

**Comment by sujalgoel** [comment]
> I noticed a few issues with the project. I've open issues on the original repo here:
> [Issue 1: [BUG] Fails to install on Windows 10](https://github.com/DevSnowflake/canvacord/issues/96)
> [Issue 2: [Feature Request] Use a bundling service](https://github.com/DevSnowflake/canvacord/issues/97)
> 
> I would like to do more research into the project but I'm a little busy at the moment
[Issue 1](https://github.com/DevSnowflake/canvacord/issues/96) can be resolved by following this [method](https://github.com/DevSnowflake/canvacord/issues/96#issuecomment-860452728).

**Comment by sujalgoel** [comment]
> I noticed a few issues with the project. I've open issues on the original repo here:
> [Issue 1: [BUG] Fails to install on Windows 10](https://github.com/DevSnowflake/canvacord/issues/96)
> [Issue 2: [Feature Request] Use a bundling service](https://github.com/DevSnowflake/canvacord/issues/97)
> 
> I would like to do more research into the project but I'm a little busy at the moment

[Issue 1](https://github.com/DevSnowflake/canvacord/issues/96) can be resolved by following this [method](https://github.com/DevSnowflake/canvacord/issues/96#issuecomment-860452728).

**Comment by michaelrambeau** [comment]
Hello @Scientific-Guy 
Sorry I forgot to confirm but `Canvascord` is online.
Checking the issues mentioned by @L1lith I have the impression the project is not totally mature, I'm still not sure how to ensure a given level of quality for projects tracked by _Best of JS_ but it's an other debate.

About Discord, it was nice to invite all your friends but I'm not sure they understand the purpose of the _Best of JS_ Discord server.
_Best of JS_ Discord server was supposed to be about _Best of JS_, it was obvious to me but maybe not to them?
I didn't expect that amount of crap, I'm not sure if we should clean everything and ban user but we don't want to behave like a dictator 😅 ?
What do you think, I suppose you know them, maybe I missed something when I introduced the server?
Thank you for your feedback!

**Comment by L1lith** [comment]
I don't think I'm in the server in the first place and I have no recollection of inviting anyone. I think it's good to be open to creative and fun projects and CanvaCord seems like something developers like. I didn't mean to say the project wasn't a good project, I just wanted to share some ideas about what might improve the project and get their feedback on it. I wanted to share some ideas I thought could be helpful, not to be judgemental.

**Comment by scientific-dev** [comment]
> Hello @Scientific-Guy
> Sorry I forgot to confirm but `Canvascord` is online.
> Checking the issues mentioned by @L1lith I have the impression the project is not totally mature, I'm still not sure how to ensure a given level of quality for projects tracked by _Best of JS_ but it's an other debate.
> 
> About Discord, it was nice to invite all your friends but I'm not sure they understand the purpose of the _Best of JS_ Discord server.
> _Best of JS_ Discord server was supposed to be about _Best of JS_, it was obvious to me but maybe not to them?
> I didn't expect that amount of crap, I'm not sure if we should clean everything and ban user but we don't want to behave like a dictator  ?
> What do you think, I suppose you know them, maybe I missed something when I introduced the server?
> Thank you for your feedback!

Btw spelling mistake it is `Canvacord`. Sorry for a late response. I either don't know the purpose of the discord server for best of js either. The reason most people want is basically to talk with other developers who created the projects of best of js so that they can communicate with each other (I am not sure with it). And discord is a complicated stuff at beginning.
