### ISSUE TITLE
Add boostercloud/booster

### ISSUE THREAD

**Issue by purefun** [michaelrambeau/bestofjs#399]
Project: https://github.com/boostercloud/booster

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

#event-sourcing
#nodejs-framework
#graphql
#realtime

**Comment by michaelrambeau** [comment]
Hello @purefun thank you for the suggestion, it's a very interesting project!

Booster is now available on _Best of JS_, check here for example: https://bestofjs.org/projects?tags=event-sourcing

Thank you in advance for your feedback!
