### ISSUE TITLE
Weekly JS Update Podcast

### ISSUE THREAD

**Issue by L1lith** [michaelrambeau/bestofjs#403]
I was thinking that it would be good to establish a social media presence, there's only so much attention that being listed on github and NPM can gather so it would be good to look to other platforms.

One way we could do this is to make a podcast where we give an overview of the the trending libraries and possibly other JS news. This could be more convenient for developers who want a summary of whats hot without having to manually go through each one's documentation. This would also allow us to gather a lot more attention to the project on social media platforms organically.

**Comment by michaelrambeau** [comment]
Thank you @L1lith for the idea.
That would be nice but I think it would require a lot of work and preparation.
I guess you know that I used to send a weekly newsletter (139 issues between 2019 and February 2021: https://weekly.bestofjs.org/ )... but writing short posts is one thing, speaking is an other, and I don't have any experience in the podcast field... not to mention I speak English with a strong French accent 😅 
I wonder what is the landscape, I remember a podcast called "5 minutes of JavaScript" from the CodeSchool team. but it does not seem to be online anymore.

Anyway I agree with the need of a strong social media presence, it could be a _Best of JS_ Twitter account that publishes tweets anytime projects or tags are added for example.
