### ISSUE TITLE
Add @okikio/animate to Best of JS 

### ISSUE THREAD

**Issue by okikio** [michaelrambeau/bestofjs#404]
Hi I'd like to suggest [@okikio/animate](https://www.npmjs.com/package/@okikio/animate), an animation library that utilizes the Web Animation API to create fluid and performant animations.

Links:
* NPM: https://www.npmjs.com/package/@okikio/animate
* Demo: https://okikio.github.io/native/demo/animate.html
* Examples: https://codepen.io/collection/rxOEBO
* GitHub: https://github.com/okikio/native/tree/master/packages/animate#readme
* CSS-Tricks article: https://css-tricks.com/how-i-used-the-waapi-to-build-an-animation-library/

Checks:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

Tags:

* Animation
* Scrolling

**Comment by michaelrambeau** [comment]
Hello @okikio 
Thank you for the recommendation.
While checking the documentation, I noticed a dead link when I wanted to see the full API documentation, here:

> Not all available methods and properties are listed here (otherwise this README would be too long), so go through the API documentation for the full documented API.

Dead link: https://okikio.github.io/native/docs/modules/_okikio_animate.html

Could you fix it?

**Comment by okikio** [comment]
Yeah, I noticed that error and I am currently working on it. The error occurred while I was trying to update the api docs. I'm currently revamping the entire documentation and splitting it into chucks, so, it's easier to understand, so, it may take me a few days, but I'll get it done.
