### ISSUE TITLE
Add the Discord Server to bestofjs.org

### ISSUE THREAD

**Issue by L1lith** [michaelrambeau/bestofjs#405]
The official invite link is https://discord.gg/8RBMtuuJmn, we should add it to bestofjs (potentially with a discord icon?) so that people can be attracted to the server

**Comment by michaelrambeau** [comment]
Thank you @L1lith for the suggestion.

It could look like this:

![image](https://user-images.githubusercontent.com/5546996/125373672-889abb80-e3c0-11eb-9016-9687e6663404.png)

The thing that annoys me with this layout is that we have 4 different patterns for links in the header:

- 2 text links to specific pages: Projects and Tags
- A dot-dot-dot button (the kebab menu!) to access extra links
- The "Sign in" button
- Icons to open external site: GitHub and Discord
 
So I think it needs to be improved.

**Comment by BBlackwo** [comment]
What if the internal links were on the left, and the external links were on the right? Something like the Angular website:

![image](https://user-images.githubusercontent.com/7598058/125375587-a40bc380-e3cc-11eb-989d-a7225d89d00b.png)

Also, what's the `Sign in` link for? :slightly_smiling_face:

**Comment by BBlackwo** [comment]
Potentially `Sign in` could be in the kebab menu if it's not used often?

**Comment by michaelrambeau** [comment]
Thank you @BBlackwo yes, that's a neat example!

About the "Sign in" button, it's not obvious but it lets users create "bookmarks" when they are authenticated with GitHub.

![image](https://user-images.githubusercontent.com/5546996/125376115-4c1d8e80-e3c5-11eb-84c2-01db019ec200.png)

This is also a feature I should improve.

**Comment by BBlackwo** [comment]
What about something like this?

![Screenshot from 2021-07-13 12-22-00](https://user-images.githubusercontent.com/7598058/125380058-f7820f80-e3d4-11eb-8072-b37046567f96.png)

**Comment by BBlackwo** [comment]
Or use the same border radius for more consistency?

![image](https://user-images.githubusercontent.com/7598058/125380185-2304fa00-e3d5-11eb-9070-de03677d8feb.png)

**Comment by BBlackwo** [comment]
> About the "Sign in" button, it's not obvious but it lets users create "bookmarks" when they are authenticated with GitHub.

Cool! I didn't know that feature existed.

**Comment by michaelrambeau** [comment]
@BBlackwo  Thank you very much Benjamin for the good ideas.

So I think there is a problem of "definition", what do you think of this concept:

On the left:

- Branding (logo)
- Direct links (including a new HOME link)
- Extra links under a "More..." button

On the right:

- Sign in button
- External links: Discord and GitHub

![image](https://user-images.githubusercontent.com/5546996/125543014-2358ca65-4465-4473-8984-c70f65cf76fb.png)

The look and feel of the direct links is vaguely inspired by https://yarnpkg.com/

The inconvenient is that it's kind of cluttering the header of the application, that looks more crowded that before.

About the Sign in, we have a total of about 4000 users who have tried at least once to login with GitHub, FYI, but it does not mean the feature is used a lot of course, I should extract statistics to see who uses the "Bookmarks" feature.

**Comment by BBlackwo** [comment]
That looks great @michaelrambeau!

I don't think it's too cluttered and it makes it quite clear what the different pages on the site are. 

In the future if we wanted to add more pages to the main navigation rather than under the `More...` link we could make the header go full width like it is on https://yarnpkg.com/. But I think what you've done is good for now!

**Comment by michaelrambeau** [comment]
Hello @BBlackwo and @L1lith 

Here is a link to check the new layout: https://bestofjs-git-feature-discord-link-bestofjs.vercel.app/

#### On mobile

![image](https://user-images.githubusercontent.com/5546996/126086598-8fec1eba-decf-4714-8b20-7124b00e255a.png)

#### On desktop

![image](https://user-images.githubusercontent.com/5546996/126086616-3b0322c6-3eca-43dd-8a7f-bb75e52d1316.png)

**Comment by BBlackwo** [comment]
Nice work @michaelrambeau! You may just want to add some right margin to the sign in button so there's consistent spacing between the items on the right :)

**Comment by michaelrambeau** [comment]
Hello @BBlackwo here is the next iteration: https://bestofjs-git-feature-discord-link-bestofjs.vercel.app/

- specific font for the header
- link "Sign in" instead of a button
- Better spacing
- "chevron" icon for the "More" button instead of `...`

![image](https://user-images.githubusercontent.com/5546996/126250255-999f2874-22cb-46d5-bfcb-7ba80da59661.png)

**Comment by BBlackwo** [comment]
Looks good! :rocket:

**Comment by michaelrambeau** [comment]
## Released!

Now there is a link to join Discord at the top of the page... I hope it's not going to attract all spammers from the Earth 😄 

![image](https://user-images.githubusercontent.com/5546996/128700557-a7bba8dc-495f-454a-852c-dc060dd510a7.png)

**Comment by michaelrambeau** [comment]
Closing the issue as we have a link to the Discord server (since the release [0.32.1](https://github.com/bestofjs/bestofjs-webui/releases/tag/0.32.1))
