### ISSUE TITLE
Add FZF for JS 

### ISSUE THREAD

**Issue by ajitid** [michaelrambeau/bestofjs#407]
This project brings [FZF](https://github.com/junegunn/fzf)’s fuzzy finding mechanism to the web.

Project repo: https://github.com/ajitid/fzf-for-js
Documentation: https://fzf.netlify.com

- [x] The project is related to the web platform or Node.js.
- [x] The project has more than 100 stars on GitHub.
- [x] The project has thorough documentation in English.
- [x] The project is not deprecated and actively maintained. 

How would this project be tagged?
- Fuzzy

There are few libraries similar to this that are grouped under "Full-text search" like Fuse.js, match-sorter, fuzzball.js, fuzzysort that could be better grouped under "Fuzzy". However if the merging of these two tags was intentional, then I would prefer this library to be put under "Full-text search" as well.

**Comment by michaelrambeau** [comment]
Hello @ajitid 
Thank you for the recommendation, FZF is available on _Best of JS_  please check here: 

https://bestofjs.org/projects?tags=search

About the tagging, yes, "Full-text search" was supposed to be a generic tag to handle tools that provide features related to search about strings.

So the concept of `fuzzy search` can be considered as a subset of the existing tag since not all projects in this category perform a "fuzzy search".

Now that we have several projects with a similar scope, we could create a more specific tag called `fuzzy search`, I think?

If we do this, how would you tag the other projects from https://bestofjs.org/projects?tags=search that don't do fuzzy search?

Thank you in advance for your help!

**Comment by ajitid** [comment]
Hi, thanks for adding it!

Can I make one more request? Could we rename the package name to "FZF for JS" please? Reason being, FZF is already a popular command line tool and other developers usually suggest/prefer to have derived packages not bearing the name of the original one. 

For naming yes, we can have "full-text search" and "fuzzy search" as tags. Usually if a library is doing full-text search, it wouldn't be doing a fuzzy match. So I wouldn't make "fuzzy search" a subset of "full-text search" rather make both of them at same levels have a "search" tag as the parent for both of them.

So,
- Fuse.js: 			search, fuzzy search
- List.js: 			search, fuzzy search ([Has fuzzy support](https://listjs.com/docs/search-sort/#:~:text=Alternatively%2C%20using%20fuzzy-search%20here%20will%20switch%20to%20the%20Fuzzy%20Search%20function.))
- lunr: 			search, full-text search, fuzzy search ([Has fuzzy support](https://lunrjs.com/guides/searching.html#:~:text=bar%5E5%20baz%27\)-,FUZZY%20MATCHES,-Lunr%20supports%20fuzzy))
- flexsearch: 		search, full-text search
- Reactive Search: 	search, full-text search, fuzzy search, react, vue (Elasticsearch, which this library uses, provides support both full-text search and fuzzy search. This also means that unlike others, this is not a full client side search solution.)
- InstantSearch.js: search (It has typo tolerance support but that doesn't count as fuzzy)
- match-sorter: 	search, fuzzy search
- fuzzysearch: 		search, fuzzy search
- fuzzysort: 		search, fuzzy search
- mark.js: 			Doesn't seems like a searching solution. It is more comparable to https://roughnotation.com/
- Elasticlunr.js: 	search, full-text search (Though its development has kind of stopped)
- Algolia Autocomplete.js: This is an autocomplete solution. I might give it tags "search", "autocomplete". This libaray is more comparable to https://www.npmjs.com/package/sifter
- React InstantSearch: [same as InstantSearch.js], react
- fuzzyset: 		search, fuzzy search
- FZF for JS: 		search, fuzzy search
- Fuzzball: 		search, fuzzy search

The above list is made with best of my knowledge.

**Comment by michaelrambeau** [comment]
Thank you very much for your thorough investigation @ajitid 
Finding the right balance for tagging is difficult but I think it's what _Best of JS_ valuable, so I appreciate your help.

So we will have a generic tag simply called `Search` and 2 sub tags, more specific: "Fuzzy search" and "Full-text".

The changes will be online in less than 24 hours.

About `mark.js`, to me it's a search library that includes UI features to highlight the results, check this example: https://jsfiddle.net/julmot/hdyLpy37/ this is why I think we could apply the tag "Search"?

`sifter` project does not seem very active (last commit 2 years ago), so I'm not adding it, if you are OK.

I will confirm when the changes are live.

**Comment by ajitid** [comment]
Okay! There is one that I missed in the list, which is that List.js has a tag "table" that still needs to be kept. I'm quite sure that you would've kept it, I am commenting this just for the sake of completeness.

**Comment by michaelrambeau** [comment]
Hello @ajitid thank you for your patience, the changes have been released, please check here:

https://bestofjs.org/projects?tags=fuzzy

![image](https://user-images.githubusercontent.com/5546996/127786969-23982606-3189-4b4f-ab99-3ced43a946be.png)

**Comment by ajitid** [comment]
Heya! Looked at the updated list and everything looks fine except one thing. FlexSearch and Lunr both fall in the same category (full-text search). It just happened to be that Lunr has an option to enable fuzzy matching. I think either "search", "full-text search" and "fuzzy search" all three need to be there, otherwise if we cannot put both sub-categories then "search" and "full-text search" could be used for Lunr.

**Comment by michaelrambeau** [comment]
Hello @ajitid, done, please chek again: https://bestofjs.org/projects?tags=search

Thank you again for the great feedback!

**Comment by ajitid** [comment]
Looks good! 👍

Thank you for putting effort in all of this.
