### ISSUE TITLE
Suggesting Directus 

### ISSUE THREAD

**Issue by alesvaupotic** [michaelrambeau/bestofjs#408]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

https://github.com/directus/directus

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

universal
nodejs-framework
cms
vue
scaffolding
graphql

Project got rewritten from scratch for v9 and is now Node based. 

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by michaelrambeau** [comment]
Hello @alesvaupotic 

Thank you for the suggestion, `Directus` is now available on _Best of JS_, please check here for example: 

https://bestofjs.org/projects?tags=cms

Thank you for your feedback!

**Comment by alesvaupotic** [comment]
Thanks, Michael, appreciate a quick response.
