### ISSUE TITLE
Add bundle.js.org to Best of JS

### ISSUE THREAD

**Issue by okikio** [michaelrambeau/bestofjs#409]
Hi I'd like to suggest [bundle.js.org](https://bundle.js.org), it's an online js bundle size checker that can auto bundle npm packages for you

Links:
* Website: https://bundle.js.org
* GitHub: https://github.com/okikio/bundle
* Product Hunt: https://www.producthunt.com/posts/bundle-6

Checks:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

Tags:

* Building tool
* Module - bundler

**Comment by michaelrambeau** [comment]
Hello @okikio thank you for the suggestion.

`bundle` is now available on _Best of JS_, please check here: 

https://bestofjs.org/projects?tags=build

**Comment by okikio** [comment]
Awesome
