### ISSUE TITLE
Add `jsdelivr/jsdelivr` project

### ISSUE THREAD

**Issue by martinheidegger** [michaelrambeau/bestofjs#41]
https://github.com/jsdelivr/jsdelivr
While not entirely a JavaScript project it is a CDN for javascript libraries.

**Comment by michaelrambeau** [comment]
Following our discussion, we will try to find a way to create something related to services such as CDNs, and online tools like jsbin, webpackbin, gomix...
This is why I put the label "stand by" とりあえず。
