### ISSUE TITLE
Add Next-JS-Landing-Page-Starter-Template to Best of JS

### ISSUE THREAD

**Issue by ixartz** [michaelrambeau/bestofjs#410]
GitHub project: https://github.com/ixartz/Next-JS-Landing-Page-Starter-Template
Link to live demo: https://creativedesignsguru.com/demo/nextjs-landing-page/

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

React, Static site generator, Boilerplate

**Comment by michaelrambeau** [comment]
Hello Remi @ixartz 
Thank you for the suggestion.
`NextJS Landing Page Template` is now available on _Best of JS_.
What a long name, you don't have a shorter name by the way 😄 ?
Thank you in advance for the feedback!

**Comment by ixartz** [comment]
@michaelrambeau, Thank you for adding the project so quickly.
Definitively, I'm not a good marketer, let's see if I can find a better name.

Open to any suggestion haha.
