### ISSUE TITLE
Request to add Reaflow

### ISSUE THREAD

**Issue by amcdnl** [michaelrambeau/bestofjs#412]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

react, charting, d3

the library details:

Name: Reaflow
Website: https://reaflow.dev
Github: https://github.com/reaviz/reaflow
Description: React library for building workflow editors, flow charts and diagrams

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by michaelrambeau** [comment]
@amcdnl Thank you Austin for the recommendation.

It will be available on Best of JS very soon, I think the tag "Flow chart" would be appropriate, too:

https://bestofjs.org/projects?tags=diagram

**Comment by michaelrambeau** [comment]
Hello Austin @amcdnl 
`Reaflow` is available on _Best of JS_, please check here: https://bestofjs.org/projects?tags=diagram
Thank you in advance!
