### ISSUE TITLE
Add speedscope

### ISSUE THREAD

**Issue by EmiM** [michaelrambeau/bestofjs#413]
https://github.com/jlfwong/speedscope

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

`Analytics`, `Charting`, `Performance Optimization` (well, it's not a tool that optimizes but rather tool for performance profiling so I am not sure about the last tag)

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by michaelrambeau** [comment]
Hello @EmiM 
Thank you for recommendation, `Speedscope` will be available on _Best of JS_ very soon.
Maybe I should rename `Performance Optimization` simply `Performance`? or `Web performance`, what do you think? 

This tag is about the tools that can help to improve web performance (and monitoring tools can help improve performance).

**Comment by EmiM** [comment]
Hello :)
Yeah, I think `performance` is a good choice. I was playing with this tool on nodejs project so 'web' would be too narrow.

**Comment by michaelrambeau** [comment]
Thank you @EmiM !

Speedscope is now available on _Best of JS_, and the tag has been renamed:

https://bestofjs.org/projects?tags=performance

**Comment by EmiM** [comment]
Wow, that was fast :D Thank you!
