### ISSUE TITLE
Add CDBReact to Best of JS

### ISSUE THREAD

**Issue by Speedwares** [michaelrambeau/bestofjs#414]
https://github.com/Devwares-Team/cdbreact

Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

CSS Toolkit, Component Toolkit

**Comment by michaelrambeau** [comment]
Hello @Speedwares thank you for the recommendation.

I was checking the demo and I wanted to see how components look like in the Dark Mode but it seems that nothing happens when I click on the 🌔  button?

It's not a big deal but in the left side bar, the active state of the menu item looks a bit weird (the icon is not at the center of its white square container)

Screenshot in Firefox:

![image](https://user-images.githubusercontent.com/5546996/131753953-f17a4b5f-6bb5-4be6-af62-604f585e608c.png)

**Comment by Speedwares** [comment]
Hey @michaelrambeau thank you so much for taking the time to go through contrast and the detailed response. Really appreciate it and am so sorry for the late response on this.

Yes, you are absolutely right about the dark mode button it is not actually working because we did not add that feature to it. the icon was meant for in case someone wanted to add it to their dashboard, they could easily have an icon button already for the functionality.

On the second issue, that's really weird. It does look very out of place that way I will try to replicate it today, fix it up and let you know.

Thanks again for taking the time to go through

**Comment by L1lith** [comment]
@Speedwares Hey there, I've created a few issues on the project repo and would love to hear your feedback. I think these changes could help polish up your library, but you're welcome to take the suggestions at your discretion.
https://github.com/Devwares-Team/cdbreact/issues/6
https://github.com/Devwares-Team/cdbreact/issues/5
https://github.com/Devwares-Team/cdbreact/issues/4

**Comment by Speedwares** [comment]
Hey, @L1lith thank you very much for taking the time to create those issues and even leaving code examples, appreciate it! I am currently working on some improvements to the library and these were all awesome suggestions, thank you again. Hoping to get out those improvements which also fixes the issue Michael brought to my notice above in the next few days.
I will make sure to incorporate these issues fixes as well into the update. 🙏

**Comment by Speedwares** [comment]
Hey @michaelrambeau ,

So sorry I forgot to get back to you on this. I fixed up the issue back then but forgot to update this thread. Could you consider looking at this again. Thank you so much!

Regards

**Comment by michaelrambeau** [comment]
Hello @Speedwares 
OK thank you for the update, CDBReact will be available on _Best of JS_ very soon.

**Comment by Speedwares** [comment]
Thank you so much for responding @michaelrambeau. Hugely looking forward to it 🙏
