### ISSUE TITLE
flooks: A state manager for React Hooks

### ISSUE THREAD

**Issue by nanxiaobei** [michaelrambeau/bestofjs#415]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

https://github.com/nanxiaobei/flooks

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

React, State management, Hooks

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by michaelrambeau** [comment]
Hello @nanxiaobei `flooks` is available on _Best of JS_.

Check `React + State management` tags for example: https://bestofjs.org/projects?tags=state&tags=react

Thank you in advance for the feedback!
