### ISSUE TITLE
Retalk: The simplest solution for Redux

### ISSUE THREAD

**Issue by nanxiaobei** [michaelrambeau/bestofjs#416]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

https://github.com/nanxiaobei/retalk

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

React, State management, Redux

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by L1lith** [comment]
I haven't had the chance to try this library out yet, but I like what I've seen in the documentation. I also noticed that they have a language option for what I believe is Mandarin, which is great considering how common it is. There is a definite need for state libraries in React that cater to the hook API so there's definitely potential here. 

I also opened a minor issue here:
[https://github.com/nanxiaobei/retalk/issues/27](https://github.com/nanxiaobei/retalk/issues/27) (as well as in the Flooks repo)

**Comment by nanxiaobei** [comment]
Thanks, I've replied in the issues.

**Comment by michaelrambeau** [comment]
Thank you for the suggestion @nanxiaobei 
You are really brave as the "State management" field is pretty crowded https://bestofjs.org/projects?tags=state 😄 

I wonder if there is any TypeScript support as developers often appreciate the safety and the developer experience provided by types? It's worth mentioning in the README.md maybe.

**Comment by nanxiaobei** [comment]
Thanks.

[`flooks`](https://github.com/nanxiaobei/flooks) is written in typescript.

`retalk` is currently not.

And I believe `flooks` and `retalk` are the most "simple" solutions for React state management. 😆

**Comment by michaelrambeau** [comment]
Hello @nanxiaobei `Retalk` is available on _Best of JS_.

Please check, here for example: https://bestofjs.org/projects?tags=redux
