### ISSUE TITLE
Add MiniSearch

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#417]
https://github.com/lucaong/minisearch

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

- `Search`
- `Full-text search`
- `Fuzzy search`

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Thank you, as always!
Done, please check here: https://bestofjs.org/projects?tags=search
