### ISSUE TITLE
Add tRPC.io

### ISSUE THREAD

**Issue by KATT** [michaelrambeau/bestofjs#418]
Proposal to add https://trpc.io 

---

- [x] The project is related to the web platform or Node.js
- [x] The project has more than ~100~1000 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

- react
- nodejs-framework
- data
- http
- websocket

## Review Process

After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by michaelrambeau** [comment]
Hello Alex @KATT 
Thank you but tRPC is already on _Best of JS_, I added it 2 months ago:
https://bestofjs.org/projects?tags=nodejs-framework&sort=newest

Now I worry about the search engine 🙀 , is there anything wrong, I wonder why you were not able to find it on _Best of JS_, what kind of query you used... ?

Thank you in advance for your feedback to help us improve the features!

**Comment by KATT** [comment]
Ooops! I missed that - thanks! I was expecting it to be part of [this list](https://bestofjs.org/projects?tags=data&sort=total) as it's all about data fetching 😅

**Comment by michaelrambeau** [comment]
Thank you Alex @KATT for the feedback. The tag "Data fetching" was intended for client side solutions to help with data fetching, without being tied to a given backend, this is why I didn't use this tag for _tRPC_ project.

However I understand that boundaries between tags are not very clear and providing the best tagging is difficult! It's also what makes _Best of JS_ valuable to me, so any feedback is welcome!

**Comment by KATT** [comment]
Well, that becomes a bit fuzzy. Trpc is tied to our rpc spec in the same way Apollo is tied to the GraphQL spec ☺

**Comment by michaelrambeau** [comment]
Thank you again @KATT for helping me!
Yes it's totally fuzzy, finding tags that make sense is a task that has been tormenting me since the start of the project (2015)!

So actually both _Apollo_ and _GraphQL_ projects should not be in this list if we stick with the definition I mentioned.
It's OK to remove them because we have a specific tag "GraphQL" for them.

But then what about Falcor from Netlfix because it's also tied to a specific backend if I understand well. It's an alternative to REST but it's not GraphQL and it's not RPC?

Can you imagine a tag for this kind of project?

So maybe I should just enlarge the scope and accept Apollo, Falcor and tRPC of course, would it make more sense to you?

Note that I'm aware that the definition of the tags should be displayed on the screen when it's not obvious, it's something I should improve.

Not related and back to your initial request, I will add the "web sockets" tag as requested.

**Comment by KATT** [comment]
> Thank you again @KATT for helping me!
> Yes it's totally fuzzy, finding tags that make sense is a task that has been tormenting me since the start of the project (2015)!
😅
> So actually both _Apollo_ and _GraphQL_ projects should not be in this list if we stick with the definition I mentioned.
> It's OK to remove them because we have a specific tag "GraphQL" for them.
> 
> But then what about Falcor from Netlfix because it's also tied to a specific backend if I understand well. It's an alternative to REST but it's not GraphQL and it's not RPC?
> 
> Can you imagine a tag for this kind of project?

Maybe "API"s? But then it's bundled in the same place as any sort of swagger-to-SDK-type stuff too (which might makes sense?)


> So maybe I should just enlarge the scope and accept Apollo, Falcor and tRPC of course, would it make more sense to you?

Maybe I would put all of them under "data". It's all to do with data fetching. 

> Note that I'm aware that the definition of the tags should be displayed on the screen when it's not obvious, it's something I should improve.

Don't worry, I know how it is to maintain a large OSS-project, you can't do it all.

> Not related and back to your initial request, I will add the "web sockets" tag as requested.

👌

**Comment by michaelrambeau** [comment]
Hello Alex @KATT 

Just to confirm, I've added the missing tags, including "Data fetching".

Also we have now a Dark Mode!

![image](https://user-images.githubusercontent.com/5546996/135424075-856cea39-c5e2-4ec5-bf0f-48afed21b8f1.png)

Any feedback is welcome!

**Comment by KATT** [comment]
Woah, that's cool! Thanks! 🙇🏼‍♂️
