### ISSUE TITLE
Add `frontpressorg/frontpress` project

### ISSUE THREAD

**Issue by martinheidegger** [michaelrambeau/bestofjs#42]
https://github.com/frontpressorg/frontpress
Fairly active Userinterface for frontend, maybe worth adding?

**Comment by michaelrambeau** [comment]
Hello Martin,
The project scope is limited to Wordpress API, but since Wordpress is very popular, why not...

Any idea about how to tag correctly the project, besides the `Angular` tag ? `CMS` (it already exists => http://bestof.js.org/tags/cms) ?

**Comment by martinheidegger** [comment]
CMS seems good!

**Comment by michaelrambeau** [comment]
Hello Martin, the project is online, check the `CMS` tag:

http://bestof.js.org/tags/cms

Also I added in the same category Calypso (an admin UI client for WordPress, built by the Automattic team, one of the biggest real-world React Redux app I know)
