### ISSUE TITLE
Add cassidoo to the HOF!

### ISSUE THREAD

**Issue by PhilipJohnBasile** [michaelrambeau/bestofjs#420]
The JavaScript Hall of Fame gathers the greatest developers, authors and speakers of the JavaScript community.

Before submitting the request to add a new member, check the following points:

- [ ] The member has a GitHub profile with more than 500 followers
- [ ] The member is renowned for her/his writings, talks or projects

cassidoo aka Cassidy Williams

**Comment by michaelrambeau** [comment]
Hello Philip @PhilipJohnBasile 
OK, It seems a lot of people want to see Cassidy Williams in the Hall of Fame 😄 
See #421
_Vox populi, vox dei_
Be patient!

**Comment by michaelrambeau** [comment]
Hello @PhilipJohnBasile 

Not 1 but 2 breaking news today:

- Cassidy Williams has been inducted to the Hall of Fame, please check.
- We have now a "Dark Mode"

Any feedback is welcome!
