### ISSUE TITLE
Cassidy Williams

### ISSUE THREAD

**Issue by lynellf** [michaelrambeau/bestofjs#421]
The JavaScript Hall of Fame gathers the greatest developers, authors and speakers of the JavaScript community.

Before submitting the request to add a new member, check the following points:

- [✅] The member has a GitHub profile with more than 500 followers
- [✅] The member is renowned for her/his writings, talks or projects

IMO, Cassidy Williams is one of the core pillars of the React/JavaScript community. 

From her time as an instructor with [React Training](https://reacttraining.com/) to engaging and supporting the community through various channels (Conference Talks, Scrimba, GitHub, Twitter, Twitch, and Discord), it's difficult to emphasize how beneficial her contributions have been to my career, and likely, many others.

**Comment by michaelrambeau** [comment]
Hello Ezell @lynellf 
Thank you for the recommendation, Cassidy Williams will join the Hall of Fame in a few hours!

I wonder what happened today: I almost never have recommendations and today I have 2 requests for the same person! 😄 
#420

**Comment by michaelrambeau** [comment]
Hello @lynellf I have 2 news:

- Cassidy Williams has been inducted to the Hall of Fame, please check.
- We have now a "Dark Mode"

Any feedback is welcome!

**Comment by lynellf** [comment]
This is awesome. Thanks a ton!
