### ISSUE TITLE
Add JSXGraph

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#422]
https://github.com/jsxgraph/jsxgraph

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

`Charting`, maybe also `Math` and `Geometry`.

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq , I was about to add it!

I guess we read the same newsletter? 😄 (https://javascriptweekly.com/issues/558)

**Comment by gamtiq** [comment]
Hello Michael,

Yes, you're right, I've found JSXGraph in JS Weekly. :-)

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq done, please check!

You may have noticed I released the dark mode feature last week.
As an advanced user,  your feedback would be very valuable, thank you in advance!

![image](https://user-images.githubusercontent.com/5546996/136114989-fbc17017-8edb-4081-95ad-0c95c68736e4.png)

**Comment by gamtiq** [comment]
Hello Michael,

Dark mode looks very attractive! By now I've not spot any issue.
Great work!
