### ISSUE TITLE
Add Vizzu to Best of JS

### ISSUE THREAD

**Issue by petervidos** [michaelrambeau/bestofjs#427]
Hey,
I'd like to ask you to add Vizzu - https://github.com/vizzuhq/vizzu-lib
It's an open-source charting library focused on animated charts.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English (https://lib.vizzuhq.com/0.3.0/)
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
Charting, Animation, Canvas, Web Assembly, Dashboard

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by michaelrambeau** [comment]
Hello @petervidos 
Thank you the suggestion, `Vizzu` is available on Best of JS, please check.

Web assembly tag: https://bestofjs.org/projects?tags=webassembly

**Comment by petervidos** [comment]
Thanks a lot, @michaelrambeau. Would it be ok for you to add the Animation tag as well? That's kind of our lib's specialty.
Thank you!

**Comment by michaelrambeau** [comment]
Hello @petervidos 
Sorry, I forgot to tell you, it's done, please check again.
Any feedback about _Best of JS_ is welcome, thank you!

![image](https://user-images.githubusercontent.com/5546996/139509921-61133634-5c1b-4781-ad32-3d92e0d2eb74.png)

**Comment by petervidos** [comment]
Thanks a lot @michaelrambeau 
Will keep an eye on Best of JS and get back to you if I have a suggestion.
