### ISSUE TITLE
Add html-to-image

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#429]
https://github.com/bubkoo/html-to-image

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

`DOM manipulation`

**Comment by michaelrambeau** [comment]
@gamtiq Done, check this one too!
Related #430 
Thank you!
