### ISSUE TITLE
Add html2canvas

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#430]
https://github.com/niklasvh/html2canvas

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

`DOM manipulation`

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Done, please check!
Also I've created a new tag called "Screenshot" for projects that can generate screenshots from web pages.
https://bestofjs.org/projects?tags=screenshot
