### ISSUE TITLE
Add clsx

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#432]
https://github.com/lukeed/clsx

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

`React`, `String`

**Comment by michaelrambeau** [comment]
Hello Denis, done! @gamtiq 

Note: I didn't add the `React` tag because I think the library is totally agnostic, its only purpose is to generate a single string that can be used as the "class name" of a DOM element.
