### ISSUE TITLE
Add Excalibur

### ISSUE THREAD

**Issue by felladrin** [michaelrambeau/bestofjs#433]
[![excalibur](https://user-images.githubusercontent.com/418083/139750419-2aafd659-9917-4816-8abf-9edab0f3da84.png)](https://excaliburjs.com/)
Excalibur is a free game engine written in TypeScript for making 2D games in HTML5 canvas.

- https://excaliburjs.com/
- https://github.com/excaliburjs/Excalibur

---

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

- Game engine

**Comment by michaelrambeau** [comment]
Hello Victor @felladrin 

Thank you for the suggestion, `Excalibur` will be available in _Best of JS_ very soon.

Thank you for sponsoring the project too!

**Comment by felladrin** [comment]
Thank you for creating and maintaining _Best of JS_! Love how it's organized.
I've been checking it daily, and there's always something new to explore!

**Comment by michaelrambeau** [comment]
Hello Victor @felladrin , done, please check the "Game Engine" category: https://bestofjs.org/projects?tags=game

Thank you for your kind words!
About _Best of JS_ future, I'm thinking about a new architecture to go beyond the current limits, I've gathered some ideas here: https://github.com/bestofjs/bestofjs-webui/issues/109
Stay tuned!
