### ISSUE TITLE
Add Cocos Creator

### ISSUE THREAD

**Issue by felladrin** [michaelrambeau/bestofjs#434]
Cocos Creator, A Cross-Platform 2D/3D Game Creation Tool.

- https://www.cocos.com/en/creator
- https://github.com/cocos-creator/engine/tree/develop

This is a different product from the one that is already registered (https://bestofjs.org/projects/cocos2d-html5), as this one uses TypeScript as the scripting language and allows 3D games development.

---

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

- Game engine
- 3D
- WebGL

**Comment by michaelrambeau** [comment]
@felladrin Thank you for that suggestion too!
It will be available in _Best of JS_ too.

I wanted to check the documentation to see how to use it but the link "Docs" from this page https://www.cocos.com/en/docs currently leads to an error 504 page, could you fix it (or ask to fix it)?

**Comment by felladrin** [comment]
Ah, maybe a temporary error? That link from https://www.cocos.com/en/docs worked for me.
But here's the direct link for the latest engine version (v3.3) docs: https://docs.cocos.com/creator/3.3/manual/en/
Which currently displays this:
![image](https://user-images.githubusercontent.com/418083/139754149-4bfefc73-a368-4947-bd72-55a7068b16b3.png)

**Comment by michaelrambeau** [comment]
I tried twice in a row and it failed, but now it works indeed!

Thank you and sorry for the false alert.

**Comment by michaelrambeau** [comment]
@felladrin _Cocos  Creator_ is now available on _Best of JS_, please check!

**Comment by michaelrambeau** [comment]
...actually the tags are missing, sorry for the mistake, it will be fixed very soon!

**Comment by michaelrambeau** [comment]
Hello Victor @felladrin 
Now it should be OK.
Thank you for your patience!

![image](https://user-images.githubusercontent.com/5546996/140198527-9bce8e73-37b1-40c0-a3bb-b9c47af77340.png)
