### ISSUE TITLE
Add react-location to BoJ

### ISSUE THREAD

**Issue by tannerlinsley** [michaelrambeau/bestofjs#435]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
`Routing`

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by tannerlinsley** [comment]
https://react-location.tanstack.com/
https://github.com/tannerlinsley/react-location

**Comment by michaelrambeau** [comment]
Thank you Tanner @tannerlinsley it's great to see you here (and on Discord too, I didn't realize you created this issue when we talked on Discord 😅)

It's coming!

**Comment by michaelrambeau** [comment]
Hello Tanner @tannerlinsley 
`React Location` is now available in _Best of JS_.

I have also added `React Charts`, so we have now 5 projects from the famous "Tanstack", please check!

![image](https://user-images.githubusercontent.com/5546996/140625894-8f0d27f7-031f-44cd-837d-7f9481bd30af.png)
