### ISSUE TITLE
Add generate-schema

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#436]
https://github.com/Nijikokun/generate-schema

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

`JSON`, `Converter` (new tag)

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq done, please check! 

I'm not sure about the "Converter" tag, maybe a `schema` tag would be better?

**Comment by gamtiq** [comment]
Yes, `Schema` is better.
