### ISSUE TITLE
Add ts-json-schema-generator

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#437]
https://github.com/vega/ts-json-schema-generator

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

`JSON`, `Types`, `Code generator` (new tag)

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq  OK done!

I guess you were investigating deeply the topic of moving between JSON schema format and TypeScript types 😄

Related comments: https://github.com/michaelrambeau/bestofjs/issues/438

**Comment by gamtiq** [comment]
Hello Michael!

Yes, you're right. :-)
A couple of days ago I was searching for a tool to describe and/or generate JSON schema/format (including from TypeScript types).
As usual I started my investigation from Best Of JS but found nothing there.
So I decided to recommend my search results to fill the gap. :-)
