### ISSUE TITLE
Add typescript-json-schema

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#438]
https://github.com/YousefED/typescript-json-schema

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

`JSON`, `Types`, `Code generator` (new tag)

**Comment by michaelrambeau** [comment]
Hello Denus @gamtiq done, please check!

About the tagging, we have a tag called "Scaffolding - generator" https://bestofjs.org/projects?tags=scaffolding but the concept is more general, it's about scaffolding the whole filesystem of a new project. Again maybe a "Schema" tag would be good?

**Comment by gamtiq** [comment]
Hello Michael,

I agree that "Scaffolding - generator" tag isn't appropriate for this project.
"Schema" is more suitable. Another alternative is "Model" but I'm not sure it's better than "Schema".

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
I have added a tag "Schema", please check: https://bestofjs.org/projects?tags=schema

By using the "Refine your search" buttons to combine the 3 tags "JSON", "Schema" and "Types", we get the 3 projects you mentioned, isn't beautiful 😄 ?

https://bestofjs.org/projects?tags=schema&tags=json&tags=types

![image](https://user-images.githubusercontent.com/5546996/142508870-77cd8ee9-b6bf-4f9a-8d26-9f49c261ee53.png)

**Comment by gamtiq** [comment]
Hello Michael,

That's great! Thank you!
