### ISSUE TITLE
Add refine to Best of JS

### ISSUE THREAD

**Issue by omeraplak** [michaelrambeau/bestofjs#439]
A React-based framework for building data-intensive applications 

Website: https://refine.dev
GitHub: https://github.com/pankod/refine

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?
- React
- Dashboard

**Comment by michaelrambeau** [comment]
Hello Faruk @omeraplak 
Thank you for the recommendation!
`Refine` is now available on _Best of JS_, please check https://bestofjs.org/projects?tags=dashboard
