### ISSUE TITLE
Remix Run

### ISSUE THREAD

**Issue by skiabox** [michaelrambeau/bestofjs#440]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [ ] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [ ] The project has thorough documentation in English
- [ ] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by michaelrambeau** [comment]
Hello Stavros @skiabox 
Thank you, _Remix_ is available on _Best of JS_ (data has been updated 5 minutes ago!)
And of course it's the project number one of the day!

![image](https://user-images.githubusercontent.com/5546996/143323210-229f7a14-2f7c-4332-a921-c50a29d4c582.png)
