### ISSUE TITLE
Add next-saas-starter to Best of JS

### ISSUE THREAD

**Issue by bmstefanski** [michaelrambeau/bestofjs#441]
Howdy partner 🤠

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

> How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

`Next.js`, `Static site generator`, `Boilerplate`, `React`, `Blog`? Is there a limit with tags 😄 ?

Github: https://github.com/Blazity/next-saas-starter
Preview: https://next-saas-starter-ashy.vercel.app/

**Comment by michaelrambeau** [comment]
Hello Bart @bmstefanski thank you for the suggestion.

At first I thought: oh no, an other SASS template, I just want plain CSS. But then I realized, it's not SASS, it's for SaaS, so that is fine 😄 !

`next-saas-starter` will be available on _Best of JS_ very soon.

**Comment by bmstefanski** [comment]
Thank you! :D <3

**Comment by michaelrambeau** [comment]
Hello Bart @bmstefanski 
`next-saas-starter` is now available on _Best of JS_, please check, any feedback is welcome!
