### ISSUE TITLE
Add Rowy

### ISSUE THREAD

**Issue by harinij** [michaelrambeau/bestofjs#442]
Repo: https://github.com/rowyio/rowy

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? 
Spreadsheet, Workflow automation, CMS

**Comment by michaelrambeau** [comment]
Hello @harinij thank you for the recommendation, that is a very interesting project.
`Rowy` will be available on _Best of JS_ very soon.

I wonder how it compares to "headless CMS" like Strapi.
About the "Workflow automation" tag, could you explain or share a link to the relevant part of the documentation? Maybe the concept of "low code / visual programming" would be more appropriate?

**Comment by michaelrambeau** [comment]
Hello @harinij 
`Rowy` is now available on _Best of JS_, please check here for example: https://bestofjs.org/projects?tags=cms

Any feedback is welcome, thank you in advance!

**Comment by harinij** [comment]
Thanks @michaelrambeau for checking out and adding Rowy.

Rowy is an Airtable-like experience for your actual production database (Firestore) on which you can build workflow automations for data CRUD (use any NPM packages or APIs to code in JS). Rowy is aimed at making your product backend development easy than a CMS product focused on frontend. Documentation with product walkthrough video available [here].(https://docs.rowy.io/field-types/derivative)

Low-code/visual programming or workflow automations tags both work. Happy to share any additional info.
