### ISSUE TITLE
Add Cogo Toast

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#443]
https://github.com/Cogoport/cogo-toast

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged?

`Notification`, `React`

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 
Done, `Cogo Toast` is available on _Best of JS_ please check.
The bad news is that it's losing stars, it's not usual for recently added projects.

![image](https://user-images.githubusercontent.com/5546996/145652625-8fa3f9ec-abd2-4696-92e8-0126c50ce334.png)
