### ISSUE TITLE
Add vercel/turborepo

### ISSUE THREAD

**Issue by jaredpalmer** [michaelrambeau/bestofjs#444]
Best of JavaScript is for the most popular open-source projects related to the web platform and Node.js.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
Building tool, performance, scaffolding, caching, monorepo

## Review Process
After you submit your project the members of Best of JS will respond with 👍 or 👎, and will provide feedback about your project. Once a consensus has been reached your project will either be approved and added to Best of JS, or it will be rejected until you have addressed the areas of your project that could be improved.

**Comment by michaelrambeau** [comment]
Hello Jared @jaredpalmer 
Thank you for the suggestion and congratulations for joining Vercel!
`Turborepo` will be available on _Best of JS_ very soon.

We have already several projects from you, by the way, let us know if you have any feedback, thank you!

![image](https://user-images.githubusercontent.com/5546996/145694096-7301cf89-ea9e-472e-8bc3-9f60e331c55a.png)

**Comment by michaelrambeau** [comment]
Hello Jared @jaredpalmer `Turborepo` is now available on _Best of JS_ and guess what, it's the hottest project of the day!

Please have a look, thank you for your feedback.

![image](https://user-images.githubusercontent.com/5546996/145766444-3b673914-71f0-4bda-9e17-01717158c10c.png)
