### ISSUE TITLE
Add GraphCMS to Best of JS

### ISSUE THREAD

**Issue by castroalves** [michaelrambeau/bestofjs#447]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 
https://graphcms.com

Before submitting the request to add a new project, please check the following points:

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

`CMS`, `GraphQL`, `Database`, `Schema`
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.

**Comment by michaelrambeau** [comment]
Hello @castroalves 
Thank you for the suggestion.
What is the main repo, I can see a repo with examples, an other one called `management-sdk`, is it this one?
It seems that GraphCMS is a CMS that runs in the cloud (as a SaaS), you cannot "self host it"?
