### ISSUE TITLE
Add MiroTalk

### ISSUE THREAD

**Issue by miroslavpejic85** [michaelrambeau/bestofjs#448]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 

GitHub: https://github.com/miroslavpejic85/mirotalksfu
Demo: https://sfu.mirotalk.org/

Before submitting the request to add a new project, please check the following points:

- ✅ The project is related to the web platform or Node.js
- ✅ The project has more than 100 stars on GitHub
- ✅ The project has thorough documentation in English
- ✅ The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

WebRTC, Websocket, Real-Time
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags. 

self-hosted, sfu, p2p, web-app, video-conferencing, video-call, voip, streaming, file-sharing, screen-sharing, whiteboard

**Comment by michaelrambeau** [comment]
Hello Miroslav @miroslavpejic85 
Thank you for the suggestion, `MiroTalk` will be available on _Best of JS_ very soon.

About tagging:

- we have a `video` tag: https://bestofjs.org/projects?query=video
- we don't have `p2p` but we have `decentralized`: https://bestofjs.org/projects?tags=decentralized does it make sense to assign it to `MiroTalk`? Or should I rename it `p2p`, it would be better?

Thank you for your help! (tagging is so difficult 😅 )

**Comment by miroslavpejic85** [comment]
Hello @michaelrambeau, thank you very much.

For this version, in case you could also add the video tag, so 

```bash
WebRTC, Websocket, Video, Real-Time
```

You're right, sorry, decentralized is fine in place of p2p.

In theory there are two versions of MiroTalk, this one (SFU) and the MiroTalk P2P (Decentralized)

## MiroTalk P2P

Best of JS is for the most popular open-source projects related to the web platform and Node.js.

What is the URL of the project you'd like to add to Best of JS?

GitHub: https://github.com/miroslavpejic85/mirotalk
Demo: https://mirotalk.up.railway.app

Before submitting the request to add a new project, please check the following points:

- ✅ The project is related to the web platform or Node.js
- ✅ The project has more than 100 stars on GitHub
- ✅ The project has thorough documentation in English
- ✅ The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

WebRTC, Decentralized, Websocket, Video, Real-Time

Also you can suggest new tags to add if you think Best of JS is missing useful tags.

---

Does it make sense to add both of them, or just the first one ?

The difference between 2 you can check out [here](https://github.com/miroslavpejic85/mirotalksfu/issues/14#issuecomment-932701999)

Thanks to you and nice to meet you :)

**Comment by michaelrambeau** [comment]
@miroslavpejic85  Nice to meet you too 😄 

Thank you for the explanations.

Just to confirm, there will be two projects on _Best of JS_:

- MiroTalk SFU
- MiroTalk P2P (this one will have the tag `decentralized`... that I should rename `P2P`maybe, I'm not sure which term makes more sense for most of the users)

**Comment by miroslavpejic85** [comment]
@michaelrambeau Yeah :)

`MiroTalk SFU` - Tags: WebRTC, Websocket, Real-Time
`MiroTalk P2P` - Tags: WebRTC, Decentralized (you can keep this instead of p2p), Websocket, Real-Time

A peer-to-peer (P2P) service is a decentralized platform whereby two individuals interact directly with each other, without intermediation by a third party. So without adding new tags, you can keep the existing one. 

Thank you again!

**Comment by michaelrambeau** [comment]
Hello Miroslav @miroslavpejic85 , done, please check!

You look like the super star of the `Video` section 😄 : https://bestofjs.org/projects?tags=video&sort=newest

![image](https://user-images.githubusercontent.com/5546996/148705511-834be981-f387-4886-b639-35e66f50932f.png)

**Comment by michaelrambeau** [comment]
But sorry I made a mistake with the tagging, I'm going to fix it...

**Comment by michaelrambeau** [comment]
...done, please check again. The screenshot has been edited.

**Comment by miroslavpejic85** [comment]
Good, Thank you @michaelrambeau!
