### ISSUE TITLE
Add Anthony Fu

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#449]
The JavaScript Hall of Fame gathers the greatest developers, authors and speakers of the JavaScript community.

Before submitting the request to add a new member, check the following points:

- [x] The member has a GitHub profile with more than 500 followers
- [x] The member is renowned for her/his writings, talks or projects

@antfu is an amazing developer that should belong in the JS hall of fame :)

**Comment by michaelrambeau** [comment]
Hello Sébastien @Atinux 
Done! Of course @antfu deserves a spot in the Hall of Fame after his great contribution to the _2021 JavaScript Rising Stars_!

https://bestofjs.org/hall-of-fame
