### ISSUE TITLE
Your First RPG

### ISSUE THREAD

**Issue by L1lith** [michaelrambeau/bestofjs#450]
What is the URL of the project you'd like to add to _Best of JS_? 
Live: [https://yourfirstrpg.com/](https://yourfirstrpg.com/)
Source: [https://github.com/L1lith/Your-First-RPG](https://github.com/L1lith/Your-First-RPG)
Before submitting the request to add a new project, please check the following points:

- [X] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
Learning Resource, Multilingual (would this be a good tag to add?)

**Comment by michaelrambeau** [comment]
Hello @L1lith OK, it's coming, be patient!

**Comment by michaelrambeau** [comment]
Hello @L1lith 
`Your First RPG` is now available in _Best of JS_, please check!
