### ISSUE TITLE
Adding $mol

### ISSUE THREAD

**Issue by nin-jin** [michaelrambeau/bestofjs#451]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 

https://github.com/hyoo-ru/mam_mol

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

For whole framework:

- framework
- component
- mobile

Some alienable parts:

- chart ($mol_plot)
- reactive, state ($mol_atom2)
- css-in-js ($mol_style)
- date ($mol_time)
- types ($mol_type)
- package ($mol_build)
- schema ($mol_data)
- data-structure ($mol_tree2)
- highlight ($mol_text_code, $mol_textarea)
- regexp ($mol_regexp)
- flow ($mol_fiber)
- crypto ($mol_crypto)
 
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.  

- tiny (less then few kb)
- $mol (there are a lot of other useful modules in the ecosystem)
- virtual (rendering virtualization, not only lists)
- collaborate (OT, CRDT and other libs to work users together)

**Comment by michaelrambeau** [comment]
Hello @nin-jin 
Thank you for the recommendation.
What is the documentation web site?
When I go to https://sobe.ru/na/mol it shows a form to send money, it looks suspicious to me 😅

**Comment by nin-jin** [comment]
> What is the documentation web site?

https://mol.hyoo.ru/

> When I go to https://sobe.ru/na/mol it shows a form to send money, it looks suspicious to me 😅

What is suspicious about being able to support the developers of an open source project?

**Comment by michaelrambeau** [comment]
Hello again @nin-jin 
Oh sorry for the confusion, I was expecting the documentation site when clicking on the web site link form GitHub and instead the screen showed a page with a single form, I was surprised and I didn't understand the purpose was to support the developers, my bad.

So OK, `$mol` will be available on _Best of JS_ very soon! 🎉 

How do you pronounce it by the way, "dollar-mol"? (or what is the meaning of the $ symbol that also reminds me of jQuery objects... memories!)

And what is the `MAM` thing mentioned in the README.md? Is there a simple introduction somewhere?

> The easiest way is to checkout this preconfigured MAM repository and start a dev server

Sorry for all my questions but I feel like I'm discovering a brand new ecosystem that I have never heard about before and it's really interesting.

Thank you for your explanations!

**Comment by nin-jin** [comment]
> How do you pronounce it by the way, "dollar-mol"? (or what is the meaning of the $ symbol that also reminds me of jQuery objects... memories!)

Simply "mol" or sometimes "small"  because it's really very small.

> And what is the MAM thing mentioned in the README.md? Is there a simple introduction somewhere?

Short in English (I just have added more info): https://github.com/hyoo-ru/mam
Long (translated from Russian): https://github-com.translate.goog/nin-jin/HabHub/issues/18?_x_tr_sl=ru&_x_tr_tl=en

> I'm discovering a brand new ecosystem that I have never heard about before and it's really interesting.

So this review may be interesting for you: https://github-com.translate.goog/nin-jin/HabHub/issues/23?_x_tr_sl=ru&_x_tr_tl=en

**Comment by michaelrambeau** [comment]
Hello @nin-jin 
`$mol` is now available on _Best of JS_.
For now it's only under the `UI framework` tag but I will assign the tags you suggested.
The number of available features is amazing 😄

**Comment by nin-jin** [comment]
Nice to see it!

It's a micro-modular framework. So every module can be used as tiny standalone lib. The easiest way is to add tags from first message of this issue to $mol. The more precise way is to add each module with its tags separately. What do you prefer?

Could you change the `id` from `dollarmol` to `mol`?

**Comment by michaelrambeau** [comment]
_Best of JS_ tracks only GitHub repositories so it's better to apply all tags to the project since it's a "monorepo" (you were ahead of time, you created monorepos before it became a trend!), I will add the tags, no problem.

About the slug in the URL, it's generated automatically in the UI from `slugify` package so it's not simple to so simple to change it.

https://github.com/simov/slugify/blob/0f1b9e267d0611cdca675c9eab54312b6b76c2a0/config/charmap.json#L2

The best would be to be able to customize the slugs and make the API return the project's slug instead of computing the slug in the UI, I will think about that.

**Comment by nin-jin** [comment]
I think any special characters can be safely cut out, as github does in the in-page links.

**Comment by michaelrambeau** [comment]
OK @nin-jin I'm going to prepare a new version of _Best of JS_ where we generate by ourselves the project slugs, instead of relying on `slugify` package, in order to handle properly this use case.

**Comment by michaelrambeau** [comment]
Hello again @nin-jin sorry for keeping pinging you with my requests!

`$mol` is now available here: https://bestofjs.org/projects/$mol

Could you please check again?

![image](https://user-images.githubusercontent.com/5546996/150636645-8225f943-7303-447a-9ffa-65b3da8826ac.png)

**Comment by nin-jin** [comment]
Cool!
