### ISSUE TITLE
Add $hyoo_crowd

### ISSUE THREAD

**Issue by nin-jin** [michaelrambeau/bestofjs#452]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 

https://github.com/hyoo-ru/crowd.hyoo.ru

There is no homepage yet. crowd.hyoo.ru is just a demo.

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

- data-structure
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.  

- collaborate
- merge

**Comment by michaelrambeau** [comment]
Hello again @nin-jin 
Thank you for the suggestion.
I was checking in Firefox but it seems to freeze the browser, is it supposed to work in all modern browsers?

![image](https://user-images.githubusercontent.com/5546996/150437335-42a62b45-3d94-4270-95ee-7df59177dffa.png)

**Comment by nin-jin** [comment]
It was a bug in the markdown visualizer. I just have fixed it.
But this lib don't have enough stars.

**Comment by michaelrambeau** [comment]
It works, thank you for the fix @nin-jin !

About the 100 stars requirement , it's because it's hard to say "no" to people who want their projects to be featured on _Best of JS_ but I can make an exception for the projects that really deserve more attention like yours 😄 !

**Comment by michaelrambeau** [comment]
Hello @nin-jin 
Sorry for the late reply.
I'm adding it to _Best of JS_.

Just to confirm: 

- the name displayed on the screen will be `CROWD` (all upper case, no final `s`, OK?)
- Package name: `hyoo_crowd_lib`
- I'm creating a new tag `CRDT`

**Comment by nin-jin** [comment]
> the name displayed on the screen will be CROWD (all upper case, no final s, OK?)

Yes, hyoo_crowd_lib implements only CROWD without secure abilities (S).

**Comment by michaelrambeau** [comment]
Hello @nin-jin 
CROWD is now available on _Best of JS_, thank you for your patience! 😅 
As promised I've created a new tag `CRDT`: https://bestofjs.org/projects?tags=crdt
I could only find 3 projects that relate to this tag;
![image](https://user-images.githubusercontent.com/5546996/151899724-b8bc47fb-9d8a-41ed-ab93-23968ff3b0d6.png)

Let me know if you think great projects from _Best of JS_  are missing are in this category because you have been officially promoted as our CRDT expert!

Also you may have noticed that the page layout has changed a little (we show the graph pf NPM download right away), let me know if you have any feedback.

Thank you again for your help!

**Comment by nin-jin** [comment]
Okay :) Some other CRDT libs:

- https://github.com/yjs/yjs
- https://github.com/inkandswitch/peritext
- https://github.com/peer-base/js-delta-crdts

**Comment by michaelrambeau** [comment]
Thank you @nin-jin for the suggestions, I've added `Yjs` and `Peritext`projects.

I'm not sure [js-delta-crdts](https://github.com/peer-base/js-delta-crdts) is still maintained (last commit 2 years ago) but I will keep an eye on it.

![image](https://user-images.githubusercontent.com/5546996/152705397-9dca17d1-1b98-49f6-9d2b-614c283790d8.png)
