### ISSUE TITLE
Add litegraph.js

### ISSUE THREAD

**Issue by bluehat974** [michaelrambeau/bestofjs#453]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 

https://github.com/jagenjo/litegraph.js

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

Charting ?
Canvas
Drag and drop
WebGL
Diagram / Flow chart
Visual Programming ?
Tree / Explorer component
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.

**Comment by michaelrambeau** [comment]
Hello @bluehat974 Audrien,
Thank you for the suggestion, LiteGraph will be available on _Best of JS_ very soon.
