### ISSUE TITLE
Add `@okikio/sharedworker` to best of js

### ISSUE THREAD

**Issue by okikio** [michaelrambeau/bestofjs#455]
I'd like to suggest adding `@okikio/sharedworker`, it's a small spec. compliant polyfill/ponyfill for `SharedWorkers`, that enables devs to use `SharedWorkers` on all browsers
  
What is the URL of the project you'd like to add to _Best of JS_? 

- NPM: https://npmjs.com/@okikio/sharedworker
- Website: https://sharedworker.okikio.dev
- GitHub: https://github.com/okikio/sharedworker

^ not sure which you would prefer

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
webworker
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.  
sharedworker, polyfill

**Comment by michaelrambeau** [comment]
Hello @okikio 
Thank you for the recommendation, it will be available on _Best of JS_ very soon.
An important question now.
What is the project "friendly name"? Can it be called "sharedworker" or it should really be called `@okikio/sharedworker`?

**Comment by okikio** [comment]
Thanks, I'm not sure, but I'd prefer if it were called `sharedworker`, however, as I don't own the npm package name `sharedworker` another package has that name, I'm not sure if I'd be breaking some rule by claiming the package is `sharedworker`

**Comment by michaelrambeau** [comment]
No worries about the "friendly name" being different from the package name @okikio it's a very common situation.

What I call the "friendly name" is only the name displayed on the screen when displaying list of projects for example.
It's also used to generate the project's slug when opening the project's details page (`/projects/:slug` URLs).

So let's say that `sharedworker` (or `Sharedworker`, as you want!) is coming soon!

**Comment by okikio** [comment]
Awesome. I think `sharedworker` sounds good

**Comment by michaelrambeau** [comment]
Hello @okikio `sharedworker` is available on _Best of JS_!

You can check here for example: https://bestofjs.org/projects/sharedworker

Also a new tag was instroduced: https://bestofjs.org/projects?tags=webworker

Note: the project's page will change a little very soon as I'm working on a PR https://github.com/bestofjs/bestofjs-webui/pull/123

Any feedback is welcome!

**Comment by okikio** [comment]
Awesome, thanks
