### ISSUE TITLE
Add `spring-easing` to Best of JS

### ISSUE THREAD

**Issue by okikio** [michaelrambeau/bestofjs#456]
`spring-easing`, is a quick and easy spring animations generator library. It works by generating arrays of keyframe's which when placed in linear order create smooth spring like animations. `spring-easing` works with other animation libraries (gsap, animejs, @okikio/animate, motion one, framer motion, etc...) or the Web Animation API (WAAPI), so, you can carry your spring animations with anywhere you go.
  
What is the URL of the project you'd like to add to _Best of JS_? 

- NPM: https://npmjs.com/spring-easing
- Website: https://spring-easing.okikio.dev
- GitHub: https://github.com/okikio/spring-easing

^ not sure which you would prefer

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
- Animation
- Physics
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.

**Comment by michaelrambeau** [comment]
Hello again @okikio 
You must be super busy creating all these interesting projects? 😄 
`spring-easing` is coming too!

**Comment by okikio** [comment]
Lol, yeah, I made spring-easing to be a spring generation library with great support for 3rd party animation libraries, e.g. https://codepen.io/okikio/pen/MWEMEgJ

**Comment by michaelrambeau** [comment]
Hello @okikio `spring-easing` is now available on _Best of JS_.

![image](https://user-images.githubusercontent.com/5546996/151260735-3b80a881-ccf4-4938-b4a8-5da9a55d8083.png)

**Comment by okikio** [comment]
That's awesome
