### ISSUE TITLE
Add `Appcelerator Titanium` 

### ISSUE THREAD

**Issue by m1ga** [michaelrambeau/bestofjs#457]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 

* Repo: https://github.com/appcelerator/titanium_mobile
* NPM (for the CLI): https://www.npmjs.com/package/titanium
* Documentation: https://titaniumsdk.com/

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
* mobile
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.

**Comment by michaelrambeau** [comment]
Hello Michael @m1ga 
Thank you for the suggestion, Titanium will be available on _Best of JS_ very soon.
Could you tell me about the status of the project: going to the web page https://www.axway.com/en/appcelerator-end-of-life, I can read:

> The Appcelerator offering has been discontinued

It used to be a paid service but it became an open source project? Do you think the project has still traction?

**Comment by m1ga** [comment]
Hi @michaelrambeau 
there is a non profit organization (TiDev Inc.) that will take over all the repos to continue working on it. Most of the repos are (and have been) open source already. Some premium modules are open source now, the main SDK was always open source. The paid services (API backend, push service, analytics) are shutting down but there are many alternative - open source - modules for those parts.
From a community member view I'm looking forward to it. Since many PRs are waiting to be merged (SDK or modules) and the company moved most devs away already the new board/community can finally merge those PRs and keep the modules up to date!
Another bullet-point on their list is marketing! So it will be on the "mobile frameworks to check out" lists again 😉

**Comment by michaelrambeau** [comment]
Thank you for the explanation Michael @m1ga !
Don't you think the GitHub repo should be linked to https://titaniumsdk.com/ instead of http://appcelerator.com/ (if you have the rights on the repo) ?
(actually even the README.md does not include any link to https://titaniumsdk.com/ , I only know it because you included the link in this issue!)
I was a confused between "Axway" (it was the company behind the eco-system?), "Appcelerator" (what is the link with Titanium, is it a set of services around the SDK?) and Titanium itself (the SDK I suppose).

**Comment by m1ga** [comment]
Axway still owns everything at the moment and they only have the repo rights. The switch-over should be March/April. Then we can remove all the Axway traces 😄 
Naming: Away is the company that bought "Appcelerator". Titanium is the SDK and Appcelerator was the platform name (it includes the SDK and other tools). But yes: it was very confusing when they bought it.

**Comment by michaelrambeau** [comment]
Hello Michael @m1ga 
Thank you again for your explanations.

`Titanium` is now available on _Best of JS_, please check!

https://bestofjs.org/projects?tags=mobile

**Comment by m1ga** [comment]
Thanks, looking good 👍
