### ISSUE TITLE
Add "UI5 Web Components for React"

### ISSUE THREAD

**Issue by MarcusNotheis** [michaelrambeau/bestofjs#458]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 
GitHub: https://github.com/SAP/ui5-webcomponents-react
Homepage: https://sap.github.io/ui5-webcomponents-react/ 

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
- `React`
- `Web Components`
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.  

*Additional Information*
This project is closely related to UI5 Web Components (https://github.com/michaelrambeau/bestofjs/issues/366), but maintained in a separate repository and actively developed.

**Comment by michaelrambeau** [comment]
Hello Marcus @MarcusNotheis 
Thank you for the recommendation, it will be available on _Best of JS_ very soon.

I'm just curious: do you know if the _UI5 Web Components_ ecosystem is used outside of the SAP world?

What is the "SAP Fiori User Experience" mentioned by the description of the project, is it a kind of Design System that is open-source too?

Thank you in advance for your answers!

**Comment by MarcusNotheis** [comment]
Awesome, thank you @michaelrambeau!

The Fiori User Experience is not a library but a guideline which describes how certain elements and layouts should look like and recommends how user interactions on a page should work. It's publicly accessible here: https://experience.sap.com/fiori-design-web/

Regarding the usage of the UI5 Web Components Eco System outside of SAP: It's definitely used outside of SAP itself, e.g. by customers or SAP partners to built their own web apps - I would also assume that there are some usages that are not related to SAP in any way but those numbers are rather low I guess. Maybe @petermuessig has some more insights here 🙂

**Comment by MarcusNotheis** [comment]
In case you need a logo for this project: I guess we can just use the same logo like the [UI5 Web Components](https://github.com/michaelrambeau/bestofjs/issues/366#issuecomment-748016680) if @petermuessig is fine with that.

**Comment by michaelrambeau** [comment]
Hello Marcus @MarcusNotheis 
`UI5 Web Components for React` is available on _Best of JS_, with the same logo as `UI5 Web Components` (the orange one, not the blue one! 😄) please check.

**Comment by MarcusNotheis** [comment]
Looks good, thanks!
There is only one minor thing I noticed: The bundlephobia data doesn't seem to be populated although there is data available on bundlephobia directly? Or does it just take some time to warm up the cache?

![image](https://user-images.githubusercontent.com/8775211/151750390-f9451f4a-858c-4c34-b3b0-bca583a90ca1.png)

And thanks for maintaining _Best of JS_ 🙂

**Comment by michaelrambeau** [comment]
Thank you for your feedback @MarcusNotheis 

Data was not correctly initialized, I should improve my processes, sorry! 😅 

Could you please check again?

![image](https://user-images.githubusercontent.com/5546996/151753408-22b99d91-1a0e-4fed-bdc0-4dd4af2d87eb.png)


You may have noticed the layout of the page changed a bit compared to last week (see https://github.com/bestofjs/bestofjs-webui/pull/123) , I hope everything is OK.

**Comment by MarcusNotheis** [comment]
Now everything looks good, thank you!
I think the new layout is a very nice addition 🙂
