### ISSUE TITLE
Add Rete.js library

### ISSUE THREAD

**Issue by bluehat974** [michaelrambeau/bestofjs#459]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 
https://github.com/retejs/rete
https://rete.js.org/

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
Visual Programming
Drag and drop
Diagram / Flow chart
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.

**Comment by michaelrambeau** [comment]
Hello Audrien @bluehat974 
Thank you for that suggestion too!
`Rete.js` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Audrien @bluehat974 
`Rete.js` is now available on _Best of JS_.

https://bestofjs.org/projects?tags=visual-programming

Check the "visual programming" tag, for example.
I wonder if we should rename this tag "low-code" or if we have an extra tag "low-code" if we consider that the concepts are not the same 🤔 ...


Thank you in advance for your feedback!

**Comment by bluehat974** [comment]
Hello @michaelrambeau 

Thanks for the news 👍

For the tags, I clearly don't know, I think it's equivalement, but Visual Programming can also be No Code
Why not rename like Visual Programming / Low Code / No Code... but i'm not convinced, the problem is if someone try to search low code and don't think to search visual programming, he won't find the desired tools

I find this article which try to define the three concepts, but as the author suggest 
https://codeornocode.com/no-code/low-code-vs-no-code/#What_is_Visual_Development

The article also says:
"There is a lot of grey area when you are trying to figure out the difference between Low Code vs No Code. It’s partly a fault of marketers and journalists who use “No Code”, “Low Code” and “Visual Development” interchangeably."

**Comment by michaelrambeau** [comment]
Thank you for the link!
As you said, the main thing is to let people find what they need when using _Best of JS_.
Maybe it would be nice to have kind of **aliases** for some tags, even if the definitions are not **exactly** the same.

A typical example that always comes to my mind is the UI widget called _slider_ by some people or _carousels_ by other people: https://bestofjs.org/projects?tags=slider

Back to our topic, for now, the easiest solution is to rename the tag `Visual Programming / Low Code` as `Low Code` concept has a lot of traction, I will do that.
