### ISSUE TITLE
Selenium

### ISSUE THREAD

**Issue by natorion** [michaelrambeau/bestofjs#461]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 
https://www.selenium.dev/
https://github.com/SeleniumHQ/selenium

Before submitting the request to add a new project, please check the following points:

- [Yes ] The project is related to the web platform or Node.js
- [ Yes] The project has more than 100 stars on GitHub
- [ Yes] The project has thorough documentation in English
- [ Yes] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
 Testing
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.

**Comment by michaelrambeau** [comment]
Hello Michael @natorion 
Thank you for the suggestion.
It seems that even if it's a Java project (not to be confused with JavaScript 😆) users can write tests in JavaScript using the NPM package `selenium-webdriver`, if I understand well, could you confirm?

https://www.npmjs.com/package/selenium-webdriver

**Comment by natorion** [comment]
Your assessment is correct.

Selenium is used to test web applications. It's the tool that is most widely used to actually achieve that. Tests are written in a multitude of languages (Java, C#, JavaScript, Python, ...). I think only listing "selenium-webdriver" would be sufficient though.

**Comment by michaelrambeau** [comment]
Thank you for the confirmation Michael @natorion 
OK, so `Selenium` will be available very soon on _Best of JS_ (I think it's better to stick with the original "branding" name, the page will show details about the NPM package anyway).

About tagging, it will also be under `Browser  automation`, that is a kind of sub-category of the testing category.

You can check the "contenders" here: https://bestofjs.org/projects?tags=auto

**Comment by natorion** [comment]
Thanks, Browser Automation sounds better fitting.

**Comment by michaelrambeau** [comment]
Hello Michael @natorion 
`Selenium` is now available on _Best of JS_, thank you for your patience!
Please check here for example: https://bestofjs.org/projects?tags=auto

Any feedback is welcome!

![image](https://user-images.githubusercontent.com/5546996/154582707-e6fc6bfb-8322-4da9-ac39-aced9edcfced.png)

**Comment by natorion** [comment]
Thank you very much!
