### ISSUE TITLE
Please add pdfme

### ISSUE THREAD

**Issue by hand-dot** [michaelrambeau/bestofjs#462]
Hi @michaelrambeau Please add pdfme!

---
  
> What is the URL of the project you'd like to add to _Best of JS_? 

- https://github.com/pdfme/pdfme
- https://pdfme.com/

> Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

> How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

PDF

**Comment by michaelrambeau** [comment]
Hello Kyohei @hand-dot 
I'm in Japan too, nice to meet you!
OK that rabbit mascot is so cute, it deserves to be in _Best of JS_ 😄

**Comment by hand-dot** [comment]
@michaelrambeau 
Nice to meet you too! Osaka right? surprising!
Best of js is a very cool site, I appreciate your great work.

> OK that rabbit mascot is so cute, it deserves to be in Best of JS 😄

I'm glad to hear that. 

Thanks!!

**Comment by michaelrambeau** [comment]
Yes, I'm in Osaka, where sakura 🌸  are expected to be delivered... tomorrow!

Thank you for your kind words!
I will tell you when `pdfme` is available on _Best of JS_, be patient.

**Comment by michaelrambeau** [comment]
Hello @hand-dot `pdfme` is available on _Best of JS_, please check!

https://bestofjs.org/projects?tags=pdf&sort=daily

**Comment by hand-dot** [comment]
Thank you!
