### ISSUE TITLE
Materio Free VueJS Admin Template

### ISSUE THREAD

**Issue by abhidave001** [michaelrambeau/bestofjs#463]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.

What is the URL of the project you'd like to add to Best of JS?

- Project URL: https://github.com/themeselection/materio-vuetify-vuejs-admin-template-free
- Website: https://themeselection.com/

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
- Vue

**Comment by michaelrambeau** [comment]
Hello Abhi @abhidave001 
Thank you for the recommendation, `Materio` will be available on _Best of JS_ very soon.

**Comment by abhidave001** [comment]
Thank you very much.

**Comment by michaelrambeau** [comment]
`Materio` is now available on _Best of JS_, thank you for your patience!
