### ISSUE TITLE
Sneat Free Bootstrap 5 HTML Admin Template

### ISSUE THREAD

**Issue by saanvi-ts** [michaelrambeau/bestofjs#464]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 

- https://github.com/themeselection/sneat-html-admin-template-free
- https://themeselection.com/

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

- Dashboard
- Bootstrap
- HTML Template

**Comment by michaelrambeau** [comment]
Hello Saanvi @saanvi-ts 
Thank you for the recommendantion,`Sneat` is now available on _Best of JS_, please check.
https://bestofjs.org/projects?tags=html

**Comment by saanvi-ts** [comment]
Thank You very much for including Sneat.👍🏻
