### ISSUE TITLE
Mind Elixir

### ISSUE THREAD

**Issue by SSShooter** [michaelrambeau/bestofjs#466]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 

- Project URL: https://github.com/ssshooter/mind-elixir-core
- Website: https://mindelixir.ink/

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
- charting

**Comment by michaelrambeau** [comment]
Hello @ssshooter 
Thank you for the recommendation, `Mind Elixir` is now available on _Best of JS_, please check!

**Comment by SSShooter** [comment]
Thank you👏
