### ISSUE TITLE
Add: FormKit

### ISSUE THREAD

**Issue by justin-schroeder** [michaelrambeau/bestofjs#467]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_? 

https://formkit.com/

https://github.com/formkit/formkit

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)
 
- form
- vue
- validation

Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.

**Comment by michaelrambeau** [comment]
Hello Justin @justin-schroeder 
Thank you for the recommendation, `FormKit` is now available on _Best of JS_, please check!
