### ISSUE TITLE
Add Xtend UI

### ISSUE THREAD

**Issue by minimit** [michaelrambeau/bestofjs#468]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
What is the URL of the project you'd like to add to _Best of JS_?

- https://xtendui.com/
- https://github.com/xtendui/xtendui

Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

- Component Toolkit
- Animation
  
Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.  

Tailwindcss

**Comment by michaelrambeau** [comment]
Hello Riccardo @minimit 
Thank you for the suggestion, Xtend UI is now available on _Best of JS_, please check!

As you said, a tag "Tailwind CSS" may be useful as we have more and more projects related to Tailwind CSS, it's becoming a kind of "standard" (a bit like Bootstrap a few years ago).
