### ISSUE TITLE
Add: jest-preview

### ISSUE THREAD

**Issue by nvh95** [michaelrambeau/bestofjs#469]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**
When debugging a Jest test (e.g: React), it's extremely difficult to imagine what the UI looks like in your head. [jest-preview](https://github.com/nvh95/jest-preview) helps to preview the UI of your app in Jest to an external browser (such as Chrome), increasing productivity when debugging or writing new tests.

**What is the URL of the project you'd like to add to _Best of JS_?** 
- https://github.com/nvh95/jest-preview
- https://www.jest-preview.com/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- React
- Testing
- Debugging
- CLI

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**  
- Productivity

**Comment by michaelrambeau** [comment]
Hello @nvh95 thank you for the suggestion, `Jest Preview` will be available on _Best of JS_ very soon.

**Comment by nvh95** [comment]
Thank you @michaelrambeau. I can't wait.

**Comment by michaelrambeau** [comment]
@nvh95 `Jest Preview` is now available on _Best of JS_, please check!

Note: I didn't assign the tag "CLI" that is reserved for projects that help with building CLI applications. The tag definition is not clear, it should show up in the application, sorry!

**Comment by nvh95** [comment]
@michaelrambeau I see. I'm so happy to see Jest Preview joins bestofjs list. Thank you very much.
