### ISSUE TITLE
Add `nuxt/nuxt.js` project

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#47]
https://github.com/nuxt/nuxt.js
Framework for server-rendered Vue.js applications

**Comment by michaelrambeau** [comment]
Thank you @Atinux , I'm adding the project to bestof.js.org, it will be online very soon.

**Comment by atinux** [comment]
Thanks @michaelrambeau 

Bestof.js.org is a great initiative 👍

**Comment by michaelrambeau** [comment]
Thank you for your support ;)

**Comment by michaelrambeau** [comment]
It's online, under the following tags:
* `Vue components`
* `Isomorphic`

http://bestof.js.org/tags/vue

**Comment by atinux** [comment]
Great, thank you @michaelrambeau 👏
