### ISSUE TITLE
Please add Histoire

### ISSUE THREAD

**Issue by stepaniukm** [michaelrambeau/bestofjs#471]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**

New Vite based Storybook alternative.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://histoire.dev/

**Before submitting the request to add a new project, please check the following points:**

- [+] The project is related to the web platform or Node.js
- [+] The project has more than 100 stars on GitHub
- [+] The project has thorough documentation in English
- [+] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Vue, Testing, Playground
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Mateusz @stepaniukm 
Thank you for the suggestion, `Histoire` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Mateusz @stepaniukm 
Not only `Histoire` is available on _Best of JS_, but it's the project number two today! 🔥 

![image](https://user-images.githubusercontent.com/5546996/172271912-62e9bbad-5078-4981-a34b-cc62b0a30d30.png)

**Comment by stepaniukm** [comment]
Awesome stuff 🎊
