### ISSUE TITLE
Add @xata.io/screenshot

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#472]
**Please briefly describe the project you'd like to add to _Best of JS_?**

A tool to take screenshots of a given web page.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/xataio/screenshot

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Screenshot

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq 

Sorry for the delay, I've missed the notification 😅 .
OK, it will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
@gamtiq Done, please check https://bestofjs.org/projects?tags=screenshot for example.

Thank you for your patience :)
