### ISSUE TITLE
Add Pothos (gh: hayes/pothos, npm: @pothos/core)

### ISSUE THREAD

**Issue by fcanela** [michaelrambeau/bestofjs#473]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**

Pothos is a plugin based GraphQL schema builder for typescript.

It makes building graphql schemas in typescript easy, fast and enjoyable. The core of Pothos adds 0 overhead at runtime, and has graphql as its only dependency.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://pothos-graphql.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

GraphQL, Node.js framework (this last one is debatable, gives structure but it's more a library for generating the schema that can be plugged into different frameworks).
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Node.js or server-side library

**Additional info**
The [GitHub repo](https://github.com/hayes/pothos) is `https://github.com/hayes/pothos` and the [main package](https://www.npmjs.com/package/@pothos/core) is `@pothos/core`.

**Comment by michaelrambeau** [comment]
Hello Francisco @fcanela thank you for the suggestion!

`Pothos` is now available on _Best of JS_, please check the GraphQL tag for example.
