### ISSUE TITLE
Add CASL to Best of JavaScript

### ISSUE THREAD

**Issue by IgnusG** [michaelrambeau/bestofjs#474]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**
It's an authorization/permission management library. I found Authorization to be missing in Best of JS in terms of available libraries. This could be a good start for a new tag 🙂 

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/stalniy/casl

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
None of the existing ones.
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
It would need a new tag: either `Authorization` or `Permissions`

**Comment by michaelrambeau** [comment]
Hello @IgnusG thank you for the suggestion, `CASL` will be available on _Best of JS_ very soon.

Actually there is a tag `Auth` https://bestofjs.org/projects?tags=auth that mixes authentication and authorization.

![image](https://user-images.githubusercontent.com/5546996/175148344-3f282ebd-2075-4617-b5e4-c53bb6b98358.png)


Is it the tag you were looking for? Or you'd think 2 different tags would be better?

**Comment by IgnusG** [comment]
> Hello @IgnusG thank you for the suggestion, CASL will be available on Best of JS very soon.

Cool!

> Is it the tag you were looking for? Or you'd think 2 different tags would be better?

Yeah I think 2 tags would be better. They are after all [2 separate concepts](https://www.onelogin.com/learn/authentication-vs-authorization) (even though they are often both grouped under the less descriptive `Auth` shorthand - but the text of the tag seems to imply it's only Authentication). 

I found that most of the libraries under the `Authentication` tag were more or less only for Authentication which is why I suggested the new tag and adding CASL (and some other ones when I collect them - hope that's alright 🙂)

PS: Really cool project btw. Became one of my favourites for discovering promising libraries ❤️

**Comment by michaelrambeau** [comment]
Thank you for your kind words @IgnusG !

About the tags, maybe we should rename the existing tag either simply `Auth` or `Authentication / Authorization`, otherwise we would have only 1 project under the new tag "Authorization", maybe two if we include the project https://bestofjs.org/projects/graphql-shield

And if gather more projects related to Authorization and permissions, I agree that we should definitively split the current tag.

**Comment by michaelrambeau** [comment]
Hello @IgnusG , `CASL` is available on _Best of JS_ and the "auth" has been renamed.

Please check here: https://bestofjs.org/projects?tags=auth

![image](https://user-images.githubusercontent.com/5546996/175804506-a2c4f3a4-52e8-464f-9396-8562674758eb.png)
