### ISSUE TITLE
Add Chii

### ISSUE THREAD

**Issue by surunzi** [michaelrambeau/bestofjs#475]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
Chii is a remote debugging tool like [weinre](https://people.apache.org/~pmuellr/weinre/docs/latest/Home.html), replacing web inspector with the latest [chrome devtools frontend](https://github.com/ChromeDevTools/devtools-frontend).

https://github.com/liriliri/chii

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

[Dev tool](https://bestofjs.org/projects?tags=devtool)
[Debugging](https://bestofjs.org/projects?tags=debug)

**Comment by michaelrambeau** [comment]
Hello @surunzi, thank you for the suggestion, `Chii` is available on _Best of JS_.

Please check here for example: https://bestofjs.org/projects?tags=debug
