### ISSUE TITLE
Add Oso to Best of JS

### ISSUE THREAD

**Issue by IgnusG** [michaelrambeau/bestofjs#476]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**
It's another authorization library which uses a custom syntax to define user abilities which can be loaded by the library and used inside of Node.js as well as the Browser.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/osohq/oso
- https://docs.osohq.com/index.html

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
`auth` (`Authentication/Authorization`)  

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @IgnusG thank you for this suggestion too!
The project looks great but it seems to be a Rust project (you have to set up the permission rules writing Rust code if I understand well, but I'm not sure about what is the `.polar` format)?

That being said, I know that scope of _Best of JS_ is a bit blurry ("related to the web platform" can mean anything but things like web frameworks written in other languages are excluded, for example).

There are not a lot of contenders in this category (authorization / permissions) and Oso provides Node.js bindings so maybe we should accept it, what do you think?

**Comment by IgnusG** [comment]
Hi @michaelrambeau!

> Hello @IgnusG thank you for this suggestion too! The project looks great but it seems to be a Rust project (you have to set up the permission rules writing Rust code if I understand well, but I'm not sure about what is the `.polar` format)?

Good question! The project's core is written in rust and compiled into web assembly so that it can run on different platforms (including the browser and Node.js). 

In addition there is a platform specific layer on top to offer easier integration with the language of choice with the Node.js & Browser one written and usable in JavaScript as a regular JS library.

The polar file format on the other hand is more akin to a declaration file with a custom syntax like [prisma's schemas](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model). You define your rules in it, then load it into your JS project through the library. 

So to sum up, the format defines which actions users can perform on different objects. The library provides a wrapper for JS projects to make use of a simple API and the WASM core evaluates the conditions and rules. [Like this for example](https://docs.osohq.com/node/guides/enforcement/resource.html).

> There are not a lot of contenders in this category (authorization / permissions) and Oso provides Node.js bindings so maybe we should accept it, what do you think?

I think oso would be a good addition as a purely authorization oriented library (to complement CASL.js). I do agree though that it is stretching the definition of what to include as the core is not written in JS and requires a [working WASM setup](https://github.com/osohq/oso/issues/1113). I'll leave the choice up to you based on the above details 🙂

**Comment by michaelrambeau** [comment]
Thank you very much @IgnusG for the thorough explanation, that looks like a very useful project as handling the permissions the right way is so difficult... you convinced me 🤝 😄 !

Oso will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
@IgnusG Oso is now available on _Best of JS_, thank you for your patience!
