### ISSUE TITLE
Add bun (gh: Jarred-Sumner/bun

### ISSUE THREAD

**Issue by qwertyuiop6** [michaelrambeau/bestofjs#477]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**
Bun is a fast all-in-one JavaScript runtime, Much faster than node and deno
**What is the URL of the project you'd like to add to _Best of JS_?**
https://bun.sh/
**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
  Runtime, Types, Cli
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @qwertyuiop6 , another friend told me about Bun, the project is very hot 🔥 indeed!

It's now available on _Best of JS_!
