### ISSUE TITLE
Add Cirrus UI to Best of JS

### ISSUE THREAD

**Issue by Spiderpig86** [michaelrambeau/bestofjs#478]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**
A component-and-utility-centric SCSS framework designed for rapid prototyping. Use beautiful pre-built components to bootstrap your next project and utility classes to polish your final design.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://www.cirrus-ui.com/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

I think CSS Toolkit makes the most sense.
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
N/A

Thanks for looking into this :)

**Comment by michaelrambeau** [comment]
Hello @Spiderpig86 thank you for the recommendation, `Cirrus UI` will be available on _Best of JS_ very soon.

**Comment by Spiderpig86** [comment]
Thanks!

**Comment by michaelrambeau** [comment]
Hello Stanley @Spiderpig86, `Cirrus UI` is now available on _Best of JS_, please check!

**Comment by Spiderpig86** [comment]
Thank you!
