### ISSUE TITLE
Add GraphQL Zeus

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#479]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**

- GraphQL Zeus is the absolute best way to interact with your GraphQL endpoints in a type-safe way. Zeus uses your schema to generate Typescript types and strongly typed clients to unlock the power, efficiency, productivity and safety of Typescript on your GraphQL requests.

**What is the URL of the project you'd like to add to _Best of JS_?**

- https://zeus.graphqleditor.com/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- GraphQL
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat thank you for the recommendation, `GraphQL Zeus` is now available on _Best of JS_, please check!
