### ISSUE TITLE
Add `egoist` user to the Hall of Fame

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#48]
https://github.com/egoist
Great developer of the Vue community.

**Comment by michaelrambeau** [comment]
Thank you, OK, I'am adding him.

The Hall of Fame page will be rebuilt tomorrow, I will let you know.

**Comment by atinux** [comment]
@egoist 😄

**Comment by egoist** [comment]
Woot, thank you both @Atinux @michaelrambeau ❤️

**Comment by egoist** [comment]
btw my npm username is rem, cannot find a place to send PR so I just leave it here 🙂

**Comment by michaelrambeau** [comment]
Hello @egoist ,
Thank you, I have just rebuilt the [JavaScript Hall of Fame](http://bestof.js.org/hof/).
In bestof.js.org, there is only one project from you (`Hack` CSS toolkit), let me know if you want more projects, or if you have any feedback about the application.

![image](https://cloud.githubusercontent.com/assets/5546996/22178615/0c6d4e90-e07f-11e6-9b2d-07edfc93bf15.png)
