### ISSUE TITLE
Change wagmi info

### ISSUE THREAD

**Issue by tmm** [michaelrambeau/bestofjs#480]
[wagmi](https://bestofjs.org/projects/wagmi) was added in https://github.com/michaelrambeau/bestofjs/issues/465, but the repo has moved from `tmm/wagmi` to [`wagmi-dev/wagmi`](https://github.com/wagmi-dev/wagmi). Can you update the link?

**Comment by michaelrambeau** [comment]
Hello @tmm thank you for the notification.

I suppose you have moved the repo from `tmm/wagmi` to `wagmo-dev/wagmi` less than 3 hours ago?
The next time the site is rebuilt (around 21:00 GMT), the correct URL should show up as data is updated from GitHub automatically.

**Comment by tmm** [comment]
Great, thanks! Didn't know if it was a manual process or no.

**Comment by michaelrambeau** [comment]
Hello @tmm 
Just to confirm, the repo org is now displayed correctly.
![image](https://user-images.githubusercontent.com/5546996/180094707-843d80fa-848e-4d16-beac-16513e2b4a93.png)

Could you check again?

**Comment by tmm** [comment]
Looks great! Thanks!
