### ISSUE TITLE
React Query -> TanStack Query, React Table => TanStack Table

### ISSUE THREAD

**Issue by tannerlinsley** [michaelrambeau/bestofjs#481]
These projects already exists, they just need a naming update :)

**Comment by michaelrambeau** [comment]
Hello Tanner @tannerlinsley 
The two projects have been renamed and the site has just been rebuilt, please check here: 

https://bestofjs.org/projects?query=tanstack&sort=total

Also I recently created a new tag `Headless components` that I assigned to `TanStack Table` project.

As always, thank you for your feedback!

![image](https://user-images.githubusercontent.com/5546996/180318586-11a18a77-20a6-440b-b92d-0cfbdd30aa6b.png)
