### ISSUE TITLE
Add TanStack Virtual to Best of JS

### ISSUE THREAD

**Issue by tannerlinsley** [michaelrambeau/bestofjs#482]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**
TanStack Virtual

**What is the URL of the project you'd like to add to _Best of JS_?**
https://tanstack.com/virtual

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Not sure. It's framework agnostic.
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello again Tanner @tannerlinsley 
I think the project is already on _Best of JS_, we just have to rename it, as it used to be called `React Virtual`?

We have a tag `Virtual List` with the main contenders in this category, let me know if it makes sense: https://bestofjs.org/projects?tags=virtual-list

Your project being the number 2 over the last month!

![image](https://user-images.githubusercontent.com/5546996/180319440-243621c7-0e74-465e-827c-004013bc1561.png)

**Comment by tannerlinsley** [comment]
Yep that all makes sense.

**Comment by michaelrambeau** [comment]
Hello @tannerlinsley it's done, please check again.

Thank you in advance for your feedback!

https://bestofjs.org/projects/tanstack-virtual
