### ISSUE TITLE
Add Piral

### ISSUE THREAD

**Issue by FlorianRappl** [michaelrambeau/bestofjs#483]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
Piral is a framework for creating web applications using micro frontends. By default it supports application shells written using React with micro frontends using any kind of technologies. It does render on the client and can also be server-side pre-rendered / composed.

More infos can be found at https://piral.io or directly on GitHub (https://github.com/smapiot/piral). The documentation lives at https://docs.piral.io

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

react,nodejs-framework,framework,serverless
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

microfrontends

**Thanks** ❤️ for the great project and resource!

**Comment by michaelrambeau** [comment]
Hello @FlorianRappl thank you for your kind words!

`Piral` is now available on _Best of JS_, this is a very interesting project with a rich ecosystem.

About the tagging, if my understanding is correct, it does not seem to be either a frontend framework (as it can play with any frontend framework) or a backend framework (unless you can use it to create standalone backend applications?) so I created a new tag "Micro frontend": https://bestofjs.org/projects?tags=microfontend

We can adjust the tagging at any time of course, I'm open to the discussion 😄 

For now, Piral is alone in its category as I'm not familiar with the micro frontend trend but let me know if you think important projects are missing in this category, thank you!

**Comment by FlorianRappl** [comment]
> About the tagging, if my understanding is correct, it does not seem to be either a frontend framework (as it can play with any frontend framework) or a backend framework (unless you can use it to create standalone backend applications?) so I created a new tag "Micro frontend": https://bestofjs.org/projects?tags=microfontend

Perfect - yes. That's great! Thanks for the effort. 🚀
