### ISSUE TITLE
Add react-spinners to Best of JS

### ISSUE THREAD

**Issue by davidhu2000** [michaelrambeau/bestofjs#484]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**
React spinners is a collection of loading spinners

**What is the URL of the project you'd like to add to _Best of JS_?**
https://www.davidhu.io/react-spinners/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
 React,  Component Toolkit

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello David @davidhu2000 
Thank you for the suggestion, `React Spinners` is now available on _Best of JS_, under the tag "Progress / Spinner", please check.

https://bestofjs.org/projects?tags=spinner

**Comment by davidhu2000** [comment]
Thank you very much!!
