### ISSUE TITLE
Jspreadsheet CE

### ISSUE THREAD

**Issue by hodeware** [michaelrambeau/bestofjs#485]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**

Jspreadsheet, a lightweight Vanilla JavaScript plugin, can help you create exceptional web-based interactive tables and spreadsheets. It is compatible with the most widely-used spreadsheet software. It offers users an unrivaled spreadsheet-like user experience. It also works well with prominent modern frameworks and flexibly utilizes a large collection of events, extensions and configurations to meet different application requirements.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://bossanova.uk/jspreadsheet
https://github.com/jspreadsheet/ce

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Spreadsheet
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by L1lith** [comment]
This is awesome!

**Comment by michaelrambeau** [comment]
Hello @hodeware thank you for the recommendation,`Jspreadsheet` is now available on _Best of JS_, please check!

https://bestofjs.org/projects?tags=spreadsheet
