### ISSUE TITLE
Add Master CSS

### ISSUE THREAD

**Issue by 1aron** [michaelrambeau/bestofjs#486]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.

`@master/css`

**Please briefly describe the project you'd like to add to _Best of JS_?**
: A Virtual CSS language with enhanced syntax. ~13KB

**What is the URL of the project you'd like to add to _Best of JS_?**
: https://css.master.co ( repo: https://github.com/master-co/css )

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
: CSS in JS, CSS Toolkit
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
: CSS Language, Master CSS, CSS, Language, UI

**Comment by michaelrambeau** [comment]
Hello @1Aron thank you for the recommendation, it's very interesting,`Master CSS` will be available on _Best of JS_ very soon!

I'm just curious, I wonder how it compares to TailwindCSS?

**Comment by 1aron** [comment]
@michaelrambeau Thx! 😍 We created our own structured syntax for class names, and the ~13KB JIT mode has good performance that can be used directly in production.

Check out the following documentation and you'll find something amazing. 😼

- [Why Master CSS](https://docs.master.co/css/why-master-css)
- [Syntax Tutorial](https://docs.master.co/css/syntax-tutorial)

**Comment by 1aron** [comment]
@michaelrambeau We just updated the README. 😇 https://github.com/master-co/css

**Comment by michaelrambeau** [comment]
Thank you for the update, you will see `Master CSS` on _Best of JS_ in exactly 8 hours, when data is rebuilt... be patient 😄

**Comment by michaelrambeau** [comment]
Hello @1Aron 
Please check https://bestofjs.org/projects/master-css
Thank you in advance for your feedback!
