### ISSUE TITLE
Add fluent-vue

### ISSUE THREAD

**Issue by Demivan** [michaelrambeau/bestofjs#487]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**
fluent-vue - Internationalization plugin for Vue.js. fluent-vue is a Vue.js integration for [Fluent.js](https://github.com/projectfluent/fluent.js) - JavaScript implementation of Mozilla's [Project Fluent](https://projectfluent.org/)

**What is the URL of the project you'd like to add to _Best of JS_?**
repo: https://github.com/fluent-vue/fluent-vue
docs: https://fluent-vue.demivan.me/

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Vue, i18n
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Ivan @Demivan 
Thank you for the suggestion, `fluent-vue` is now available on _Best of JS_, please check here for example:
https://bestofjs.org/projects?tags=i18n

**Comment by Demivan** [comment]
Looks good. Thanks
