### ISSUE TITLE
Excalidraw

### ISSUE THREAD

**Issue by dwelle** [michaelrambeau/bestofjs#488]
(Disclaimer: I'm the co-maintainer of the library.)

**Please briefly describe the project you'd like to add to _Best of JS_?**

Excalidraw is canvas-based React whiteboarding library to build your apps on top of.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://excalidraw.com
https://github.com/excalidraw/excalidraw
https://www.npmjs.com/package/@excalidraw/excalidraw

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

`Canvas` `Drawing` `React` `SVG`
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

`Whiteboard`

**Comment by michaelrambeau** [comment]
Hello David @dwelle 
Thank you for the great work on the `Excalidraw` project, it would be a great addition to _Best of JS_, definitively!
I didn't know it was an open source project with a package to integrate the whiteboard in any application.
Be patient, it's coming!

**Comment by dwelle** [comment]
@michaelrambeau nice, and thank your for the awesome project that beofjs is as well! ❤️

**Comment by michaelrambeau** [comment]
Hello David @dwelle 
`Excalidraw` is now available on _Best of JS_, and it's most popular project with the `Drawing` tag!
Please check https://bestofjs.org/projects?tags=drawing

![image](https://user-images.githubusercontent.com/5546996/186034835-68066681-7203-4c84-892e-92a203d10e7e.png)

**Comment by dwelle** [comment]
omg, must have missed the noti in the onslaught. Thanks a lot! We'll tweet later! ❤️
