### ISSUE TITLE
Add `egoist/docute` project

### ISSUE THREAD

**Issue by egoist** [michaelrambeau/bestofjs#49]
https://github.com/egoist/docute
this is a framework for writing docs without build process

**Comment by michaelrambeau** [comment]
@egoist Thank you for that recommendation too!

I will let you know when it's online.

**Comment by michaelrambeau** [comment]
Hello @egoist, `docute` project is available on bestof.js.org, thank you for the suggestion! 

http://bestof.js.org/projects/tags/doc

**Comment by egoist** [comment]
thanks!
