### ISSUE TITLE
Add DevUI to Best of JS

### ISSUE THREAD

**Issue by kagol** [michaelrambeau/bestofjs#490]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**

DevUI is an Angular UI Component Library based on DevUI Design, advocates the design values of immersive, flexible and simplicity.

**What is the URL of the project you'd like to add to _Best of JS_?**

[https://devui.design](https://devui.design)
[https://github.com/DevCloudFE/ng-devui](https://github.com/DevCloudFE/ng-devui)
[https://www.npmjs.com/package/ng-devui](https://www.npmjs.com/package/ng-devui)

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

`component` and `angular`  

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @kagol thank you for the suggestion, `DevUI` is now available on _Best of JS_, please check!
