### ISSUE TITLE
Add astro-18next

### ISSUE THREAD

**Issue by L1lith** [michaelrambeau/bestofjs#491]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Before this library existed I couldn't find any good translation solutions for Astro. This library is awesome, and the author was very nice and supportive when I ran into a problem. They're also constantly adding new features (though the library is already usable as is)

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/yassinedoghri/astro-i18next

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English (It doesn't have a full doc site yet but the readme is thorough)
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Translation, Full stack framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
Should Astro and Vite have their own tags? Astro is on top of Vite but some libs are Astro specific.

Edit: if you feel this library is not ready yet we could leave this issue open until a later time or close and re-open it
[I made an issue about it here](https://github.com/yassinedoghri/astro-i18next/issues/30)

**Comment by michaelrambeau** [comment]
Thank you @L1lith for the recommendation, we can add it!

About the tagging, Astro being very popular and unique, it could have its own tag, similar to the Next.js tag.
It's just we need more related projects 😅 !

You said it Astro is a "full-stack framework" but in _Best of JS_ it's only a "static site generator".
Can Astro let users write server-side code (serverless functions for example?) which would justify the tag "Full stack"?

**Comment by L1lith** [comment]
> Thank you @L1lith for the recommendation, we can add it!
> 
> About the tagging, Astro being very popular and unique, it could have its own tag, similar to the Next.js tag. It's just we need more related projects 😅 !
> 
> You said it Astro is a "full-stack framework" but in _Best of JS_ it's only a "static site generator". Can Astro let users write server-side code (serverless functions for example?) which would justify the tag "Full stack"?

Astro has [SSR support](https://docs.astro.build/en/guides/server-side-rendering/) so I would consider it full-stack 😄 Also I do think it giving it it's own tag would be convenient!

**Comment by michaelrambeau** [comment]
OK @L1lith thank you for the details, `astro-i18next` is now available on _Best of JS_, please check!
