### ISSUE TITLE
Add Nhost to Best of JS

### ISSUE THREAD

**Issue by elitan** [michaelrambeau/bestofjs#492]
_Best of JS_ is for the most popular open-source projects related to the web platform and Node.js.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**

Nhost is an Open Source Firebase Alternative with GraphQL.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/nhost/nhost

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- Database
- SQL
- Authentication / Authorization
- GraphQL
- Websocket
- Real-Time
- Serverless
- File upload
- CLI
- Dev tool
  
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Johan @elitan 
Thank you for the suggestion, `Nhost` is now available on _Best of JS_, please check!
About the tagging, some of the tags you suggested are very specific (`CLI` is for tools to buid CLI apps for example) but I'm aware the scope / definition of each tag is very blurry and should be displayed somewhere in the app, so nothing is frozen and we can adjust things.

Also we have projects like Nhost and Supabase (and maybe NocoDB too, or other projects I'm not aware of) that seem to share the same concept of "backend apps that provide solutions for the most common needs, including database storage and authentication", I wonder if there could be a tag for them? (like `backend-as-a-service` or can you think about better words?) 
Blitz seem to a project that goes in this direction too: https://blitzjs.com/docs/blitz-pivot
