### ISSUE TITLE
Add prettier-plugin-astro to Best of JS

### ISSUE THREAD

**Issue by L1lith** [michaelrambeau/bestofjs#493]
**Please briefly describe the project you'd like to add to _Best of JS_?**
prettier-plugin-astro combines the functionality of two awesome projects Prettier and Astro. I think this project would be a great pick to expand the number of projects under the Astro tag. It's also maintained by the core team

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/withastro/prettier-plugin-astro

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
 Astro, IDE, linter

**Comment by michaelrambeau** [comment]
Hello @L1lith done, please check your favorite web application 😃 !
