### ISSUE TITLE
Add Nice Modal

### ISSUE THREAD

**Issue by bluehat974** [michaelrambeau/bestofjs#495]
**Please briefly describe the project you'd like to add to _Best of JS_?**
In React environment, this project will manage Dialog state using Context & hook.
Instead of managing Dialog state (open, setOpen, setClose...) inside a parent component (and manage boilerplate), 
delegate Dialog state to a context provider and use hook to open/close Dialog - and let Dialog to live it life.

**What is the URL of the project you'd like to add to _Best of JS_?**
Website
https://opensource.ebay.com/nice-modal-react/

Github
https://github.com/eBay/nice-modal-react

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Modal
State Management
React

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Audrien @bluehat974 
Thank you for the suggestion.
`Nice Modal` is now available on _Best of JS_, please check!
