### ISSUE TITLE
Add Liveblocks to Best of JS

### ISSUE THREAD

**Issue by pierrelevaillant** [michaelrambeau/bestofjs#496]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Liveblocks is a set of APIs and tools that helps you create performant and reliable multiplayer experiences in minutes.

**What is the URL of the project you'd like to add to _Best of JS_?**

Website: https://liveblocks.io/
Github: https://github.com/liveblocks/liveblocks

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Real-time, Websocket, React, React Native, Next.js, Vue

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @pierrelevaillant thank you for the recommendation!

Just for my understanding, you cannot use the clients and API provided by this project without subscribing to the product?
Or is there an option to host it on your own servers?

**Comment by pierrelevaillant** [comment]
Hello @michaelrambeau,

1. Exact, you must sign up to use the APIs
2. There is no option to host it on your own server

There is a free plan (no credit card required) with unlimited rooms & up to 5,000 connections per month. Perfect to try it out and explore ideas about real-time collaboration really quickly!

**Comment by michaelrambeau** [comment]
Thank you Pierre @pierrelevaillant for the details.

I asked this question because of the scope of _Best of JS_ that is about open source projects. There are similar projects that are open source clients for paid services (Auth0.js, Angular Fire), so I think it's relevant.

So OK, `Liveblocks` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello Pierre @pierrelevaillant 
`Liveblocks` is now available on _Best of JS_, please check!
