### ISSUE TITLE
Add Remult to Best of JS

### ISSUE THREAD

**Issue by yoni-rapoport** [michaelrambeau/bestofjs#497]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Remult is a CRUD framework for full-stack TypeScript

**What is the URL of the project you'd like to add to _Best of JS_?**

Website: https://remult.dev
Github: https://github.com/remult/remult

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Full-stack framework, Node.js framework, Universal, Data fetching, RPC, ORM

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Yoni @yoni-rapoport 
Thank you, that is a very interesting project I have never heard of, it deserves more exposition!

**Comment by michaelrambeau** [comment]
Hello @yoni-rapoport 
`Remult` is now available on _Best of JS_, please check!
