### ISSUE TITLE
Add RegexLearn to Best of JavaScript

### ISSUE THREAD

**Issue by aykutkardas** [michaelrambeau/bestofjs#498]
**Please briefly describe the project you'd like to add to _Best of JS_?**
A platform to learn regular expression interactively.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://regexlearn.com
https://github.com/aykutkardas/regexlearn.com

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Learning resource
Regular expression

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
-

**Comment by michaelrambeau** [comment]
Hello @aykutkardas thank you for the suggestion.

`RegexLearn` is now available on _Best of JS_, please check!
