### ISSUE TITLE
Add connect-web to Best of JS

### ISSUE THREAD

**Issue by mfridman** [michaelrambeau/bestofjs#499]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Connect-Web is a simple library to call remote procedures from a web browser. Unlike REST, you get a type-safe client and never have to think about serialization again.

Modern alternative to https://bestofjs.org/projects/grpc-web

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/bufbuild/connect-web

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

`RPC`

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

`Proto` or `Protobuf` (I think this category is slightly broader as compared to `RPC`)

**Comment by michaelrambeau** [comment]
Hello Michaej @mfridman thank you for the suggestion, `Connect-Web` is now available on _Best of JS_, please check!

Also a new tag `Protobuf` has been created: https://bestofjs.org/projects?tags=protobuf

Can you see other projects that should be under this new tag?

![image](https://user-images.githubusercontent.com/5546996/190880059-9e977787-0d0c-49a4-96bf-99336eb11165.png)
