### ISSUE TITLE
Add `lindell/JsBarcode` project

### ISSUE THREAD

**Issue by lindell** [michaelrambeau/bestofjs#5]
https://github.com/lindell/JsBarcode
No barcode libraries currently on the bestof.js

**Comment by michaelrambeau** [comment]
Hello @lindell , sorry for the very late answer.
JsBarcode is now listed on http://bestof.js.org/ !

![image](https://cloud.githubusercontent.com/assets/5546996/19009564/3c39ed90-87b0-11e6-8822-16a609220a7e.png)

I didn't know how to tag it, so I created a new tag called `canvas`, let me know if something else makes more sense.
Thank you!
