### ISSUE TITLE
Add SafeQL

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#500]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- SafeQL is an ESLint plugin for writing SQL queries in a type-safe way.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://safeql.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Linter

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat congratulations for the issue number `500`, what a great number 😄 !

`SafeQL` is already available on _Best of JS_, but there was a typo in the name, this is why you didn't find it, I think.

Please check again: https://bestofjs.org/projects/safeql

**Comment by xeusteerapat** [comment]
Oh, that's OK 😄. Thank you for the update.
