### ISSUE TITLE
Add ConnectKit to Best of JS

### ISSUE THREAD

**Issue by lochie** [michaelrambeau/bestofjs#501]
**Please briefly describe the project you'd like to add to _Best of JS_?**

ConnectKit is a powerful React component library for connecting a wallet to a web3 dApp. It supports the most popular connectors and chains out of the box and provides a beautiful, seamless experience.

**What is the URL of the project you'd like to add to _Best of JS_?**

GitHub: https://github.com/family/connectkit
Documentation: https://docs.family.co/connectkit

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

`Blockchain` `React`

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

`web3`

**Comment by michaelrambeau** [comment]
Hello @lochie thank you for the suggestion!
A `Web3` tag makes sense, considering the traction of the topic.

I wonder if all projects with the tag "Blockchain" https://bestofjs.org/projects?tags=blockchain could get this `Web3` tag?

Also we have only 7 projects in this category because I'm not familiar with the topic, let me know if we are missing great projects that should belong to _Best of JS_, thank you!

**Comment by michaelrambeau** [comment]
Hello @lochie 
`ConnectKit` is available on _Best of JS_, please check!
I'm waiting for your feedback about the tagging: we could either rename the current `Blockchain` tag `Web3` or add a new tag `Web3` depending on how scopes overlap... thank you for your help, in advance!

**Comment by lochie** [comment]
Hey @michaelrambeau

I would suggest adding a new tag for `Web3`. `Blockchain` is more of a specific subcategory for what projects exist within web3, and there are few things currently in the `Blockchain` tag that are better suited for the blockchain tag (such as [Truffle](https://bestofjs.org/projects/truffle), [Waffle](https://bestofjs.org/projects/waffle) and [Hardhat](https://bestofjs.org/projects/hardhat)).

Thanks for adding our project to Best of JS, we appreciate it!

**Comment by michaelrambeau** [comment]
Hello @lochie 
A new tag `Web3` is available: 

https://bestofjs.org/projects?tags=web3

![image](https://user-images.githubusercontent.com/5546996/193708672-498936d5-e9be-47ab-ab3c-125eae112738.png)

Please check again and let us know if you think great projects are missing, thank you again for your help!
