### ISSUE TITLE
Add Tremor

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#502]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- The react library to build dashboards fast.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://www.[tremor](https://www.tremor.so/).so/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Component Toolkit
- React
- Dashboard

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat thank you for that suggestion, `Tremor` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Tremor` is now available on _Best of JS_, please check.

I'm waiting for your next recommendation 😉
