### ISSUE TITLE
Add Alinea

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#503]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Alinea is a modern content management system.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://alinea.sh/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- CMS

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Alinea` is available on _Best of JS_, thank you for that suggestion!

This headless CMS is really interesting, I'd like to investigate the "Embedded database" feature to see if we could do something similar with _Best of JS_ data.

> Content is indexed in an embedded SQLite database. The database is deployed with your code and can be queried during build time or at runtime with Node.js or inside an edge or serverless function.
