### ISSUE TITLE
Add oauth4webapi

### ISSUE THREAD

**Issue by panva** [michaelrambeau/bestofjs#505]
**Please briefly describe the project you'd like to add to _Best of JS_?**

OAuth 2 / OpenID Connect for Web Platform API JavaScript runtimes

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/panva/oauth4webapi

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Authentication/Authorization

**Comment by michaelrambeau** [comment]
Hello Filip @panva it's been a long time, thank you for the recommendation!

I can see that all your projects are going well on _Best of JS_!

Also It makes me think that there should be an easy way to see all projects from the same author (technically: from the same GitHub "owner") even if I can enter `panva` in the search field and find all your projects: https://bestofjs.org/projects?query=panva&sort=weekly

Something like a link "From the same author" that would  launch a link `.../projects?owner=panva` for example.

As a library author, let me know if such a link would make sense.

**Comment by panva** [comment]
> As a library author, let me know if such a link would make sense.

I rarely search for modules solely based on their author. The author makes a difference when multiple choices are presented but usually the authors i'd look for have their packages on top due to high use / star count anyway.

**Comment by michaelrambeau** [comment]
Thank you Filip @panva for your patience, `oauth4webapi` is now available on _Best of JS_, please check!

My question was about your own projects, how do you check globally all of your projects numbers, for example what was the trend on GitHub over the last 30 days.  Now the only way is to enter `panva` in the search box and then you can adjust the "Sort: " menu.

![image](https://user-images.githubusercontent.com/5546996/195203213-fdb31cb0-c786-4a79-9089-62787edd2986.png)

Anyway it was just to tell you that any feedback is welcome 😄

**Comment by panva** [comment]
Thank you.
