### ISSUE TITLE
Add Redis-SMQ

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#508]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- A simple high-performance Redis message queue for Node.js.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/weyoss/redis-smq

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Queue

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat thank you for that suggestion too!

`RedisSMQ` is now available on _Best of JS_, please check here for example: https://bestofjs.org/projects?tags=queue
