### ISSUE TITLE
Add `davidjbradshaw/iframe-resizer` project

### ISSUE THREAD

**Issue by davidjbradshaw** [michaelrambeau/bestofjs#51]
https://github.com/davidjbradshaw/iframe-resizer
Solves all the problems inherent with using iframes

**Comment by michaelrambeau** [comment]
Hello @davidjbradshaw thank you for the recommendation.
It will be online soon, be patient!

**Comment by michaelrambeau** [comment]
Hello @davidjbradshaw , it's online.

I didn't know how to "tag" the project, so I chose the tag "Utils".

http://bestof.js.org/tags/util
