### ISSUE TITLE
Add Linen

### ISSUE THREAD

**Issue by sandrodesouza** [michaelrambeau/bestofjs#510]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Linen syncs your Slack and Discord threads to an SEO friendly website that allows your community to discover you through search engines and reduces the number of repeat questions.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/Linen-dev/linen.dev

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

ssg, realtime, search, nextjs, archive

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

chat, community

**Comment by michaelrambeau** [comment]
Hello @sandrodesouza thank you for the suggestion.

It looks very interesting and I wonder if it could be used for _Best of JS_ community (we have a Discord server)... so I have two questions about the features:

- Does it support webhooks? (to be able to get notifications automatically)
- Is there any official app? (mobile/desktop)
 
Thank you!

**Comment by cheeseblubber** [comment]
Hey @michaelrambeau one of the authors of Linen here. We do support webhooks. We don't have a mobile app and desktop client yet. We're probably aiming to get the beta version of the desktop client out sometime next month.

**Comment by michaelrambeau** [comment]
Thank you @cheeseblubber for the feedback.

I was reading the introduction you wrote https://news.ycombinator.com/item?id=33248488 it's nice that you made it open-source!

`Linen` will be available on _Best of JS_ very soon.

**Comment by cheeseblubber** [comment]
Thanks I'm glad you enjoyed the read! 

Btw do you mind changing the description to:
Linen is a Google-searchable Slack alternative for communities. Its aim is to bring all the benefits of a forum in a familiar chat-like user experience.

**Comment by michaelrambeau** [comment]
Hello @sandrodesouza and @cheeseblubber 
`Linen` is now available on _Best of JS_, please check here for example: 
https://bestofjs.org/projects?tags=chat
