### ISSUE TITLE
Add Phero

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#512]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Phero is a Full-stack type-safety with pure TypeScript

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://phero.dev/docs/Introduction

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js 
- [x] The project has more than 100 stars on GitHub (_Currently it's 97 stars, a few to go_ 😅)
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- RPC

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you for the recommendation @xeusteerapat

`Phero` is now available on _Best of JS_, please check!

**Comment by JasperH8g** [comment]
Thanks for adding us @xeusteerapat, really appreciate it! 🙏
