### ISSUE TITLE
Add: vitest-preview

### ISSUE THREAD

**Issue by nvh95** [michaelrambeau/bestofjs#514]
**Please briefly describe the project you'd like to add to _Best of JS_?**

When writing tests, we usually have to debug by reading the cryptic HTML output on the terminal. Sometimes, they are too complicated to visualize the UI in our heads.

vitest-preview previews your Vitest tests right in a browser, then you can see your actual UI visually. You can write tests and watch rendered output changes accordingly. Vitest Preview lets you concentrate on tests in the "real world" rather than deciphering HTML code.

Vitest Preview is [Jest Preview](https://github.com/nvh95/jest-preview)'s little brother. Vitest Preview is built on top of Vite and has first-class support for Vitest.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://www.vitest-preview.com/
- https://github.com/nvh95/vitest-preview/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- **Testing**
- **Debug**
- **React**
- **Vue**
- **Svelte**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
- **Vite**: since many tools/ frameworks/ meta-frameworks are building on top of Vite. I think it's nice if we have a Vite tag to categorize those kind of libraries/ packages

**Comment by michaelrambeau** [comment]
Congratulations Hung @nvh95 😄, `Vitest Preview` is now available on _Best of JS_!

**Comment by nvh95** [comment]
@michaelrambeau Thank you very much. What do you think about the new tag **Vite** I propose?

**Comment by michaelrambeau** [comment]
Sorry Hung I missed that point, my bad, I'm preparing that new tag, OK!

**Comment by michaelrambeau** [comment]
@nvh95 Now we have a tag `Vite` but I must be missing a lot of projects, please check here for example: https://bestofjs.org/projects?tags=vite&sort=daily

![image](https://user-images.githubusercontent.com/5546996/198433857-7bf3e325-acb0-4c01-aeb8-58393eea7040.png)

**Comment by nvh95** [comment]
@michaelrambeau Thanks. I love this new tag. Let me ask some Vite folks on Twitter 😂
