### ISSUE TITLE
Add Express Zod API

### ISSUE THREAD

**Issue by RobinTail** [michaelrambeau/bestofjs#515]
**Please briefly describe the project you'd like to add to _Best of JS_?**

A Typescript library to help you get an API server up and running with I/O schema validation and custom middlewares in minutes.

**What is the URL of the project you'd like to add to _Best of JS_?**

GitHub: https://github.com/RobinTail/express-zod-api
Website: https://ez.robintail.cz/
NPM: https://www.npmjs.com/package/express-zod-api

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Express, Types, Validation, Schema, Documentation, Middleware, RPC, Routing, Logging, File upload

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @RobinTail thank you for the recommendation.

`Express Zod API` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @RobinTail `Express Zod API` is now available on _Best of JS_, please check!

**Comment by RobinTail** [comment]
Yes, it's there. Thank you so much, @michaelrambeau
