### ISSUE TITLE
Add protobuf-es to Best of JS

### ISSUE THREAD

**Issue by mfridman** [michaelrambeau/bestofjs#516]
**Please briefly describe the project you'd like to add to _Best of JS_?**

An implementation of Protocol Buffers for TypeScript and JavaScript with full support for the ECMAScript standard.

Launch post: https://buf.build/blog/protobuf-es-the-protocol-buffers-typescript-javascript-runtime-we-all-deserve

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/bufbuild/protobuf-es

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

`RPC` and `Protobuf`

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Picking up from https://github.com/michaelrambeau/bestofjs/issues/499#issuecomment-1250157880, I think you got the majority of them 😄.

**Comment by michaelrambeau** [comment]
Hello Michael, thank you for the recommendation @mfridman 

Even if the project is written in Go, I guess it's in the scope of _Best of JS_ because it generates JS and TS clients, if my understanding is correct.

Is there a NPM library linked to the project? (to be able to show the graph of the monthly downloads)

**Comment by mfridman** [comment]
Heya, the plugin that generates code is written in TS (and [published to the NPM registry](https://www.npmjs.com/package/@bufbuild/protoc-gen-es)).

The accompanying runtime library is available here which gets published to NPM:

https://www.npmjs.com/package/@bufbuild/protobuf

Both of these originate from the https://github.com/bufbuild/protobuf-es repository.

**Comment by mfridman** [comment]
Ah, I think I understand your question. I think it's more accurate to use the graph data for:

https://www.npmjs.com/package/@bufbuild/protobuf

As this is the runtime library.

**Comment by mfridman** [comment]
You could technically add both:

- the plugin (`protoc-gen-es`) since it is written in TS and generates JS/TS clients
- the runtime library (`@bufbuild/protobuf`), which is a dependency of the generated code

Browsing around the Best of JS site, I didn't see Protobuf plugins published and there aren't that many of them. Fwiw we'd like to change that, so more plugins are written in TS using [`@bufbuild/protoplugin`](https://www.npmjs.com/package/@bufbuild/protoplugin)

**Comment by michaelrambeau** [comment]
Thank you @mfridman for the details.

I was checking https://github.com/bufbuild/buf instead of https://github.com/bufbuild/protobuf-es that you mentioned, my bad! 😅

**Comment by mfridman** [comment]
No problem @michaelrambeau, thanks for all the hard work all these years.

Fwiw I still couldn't figure out a better tagging solution for [bestofgo.dev](https://bestofgo.dev/?t=24h) (a site specific for Go inspired by Best of JS). But that's probably outside the scope of this PR hehe, I think we chatted about this many years ago.

**Comment by michaelrambeau** [comment]
Hello @mfridman `Protobuf-ES` is now available on _Best of JS_, please check!

Good job with `Best of Go`, I guess one of the the main differences is that you your project covers all GitHub projects on GitHub whose main language is Go, there is no "manual" process of picking projects to track?
Also it seems you fetch data from the GitHub API (the one that feeds https://github.com/trending/go?since=daily for example) to show the trending repositories by day, week and month.

The "Star chart" is really nice, I'm curious where you get data from? For _Best of JS_, we track data about stars by ourselves because I couldn't find a good API (at least when I started the project!).

**Comment by mfridman** [comment]
I think you linked to https://github.com/bufbuild/buf, but I think the links (and stars) should be associated with https://github.com/bufbuild/protobuf-es for a more accurate reflection of the project

The highlighted items should probably be linked to github.com/bufbuild/protobuf-es.

![CleanShot 2022-11-02 at 19 39 28@2x](https://user-images.githubusercontent.com/6278244/199622348-d63bb0cd-90c8-4daa-b07c-d1e1b06eef2c.png)

---

Thanks! I should probably write a blog post about the internals of how bestofgo works.

The tl;dr is .. every hour there is a cron job that hits the GitHub Search query and paginates over all the repositories with >= 50 stars. (The star minimum is to stay within the API limits). This operation is fairly cheap, and I store the 22K repositories in a database. This repository object will have the number of stars.

I then have another table that has _all_ the raw stargazer counts, ~14.5M. If it's a repository with <5000 stars, and there is a star change then I scrape all the stars for the given repository and resolve the star count (delete and insert). If someone unstarred and another user starred within the hourly timeframe, the star count is the same, and we do nothing. The tradeoff is having stale stargazer events with an accurate star count to preserve API requests to avoid rate limits.

For larger repositories, >5000 stars, if the delta between the new repository star count (from the Search query) and what we have in the database is >3 stars then we do a full scrape. The same logic applies to >20,000 stars but the delta is higher, I think 10.

The tradeoff for these larger ones is star accuracy to preserve API requests. The star count might be off by a bit for very popular repositories, but at least we'll be able to fit within the 5k requests GitHub gives you for v3 (RESTful API) and 5k requests for the v4 (GraphQL API) per hour.

There are other optimizations as well. Once all the data is fetched and resolved, it gets stored in a cache. The 14M or so raw events get aggregated into rollup tables by day, month and year. So other queries are extremely cheap.

**Comment by michaelrambeau** [comment]
@mfridman Thank you very much for the deep explanations, the system you created looks smart (far much smarter than my approach of taking every day a "snapshot" of the number of stars for all the projects we "track")... so it can inspire me to expand _Best of JS_ project beyond the current limits.

I'm sorry about the link to the GitHub repository, I said previously I missed the right repository but I didn't fix my data.
This is why I always ask people to check 😅 

I will fix and rebuild everything, sorry for the delay!
Note that the number of stars will be from `protobuf-es` repo (around 316).

**Comment by michaelrambeau** [comment]
OK @mfridman the site has been re-built, please check again.
We can link only one NPM package per project so I picked `@bufbuild/protobuf` but I can link the other one if you prefer.

![image](https://user-images.githubusercontent.com/5546996/199852198-c06dc1f4-ddf9-49a3-95e8-74d1b85e51f8.png)

**Comment by mfridman** [comment]
Thanks @michaelrambeau, looks great. Thank you!
