### ISSUE TITLE
Update refine project

### ISSUE THREAD

**Issue by omeraplak** [michaelrambeau/bestofjs#517]
Hey,
We have a few updates in the [refine](https://bestofjs.org/projects/refine) package.

- Can we update the URL of the npm package? "https://www.npmjs.com/package/@pankod/refine-core" 
- Can we update the package description? "Build your React-based CRUD applications, without constraints."

Thank you! 👊

**Comment by michaelrambeau** [comment]
Hello @omeraplak thank you for reaching us, it's done, please check!

I'm curious : why the project has been so hot 🔥 on _Best of JS_ (number 2 this week!), I guess it reached a special milestone?

![image](https://user-images.githubusercontent.com/5546996/200438993-25bfe22c-66f4-4424-80e3-b294d0a5bbf4.png)

**Comment by omeraplak** [comment]
Hey @michaelrambeau ,
Thank you very much! A successful hacktoberfest event and we recently announced our support for two interesting UI frameworks 💥

**Comment by michaelrambeau** [comment]
Great, I'm very interested in the topic as I need a real admin panel for _Best of JS_ data.

The support of CharkraUI is a great feature as I really love the DX provided by their components.

**Comment by omeraplak** [comment]
We would love to share it as a use-case. Come to our [Discord server](https://discord.gg/refine) and let's chat :)
