### ISSUE TITLE
Add SonicJS

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#518]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- SonicJS is a Modern Open Source NodeJs Based Content Management System

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://sonicjs.com

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- CMS
- MongoDB
- GraphQL

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat for the suggestion, `SonicJS` will be available on _Best of JS_ very soon.

I'm a bit disappointed because it does not seem to be related to Sonic the Hedgehog 🦔 😄

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `SonicJS` is available on _Best of JS_, please check.

Also I couldn't find the NPM package related to the project (to show the monthly downloads graph), please let me know!

**Comment by xeusteerapat** [comment]
@michaelrambeau Hmm 🤔 based on the document, It seems the only way to install is by cloning and running `npm install`. There is no `cli` tool yet.
