### ISSUE TITLE
Add DuckDB-wasm

### ISSUE THREAD

**Issue by bluehat974** [michaelrambeau/bestofjs#519]
**Please briefly describe the project you'd like to add to _Best of JS_?**
DuckDB is an database equivalent to SQLite for OLAP/analytics data.
Here is the project pointing to the WASM wrapper (equivalent to SQL.js)

**What is the URL of the project you'd like to add to _Best of JS_?**
WASM Project
https://github.com/duckdb/duckdb-wasm

Original project
https://github.com/duckdb/duckdb

Website
https://duckdb.org/

**Before submitting the request to add a new project, please check the following points:**

- [ X ] The project is related to the web platform or Node.js
- [ X ] The project has more than 100 stars on GitHub
- [ X ] The project has thorough documentation in English
- [ X ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Web Assembly
Database
SQL
Analytics

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
`DuckDB-Wasm` is now available on _Best of JS_, thank you Audrien for the suggestion!
