### ISSUE TITLE
Add Apache Arrow

### ISSUE THREAD

**Issue by bluehat974** [michaelrambeau/bestofjs#520]
**Please briefly describe the project you'd like to add to _Best of JS_?**
JS version for Apache Arrow
Apache Arrow is a columnar memory layout specification for encoding vectors and table-like containers of flat and nested data.
It's an equivalent to Apache Parquet file format.
Some frontend libs (Perspective) use Apache Arrow file to load columnar data

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/apache/arrow/tree/master/js
https://arrow.apache.org/

**Before submitting the request to add a new project, please check the following points:**

- [ X ] The project is related to the web platform or Node.js
- [ X ] The project has more than 100 stars on GitHub
- [ X ] The project has thorough documentation in English
- [ X ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Data Structure
Analytics

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
To debate

"Columnar Data" or "DataFrame" 
or "Data Analysis" / "Data Wangling" for more generic terms

I'm thinking a generic tags regrouping all tools which can be used for data wangling procress
Equivalent to all tools in Python like panda or Apache Parquet

There is multiple libs which can be grouped to Data Analysis / Data Wangling tools
SQL.js https://bestofjs.org/projects/sqljs
AlaSQL https://bestofjs.org/projects/alasql
Perspective https://bestofjs.org/projects/perpective
Cube.JS https://bestofjs.org/projects/cubejs
...

**Comment by michaelrambeau** [comment]
Hello Audrien @bluehat974 thank you for all the suggestions!

Maybe we should rename the current tag "Analytics" "Web Analytics" and create a new tag "Data analysis" with the 4 projects you mentioned + the 3 new ones you suggested (DuckDB-Wasm, Apache Arrow and Arquero), what do you think?

About the naming of the new tag, we could be even more generic and call it "Big data" ? I know it sounds very marketing 😅

**Comment by bluehat974** [comment]
Bonjour @michaelrambeau 

I like the idea to rename "Analytics" by "Web Analytics" and create new "Data Analysis" tag

Please also add "Data analysis" on 
4 existing projects (SQL.js, AlaSQL, Perspective, Cube.JS) 
+ the 3 new ones (DuckDB-Wasm, Apache Arrow and Arquero)

"Big data" looks good, very marketing and can group lot of data oriented libs
But in this context, I don't really like "Big data" tag, because it's not BIG data, the libs won't manipulate billions of data (datalake, Spark, Hadoop, etc...)
Here it's really "Data Analysis", like panda for Python, that these libs will solve (data query, group by/aggregate, pipeline, etc...) or storage/streaming file format (Parquet/Arrow), or local database to run SQL against small dataset (SQL.js, DuckDB, AlaSQL)

Thanks for your help

**Comment by michaelrambeau** [comment]
Thank you very much for the clarification Audrien @bluehat974 , I'm not a specialist so I appreciate your help!

OK, so let's create a`Data analysis` tag. I'm preparing that and I will ask you to check the result in a few hours, be patient!

**Comment by michaelrambeau** [comment]
Hello Audrien @bluehat974 
The new tag is available here: https://bestofjs.org/projects?tags=data-analysis
It includes the 3 projects you submitted, please check!

![image](https://user-images.githubusercontent.com/5546996/201223978-42d74e19-fb13-4175-baac-6bb299d416ad.png)

**Comment by bluehat974** [comment]
Perfect 👍 thanks Michael
