### ISSUE TITLE
Add Arquero

### ISSUE THREAD

**Issue by bluehat974** [michaelrambeau/bestofjs#521]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Arquero is a library for query processing and transformation of array-backed data tables. 

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/uwdata/arquero
https://uwdata.github.io/arquero/

**Before submitting the request to add a new project, please check the following points:**

- [ X ] The project is related to the web platform or Node.js
- [ X ] The project has more than 100 stars on GitHub
- [ X ] The project has thorough documentation in English
- [ X ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Analytics

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
Data Analysis / Data Wangling

**Comment by michaelrambeau** [comment]
`Arquero` is now available on _Best of JS_, thank you Audrien for the suggestion!
