### ISSUE TITLE
Add Rakkas

### ISSUE THREAD

**Issue by cyco130** [michaelrambeau/bestofjs#523]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Rakkas is a React metaframework powered by Vite.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://rakkasjs.org/
- https://github.com/rakkasjs/rakkasjs

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- React
- Universal
- Static site generator
- Full-stack framework
- Node.js framework

**Comment by michaelrambeau** [comment]
Hello @cyco130 thank you for the suggestion!

`Rakkas` looks like a great contender in the hot space of the React "meta frameworks".

It will be available on _Best of JS_ very soon!

Also I'm adding `HatTip` that I've found when checking the documents.

**Comment by michaelrambeau** [comment]
Hello @cyco130 `Rakkas` is now available on _Best of JS_, please check!

**Comment by cyco130** [comment]
Thank you very much!
