### ISSUE TITLE
Add Hadmean

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#524]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Generate powerful, fully functional, ready-to-be-deployed admin apps in seconds.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://hadmean.com

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- admin
- database

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Hadmean` is available on _Best of JS_, please check.

It seems that recently we added several projects in this category of tools to generate "Admin UI" (or "Admin panels") to handle CRUD operations with "low code"... or no code at all:

- Tremor
- PayloadCMS
- Refine

So maybe we could introduce a new tag: `Admin UI`?
