### ISSUE TITLE
Add @web/test-runner and @web/dev-server

### ISSUE THREAD

**Issue by bennypowers** [michaelrambeau/bestofjs#526]
**Please briefly describe the project you'd like to add to _Best of JS_?**
@web/test-runner and @web/dev-server
**What is the URL of the project you'd like to add to _Best of JS_?**
https://modern-web.dev/
**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- Testing
- CLI
- web components
- browser automation
- dev tool

**Comment by michaelrambeau** [comment]
Hello Benny @bennypowers 
Thank you for the recommendation, so https://github.com/modernweb-dev/web repo contains the 2 packages `@web/test-runner` and `@web/dev-server`.

The only problem is that the current structure of _Best of JS_ only supports one package by repository, so we would have to choose only one, until we change to make things more flexible.

**Comment by bennypowers** [comment]
cc @web-padawan @dakmor @larsdenbakker @westbrook @thepassle

**Comment by michaelrambeau** [comment]
@bennypowers  Actually the `@web/test-runner` package was already on _Best of JS_! https://bestofjs.org/projects/web-test-runner

I will improve the tagging.

![image](https://user-images.githubusercontent.com/5546996/203054206-8ce7dbec-011a-439e-852a-3edeb129a35d.png)
