### ISSUE TITLE
Add @effect/core

### ISSUE THREAD

**Issue by tim-smart** [michaelrambeau/bestofjs#528]
A Fully-fledged functional effect system for typescript with a rich standard library

https://github.com/effect-ts/core

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [ ] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- nodejs-framework

**Comment by michaelrambeau** [comment]
Hello Tim @tim-smart 
Thank you for the recommendation, I may be missing something obvious but I cannot find any documentation.
The README.md simply says: "coming soon".
So I wonder how did you find that project? 😅 
Thank you for your help!

**Comment by tim-smart** [comment]
They have renamed the project recently: https://github.com/Effect-TS/effect
For now it is just API docs: https://effect-ts.github.io/effect/

There are several talks about it on Youtube, which is where I discovered it :)

I opened this PR, as I wasn't able to select it for the best of JS survey.

**Comment by michaelrambeau** [comment]
Hello @tim-smart thank you, that's interesting.

I really wonder how a project can have almost 1000 stars without proper documentation that just says what it does, I must me be missing something! 😄 

Anyway `Effect` will be available on _Best of JS_ very soon, thank you for the recommendation!

**Comment by michaelrambeau** [comment]
Hello @tim-smart I was about to ask you to check, as `Effect` is now available on _Best of JS_, you are too fast 😄 

I was not sure about the tagging (is it a frontend or a backend solution?) as I need to watch the video until the end, my bad!

**Comment by tim-smart** [comment]
It can be used for both front and back end.

It is generally used for writing the business logic in your apps, covering off things like dependency management, error handling etc.

**Comment by michaelrambeau** [comment]
I will add the missing tags, sorry again for the delay, somehow I lost track of that request because of the sudden flow of issues, thank you for your patience @tim-smart !
