### ISSUE TITLE
nps

### ISSUE THREAD

**Issue by wmertens** [michaelrambeau/bestofjs#529]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Better package scripts

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/sezna/nps

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

build tool

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @wmertens  thank you for the recommendation, `nps` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Wout @wmertens `nps` is now available on _Best of JS_, please check!

About the tagging, I wonder if we should create a more specific tag `NPM scripts` to cover the projects that help with managing/launching NPM scripts (projects like `npm-all`, `concurrently`, or `Wireit`, recently added to _Best of JS_)

**Comment by wmertens** [comment]
Yes, a tag would be nice, some ideas:
- `NPM scripts` as you propose
- `package scripts`: I searched for "scripts" first
- `build tooling`: "tooling" was the second thing I searched

**Comment by michaelrambeau** [comment]
Hello @wmertens sorry for the late reply!

A new tag `NPM scripts` has been added, let me know if it makes sense or if you think about more great projects that should belong to this category.

Thank you for your feedback!

https://bestofjs.org/projects?tags=npm-scripts

![image](https://user-images.githubusercontent.com/5546996/205765671-acc54193-baa9-4798-b539-7a04170eec53.png)

**Comment by wmertens** [comment]
Cool! How about adding lint-staged, husky, np?

**Comment by wmertens** [comment]
And changesets!

**Comment by michaelrambeau** [comment]
Thank you @wmertens they are legit candidates for _Best of JS_, indeed, I will add them!
Note: `husky` is already tracked by _Best of JS_, but it's under the tag `Git`.

I'm thinking about the definition of this this new tag `NPM scripts`: in my mind it was something like: "Tools to help orchestrate / coordinate NPM scripts"
With these new additions it's more like "stuff you put in your package JSON file for the workflow related to NPM scripts" 😄 
I wonder if you could come up with a good definition.

Note: I plan to show the definition of the tags somewhere in _Best of JS_ to make things more obvious.

**Comment by wmertens** [comment]
Right for me it's more about workflow and build things you put in npm, and then e.g. prettier is in a subcategory. Hmmm.

**Comment by michaelrambeau** [comment]
Hello @wmertens and thank you again for all your suggestions!

The following projects were added under the tag [NPM scripts](https://bestofjs.org/projects?tags=npm-scripts)

- `np`
- `lint-staged`
- `Changesets`
- `concurrently`
 
Tagging things properly is the most difficult task of the project so I appreciate your help!

**Comment by wmertens** [comment]
Excellent! I think this can be closed now :) thanks for your efforts, such a cool project!
