### ISSUE TITLE
Add `quasarframework/quasar` project

### ISSUE THREAD

**Issue by skiabox** [michaelrambeau/bestofjs#53]
https://github.com/quasarframework/quasar
Build responsive websites and hybrid mobile Apps (that look native!) using same code, with VueJs 2.

**Comment by michaelrambeau** [comment]
Thank you for the suggestion, it will be online soon.

**Comment by michaelrambeau** [comment]
Hello @skiabox,
It's online, check here: http://bestof.js.org/tags/mobile
