### ISSUE TITLE
Add Mitt to Best of JS

### ISSUE THREAD

**Issue by developit** [michaelrambeau/bestofjs#530]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Mitt is a popular event bus / eventemitter.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://GitHub.com/developit/mitt

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Jason @developit it's great to see you here, we already track some projects from you 😄 
(not to mention Preact of course).

`Mitt` will be available on _Best of JS_ very soon.
About the tagging, I think we could introduce a new tag, either `Event Emitter` or `Pub Sub`? (the more generic, the better, to be able to include more projects under this tag)

![image](https://user-images.githubusercontent.com/5546996/203189490-c68f3015-b09a-4327-a2a1-2f547cd2bb6f.png)

**Comment by developit** [comment]
@michaelrambeau thanks! `Pub Sub` would work and feels like it covers a nice wide spectrum of libraries.

**Comment by michaelrambeau** [comment]
Hello Jason @developit 

`Mitt` is now available on _Best of JS_, please check the new tag `PubSub`

https://bestofjs.org/projects?tags=pubsub
