### ISSUE TITLE
Add Rive to Graphics & Animations

### ISSUE THREAD

**Issue by fredericoo** [michaelrambeau/bestofjs#531]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Rive is the new standard for interactive graphics. Think Lottie, but more efficient.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://rive.app
https://github.com/rive-app/rive-react

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Animation

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
—

**Comment by michaelrambeau** [comment]
Hello @fredericoo thank you for the recommendation, `Rive` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @fredericoo `Rive` is now available on _Best of JS_, please check!
