### ISSUE TITLE
Add `nitropack` to Best of JS

### ISSUE THREAD

**Issue by danielroe** [michaelrambeau/bestofjs#532]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Nitro provides a powerful toolchain and a runtime framework from the [UnJS](https://github.com/unjs) ecosystem to build and deploy any JavaScript server, anywhere!

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/unjs/nitro
https://nitro.unjs.io/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

* nodejs-framework
* ssg
* build
* routing

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Daniel @danielroe 
Thank you but I have already added `Nitro` a few days ago.
I wonder if there is something wrong with _Best of JS_ search  engine 😅 
Thank you for your feedback!

![image](https://user-images.githubusercontent.com/5546996/203298298-1a976cd3-d58d-4a74-9399-65c5d1d6af87.png)

**Comment by danielroe** [comment]
The search on bestofjs.org seems fine - my apologies! I didn't see that I could add it in the stateofjs.com survey, but that also might be user error.

**Comment by michaelrambeau** [comment]
No problem at all Daniel, I think it was just a timing issue, because as you can see, `Nitro` is the latest addition to _Best of JS_.
