### ISSUE TITLE
Add `magic-regexp` to Best of JS

### ISSUE THREAD

**Issue by danielroe** [michaelrambeau/bestofjs#533]
**Please briefly describe the project you'd like to add to _Best of JS_?**

A compiled-away, type-safe, readable RegExp alternative

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/danielroe/magic-regexp
https://regexp.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- types
- regexp

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you Daniel @danielroe 
We need more magic ✨ in _Best of JS_!
`magic-regexp` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Daniel @danielroe  `magic-regexp` is now available on _Best of JS_, please check!

**Comment by danielroe** [comment]
Amazing - thank you ❤️
