### ISSUE TITLE
Add threlte to Best of JS

### ISSUE THREAD

**Issue by edil-it-them** [michaelrambeau/bestofjs#534]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Threlte is a renderer and component library for Svelte to build and render three.js scenes declaratively and state-driven in Svelte apps.
**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/threlte/threlte
https://threlte.xyz/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
3D, Svelte
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Edil @Rolikasi  thank you for the recommendation `Threlte` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Edil @Rolikasi `Threlte` is now available on _Best of JS_, please check!

**Comment by edil-it-them** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/44370635/203776325-c85e6941-a002-4bb4-8f33-f9dc672c349e.png">
Cant find it

**Comment by edil-it-them** [comment]
Oh I found it on Best of js website. Probably need to wait until stateofjs will reload the data

**Comment by michaelrambeau** [comment]
Yes, there is no real-time connection with _Best of JS_ data, sorry for the confusion!

![image](https://user-images.githubusercontent.com/5546996/203781722-a7eceb0b-42e4-4170-bea8-c519938a3910.png)
