### ISSUE TITLE
Add enmap

### ISSUE THREAD

**Issue by WilsontheWolf** [michaelrambeau/bestofjs#535]
**Please briefly describe the project you'd like to add to _Best of JS_?**
I would like to add the project enmap. To quote the website: "Enmap stands for "Enhanced Map", and is a data structure based on the native JavaScript Map() structure with additional helper methods from the native Array() structure. Enmap also offers persistence, which means it will automatically save everything to save to it in a database, in the background, without any additional code or delays."

For the most part, its a fairly simple to use database wrapper, that allows you to use a map-like structure to store data in node.js. 

**What is the URL of the project you'd like to add to _Best of JS_?**
[Homepage/Docs](https://enmap.evie.dev/) [GitHub](https://github.com/eslachance/enmap) [NPM](https://www.npmjs.com/package/enmap)
**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- nodejs-framework
- sql
- db

**Comment by michaelrambeau** [comment]
Hello Wilson @WilsontheWolf thank you for the recommendation, `Enmap` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Wilson @WilsontheWolf `Enmap` is available on _Best of JS_, please check!
