### ISSUE TITLE
Add Radash to Best of JS tools list (Utils)

### ISSUE THREAD

**Issue by brandonmcconnell** [michaelrambeau/bestofjs#537]
Radash is a more modern and comprehensive alternative to Lodash.
  
**Please briefly describe the project you'd like to add to _Best of JS_?**

**What is the URL of the project you'd like to add to _Best of JS_?**

* Docs: https://radash-docs.vercel.app/docs/getting-started
* Repo: https://github.com/rayepps/radash
* NPM: https://www.npmjs.com/package/radash

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Utils

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Brandon @brandonmcconnell thank you for the recommendation, `Radash` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Brandon @brandonmcconnell `Radash` is now available on _Best of JS_, please check!
