### ISSUE TITLE
Add tsup to the list of build tools

### ISSUE THREAD

**Issue by franky47** [michaelrambeau/bestofjs#538]
**Please briefly describe the project you'd like to add to _Best of JS_?**

tsup is a zero-config wrapper around fast tooling (esbuild, Rollup, SWC) to bundle TypeScript into various output formats.

**What is the URL of the project you'd like to add to _Best of JS_?**

Code: https://github.com/egoist/tsup
Documentation: https://tsup.egoist.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Building tool + Module Bundler

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello François @franky47 thank you for the recommendation, `tsup` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @franky47 `tsup` is now available on _Best of JS_, please check!

**Comment by franky47** [comment]
I've already completed the survey (with a comment about tsup), thanks!
