### ISSUE TITLE
Add Sonar to Best of JS

### ISSUE THREAD

**Issue by gabssnake** [michaelrambeau/bestofjs#539]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Open Source static analyzer for JavaScript and TypeScript code.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/SonarSource/SonarJS

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

`Linter`

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

`Code quality`, `Security`, `Static analysis`

**Comment by michaelrambeau** [comment]
Hello Gabriel @gabssnake SonarJS  is now available on _Best of JS_, please check.

I have set `eslint-plugin-sonarjs` as the NPM package name, let me know if it makes sense, thank you!

![image](https://user-images.githubusercontent.com/5546996/203873177-b7c7bd65-50f9-4ca3-9920-c4d4d44bd087.png)

**Comment by gabriel-vivas-sonarsource** [comment]
Thank you @michaelrambeau, that was super fast 💪

**Comment by gabssnake** [comment]
Thank you Michael, that was super fast 💪

**Comment by michaelrambeau** [comment]
Thank you too Gabriel, great JS projects are like my Pokémons, I want to catch them all 😆
