### ISSUE TITLE
Add `dfahlander/Dexie.js` project

### ISSUE THREAD

**Issue by dfahlander** [michaelrambeau/bestofjs#54]
https://github.com/dfahlander/Dexie.js
The most popular pure indexedDB wrapper if you search Google. Disclaimber: I am the author of it.

**Comment by michaelrambeau** [comment]
Hello @dfahlander, thank you for the suggestion, I'am adding it, it will be online very soon.

**Comment by michaelrambeau** [comment]
Hello @dfahlander, it's online, check the `Database` tag:

http://bestof.js.org/tags/db

Thank you for your support!
