### ISSUE TITLE
Add eslint-plugin-sonarjs to Best of JS

### ISSUE THREAD

**Issue by gabssnake** [michaelrambeau/bestofjs#540]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Rules for code quality and security for JavaScript and TypeScript code.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/SonarSource/eslint-plugin-sonarjs

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

`Linter`

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

`Code quality`, `Security`, `Static analysis`

**Comment by michaelrambeau** [comment]
Hello Gabriel @gabssnake 
Thank you for the suggestion.
Considering that the ESLint plugin is a kind of sub-project inside SonarJS, is it OK if we add only SonarJS to _Best of JS_?

**Comment by gabssnake** [comment]
Hi Michael @michaelrambeau :)
Sure, I think that is cool. Thanks for taking the time to consider this 👍

**Comment by michaelrambeau** [comment]
Done here: https://github.com/michaelrambeau/bestofjs/issues/539
Thank you for checking!
