### ISSUE TITLE
React-Query

### ISSUE THREAD

**Issue by rogernomen** [michaelrambeau/bestofjs#541]
**Please briefly describe the project you'd like to add to _Best of JS_?**

**What is the URL of the project you'd like to add to _Best of JS_?**

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @rogernomen
`React Query` is now called `TanStack Query`.
Maybe we should have aliases when famous projects change their name 🤔 ?
https://bestofjs.org/projects/tanstack-query

**Comment by rogernomen** [comment]
You are right @michaelrambeau and I think those aliases might help to find them in the list as you suggested
