### ISSUE TITLE
Add Yew to Front-end Frameworks

### ISSUE THREAD

**Issue by zbyju** [michaelrambeau/bestofjs#542]
**Please briefly describe the project you'd like to add to _Best of JS_?**

https://yew.rs/ - "Yew is a modern [Rust](https://www.rust-lang.org/) framework for building front-end web apps using WebAssembly"

**What is the URL of the project you'd like to add to _Best of JS_?**

- https://yew.rs/ 
- https://github.com/yewstack/yew

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

`UI Framework`

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

`WASM`

**Comment by michaelrambeau** [comment]
Hello @zbyju thank you for the recommendation, `Yew` will be available on _Best of JS_ very soon!

Note: we have already a `Web Assembly` tag: https://bestofjs.org/projects?tags=webassembly

**Comment by michaelrambeau** [comment]
Hello @zbyju `Yew` is now available on _Best of JS_, please check!
