### ISSUE TITLE
Add Houdini

### ISSUE THREAD

**Issue by jycouet** [michaelrambeau/bestofjs#543]
**Please briefly describe the project you'd like to add to _Best of JS_?**
The disappearing GraphQL client. Normalized cache, Tiny, Colocate data requirements, Magic fragments, Subscriptions, pagination and more.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://www.houdinigraphql.com/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
`Data Fetching` `GraphQL` `Caching` `Svelte`

**Comment by michaelrambeau** [comment]
Hello @jycouet thank you for the recommendation, `Houdini` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello @jycouet `Houdini` is available on _Best of JS_, please check here for example: 

https://bestofjs.org/projects?tags=svelte&sort=newest
