### ISSUE TITLE
Add ArrowJS

### ISSUE THREAD

**Issue by MystPi** [michaelrambeau/bestofjs#544]
**Please briefly describe the project you'd like to add to _Best of JS_?**
ArrowJS is "reactivity without the framework". Think of something like React, but in vanilla JS.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://arrow-js.com/
- https://github.com/justin-schroeder/arrow-js

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- DOM
- Reactive programming

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @MystPi thank you for the recommendation, `ArrowJS` will be available on _Best of JS_ very soon.

I'm tempted to tag it as a `UI framework` too, considering the scope of this tag (any library to build UI in the browser, not only heavy frameworks)... even if the motto is "reactivity without the framework" 😄

**Comment by MystPi** [comment]
I was tempted tag it as a `UI framework` too, and I think it would be fine if you did since it seems to fit well under that category.

**Comment by michaelrambeau** [comment]
Hello @MystPi `ArrowJS` is now available on _Best of JS_, please check here for example:

https://bestofjs.org/projects?tags=reactive&sort=newest

**Comment by MystPi** [comment]
Awesome, thank you!
