### ISSUE TITLE
Add Abell.js

### ISSUE THREAD

**Issue by saurabhdaware** [michaelrambeau/bestofjs#545]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Abell is a static-site-generator that uses nodejs on build-time. It is currently on v0 but v1 will be launched soon.

GitHub: https://github.com/abelljs/abell
Documentation: https://abelljs.org/

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/abelljs/abell

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

[Static site generator](https://bestofjs.org/projects?tags=ssg), [Templating](https://bestofjs.org/projects?tags=template)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Saurabh @saurabhdaware thank you for the recommendation, `Abell` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello @saurabhdaware `Abell` is now available on _Best of JS_, please check here for example:

https://bestofjs.org/projects?tags=ssg&sort=newest

**Comment by saurabhdaware** [comment]
Yay thanks! Looks great 🕺🏼
