### ISSUE TITLE
tsup

### ISSUE THREAD

**Issue by eric-burel** [michaelrambeau/bestofjs#546]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Tsup is a layer over Esbuild and Rollup that is suited to build app but also libraries (while most high-level bundlers like Vite are focused on applications only, not libraries or NPM packages).
It is fast, complete and very satisfying.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://tsup.egoist.dev/

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

(I am not the project owner)

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
building tools, types, compiler, Module - bundler
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Eric @eric-burel 
Thank you, `tsup` was requested yesterday, it's coming soon, be patient!
(we just need 48 hours because _Best of JS_ shows the daily trends)

https://github.com/michaelrambeau/bestofjs/issues/538

**Comment by eric-burel** [comment]
ah we should have coordinated ^^ awesome!

**Comment by michaelrambeau** [comment]
No problem Eric @eric-burel , did you know your project https://bestofjs.org/projects/vulcan-next was on _Best of JS_ by the way?

Keep up the great work!

**Comment by eric-burel** [comment]
That's awesome! It has a solid +0.1 starts a day haha
