### ISSUE TITLE
Add Ramda Adjunct

### ISSUE THREAD

**Issue by ajkl2533** [michaelrambeau/bestofjs#548]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Ramda Adjunct is a set of functional utilities for use with Ramda, providing a variety of useful, well-tested functions with excellent documentation. 

**What is the URL of the project you'd like to add to _Best of JS_?**
https://char0n.github.io/ramda-adjunct

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
[Functional programming](https://bestofjs.org/projects?tags=fp), [Utils](https://bestofjs.org/projects?tags=util)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Radek @ajkl2533 

Thank you for the recommendation,`Ramda Adjunct` is now available on _Best of JS_, please check!

https://bestofjs.org/projects?tags=fp&sort=newest
