### ISSUE TITLE
Add Lume

### ISSUE THREAD

**Issue by oscarotero** [michaelrambeau/bestofjs#549]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Lume is a static site generator for Deno, similar to 11ty, Hugo or Jekyll.
GitHub repository: https://github.com/lumeland/lume

**What is the URL of the project you'd like to add to _Best of JS_?**
https://lume.land

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- [Static site generator](https://bestofjs.org/projects?tags=ssg)
- [Deno](https://bestofjs.org/projects?tags=deno)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Oscar @oscarotero `Lume` is now available on _Best of JS_, please check here for example:

https://bestofjs.org/projects?tags=deno

**Comment by oscarotero** [comment]
Perfect. Thank you!
