### ISSUE TITLE
Add `openlayers/openlayers` project

### ISSUE THREAD

**Issue by IvanSanchez** [michaelrambeau/bestofjs#55]
https://github.com/openlayers/openlayers
Framework for creating geographical maps

**Comment by michaelrambeau** [comment]
Thank you @IvanSanchez , I'am adding that project, it will be online very soon.

**Comment by michaelrambeau** [comment]
Hello @IvanSanchez , that project is online too, check (again!) the `Maps` tag: http://bestof.js.org/tags/map
