### ISSUE TITLE
Add RTK Query

### ISSUE THREAD

**Issue by louisch** [michaelrambeau/bestofjs#550]
**Please briefly describe the project you'd like to add to _Best of JS_?**
RTK Query

**What is the URL of the project you'd like to add to _Best of JS_?**
<https://github.com/reduxjs/redux-toolkit/tree/master/packages/toolkit>

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Data fetching

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Louis @louisch 
RTK Query is part of `Redux Toolkit` project that is already tracked by _Best of JS_: https://bestofjs.org/projects/redux-toolkit

Maybe we need a kind of alias to be able to find `Redux Toolkit` when searching for `RTK Query`?
A similar problem happens when famous projects are renamed (E.g. React Query became "TanStack Query")

**Comment by louisch** [comment]
Hi @michaelrambeau thanks for the reply!

I think an alias could be a possible solution, however, the reason I brought up `RTK Query` is that while it is built upon `Redux Toolkit` and therefore requires `Redux Toolkit` to operate, in usage it is a fairly high level and complete data fetching solution for wrapping an API, that does not *in usage* require the use of Redux, aside from its setup code. I do understand it is part of `Redux Toolkit`, however.

I just wished to be able to specify it specifically for the "data fetching" section of the survey, because in my view it is superior to most of the other options available currently for data fetching.

**Comment by michaelrambeau** [comment]
Thank you very much Louis @louisch for the details, I didn't know you could use RTK Query without Redux.

About _Best of JS_, the fundamental problem is that GitHub repos tracked by _Best of JS_ can only be associated with one given NPM package.
But some repos include different packages that should be handled as different entries in _Best of JS_.

I have a similar problem with [Adobe Spectrum repo](https://github.com/adobe/react-spectrum) that contains `Spectrum`, `React Aria` and some other sub projects like `@internationalized/date` that was requested a few hours ago #556.

Given the fact that mono-repos architectures are popular, this is an issue we should address in the future.
