### ISSUE TITLE
Arrow JS

### ISSUE THREAD

**Issue by cdierkens** [michaelrambeau/bestofjs#551]
**Please briefly describe the project you'd like to add to _Best of JS_?**

ArrowJS is an experimental tool for programming reactive interfaces using native JavaScript. It’s not really a framework, but not less powerful than a framework either. At its core — ArrowJS is an admission that while we developers were falling in love with UI frameworks — JavaScript itself got good, really good.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://www.arrow-js.com/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

framework,state,component

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Christopher @cdierkens 
Thank you for the recommendation, actually `ArrowJS` was already requested a few hours ago... it's coming soon!

https://github.com/michaelrambeau/bestofjs/issues/544

**Comment by cdierkens** [comment]
Whoops! Sorry for the duplicate. Thanks for the reply.
