### ISSUE TITLE
Add Vis.js

### ISSUE THREAD

**Issue by mizdra** [michaelrambeau/bestofjs#552]
**Please briefly describe the project you'd like to add to _Best of JS_?**
A dynamic, browser based visualization library.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://visjs.org/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Charting, Canvas

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @mizdra thank you for the suggestion!

Vis.js is made of multiple repos so I'm going to add the most popular ones to  _Best of JS_:

- ~~`vis-graph`~~ `vis-network`
- `vis-timeline`

**Comment by mizdra** [comment]
Thanks you! That sounds good to me.

**Comment by michaelrambeau** [comment]
Hello @mizdra `vis-network` and `vis-timeline` are now available on _Best of JS_, please check!

**Comment by mizdra** [comment]
I checked it. Looks good! Thanks.
