### ISSUE TITLE
Add nodenv

### ISSUE THREAD

**Issue by mizdra** [michaelrambeau/bestofjs#553]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Manage multiple NodeJS versions.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/nodenv/nodenv

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Node.js version management

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @mizdra thank you for the recommendation, `nodeenv` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello @mizdra `nodeenv` is now available on _Best of JS_, please check here:

https://bestofjs.org/projects?tags=nvm

**Comment by mizdra** [comment]
Looks good! Thanks.
