### ISSUE TITLE
VitePress

### ISSUE THREAD

**Issue by santiagoarizti** [michaelrambeau/bestofjs#554]
**Please briefly describe the project you'd like to add to _Best of JS_?**
succesor to VuePress
**What is the URL of the project you'd like to add to _Best of JS_?**
https://vitepress.vuejs.org/
**Before submitting the request to add a new project, please check the following points:**

- [x ] The project is related to the web platform or Node.js
- [x ] The project has more than 100 stars on GitHub
- [x ] The project has thorough documentation in English
- [x ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Vue StaticSiteGenerator Markdown
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @santiagoarizti thank you for the recommendation, `VitePress` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello @santiagoarizti `VitePress` is now available on _Best of JS_, please check for example:

https://bestofjs.org/projects?tags=ssg

**Comment by santiagoarizti** [comment]
Thanks, good job 👍
