### ISSUE TITLE
@internationalized/date

### ISSUE THREAD

**Issue by jjasonlan** [michaelrambeau/bestofjs#556]
**Please briefly describe the project you'd like to add to _Best of JS_?**
@internationalized/date
Date package that is similar to the incoming Temporal API

**What is the URL of the project you'd like to add to _Best of JS_?**
https://react-spectrum.adobe.com/internationalized/date/#introduction

**Before submitting the request to add a new project, please check the following points:**

- [ ] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [ ] The project has thorough documentation in English
- [ ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Date & time

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @jjasonlan Thank you @jjasonlan for the suggestion.

As I mentioned here #550 there is an issue with mono-repos that should be handled in a different way in _Best of JS_ .

We currently track the repo https://github.com/adobe/react-spectrum as you can see here https://bestofjs.org/projects/react-spectrum but it only relates to the "React Spectrum" project.

We should be able to search for different projects even if they all belong to the same mono-repo:

- React Spectrum
- React Aria
- `@internationalized/date`
- ...
