### ISSUE TITLE
WebC

### ISSUE THREAD

**Issue by EllyLoel** [michaelrambeau/bestofjs#557]
**Please briefly describe the project you'd like to add to _Best of JS_?**
WebC is for Single File Web Components

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/11ty/webc

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Web Components, Node.js framework, 

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @EllyLoel thank you for the recommendation, `WebC` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @EllyLoel `WebC` is now available on _Best of JS_, please check here:

https://bestofjs.org/projects?tags=webcomponent&sort=newest
