### ISSUE TITLE
Add asdf

### ISSUE THREAD

**Issue by brw** [michaelrambeau/bestofjs#558]
**Please briefly describe the project you'd like to add to _Best of JS_?**

asdf is a project runtime version manager with a large plugin ecosystem.

(Although it's not JS/web-specific, I'd still like to propose to add it because of its usefulness, especially when compared with the other available Node.js version management tools. If it does need to be JS-specific I'd suggest adding https://github.com/asdf-vm/asdf-nodejs alone.)

**What is the URL of the project you'd like to add to _Best of JS_?**
https://asdf-vm.com/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Node.js version management

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @brw thank you for the recommendation!

We have a tag `Node.js version management` so that project is valid, it's just I'm not sure about what is the best repo to track on _Best of JS_, maybe https://github.com/asdf-vm/asdf-nodejs since it's the one about Node.js?

Also I'd like to know the meaning of `asdf`... i I guess it's just 4 keys easy to type on qwerty keyboards? 😄

**Comment by brw** [comment]
Yea, it might be a little strange to track the repo of a plugin of the tool, rather than the actual tool itself, since the tool is that which you directly see and use.

On the origin of the name, I also assume it was just randomly picked from the qwerty keyboard layout hahah. Apparently there's currently an open issue about documenting the origin: https://github.com/asdf-vm/asdf/issues/1369.

**Comment by michaelrambeau** [comment]
OK @brw I thought what users would like to see first on _Best of JS_ is how to use the plugin for Node.js but you are right, it's better to show the original tool, so we are going to track the main repo https://github.com/asdf-vm/asdf.

**Comment by michaelrambeau** [comment]
Hello @brw `asdf` is now available on _Best of JS_, please check here: https://bestofjs.org/projects?tags=nvm

![image](https://user-images.githubusercontent.com/5546996/204163420-2a6715d6-558e-46ed-a06d-0a631a4169e6.png)

**Comment by brw** [comment]
Thanks! Looks good to me. I suppose I can close this now.

I don't see it pop up yet on the State of JS survey (which is how I originally found out about Best of JS), but I assume that'll either sync later or won't count at all for this year.
