### ISSUE TITLE
FeathersJS

### ISSUE THREAD

**Issue by pwachara** [michaelrambeau/bestofjs#559]
**Please briefly describe the project you'd like to add to _Best of JS_?**

**What is the URL of the project you'd like to add to _Best of JS_?**

**Before submitting the request to add a new project, please check the following points:**

- [ ] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [ ] The project has thorough documentation in English
- [ ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @pwachara `Feathers` is already available on _Best of JS_, I wonder if there was something wrong with the search engine?

https://bestofjs.org/projects/feathers

It's a detail but it's called `Feathers`, not `FeathersJS` according to the site 😅

**Comment by pwachara** [comment]
Thanks Michael.

Yeah, it is the JS part that is missing!

Kind regards,

Philemon.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
