### ISSUE TITLE
Add urql

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [michaelrambeau/bestofjs#560]
**Please briefly describe the project you'd like to add to _Best of JS_?**

urql - a GraphQL data fetching alternative to the Apollo client

**What is the URL of the project you'd like to add to _Best of JS_?**

https://formidable.com/open-source/urql/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- GraphQL
- Data fetching

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Andreas @s-h-a-d-o-w `URQL` is already available on _Best of JS_: https://bestofjs.org/projects/urql

I wonder if there is something wrong with _Best of JS_ search engine?

Maybe we should add the tags `Data fetching` and `Caching` for this library.

Thank you for your feedback!

![image](https://user-images.githubusercontent.com/5546996/204063388-62b29ec0-0812-44e0-99cb-118458c63f91.png)

**Comment by s-h-a-d-o-w** [comment]
Whoops, I only looked for it in the issues here, didn't on best of JS. 😅 
Yeah, I don't know how you want to handle it, I just came here from the survey because it was missing for the data fetching question. 😊

**Comment by michaelrambeau** [comment]
Hello @s-h-a-d-o-w the tagging of `URQL` has been improved, please check again.

Thank you again for your feedback!

![image](https://user-images.githubusercontent.com/5546996/204113573-f75ec0f6-1888-46e8-b571-928f353503e8.png)

**Comment by s-h-a-d-o-w** [comment]
You know, I think there was a misunderstanding here - I thought that with 7.6K stars and 140K weekly downloads, it would be in this list.

![Screenshot_20221127-133211](https://user-images.githubusercontent.com/16936908/204138065-9a94550b-859e-4535-90a5-952bb35202a3.png)

But I guess you thought that I meant that it doesn't show up in "Other". If so - that has always been fine. 😅

**Comment by michaelrambeau** [comment]
Hello @s-h-a-d-o-w sorry for the late reply, I missed your comment!

_Best of JS_ provides the "pool" of projects available when picking a project that is not in the initial list on the screen but the initial list itself is a choice by the authors of _State of JS_, a choice that is always hard to make, sorry for the confusion!
