### ISSUE TITLE
Rive animation library

### ISSUE THREAD

**Issue by yrogovich** [michaelrambeau/bestofjs#561]
**Please briefly describe the project you'd like to add to _Best of JS_?**
[Rive](https://rive.app/) is a real-time interactive design and animation tool that helps teams create and run interactive animations anywhere. Designers and developers use our collaborative editor to create motion graphics that respond to different states and user inputs. Cross-platform export. 

**What is the URL of the project you'd like to add to _Best of JS_?**
https://rive.app/ -- main page
https://help.rive.app/ -- developer docs

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Animation, Universal

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @yrogovich `Rive` was added to _Best of JS_ a few days ago: https://bestofjs.org/projects/rive

Let me know if you can find it, thank you for the feedback!

![image](https://user-images.githubusercontent.com/5546996/204089271-d65de529-e0d0-480c-acf2-4d8f1e4ce2b7.png)
