### ISSUE TITLE
Add elm-pages rendering framework

### ISSUE THREAD

**Issue by dillonkearns** [michaelrambeau/bestofjs#562]
**Please briefly describe the project you'd like to add to _Best of JS_?**
elm-pages, a static site generator for the Elm frontend framework. The upcoming 3.0 release is similar to tools like NextJS/Remix - it provides dynamic server-side rendering and data resolving hooks.
**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/dillonkearns/elm-pages
**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Elm, Rendering Frameworks
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @dillonkearns thank you for the recommendation, `elm-pages` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello Dillon @dillonkearns `elm-pages` is now available on _Best of JS_, please check!

https://bestofjs.org/projects?tags=ssg

**Comment by dillonkearns** [comment]
Wonderful, thank you Michael!
