### ISSUE TITLE
RTK Query

### ISSUE THREAD

**Issue by rehanshaikh1823** [michaelrambeau/bestofjs#564]
**Please briefly describe the project you'd like to add to _Best of JS_?**
 data fetching library

**What is the URL of the project you'd like to add to _Best of JS_?**
https://redux-toolkit.js.org/rtk-query/overview

**Before submitting the request to add a new project, please check the following points:**

- [ &#9745;] The project is related to the web platform or Node.js
- [&#9745; ] The project has more than 100 stars on GitHub
- [&#9745;] The project has thorough documentation in English
- [&#9745;  ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
React data fetching

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @rehanshaikh1823 thank you for your interest in _Best of JS_!

FYI this request was made a few days ago: https://github.com/michaelrambeau/bestofjs/issues/550
