### ISSUE TITLE
Wails

### ISSUE THREAD

**Issue by marc136** [michaelrambeau/bestofjs#565]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Build beautiful cross-platform applications using Go. Same goal as tauri (for rust) but was started earlier and is easier to use. 

**What is the URL of the project you'd like to add to _Best of JS_?**
wails.io

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Desktop app

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Marc @marc136 thank you for the recommendation, `Wails` will be available in _Best of JS_.

I was wondering if it was a bit out of the scope of _Best of JS_ since it uses Go language but I guess it's OK because it combines web technologies... it's always hard to define the boundaries of the project 😅

**Comment by marc136** [comment]
I understand that drawing boundaries is hard, and building native apps that use the OS webview only *also* uses JS, not primarily. So that is easily something that can be discarded. 

But if tauri is on the list, then I think wails should be, too.

**Comment by michaelrambeau** [comment]
Hello Marc @marc136 `Wails` is now available on _Best of JS_, please check!

**Comment by marc136** [comment]
Great, thank you @michaelrambeau 😍
