### ISSUE TITLE
Add pathpida

### ISSUE THREAD

**Issue by nonsugarless** [michaelrambeau/bestofjs#566]
**Please briefly describe the project you'd like to add to _Best of JS_?**
TypeScript friendly internal link client for Next.js and Nuxt.js.
**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/aspida/pathpida
**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
`Next.js` `Types` `CLI`
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
`Nuxt` `Link generator`

**Comment by michaelrambeau** [comment]
Hello @nonsugarless thank you for the recommendation, `pathpida` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @nonsugarless `pathpida` is now available on _Best of JS_, please check!
