### ISSUE TITLE
react-hook-form

### ISSUE THREAD

**Issue by jzrskc** [michaelrambeau/bestofjs#567]
**Please briefly describe the project you'd like to add to _Best of JS_?**

**What is the URL of the project you'd like to add to _Best of JS_?**

**Before submitting the request to add a new project, please check the following points:**

- [ ] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [ ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by jzrskc** [comment]
react-hook-form

**Comment by michaelrambeau** [comment]
Hello @jzrskc `React Hook Form` is already available on _Best of JS_ as you can see here:


![image](https://user-images.githubusercontent.com/5546996/204238817-95cb33f1-8305-4ba9-bc62-c1ac0740b1f7.png)

I guess you couldn't find it when filling the _State of JS_ survey? Have you tried its real name `React Hook Form`?

Thank you for the feedback!
