### ISSUE TITLE
Add @formkit/auto-animate

### ISSUE THREAD

**Issue by AnthonyLzq** [michaelrambeau/bestofjs#568]
**Please briefly describe the project you'd like to add to _Best of JS_?**
[`@formkit/auto-animate`](https://www.npmjs.com/package/@formkit/auto-animate) is a library that allows you to animate tons of things doing almost nothing.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://auto-animate.formkit.com/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
`Animation`
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
`Nuxt`

**Comment by michaelrambeau** [comment]
Hello Anthony @AnthonyLzq thank you for the recommendation, `AutoAnimate` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Anthony @AnthonyLzq `AutoAnimate` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/autoanimate

**Comment by AnthonyLzq** [comment]
Thank you @michaelrambeau!
