### ISSUE TITLE
Add date-io

### ISSUE THREAD

**Issue by remy90** [michaelrambeau/bestofjs#569]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Abstraction over common JavaScript date management libraries.

npm package codecov typescript travis lerna code style: prettier

The project exposes an abstraction interface over [luxon](https://moment.github.io/luxon/), [date-fns v2](https://github.com/date-fns/date-fns), [dayjs](https://github.com/iamkun/dayjs) and [moment](https://momentjs.com/). It allows you to build any UI date or time components, while utilizing the same date management library in use within your user's project.

It simplifies timezone management, allows your code to return the exact same type that your user expects and works with specific calendar systems (e.g. [Jalali calendar](https://en.wikipedia.org/wiki/Jalali_calendar))
**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/dmtrKovalenko/date-io

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
date-io
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Remy @remy90 thank you for the recommendation, `date-io` will be available on _Best of JS_ very soon!

**Comment by remy90** [comment]
@dmtrKovalenko 🎉

**Comment by dmtrKovalenko** [comment]
Wow, thanks, that is really unexpected but proudly!

**Comment by michaelrambeau** [comment]
Hello Remy @remy90 `date-io` is now available on _Best of JS_, please check here:

![image](https://user-images.githubusercontent.com/5546996/204672817-e3101e32-298d-4619-83a7-0f9116c01bf2.png)
