### ISSUE TITLE
Add `ant-design/ant-design` project

### ISSUE THREAD

**Issue by afc163** [michaelrambeau/bestofjs#57]
https://github.com/ant-design/ant-design

https://ant.design/docs/react/introduce

An enterprise-class UI design language and React-based implementation, with a set of high-quality React components.

**Comment by michaelrambeau** [comment]
Hello @afc163 
Thank you very much for the suggestion, I'am adding `Ant Design` to bestof.js.org.
It will be online very soon.

**Comment by michaelrambeau** [comment]
Hello @afc163 
`Ant Design` project is online, check the `React UI component` tag:

http://bestof.js.org/tags/reactui

![image](https://cloud.githubusercontent.com/assets/5546996/22631489/d3a9629a-ec51-11e6-8f02-f55c91e525fb.png)

**Comment by afc163** [comment]
Thank you for doing that so soon! @michaelrambeau
