### ISSUE TITLE
Surplus

### ISSUE THREAD

**Issue by Qix-** [michaelrambeau/bestofjs#570]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Reactive programming framework using lightweight JSX, no virtual DOM, and built on top of S.js.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/adamhaile/surplus

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [ ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- [UI Framework](https://bestofjs.org/projects?tags=framework)
- [State management](https://bestofjs.org/projects?tags=state)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @Qix- thank you for the recommendation, it's a bit delicate as _Best of JS_ is not supposed to show deprecated projects (I try to filter them out as possible but I'm sure I may have missed some ones), the mission of _Best of JS_ is to help people find the projects that are "relevant" (I'm aware it's a blurry concept 😅).

In the future, the architecture of the app will change to allow tracking more projects, so there may be a way to show "deprecated" and "cold" projects.

**Comment by Qix-** [comment]
What indicates that the project is deprecated? It hasn't had a commit in a few years but the project is fully feature complete. It's still used in production, etc.

**Comment by michaelrambeau** [comment]
Oh sorry for the confusion @Qix- , I noticed you didn't check the checkbox "The project is not deprecated and actively maintained" in the checklist so I guessed it was "Deprecated", my bad!

So OK, I trust your suggestion, `Surplus` will be available on _Best of JS_ very soon (I always say that because I need at least 24 hours to be able to show the daily trends).

Your project `color` is doing well on [Best of JS](https://bestofjs.org/projects/color) by the way (in addition of all the projects you contribute for, of course!)

![image](https://user-images.githubusercontent.com/5546996/204517404-39b553de-a17a-4b20-a6cb-df0b4b4801f2.png)

**Comment by Qix-** [comment]
Oh thanks :) Cool stuff! Appreciate the effort you put into this every year!

**Comment by michaelrambeau** [comment]
Hello @Qix- `Surplus` is now available on _Best of JS_, thank you for your patience!

https://bestofjs.org/projects/surplus

**Comment by Qix-** [comment]
Thanks! That's awesome. FWIW I want to pick the project up and modernize it at some point. It works fine now and has done so without any modifications for a long, long time. Adam Haile is a fantastic engineer. However he's been rather hard to reach over the last few years (hopefully everything is okay...) and we've been in contact before about maintenance strategies and whatnot. It's been at the top of performance benchmarks for years and I really think it could have a bright future if it was given a bit of the "Frontend Framework treatment" that other frameworks receive.

Really appreciate the addition :) thanks again!

**Comment by michaelrambeau** [comment]
My pleasure 😄
