### ISSUE TITLE
Add google/wireit

### ISSUE THREAD

**Issue by e111077** [michaelrambeau/bestofjs#571]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Similar to turborepo which is listed under "Monorepo Tools" but different DX

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/google/wireit

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Whatever you put NX or turborepo under (Monorepo Tools this year)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Build Orchestrators since wireit turborepo and nx are not monorepo-specific.

**Comment by michaelrambeau** [comment]
Hello Elliot @e111077 `Wireit` is already available on _Best of JS_, under the tag `CLI`:

![image](https://user-images.githubusercontent.com/5546996/204403478-2c773312-9ccf-4228-b036-713b63fa9199.png)

It does not have the `Monorepo` tag as it's not really a tool to manage monorepos (even if it plays well with monorepos of course), let me know if it makes sense.

**Comment by e111077** [comment]
Oh awesome! Yeah I think we're seeing a new family of tools altogether since things like wireit, turborepo, Nx are not necessarily building things themselves, but rather build systems or orchestrators. Something between cli, building tool, and monorepo
