### ISSUE TITLE
elm-review should definitely be in the list of the JS projects

### ISSUE THREAD

**Issue by kraklin** [michaelrambeau/bestofjs#572]
**Please briefly describe the project you'd like to add to _Best of JS_?**
elm-review analyzes your source code, trying to recognize code that is known to cause problems. All the rules describing problematic code are written in Elm, and elm-review does not come with built-in rules; instead users are encouraged to write rules themselves and publish them as Elm packages, for everyone to benefit. 

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/jfmengels/elm-review

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
elm, liner

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
elm

**Comment by michaelrambeau** [comment]
Hello @kraklin thank you for the suggestion, `elm-review` will be available on _Best of JS_ very soon.

> elm-review should definitely be in the list of the JS projects 

I like bold statements 😄

**Comment by kraklin** [comment]
@michaelrambeau :) I'm glad to provide bold statements regarding elm-review any time

**Comment by michaelrambeau** [comment]
Hello @kraklin `elm-review` is now available on _Best of JS_, please check!
