### ISSUE TITLE
Add Nightwatch to Testing

### ISSUE THREAD

**Issue by beatfactor** [michaelrambeau/bestofjs#573]
**Please briefly describe the project you'd like to add to _Best of JS_?**
End-to-end testing framework written in Node.js and using the W3C Webdriver API.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://nightwatchjs.org

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Testing

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Andrei @beatfactor 
`Nightwatch` is already available on _Best of JS_: https://bestofjs.org/projects/nightwatch
Let me know if you can find it.
It's under the tag "Browser automation" so I will add the `Testing` tag that is missing, thank you for the feedback!

![image](https://user-images.githubusercontent.com/5546996/204673842-9c580d82-86c8-41dc-94fe-ab14f34d15fc.png)

**Comment by beatfactor** [comment]
Thanks!

**Comment by michaelrambeau** [comment]
Hello @beatfactor the `Testing` tag has been added, thank you for checking!

![image](https://user-images.githubusercontent.com/5546996/204934101-e972722a-2da4-4dcd-b66b-9546179d43ec.png)

**Comment by beatfactor** [comment]
Great, thank you!
