### ISSUE TITLE
Add Halogen UI library to Best of JavaScript

### ISSUE THREAD

**Issue by liammcdermott** [michaelrambeau/bestofjs#574]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Halogen is a type-safe library for building user interfaces in PureScript.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/purescript-halogen/purescript-halogen

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

UI Framework, Functional programming, Types

**Comment by michaelrambeau** [comment]
Hello Liam @liammcdermott thank you for the recommendation, `Halogen` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Liam @liammcdermott `Halogen` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/halogen

**Comment by liammcdermott** [comment]
Looks great, thank you for adding that Michael! If you don't mind, I'm closing this issue as I think our work here is done :)
