### ISSUE TITLE
solid-start

### ISSUE THREAD

**Issue by DutchJelly** [michaelrambeau/bestofjs#575]
**Please briefly describe the project you'd like to add to _Best of JS_?**
I think it's one of the best SSR frameworks out there. It combines many of the best practises from many different frameworks.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/solidjs/solid-start

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @DutchJelly `Solid Start` is already available on _Best of JS_, let me know if you can find it:

https://bestofjs.org/projects/solid-start
