### ISSUE TITLE
Add Analog

### ISSUE THREAD

**Issue by tutkli** [michaelrambeau/bestofjs#576]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Angular meta-framework for SSG and SSR.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/analogjs/analog

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- [Angular](https://bestofjs.org/projects?tags=angular)
- [SSG](https://bestofjs.org/projects?tags=ssg)
- [Universal](https://bestofjs.org/projects?tags=universal)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @tutkli I think you forgot to mention to mention the URL and the details about the project you'd like to see on _Best of JS_ , thank you in advance!

**Comment by tutkli** [comment]
@michaelrambeau Sorry about that, I updated the issue.

**Comment by michaelrambeau** [comment]
Thank you for the recommendation @tutkli `Analog` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello @tutkli `Analog` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/analog
