### ISSUE TITLE
idb-keyval

### ISSUE THREAD

**Issue by jon49** [michaelrambeau/bestofjs#577]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Adds promise API (key-value) to IndexDB database.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/jakearchibald/idb-keyval

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

[State management](https://bestofjs.org/projects?tags=state), [Utils](https://bestofjs.org/projects?tags=util), [Database](https://bestofjs.org/projects?tags=db), 

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @jon49 thank you for the recommendation, `idb-keyval` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Jon @jon49 `idb-keyval` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/idb-keyval
