### ISSUE TITLE
Add Ts.ED

### ISSUE THREAD

**Issue by sripwoud** [michaelrambeau/bestofjs#580]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Ts.ED

**What is the URL of the project you'd like to add to _Best of JS_?**
https://tsed.io/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Node.js Framework
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @r1oga thank you for the recommendation, `Ts.ED` will be available on _Best of JS_ very soob,

**Comment by michaelrambeau** [comment]
Hello @r1oga `Ts.ED` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/tsed
