### ISSUE TITLE
Add barrelsby to Best of JS

### ISSUE THREAD

**Issue by sripwoud** [michaelrambeau/bestofjs#581]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Barrelsby: Automatic TypeScript barrels (index.ts files) for your entire code base
**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/bencoveney/barrelsby
**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @r1oga thank you for the recommendation, it's hard to tag such a tool without being too specific, any suggestion is welcome!

**Comment by sripwoud** [comment]
Hi
What about the tags "Utils" and/or "Module - bundler"?

**Comment by michaelrambeau** [comment]
OK, thank you @r1oga  let's tag it `Utils` for now, until we find something better 😄 !
`Barrelsby` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @r1oga `Barrelsby` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/barrelsby
