### ISSUE TITLE
Neodigm 55 Landing Page UX micro-library

### ISSUE THREAD

**Issue by neodigm** [michaelrambeau/bestofjs#582]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Neodigm 55 Landing Page UX micro-library. Neodigm 55 is low-code, performant, accessible. Because it’s so easy to get started it is the perfect solution for quick landing pages, business accelerators, or event sites. Neodigm 55 is different. It's an eclectic JavaScript UX micro-library. The lightweight components come together in a unique way that makes your website playful, fun, and bounceproof. Neodigm 55 Popups are “declarative”. That means that you simply add a tag to your existing HTML. No JavaScript required. You can use JavaScript if you want however it's not necessary.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://www.thescottkrause.com/emerging_tech/neodigm55_ux_library/

**Before submitting the request to add a new project, please check the following points:**

- [x ] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub (this seems to prefer only already established libs)
- [ x] The project has thorough documentation in English https://github.com/arcanus55/neodigm55/wiki/Cheat-Sheet
- [ x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
UI Framework
Animation
Canvas
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
Web Audio
Web Apps Builder
Creative UX

**Comment by michaelrambeau** [comment]
Hello @neodigm thank you for the recommendation, it's true that for now we focus on popular libraries because the current architecture cannot support thousands of project but the situation may change soon.
