### ISSUE TITLE
Add Contember

### ISSUE THREAD

**Issue by jonasnobile** [michaelrambeau/bestofjs#583]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Contember is a platform for frontend developers to build and run bespoke backends with ease.

**What is the URL of the project you'd like to add to _Best of JS_?**
- [https://www.contember.com](https://www.contember.com)
- [https://github.com/contember](https://github.com/contember)

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Node.js, React, GraphQL, 

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @jonasNobile thank you for the recommendation,`Contember` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @jonasNobile `Contember` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/contember

**Comment by jonasnobile** [comment]
Hi @michaelrambeau thanks a lot! It looks perfect.
