### ISSUE TITLE
Pitsby inclusion

### ISSUE THREAD

**Issue by jlozovei** [michaelrambeau/bestofjs#584]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Pitsby is a docs generator for JS components - vanilla, Angular, React and/or Vue. Similar to Storybook, but smoother.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://pitsby.com/ | https://github.com/glorious-codes/glorious-pitsby

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub (77 actually :star:)
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Component Toolkit, Design System, Web Components, Documentation, Playgroud, Testing

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @jlozovei thank you for the suggestion, Pitsby will be available on _Best  of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @jlozovei `Pitsby` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/pitsby
