### ISSUE TITLE
Stylify CSS

### ISSUE THREAD

**Issue by Machy8** [michaelrambeau/bestofjs#585]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Stylify CSS is a library that uses CSS-like selectors to generate optimized utility-first CSS based on what you write.
It provides features like selectors mangling, components, variables, custom selectors, splitting css into chunks and a lot more.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://stylifycss.com

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
CSS toolkit, CSS in JS

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @Machy8 thank you for the recommendation, `Stylify` will be available on _Best of JS_ very soon!

**Comment by Machy8** [comment]
Thanks a lot!

**Comment by michaelrambeau** [comment]
Hello @Machy8 `Stylify` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/stylify

**Comment by Machy8** [comment]
@michaelrambeau All is ok. Thanks a lot!
