### ISSUE TITLE
vue3-charts

### ISSUE THREAD

**Issue by ghalex** [michaelrambeau/bestofjs#586]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Vue3-Charts is an SVG-based charting library that is very easy to use and highly customizable.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://vue3charts.org/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Vue, Charting

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @ghalex thank you for the recommendation `Vue3-Charts` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @ghalex `Vue3-Charts` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/vue3-charts
