### ISSUE TITLE
Add `cssobj/cssobj` project

### ISSUE THREAD

**Issue by futurist** [michaelrambeau/bestofjs#59]
https://github.com/cssobj/cssobj
Runtime CSS manager, Turn CSS into dynamic JS module, Stylesheet CRUD

**Comment by futurist** [comment]
Also, should add a tag named `CSS in JS`

**Comment by michaelrambeau** [comment]
Hello @futurist 
Thank you for the suggestion, I am going to add it, it will be online very soon.
About the tag, there is already a tag called `Styling React`: http://bestof.js.org/tags/react-style
Do you think I should rename it ?

**Comment by michaelrambeau** [comment]
Hello @futurist,
Your project is online, check here: http://bestof.js.org/tags/css-in-js
Thank you!
