### ISSUE TITLE
Wails v2

### ISSUE THREAD

**Issue by ghgsrt** [michaelrambeau/bestofjs#591]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Wails, essentially the Go version of Tauri (which is already  included in Best of JS).

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/wailsapp/wails

**Before submitting the request to add a new project, please check the following points:**

- [ x ] The project is related to the web platform or Node.js
- [ x ] The project has more than 100 stars on GitHub
- [ x ] The project has thorough documentation in English
- [ x ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Desktop App.

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @ghgsrt `Wails` was added a  few days ago to _Best of JS_: https://bestofjs.org/projects/wails

Let me know if you can you find it, thank you!
