### ISSUE TITLE
Wails

### ISSUE THREAD

**Issue by PiterWeb** [michaelrambeau/bestofjs#592]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Make desktop APP using the native webview and your favorite JS framework with a Go Backend

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/wailsapp/wails

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Desktop app

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @PiterWeb `Wails` was added a  few days ago to _Best of JS_: https://bestofjs.org/projects/wails

Let me know if you can you find it, thank you!
