### ISSUE TITLE
@microsoft/api-extractor

### ISSUE THREAD

**Issue by NEWESTERS** [michaelrambeau/bestofjs#594]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Typescript documentation generator

**What is the URL of the project you'd like to add to _Best of JS_?**
https://api-extractor.com

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Types, Documentation, Building Tool

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you for this one too @NEWESTERS !

So it's the same problem as in https://github.com/michaelrambeau/bestofjs/issues/593

I will contact you when I find a solution to handle monorepos in a better way.
