### ISSUE TITLE
Add the Phoenix LiveView project

### ISSUE THREAD

**Issue by ron-wolf** [michaelrambeau/bestofjs#595]
#### Please briefly describe the project you'd like to add to _Best of JS_?

_Phoenix LiveView_, a declarative & reactive Elixir framework for building interactive web applications that render HTML on-demand on the server.

#### What is the URL of the project you'd like to add to _Best of JS_?

<https://www.phoenixframework.org/>

#### Before submitting the request to add a new project, please check the following points:

- [x] The project is related to the _web platform ✅_ or Node.js
- [x] The project has [more than 100 stars](https://github.com/phoenixframework/phoenix_live_view/stargazers) on GitHub
- [x] The project has [thorough documentation](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html) in English
- [x] The project is not deprecated and [actively maintained](https://github.com/phoenixframework/phoenix_live_view/graphs/code-frequency)

#### How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)

[`Functional programming`](https://bestofjs.org/projects?tags=fp), [`UI Framework`](https://bestofjs.org/projects?tags=framework), [`Reactive programming`](https://bestofjs.org/projects?tags=reactive)

#### Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.

**Comment by michaelrambeau** [comment]
Hello Ron @ron-wolf thank you for the suggestion. It's a bit controversial as _Best of JS_ does not include backend projects written in other languages than JS/TS.
That being said I'm aware that the boundaries are blurry (for categories like Desktop app for example, there are projects
whose engine is written in another language, for testing I was asked to add _Selenium_ that is written in Java and so on...).

My main concern is that we add Phoenix LiveView (that is great, don't misunderstand me!) we could/should include any web framework that runs in PHP, Java...
I guess you come from _State of JS_ survey? Maybe there be could sections for other languages in the survey.
Anyway, back to the `Best of JS` project I run, nothing is frozen, I'm open to any suggestion.
Thank you for your understanding!
