### ISSUE TITLE
Add `ni`

### ISSUE THREAD

**Issue by Not-Jayden** [michaelrambeau/bestofjs#596]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Ni is a meta package manager that automatically detects which package manager is being used for the project you're currently in, and allows you to execute standard package manager commands using the same set of aliased commands

**What is the URL of the project you'd like to add to _Best of JS_?** https://github.com/antfu/ni

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
package

**Comment by michaelrambeau** [comment]
Hello @Not-Jayden Thank you for the recommendation, `ni` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @Not-Jayden `ni` is available on _Best of JS_, please check!

Also the tag has been renamed `Package Manager`: https://bestofjs.org/projects?tags=package

![image](https://user-images.githubusercontent.com/5546996/206604349-4edf0a0a-a9d5-409b-b9ca-f3fb29b09bf1.png)

**Comment by Not-Jayden** [comment]
Ah. I think perhaps it was an issue with the search functionality in the survey. I typed in "ni" but it only returns 5 or 6 results, and none of them were ni.

**Comment by michaelrambeau** [comment]
It's just that `ni` was not available on _Best of JS_ at the time you checked.

Let me know if this `Package Manager` tag makes sense in _Best of JS_, thank you for your feedback!
