### ISSUE TITLE
Add @antvis/x6 to Best of JS

### ISSUE THREAD

**Issue by bubkoo** [michaelrambeau/bestofjs#597]
**Please briefly describe the project you'd like to add to _Best of JS_?**

X6 is a JavaScript diagramming library that uses SVG and HTML for rendering.

**Features**
- 🌱　Easy-to-customize: based on well known SVG/HTML/CSS or React/Vue/Angular to custom nodes and edges
- 🚀　Out-of-the-box: built-in 10+ plugins, such as selection, dnd, redo/undo, snapline, minimap, etc.
- 🧲　Data-driven: base on MVC architecture, you can focus on data logic and business logic
- 💯　Highly-event-driven: you can react on any event that happens inside the graph

**What is the URL of the project you'd like to add to _Best of JS_?**
- Github: https://github.com/antvis/X6
- Sites: https://x6.antv.antgroup.com

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- [Charting](https://bestofjs.org/projects?tags=chart)
- [SVG](https://bestofjs.org/projects?tags=svg)

**Comment by michaelrambeau** [comment]
Hello @bubkoo thank you for the recommendation, do you know if the documentation in English is available, I cannot find it from https://x6.antv.antgroup.com/ ?

Thank you for your help!

**Comment by bubkoo** [comment]
@michaelrambeau Thank you for response. 
English documentation is partially available from https://x6.antv.antgroup.com/en
English README is available: https://github.com/antvis/X6/blob/master/README.en-us.md

**Comment by michaelrambeau** [comment]
Thank you @bubkoo `X6` will be available on _Best of JS_ very soon.

About the doc, clicking on the API link leads to a `404` error: https://x6.antv.antgroup.com/en/api/graph

Could you try to fix it? (or ask to fix it 😄)

**Comment by michaelrambeau** [comment]
Hello @bubkoo `X6` is available on _Best of JS_, please check here for example:

https://bestofjs.org/projects?tags=diagram&sort=newest

**Comment by bubkoo** [comment]
Hi @michaelrambeau  thanks a lot! It looks good to me.
