### ISSUE TITLE
Add ascii-progress to Best of JS

### ISSUE THREAD

**Issue by bubkoo** [michaelrambeau/bestofjs#598]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Create progress-bar(s) in the terminal.
- Support multi progress-bars.
- Relative and absolute width.
- Colorful bar and text.
- Highly customizable.

![](https://github.com/bubkoo/ascii-progress/raw/master/snapshot.gif)

**What is the URL of the project you'd like to add to _Best of JS_?**
- Github: https://github.com/bubkoo/ascii-progress

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- [Utils](https://bestofjs.org/projects?tags=util)

**Comment by michaelrambeau** [comment]
Thank you @bubkoo for that recommendation too, `ascii-progress` will be available in _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello @bubkoo `ascii-progress` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/ascii-progress

**Comment by bubkoo** [comment]
@michaelrambeau Thanks a lot. LGTM
