### ISSUE TITLE
Add `bmkmanoj/js-by-examples` project

### ISSUE THREAD

**Issue by bmkmanoj** [michaelrambeau/bestofjs#6]
https://github.com/bmkmanoj/js-by-examples
Example driven approach to learn JavaScript

**Comment by michaelrambeau** [comment]
Hello @bmkmanoj ,
Thank you for the link, "JavaScript by Examples" now belongs to bestof.js.org!

Check the "documentation" tag, here => http://bestof.js.org/tags/doc
