### ISSUE TITLE
Add @rx-angular/state library to Best of JS

### ISSUE THREAD

**Issue by matejchalk** [michaelrambeau/bestofjs#600]
**Please briefly describe the project you'd like to add to _Best of JS_?**

RxState is a lightweight, flexible, strongly typed and tested tool dedicated to reduce the complexity of managing component state in Angular.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://www.rx-angular.io/docs/state

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- [Angular](https://bestofjs.org/projects?tags=angular)
- [State management](https://bestofjs.org/projects?tags=state)
- [Reactive programming](https://bestofjs.org/projects?tags=reactive)
- [Performance](https://bestofjs.org/projects?tags=performance)
- [Functional programming](https://bestofjs.org/projects?tags=fp)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @matejchalk thank you for the recommendation, `RxAngular` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @matejchalk  `RxAngular` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/rxangular
