### ISSUE TITLE
Temporal for date management

### ISSUE THREAD

**Issue by artalar** [michaelrambeau/bestofjs#601]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Temporal is a new standart to manage dates in javascript and you could use it 2 years already by [polyfills](https://github.com/tc39/proposal-temporal#polyfills)

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/tc39/proposal-temporal#polyfills

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**date**

**Comment by michaelrambeau** [comment]
Hello @artalar just to be sure I understand the context, I guess the project you are suggesting to add in _Best of JS_ is this one: https://github.com/js-temporal/temporal-polyfill (the polyfill)

Because the main repo https://github.com/tc39/proposal-temporal is only a "proposal", it's not the library/package to track in _Best of JS_.

Thank you for your help!

**Comment by artalar** [comment]
@michaelrambeau  Can't decide :)

- there are two polifills
- as it is a native API it comes to browsers and will be available in STD soon 
<img width="497" alt="image" src="https://user-images.githubusercontent.com/27290320/206331949-4a3c3a11-a84f-4bef-a3f5-e0a40c4e3a80.png">

**Comment by michaelrambeau** [comment]
OK thank you, `Temporal Polyfill` will be available on Best of JS very soon.

**Comment by michaelrambeau** [comment]
Hello @artalar `Temporal Polyfill` is now available on _Best of JS_, please check.

https://bestofjs.org/projects/temporal-polyfill
