### ISSUE TITLE
Add reatom

### ISSUE THREAD

**Issue by artalar** [michaelrambeau/bestofjs#602]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Reatom is tiny, efficient, featured and extensible core to handle reactivity right. It has a growing ecosystem for solving popular cases in a few of lines of code.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://www.reatom.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**state**, **reactive**, **caching**, **data**, **react**

**Comment by michaelrambeau** [comment]
Hello @artalar thank you for the suggestion, `Reatom` will be available on _Best of JS_ very soon.

About the doc, it seems there is an error as the snippet in the top page imports the code from `reatom/core` instead of `@reatom/core` could you fix it (or ask to fix it) if you are in charge of this project?

**Comment by artalar** [comment]
> will be available

🔥

> fix import

What a shame! Sorry for that, fixed, thank you for the mention.

**Comment by artalar** [comment]
@michaelrambeau thank you so much for adding this!

One note, could you please replace the logo?

https://github.com/artalar/reatom/blob/v3/docs/public/logo.png

![](https://github.com/artalar/reatom/raw/v3/docs/public/logo.png)

**Comment by michaelrambeau** [comment]
Hello @artalar I forgot to tell you that `Reatom` was on _Best of JS_ but you have already found it 😄 

About the logo, could you share me a SVG file instead of a raw image? Thank you!

**Comment by artalar** [comment]
@michaelrambeau here is the svg: https://github.com/artalar/reatom/blob/v3/docs/public/favicon.svg

**Comment by michaelrambeau** [comment]
Hello @artalar OK I have uploaded the logo, please check again.

Isn't it beautiful? 😄 

![image](https://user-images.githubusercontent.com/5546996/206810192-0e05aa33-0c2c-458a-911e-9621e6c7509b.png)

**Comment by artalar** [comment]
Perfect, thank you!
