### ISSUE TITLE
wdi5

### ISSUE THREAD

**Issue by vobu** [michaelrambeau/bestofjs#603]
**Please briefly describe the project you'd like to add to _Best of JS_?**

wdi5 is the Open Source e2e test framework for OpenUI5. It is an extension ("service") to WebdriverIO.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/ui5-community/wdi5

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
SAPUI5, OpenUI5, UI5, WebdriverIO, testing

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @vobu thank you for the recommendation.

OK, considering the strong relation between _Best of JS_ and the `OpenUI5` ecosystem (https://github.com/michaelrambeau/bestofjs/issues/366, #458 ) `wdi5` will be added very soon! 😄

**Comment by michaelrambeau** [comment]
Hello @vobu `wdi5` is now available on _Best of JS_, please check.

https://bestofjs.org/projects/wdi5

**Comment by vobu** [comment]
thx! keep on rocking :)
