### ISSUE TITLE
Add DeskGap

### ISSUE THREAD

**Issue by roose** [michaelrambeau/bestofjs#604]
**Please briefly describe the project you'd like to add to _Best of JS_?**

DeskGap is a framework for building cross-platform desktop apps with web technologies (JavaScript, HTML and CSS).

**What is the URL of the project you'd like to add to _Best of JS_?**

* https://github.com/patr0nus/DeskGap/
* https://deskgap.com/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Desktop app

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @roose thank you for the suggestion!

Are you sure the project is actively maintained? I can see the latest commit is 2 years ago, which means the eternity in the JS/TS ecosystem 😄 , especially given the contenders in the category: https://bestofjs.org/projects?tags=desktop

Thank you for your feedback!

**Comment by roose** [comment]
@michaelrambeau oops, was sure that the project is actively maintained, sorry for this mistake 🙁
