### ISSUE TITLE
Minimalista Tonic

### ISSUE THREAD

**Issue by ronnisoderberg** [michaelrambeau/bestofjs#605]
**Please briefly describe the project you'd like to add to _Best of JS_?**
A Low Profile Component Framework – Stable, minimal, easy to audit, zero-dependencies and build-tool-free.
**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/socketsupply/tonic
https://tonicframework.dev/
**Before submitting the request to add a new project, please check the following points:**

- [ ] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [ ] The project has thorough documentation in English
- [ ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
#react #components #framework #jam #minimalist #user-interface #zero-dependency #ui-components #cba #jamstack #tonic #zero-dependencies
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @ronnisoderberg thank you for the suggestion, `Tonic` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @ronnisoderberg `Tonic` is available on _Best of JS_, please check!

https://bestofjs.org/projects/tonic
