### ISSUE TITLE
Add "asdf" to utilities list

### ISSUE THREAD

**Issue by vancy-pants** [michaelrambeau/bestofjs#606]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Maybe it won't apply since it's not exclusive to node/JS, but I've used it in place of `nvm` and I think it's a great tool

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/asdf-vm/asdf

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
"Other Tools" -> "Utilities"

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Alex @vancy-pants `asdf` project was added a few days ago to _Best of JS_, please check here:

https://bestofjs.org/projects?tags=nvm

Thank you for your feedback!

![image](https://user-images.githubusercontent.com/5546996/206619270-af19b2a3-5fc2-4b51-8b0f-27f9c931896c.png)
