### ISSUE TITLE
Add @js-temporal/polyfill to Best of JavaScript

### ISSUE THREAD

**Issue by joshuaNathaniel** [michaelrambeau/bestofjs#607]
**Please briefly describe the project you'd like to add to _Best of JS_?**
This polyfill was kicked off by some of the champions of the [Temporal proposal](https://github.com/tc39/proposal-temporal).

**What is the URL of the project you'd like to add to _Best of JS_?**
https://www.npmjs.com/package/@js-temporal/polyfill

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
[Date & time](https://bestofjs.org/projects?tags=date)
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
Proposal

**Comment by michaelrambeau** [comment]
Hello @joshuaNathaniel thank you for the suggestion, `Temporal Polyfill` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello @joshuaNathaniel  `Temporal Polyfill` is now available on _Best of JS_, please check.

https://bestofjs.org/projects/temporal-polyfill

**Comment by joshuaNathaniel** [comment]
🥳
