### ISSUE TITLE
Add Moonrepo to the list of monorepo tools

### ISSUE THREAD

**Issue by ScarletFlash** [michaelrambeau/bestofjs#608]
**Please briefly describe the project you'd like to add to _Best of JS_?**
A build system and repo management tool for the web ecosystem, written in Rust.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://moonrepo.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
CLI, Building tool, Utils, Performance, Compiler, Queue, File system, Logging, Caching, Graph, Monorepo, NPM scripts, Notification, Dev tool, Node.js version management, Configuration, Package Manager, Process management, Git, Resource loader, Statistics, Worker thread, Workflow automation

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @ScarletFlash `Moon` is already tracked by _Best of JS_:

https://bestofjs.org/projects/moon

![image](https://user-images.githubusercontent.com/5546996/206879873-ecbd464e-3b7f-4b75-97a8-8adbae9ef32d.png)

Let me know if you can find it, thank you for the feedback!
