### ISSUE TITLE
Add Capri

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#609]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Capri is a static site generator that supports partial hydration, also known as [islands architecture](https://jasonformat.com/islands-architecture/), as well as live CMS previews that don't require SSR or a build-step.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://capri.build

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Static site generator
- CMS

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat thank you for the recommendation!
How do you know about all these cool projects before everybody 😄 ?

**Comment by xeusteerapat** [comment]
@michaelrambeau not really hahaha 😄, maybe I followed many great TS/JS developers on Twitter and GitHub. They share many cool projects they're building. And also newsletters ([Javascript](https://javascriptweekly.com/), [Node.js](https://nodeweekly.com/) and [React status](https://react.statuscode.com/)) are great too.

**Comment by michaelrambeau** [comment]
Yes, the `*weekly` newsletters are a great source, a lot of additions come from here indeed 😅

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Capri` is available on _Best of JS_, please check.

https://bestofjs.org/projects/capri

We might need a new tag [Partial hydration](https://ajcwebdev.com/2021/11/22/what-is-partial-hydration-and-why-is-everyone-talking-about-it) (or "Islands"?) as the topic has been hot recently.
