### ISSUE TITLE
Add `egoist/vbuild` project

### ISSUE THREAD

**Issue by egoist** [michaelrambeau/bestofjs#61]
https://github.com/egoist/vbuild
Refined webpack development experience for Vue.js

**Comment by michaelrambeau** [comment]
@egoist Thank you for the suggestion, your project will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello @egoist , it's online.

You have now 3 projects on bestof.js.org!

![image](https://cloud.githubusercontent.com/assets/5546996/23088191/82cdd250-f5bd-11e6-83ca-cb688784b4fd.png)

**Comment by egoist** [comment]
thanks

**Comment by michaelrambeau** [comment]
Hello @egoist ,
It seems that you changed the project name, now it's called `Poi`, can you confirm?
Thank you in advance!

**Comment by egoist** [comment]
ah yes 👌
