### ISSUE TITLE
Add Mo.js

### ISSUE THREAD

**Issue by FlipFloop** [michaelrambeau/bestofjs#610]
**Please briefly describe the project you'd like to add to _Best of JS_?**
An animation library made with CoffeeScript.

**What is the URL of the project you'd like to add to _Best of JS_?**
[https://mojs.github.io/](https://mojs.github.io/)

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Victor @FlipFloop thank you for the recommendation.

`mo.js` was already tracked by _Best of JS_ but there was a bug when trying to open the project details page.

I have just fixed it, can you check if it works for you too?

https://bestofjs.org/projects/mojs
