### ISSUE TITLE
Bolt

### ISSUE THREAD

**Issue by steve-taylor** [michaelrambeau/bestofjs#613]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Bolt - Alternative to yarn/npm workspaces. It guarantees dependency hoisting at the root.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/boltpkg/bolt

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

* Monorepo
* Package Manager

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @steve-taylor thank you for the recommendation.

I checked the project status and found this issue https://github.com/boltpkg/bolt/issues/294

...where you added the latest comment 😄 

So from what you said it seems the project should be tracked by _Best of JS_ despite the lack of activity?
