### ISSUE TITLE
Appsmith

### ISSUE THREAD

**Issue by Rishabhkaul** [michaelrambeau/bestofjs#616]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Open source framework to build UI over databases, REST API & GraphQL. Drag and drop pre-built react components, connect to  any datasource and write JS anywhere. 

**What is the URL of the project you'd like to add to _Best of JS_?**
https://appsmith.com, https://github.com/appsmithorg/appsmith

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
React, GraphQL, Drag and Drop, Dashboard, Visual Programming,

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @Rishabhkaul thank you for the suggestion.

It's a bit controversial because in principle we don't track in _Best of JS_ projects whose backend runs in another language than JS/TS, the main reason being that if we did that there would be a lot of projects missing in _Best of JS_, I'm thinking about https://github.com/appwrite/appwrite that was requested a few months ago, for example.

**Comment by Rishabhkaul** [comment]
@michaelrambeau Understood. We actually have [RTS](https://github.com/appsmithorg/appsmith/tree/release/app/rts) (real time service), which is written in TS & runs on NodeJS. But it’s arguably a smaller portion of Appsmith and is not the dominant language on the server. The users ofcourse us JS extensively in Appsmith to build their applications, but I see your point.

**Comment by michaelrambeau** [comment]
Thank you for your understanding, we may change the scope and revisit the question in the future, of course, nothing is frozen 😄
