### ISSUE TITLE
Add ffmpeg.wasm

### ISSUE THREAD

**Issue by gamtiq** [michaelrambeau/bestofjs#617]
**Please briefly describe the project you'd like to add to _Best of JS_?**

ffmpeg.wasm is a pure Webassembly / Javascript port of FFmpeg. It enables video & audio record, convert and stream right inside browsers.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/ffmpegwasm/ffmpeg.wasm

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Video

**Comment by michaelrambeau** [comment]
Hello Denis @gamtiq `ffmpeg.wasm` is now available on _Best of JS_, please check!
