### ISSUE TITLE
Add Mutative

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#618]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Efficient immutable updates, 10x faster than Immer by default, even faster than naive handcrafted reducer.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/unadlib/mutative

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Utils
- Data structure

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat I forgot to tell you that Mutative is available on _Best of JS_, thank you for the recommendation, as always!
