### ISSUE TITLE
Add `video-react/video-react` project

### ISSUE THREAD

**Issue by JimLiu** [michaelrambeau/bestofjs#62]
https://github.com/video-react/video-react
This is the best html5 video component for React

**Comment by michaelrambeau** [comment]
Hello @JimLiu 
Thank you for the suggestion, I'm adding that project, it will be available soon on bestof.js.org.

**Comment by michaelrambeau** [comment]
Hello @JimLiu ! It's online: http://bestof.js.org/tags/video
