### ISSUE TITLE
Add Danger.js

### ISSUE THREAD

**Issue by av** [michaelrambeau/bestofjs#621]
**Please briefly describe the project you'd like to add to _Best of JS_?**

- Danger runs after your CI, automating your team's conventions surrounding code review.

**What is the URL of the project you'd like to add to _Best of JS_?**

- https://github.com/danger/danger-js

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- Linter
- Dev tool

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

---

Also wanted to use this chance to express my gratitude for bestofjs.org, thank you so much!

**Comment by michaelrambeau** [comment]
Hello Ivan @av thank you for the recommendation, `Danger.js` will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Hello Ivan @av `Danger` is available on _Best of JS_, please check!

**Comment by av** [comment]
Yup, seen it live just an hour ago, thank you so much!
