### ISSUE TITLE
Add Drizzle ORM

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#622]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Drizzle ORM is a TypeScript ORM for SQL databases designed with maximum type safety in mind.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/drizzle-team/drizzle-orm

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- ORM
- SQL

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Drizzle ORM` is available on _Best of JS_, please check!

https://bestofjs.org/projects/drizzle-orm
