### ISSUE TITLE
Add Vidstack

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#624]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Open-source, accessible, and declarative player UI framework. Completely customizable, lightweight, rich with events and state management hooks.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://www.vidstack.io/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Video
- Web component

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat thank you for the recommendation, Vidstack is now available on _Best of JS_, please check.

https://bestofjs.org/projects/vidstack
