### ISSUE TITLE
Add boxyhq/saas-starter-kit

### ISSUE THREAD

**Issue by devkiran** [michaelrambeau/bestofjs#625]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Enterprise SaaS Starter Kit - Kickstart your enterprise app development with Next.js SaaS Starter Kit

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/boxyhq/saas-starter-kit

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Next.js, React, Boilerplate

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @devkiran thank you for the recommendation, `SaaS Starter Kit` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/saas-starter-kit

**Comment by devkiran** [comment]
Thank you @michaelrambeau
