### ISSUE TITLE
contentlayer

### ISSUE THREAD

**Issue by ansango** [michaelrambeau/bestofjs#626]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Contentlayer is a content SDK that validates and transforms your content into type-safe JSON data you can easily import into your application.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://www.contentlayer.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
CMS, Markdown, Types, JSON
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @ansango thank you for the recommendation!

`Contentlayer` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/contentlayer

**Comment by ansango** [comment]
Thanks for your awesome job! Best of JS is super!!
