### ISSUE TITLE
Add `repeale/time-series-clustering` project

### ISSUE THREAD

**Issue by repeale** [michaelrambeau/bestofjs#63]
https://github.com/repeale/time-series-clustering
Time Series Based Clustering in JavaScript

**Comment by michaelrambeau** [comment]
Hello @repeale , thank you for the suggestion.
Is there a way you suggest to understand what "Time Series Based Clustering" means ?
And how it could be used to solve real world problems ?

I did a quick search but I guess you know good resource to understand the concept.
Maybe you could add some information in the README.md, even if you target people who are already familiar with the concept.

Thank you for your understanding!
