### ISSUE TITLE
Add abitype to Best of JS

### ISSUE THREAD

**Issue by tmm** [michaelrambeau/bestofjs#630]
**Please briefly describe the project you'd like to add to _Best of JS_?**

[ABIType](https://abitype.dev) is a TypeScript library for converting JSON ABIs to TypeScript primitives as runtime and type-level.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://abitype.dev
https://github.com/wagmi-dev/abitype

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Blockchain
Types

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @tmm thank you for the recommendation `ABIType` is now available on _Best of JS_, please check.

https://bestofjs.org/projects/abitype

**Comment by tmm** [comment]
Legend thanks!
