### ISSUE TITLE
Add viem to Best of JS

### ISSUE THREAD

**Issue by tmm** [michaelrambeau/bestofjs#631]
**Please briefly describe the project you'd like to add to _Best of JS_?**

viem is a library for sending and receiving data on Ethereum.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://viem.sh
https://github.com/wagmi-dev/viem

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Blockchain
Web3

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello again @tmm :)

`viem` is also available on _Best of JS_, please check this too.

https://bestofjs.org/projects/viem
