### ISSUE TITLE
Add Rspack

### ISSUE THREAD

**Issue by skywalker512** [michaelrambeau/bestofjs#634]
**Please briefly describe the project you'd like to add to _Best of JS_?**
A fast Rust-based web bundler 

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/web-infra-dev/rspack
https://www.rspack.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
build module
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
none

**Comment by michaelrambeau** [comment]
Hello @skywalker512 thank you for the suggestion, `Rspack` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/rspack

**Comment by poozhu** [comment]
> Hello @skywalker512 thank you for the suggestion, `Rspack` is now available on _Best of JS_, please check!
> 
> https://bestofjs.org/projects/rspack

The correct **Rspack** npm address is https://www.npmjs.com/package/@rspack/core

**Comment by michaelrambeau** [comment]
Hello @poozhu ! The package name has been fixed, please check again, thank you!

![image](https://github.com/user-attachments/assets/69c6d14e-d9d5-4384-8074-52cfc8ff6fd9)
