### ISSUE TITLE
Add Superflare

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#635]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- A full-stack toolkit for Cloudflare Workers.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://superflare.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- ORM
- Full-stack framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat that's interesting, I have to investigate about Cloudflare Workers, as it seems to be great stack.

I wonder why it should be classified as a "Full stack framework" in Best of JS, as we use this tag for tools to build both the frontend and the backend of web applications, how does Superflare relates to the frontend?

**Comment by xeusteerapat** [comment]
@michaelrambeau Honestly, it is quite confusing they mentioned in their doc that Superflare is not a full-stack framework. But in the GitHub repository, they add the tag with full-stack. So, I followed their repository. Here is the [example](https://github.com/jplhomer/superflare/tree/main/examples/) with Remix

**Comment by michaelrambeau** [comment]
OK @xeusteerapat `Superflare` is now available on _Best of JS_.

About the tagging: I added `Queue` and `Authentication / Authorization` as job processing and authentication are included features. Please check!

https://bestofjs.org/projects/superflare
