### ISSUE TITLE
Add Orchid ORM

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#636]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Postgres ORM, query builder, migration tool. First-class TypeScript support.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://orchid-orm.netlify.app/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- ORM
- SQL

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat for all these ORM libraries that play well with TypeScript!

`Orchid ORM` is now available on _Best of JS_.
