### ISSUE TITLE
Add `docsify` project 

### ISSUE THREAD

**Issue by QingWei-Li** [michaelrambeau/bestofjs#64]
https://github.com/QingWei-Li/docsify

A magical documentation site generator.

**Comment by michaelrambeau** [comment]
@QingWei-Li Thank you for the suggestion.

Your project is very trendy right now!

![image](https://cloud.githubusercontent.com/assets/5546996/23210097/6ec649e2-f93f-11e6-9d10-268be2ecec1a.png)

It will be online very soon.

**Comment by michaelrambeau** [comment]
Hello @QingWei-Li 

Your project is online => http://bestof.js.org/tags/doc

![image](https://cloud.githubusercontent.com/assets/5546996/23335231/1e37ae28-fbf4-11e6-93e2-6166a12e9133.png)

**Comment by QingWei-Li** [comment]
Cool!
Thanks.
