### ISSUE TITLE
Add Pyodide to Best of JS

### ISSUE THREAD

**Issue by bluehat974** [michaelrambeau/bestofjs#641]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Pyodide is a Python distribution for the browser and Node.js based on WebAssembly

**What is the URL of the project you'd like to add to _Best of JS_?**
https://pyodide.org/en/stable/
https://github.com/pyodide/pyodide

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Web Assembly
Utils
Data analysis (not sure but Python has large list of Data Analysis tools)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
Python ?

**Comment by michaelrambeau** [comment]
Thank you for the suggestion Audrien @bluehat974 , `Pyodide` is now available on _Best of JS_.

https://bestofjs.org/projects/pyodide
