### ISSUE TITLE
Add Farm

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#643]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Super fast web build tool written in Rust

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://farm-fe.github.io/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Building tool

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Farm` is now available on _Best of JS_.

https://bestofjs.org/projects/farm

Maybe it's time to introduce a new tag for projects written in Rust.
