### ISSUE TITLE
Add GraphQL Inspector to Best of JS

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#646]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Validate schema, get schema change notifications, validate operations, find breaking changes, look for similar types, schema coverage

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://the-guild.dev/graphql/inspector

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- GraphQL

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat thank you for the recommendation, `GraphQL Inspector` is now availalble on _Best of JS_.

https://bestofjs.org/projects/graphql-inspector
