### ISSUE TITLE
Add discord-player to Best of Javascript

### ISSUE THREAD

**Issue by twlite** [michaelrambeau/bestofjs#647]
**Please briefly describe the project you'd like to add to _Best of JS_?**

The project I'd like to add is called [discord-player](https://github.com/Androz2091/discord-player), a node.js package to build discord music bots.

**What is the URL of the project you'd like to add to _Best of JS_?**
GitHub: https://github.com/Androz2091/discord-player
npm: https://npm.im/discord-player
Website: https://discord-player.js.org

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- nodejs-framework
- bot
- audio
- queue

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
- voip

**Comment by michaelrambeau** [comment]
Hello @skdhg thank you for the suggestion, `Discord Player` will be available on _Best of JS_ very soon.

About the tagging, note that `Node.js frameworks` is more for generic backend Note,js solutions and `Queues` relates to the processing of background jobs.

**Comment by twlite** [comment]
> Hello @skdhg thank you for the suggestion, `Discord Player` will be available on _Best of JS_ very soon.
> 
> About the tagging, note that `Node.js frameworks` is more for generic backend Note,js solutions and `Queues` relates to the processing of background jobs.

That sounds good, maybe a new voip tag would be suitable for this? audio and voip since it's the major aspect of that framework??

**Comment by michaelrambeau** [comment]
Hello @skdhg `Discord Player` is now available on _Best of JS_, please check!

![image](https://user-images.githubusercontent.com/5546996/231308766-3bf62a30-a7cf-4db1-9d45-8a74ea418779.png)


We could introduce a new tag `VoIP` if we find at least another project that belongs to this tag maybe?

**Comment by twlite** [comment]
> Hello @skdhg `Discord Player` is now available on _Best of JS_, please check!

Thank you 😊 


> We could introduce a new tag `VoIP` if we find at least another project that belongs to this tag maybe?

Sure no problem
