### ISSUE TITLE
Add Modern.js

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#648]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Modern.js is a web engineering system, including a web framework, a npm package solution and a documentation site solution.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://modernjs.dev/en

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- React
- Node.js framework
- Building tool

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat 
`Modern.js` is now available of _Best of JS_ please check.
Do you think it can be considered as a "React meta framework", a contender of Next.js and Remix?

**Comment by xeusteerapat** [comment]
@michaelrambeau Yes, I think so. Based on their documentation also mentioned how to create a routing, data fetching, etc. Pretty much the same as Next.js and Remix.
