### ISSUE TITLE
Add `zuiidea/antd-admin` project

### ISSUE THREAD

**Issue by JuelChiang** [michaelrambeau/bestofjs#65]
https://github.com/zuiidea/antd-admin
sdfsdf

**Comment by michaelrambeau** [comment]
Hello @JuelChiang,
What is the project about? I don't understand your comment ;)

> sdfsdf

If you want me to add the project to bestof.js.org, is it possible to add documentation in English?

**Comment by JuelChiang** [comment]
Sorry for typo 😅 @michaelrambeau
