### ISSUE TITLE
Add Nitrogql

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#651]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Nitrogql is a toolchain for using GraphQL with TypeScript. It can generate TypeScript types from your GraphQL schema and queries and also provides static checking for your queries.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://nitrogql.vercel.app/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- GraphQL
- Types

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you for the recommendation @xeusteerapat , `nitrogql` is now available on Best of JS

https://bestofjs.org/projects/nitrogql
