### ISSUE TITLE
Add T3 Env to Best of JS

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#657]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Deploying your app with invalid environment variables is a hassle. This package helps you to avoid that.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://env.t3.gg/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Configuration
- Validation

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
@xeusteerapat Thank you for the recommendation, T3 Env is the hottest project of the day on _Best of JS_!

![image](https://user-images.githubusercontent.com/5546996/235327773-b55e2ca1-d3ce-49f1-b02e-ffe930b43836.png)
