### ISSUE TITLE
Add TanStack Form

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#658]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Powerful and type-safe form state management for the web. TS/JS, React Form, Solid Form, Svelte Form and Vue Form.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://tanstack.com/form/latest

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Form
- React
- Vue
- Solid
- Svelte

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat for the recommendation, about the TanStack, we have never enough! 😄 

https://bestofjs.org/projects/tanstack-form
