### ISSUE TITLE
add winkNLP

### ISSUE THREAD

**Issue by rachnachakraborty** [michaelrambeau/bestofjs#659]
**Please briefly describe the project you'd like to add to _Best of JS_?**
WinkNLP is a JavaScript library for Natural Language Processing (NLP). Designed specifically to make development of NLP applications easier and faster, winkNLP is optimized for the right balance of performance and accuracy. WinkNLP with full [Typescript support](https://github.com/winkjs/wink-nlp/blob/master/types/index.d.ts), runs on Node.js and browsers.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/winkjs/wink-nlp

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
text-processing
ml

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
nlp

**Comment by michaelrambeau** [comment]
Hello @rachnachakraborty thank you for the recommendation, `winkNLP` will be availalble on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
Hello @rachnachakraborty `winkNLP` is now available on _Best of JS_, please check.

https://bestofjs.org/projects/winknlp

**Comment by rachnachakraborty** [comment]
Hello @michaelrambeau 

We are delighted to be part of `Best of JS`

Many Thanks!

Best,
Rachna
