### ISSUE TITLE
Add `vazco/uniforms` project

### ISSUE THREAD

**Issue by radekmie** [michaelrambeau/bestofjs#66]
https://github.com/vazco/uniforms
IMHO mature and popular enough to be listed in here.

**Comment by michaelrambeau** [comment]
Hello @radekmie 
Thank you, that project will be online very soon.

**Comment by michaelrambeau** [comment]
Hello @radekmie, the project is online, as you can see here: http://bestof.js.org/tags/reactui

**Comment by radekmie** [comment]
Great!
