### ISSUE TITLE
Add Lucia-Auth

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#660]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Lucia is a simple and flexible user and session management library that provides an abstraction layer between your app and your database. It's bare-bones by design, keeping everything easy to use and understand.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://lucia-auth.com/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Authentication / Authorization
- Next.js
- Svelte
- Astro

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Funny thing: we have another project called `Lucia` on _Best of JS_: https://lucia.js.org/ that has nothing to do with that one!

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat Both Lucia projects are on _Best of JS_, please check!

![image](https://user-images.githubusercontent.com/5546996/236191384-4cf650af-725d-4a0a-8508-0add449e0496.png)
