### ISSUE TITLE
Add Orval

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#661]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Generate, valid, cache and mock in your frontend applications all with your OpenAPI specification.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://orval.dev/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Data fetching
- Codegen

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Orval` is now available on _Best of JS_ and I've added a new tag `OpenAPI` for projects related to OpenAPI / Swagger spec.

https://bestofjs.org/projects?tags=openapi

Please let lme know if you think about existing projects that should be under this tag, thank you!
