### ISSUE TITLE
Add KV.js

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#664]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Advanced in-memory caching module for JavaScript.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/HeyPuter/kv.js

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Caching
- Database

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `KV.js` is now available on _Best of JS_.

I have introduced a new tag `Key-Value` for projects related to Key-Value storage: https://bestofjs.org/projects?tags=kv

Thank you for your feedback!
