### ISSUE TITLE
Add AFFiNE

### ISSUE THREAD

**Issue by himself65** [michaelrambeau/bestofjs#669]
**Please briefly describe the project you'd like to add to _Best of JS_?**

AFFiNE is a next-gen knowledge base that brings planning, sorting and creating all together. Privacy first, open-source, customizable app.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/toeverything/AFFiNE

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
React, Desktop App, Notion Alternative

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @Himself65 thank you for the suggestion, `Affine` will be available on _Best of JS_ very soon!

I wanted to check the online demo https://app.affine.pro and I wonder if it's compatible with Firefox as the page gets stuck ("Page is loading" with an error message in the console `Uncaught (in promise) TypeError:`), but it works in Chrome

**Comment by himself65** [comment]
Currently we don’t have much time on browser compatibility. You can try out desktop version with full features.

**Comment by michaelrambeau** [comment]
OK thank you for the quick feedback!

About the tagging, I wonder if we need a new tag for "open source alternatives to products", I'm thinking about projects like: 

- https://bestofjs.org/projects/nocodb (Airtable alternative)
- https://bestofjs.org/projects/supabase (Firebase alternative)

but I cannot find a good tag name 😆, so any help is appreciated!

**Comment by michaelrambeau** [comment]
Hello @Himself65 `Affine` is available on _Best of JS_, please check!

https://bestofjs.org/projects/affine
