### ISSUE TITLE
Add VanJS

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#677]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- VanJS (Vanilla JavaScript): World's smallest reactive UI framework

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://vanjs.org/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub (9 to go)
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- UI Framework
- Reactive programming

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `VanJS` is available on _Best of JS_, I think we both read "JavaScriptWeekly" carefully 😄 

https://bestofjs.org/projects/vanjs
