### ISSUE TITLE
Add Tailwind Variants

### ISSUE THREAD

**Issue by gijsbotje** [michaelrambeau/bestofjs#681]
**Please briefly describe the project you'd like to add to _Best of JS_?**
The power of Tailwind combined with a first-class variant API.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/nextui-org/tailwind-variants

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Utils, TailwindCSS

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @gijsbotje thank you for the suggestion, `Tailwind Variants` will be available on _Best of JS_ very soon!

Interestingly I added `CVA` a few days ago.

Also note that I'm working on brand new _Best of JS_ app, built with Next.js 13 HeadlessUI and TailwindCSS, so I'm interested in the NextUI migration from Stitches to TailwindCSS!

**Comment by gijsbotje** [comment]
The addition of CVA triggered me to add Tailwind Variants 😄 I'm not affiliated by the way.

Next 13 with TW is a great combo, and with Tailwind Variants or CVA the creation and management of components is way better.

Can we see the progress of the new app or even contribute?

**Comment by michaelrambeau** [comment]
Hello @gijsbotje `Tailwind Variants` is available on _Best of JS_ and I've added a new tag called `ClassName`:

https://bestofjs.org/projects?tags=classname

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/39c5c078-54b3-40df-b939-49ee10431078)

Let me know if it makes sense.

About the Next.js 13 app, I will try to share the link as soon as possible, the difficult part is to implement the search features as everything happens in the browser, for the current version. Stay tuned and thank you for your interest!
