### ISSUE TITLE
https://ui.shadcn.com/

### ISSUE THREAD

**Issue by skiabox** [michaelrambeau/bestofjs#688]
**Please briefly describe the project you'd like to add to _Best of JS_?**

React js hi library.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://ui.shadcn.com/

**Before submitting the request to add a new project, please check the following points:**

- [ ] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [ ] The project has thorough documentation in English
- [ ] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @skiabox thank you for the recommandation, `shadcn/ui` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/shadcn-ui
