### ISSUE TITLE
Add `iview/iview` project

### ISSUE THREAD

**Issue by otabekgb** [michaelrambeau/bestofjs#69]
https://github.com/iview/iview
I couldn't find this one on your site. It is trending at the moment.

**Comment by michaelrambeau** [comment]
Hello @otabekgb 
Thank you for the recommendation.
Unfortunately there is no English translation for that project.
The Github page says the translation is "coming soon".
Do you know when the English translation is available?

**Comment by otabekgb** [comment]
I opened a new issue on iview site for English docs

**Comment by icarusion** [comment]
Hi, iView just release an alpha version to support Vue.js 2, the doc of iView is here: https://github.com/iview/iview-doc we plane upgrade to support iView 2, after that, we will translate to English.

**Comment by michaelrambeau** [comment]
👍  Great, `iview` project will be added as soon as some documentation in English is available, thank you!

**Comment by michaelrambeau** [comment]
Hello @otabekgb 
`iview` project is now available on bestof.js.org.
http://bestof.js.org/tags/vue
Sorry for the delay!
