### ISSUE TITLE
Add Zedux

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#699]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Zedux is a multi-paradigm state management tool that features a powerful composable store model wrapped in a DI-driven atomic architecture.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://omnistac.github.io/zedux/blog/zedux-is-this-the-one

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- State management
- React

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat we have never enough state management for React 😄 

https://bestofjs.org/projects/zedux
