### ISSUE TITLE
Add ESLint Plugin Perfectionist

### ISSUE THREAD

**Issue by azat-io** [michaelrambeau/bestofjs#700]
**Please briefly describe the project you'd like to add to _Best of JS_?**

ESLint plugin for sorting objects, imports, types, enums, JSX props, etc.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/azat-io/eslint-plugin-perfectionist

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Linter, Utils

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Maybe Code quality

**Comment by michaelrambeau** [comment]
Hello @azat-io thank you for the suggestion.

`Perfectionist` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/perfectionist
