### ISSUE TITLE
Add `ai`

### ISSUE THREAD

**Issue by jaredpalmer** [michaelrambeau/bestofjs#704]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Vercel AI SDK
**What is the URL of the project you'd like to add to _Best of JS_?**
sdk.vercel.ai/docs
**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Jared @jaredpalmer thank you for the recommendation, `Vercel AI SDK` will be available on _Best of JS_ very soon!

**Comment by michaelrambeau** [comment]
@jaredpalmer `Vercel AI SDK` is now available on _Best of JS_ and it's one of the hottest projects of the day, congratulations!

https://bestofjs.org/projects/vercel-ai-sdk

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/6547afd5-ab67-4a43-8604-9b19661b67cb)
