### ISSUE TITLE
Add Kuma-UI

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#705]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- 🐻‍❄️ zero-runtime CSS-in-JS with type-safe utility props

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://www.kuma-ui.com/docs/introduction

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- CSS in JS
- React

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat a few days ago, `Panda CSS` from the great Chakra team  was added and now we have another bear... same topic, same animal... is it a coincidence? 🐻 🧸 😄 

Thank for your thoughts!

https://bestofjs.org/projects/kuma-ui
