### ISSUE TITLE
Add reactish-state

### ISSUE THREAD

**Issue by szhsin** [michaelrambeau/bestofjs#711]
**Please briefly describe the project you'd like to add to _Best of JS_?**

- Simple, decentralized(atomic) state management for React

**What is the URL of the project you'd like to add to _Best of JS_?**

- https://github.com/szhsin/reactish-state

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- React
- State management
- Redux

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @szhsin thank you for the 3 projects you suggested today, they will be available on _Best of JS_ very soon!

**Comment by szhsin** [comment]
Awesome! Thank you @michaelrambeau

**Comment by michaelrambeau** [comment]
Thank you for your patience @szhsin !

`Reactish-State` is now available on _Best of JS_, please check.

https://bestofjs.org/projects/reactish-state
