### ISSUE TITLE
Add camaro

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#717]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- camaro is an utility to transform XML to JSON, using Node.js binding to native XML parser pugixml, one of the fastest XML parser around.

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/tuananh/camaro

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- XML

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `camaro` was already on _Best of JS_, let me know if there is any bug with the search feature, just in case :)

https://bestofjs.org/projects/camaro

**Comment by xeusteerapat** [comment]
Hmm, I probably spelled it wrong 😅
