### ISSUE TITLE
Add `sanctuary-js/sanctuary` project

### ISSUE THREAD

**Issue by selvacodes** [michaelrambeau/bestofjs#72]
https://github.com/sanctuary-js/sanctuary
Functional programming

**Comment by michaelrambeau** [comment]
Hello @selvacodes 
OK, thank you for the recommendation, it will be online soon!

**Comment by michaelrambeau** [comment]
Hello @selvacodes 

The project is online, check the **"Functional programming"** tag:

http://bestof.js.org/tags/fp
