### ISSUE TITLE
Add excalidraw-cn

### ISSUE THREAD

**Issue by korbinjoe** [michaelrambeau/bestofjs#721]
**Please briefly describe the project you'd like to add to _Best of JS_?**
A whiteboard supporting Chinese hand draw font and multi-canvas based on Excalidraw.

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/korbinzhao/excalidraw-cn

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
React, Drawing, Canvas
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @korbinzhao thank you for the suggestion. 

I suppose the project should be called `Handraw` in _Best of JS_, because it's the name displayed in the website and in the logo of the README?

**Comment by korbinjoe** [comment]
Hi, @michaelrambeau. Thanks for your response.

I think it is a good idea to call the project  I proposed as `Handraw` in Best of JS. 

Thanks again.

**Comment by michaelrambeau** [comment]
Hello @korbinzhao `Handraw` is available on _Best of JS_, please check!

https://bestofjs.org/projects/handraw

By the way, do you have any trouble accessing _Best of JS_? I'm asking because I got reports about connexion errors (E.g. https://github.com/bestofjs/bestofjs-webui/issues/156)

**Comment by korbinjoe** [comment]
@michaelrambeau I am so happy to see handraw on Best of JS. Otherwise, i did not have any trouble accessing Best of JS, it is all normal.
