### ISSUE TITLE
Add Svelte Sonner

### ISSUE THREAD

**Issue by wobsoriano** [michaelrambeau/bestofjs#728]
**Please briefly describe the project you'd like to add to _Best of JS_?**

An opinionated toast component for Svelte.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://svelte-sonner.vercel.app/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- Svelte
- Notification

**Comment by michaelrambeau** [comment]
Hello Robert @wobsoriano thank you for the suggestion, `Svelte Sonner` is available on _Best of JS_, please check!

https://bestofjs.org/projects/svelte-sonner

**Comment by wobsoriano** [comment]
Thank you!
