### ISSUE TITLE
Add The Learn JavaScript Book

### ISSUE THREAD

**Issue by sumn2u** [michaelrambeau/bestofjs#729]
**Please briefly describe the project you'd like to add to _Best of JS_?**

 - This book offers a clear introduction to programming and JavaScript, explaining foundational concepts in an organized and easy-to-understand manner. It includes detailed information and notes, accompanied by illustrative examples, and concludes with helpful exercises.
 
**What is the URL of the project you'd like to add to _Best of JS_?**

 - https://github.com/sumn2u/learn-javascript

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
 - Book
 - Learning resource

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @sumn2u thank you for the suggestion, `Learn JavaScript` is available on _Best of JS_, please check:

https://bestofjs.org/projects/learn-javascript

**Comment by sumn2u** [comment]
Thank you for adding it. 🙏
