### ISSUE TITLE
Add `prettydiff/prettydiff` project

### ISSUE THREAD

**Issue by prettydiff** [michaelrambeau/bestofjs#73]
https://github.com/prettydiff/prettydiff
Language aware diff and beautification tool

**Comment by michaelrambeau** [comment]
Hello Austin @prettydiff ,
Thank you for the suggestion, the project has been added to [bestof.js.org](http://bestof.js.org/) and will be online very soon.

**Comment by prettydiff** [comment]
Awesome, thank you so much!

**Comment by michaelrambeau** [comment]
Hello Austin @prettydiff 
The project is available.
I was not too sure about how to tag the project, now you can find it under the 'Syntax highlighting' tag:
http://bestof.js.org/tags/highlight

**Comment by prettydiff** [comment]
Thank you so much!
