### ISSUE TITLE
Add code-inspector-plugin

### ISSUE THREAD

**Issue by zh-lx** [michaelrambeau/bestofjs#732]
**Please briefly describe the project you'd like to add to _Best of JS_?**
This is a webpack/vite plugin for developing, click the dom on the page, it can locate the dom's source code in the IDE.
![code-inspector](https://user-images.githubusercontent.com/73059627/227070438-6e40e112-6f1d-4f67-9f26-53986bff77c3.gif)

**What is the URL of the project you'd like to add to _Best of JS_?**
https://github.com/zh-lx/code-inspector

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
`Dev Tool`、`Vite`、`Webpack`

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @zh-lx thank you for the suggestion, `code-inspector-plugin` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/code-inspector-plugin

**Comment by zh-lx** [comment]
> Hello @zh-lx thank you for the suggestion, `code-inspector-plugin` is now available on _Best of JS_, please check!
> 
> https://bestofjs.org/projects/code-inspector-plugin

Thanks!
