### ISSUE TITLE
Add Obsidian

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#748]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Dependency injection library for React and React Native applications

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://wix-incubator.github.io/obsidian/

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [ ] The project has more than 100 stars on GitHub (not yet, but 40 to go)
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- React
- React Native

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Obsidian` is available on _Best of JS_:

https://beta.bestofjs.org/projects/obsidian
