### ISSUE TITLE
Add node-casbin

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#750]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- An authorization library that supports access control models like ACL, RBAC, ABAC in Node.js and Browser

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/casbin/node-casbin

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Authentication / Authorization

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Casbin` is a Go project that has SDK for multiple languages, including JS, so I think we can assign the tag `API wrapper / SDK` to tell people it's not really a JS/TS project by itself? 

I wonder if you if you can see a better way to tag those projects?

**Comment by xeusteerapat** [comment]
@michaelrambeau The tag `API wrapper / SDK` is fine in this case. In the future, if we can provide a description for each tag,  it would be great 🙂

**Comment by michaelrambeau** [comment]
The future is now, as I'm working actively on the Next.js version (the beta link I sent you!).

You are totally right, the description of the tags should be displayed as it's far from being obvious sometimes.
So I will add them in the `/tags` page that shows the list of all tags.

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Casbin` is available on _Best of JS_:

https://beta.bestofjs.org/projects/casbin
