### ISSUE TITLE
Add Remix-Dev-Tools

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#753]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Remix.run Development tools to get your app out there in blazing speed

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/Code-Forge-Net/Remix-Dev-Tools

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Debugging
- Dev tool

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat , given the importance of Remix in modern stacks, I wonder if Remix deserves its own tag? (Next.js has its own too, a few other frameworks too: Express, Meteor, and more recently Astro)

**Comment by xeusteerapat** [comment]
@michaelrambeau Yes I think it should I'm going to ask you to add Remix as my own tag as well. 😀

**Comment by michaelrambeau** [comment]
Yes, you deserve a tag `Carefully Selected by Teerapat` 😄

**Comment by michaelrambeau** [comment]
@xeusteerapat `Remix-Dev-Tools` is available on _Best of JS_.

Here is the new tag `Remix` (only 3 projects for now)

 https://beta.bestofjs.org/projects?tags=remix
