### ISSUE TITLE
Add react-sweet-state

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#755]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Shared state management solution for React

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://atlassian.github.io/react-sweet-state

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- React
- State management

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Whaaaaat another state management library for React??? 😄 

Thank you @xeusteerapat !

https://beta.bestofjs.org/projects/react-sweet-state
