### ISSUE TITLE
Add windy-radix-palette

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#757]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Bring Radix Colors to Tailwind CSS

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://windy-radix-palette.vercel.app

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- TailwindCSS
- CSS toolkit

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat I'm adding `Radix Colors` and `Radix Icons` too, because Radix is everywhere these days 😄 

(and I use Radix too for the new Best of JS!)

**Comment by michaelrambeau** [comment]
@xeusteerapat  `Windy Radix Palette` and the 2 other projects I mentioned are available on _Best of JS_.

https://beta.bestofjs.org/projects/windy-radix-palette
