### ISSUE TITLE
Add kolorist

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#758]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- A tiny utility to colorize stdin/stdout

**What is the URL of the project you'd like to add to _Best of JS_?**
- https://github.com/marvinhagemeister/kolorist

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- CLI

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `kolorist` is available on _Best of JS_.

Let's start a discussion about a topic that always comes to my mind when I use Best of JS.

I'd like to provide a way to check easily the "contenders" of a given project, for example that `kolorist` package is an alternative to the widely used `chalk` package, and also `kleur` (https://beta.bestofjs.org/projects/kleur).

A bit similar to recommendations on e-commerce websites: "you may be interested by these projects too..."

- `chalk` (most popular option)
- `kleur`

It could be as simple as showing the projects with similar tags (here: `CLI` + `Colors`), so it's all about the right tagging, again! 
If you have any idea about this topic, please let me know :)

**Comment by xeusteerapat** [comment]
@michaelrambeau That's a great idea 😄 users can quickly discover projects that align with their interests and needs.
