### ISSUE TITLE
Add Replicache

### ISSUE THREAD

**Issue by loganvolkers** [michaelrambeau/bestofjs#760]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Replicache is a JavaScript framework for building high-performance, offline-capable, collaborative web apps.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://www.npmjs.com/package/replicache

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Similarly to the projects suggested here: https://news.ycombinator.com/item?id=28211052

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

No

**Comment by michaelrambeau** [comment]
Hello @loganvolkers thank you for the suggestion.

I guess "CRDT" and "real-time" would apply to `Replicache`.

I noticed the project is not free even if the code of the client is open source, it seems you need a license key, I wonder if we need a new tag for this kind of "not totally free" projects (I don't know how to call that!), even if we have already projects like the Auth0 SDK in _Best of JS_, classified under "API wrapper".

**Comment by michaelrambeau** [comment]
Sorry Logan, digging more, it seems that the code is not open-source: https://github.com/rocicorp/replicache/issues/1018 

The GitHub repo has no code at all (only a single file: the README.md)

Sorry for the confusion, I should make it clear in issue template (done here: https://github.com/michaelrambeau/bestofjs/commit/3b412f85bc5b997f88a17fcc90bf512b502535db)

I will check the other projects mentioned in the thread, to see if we are missing some good projects, thank you again!

**Comment by loganvolkers** [comment]
Good find!

I was reading the docs and saw it was available on NPM so just assumed it was open source.

Thanks for the quick response
