### ISSUE TITLE
Add revezone

### ISSUE THREAD

**Issue by korbinjoe** [michaelrambeau/bestofjs#770]
**Please briefly describe the project you'd like to add to _Best of JS_?**
A new way to use Excalidraw. A lightweight productivity tool to build your Second Brain that integrates enhanced Excalidraw whiteboard and Notion-like note-taking features.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/revezone/revezone

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
desktop app, canvas, react, markdown,  drawing, rich text editor

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
whiteboard, second-brain, pkm, electron

**Comment by michaelrambeau** [comment]
Thank you @korbinzhao for the recommendation. `Revezone` is available on _Best of JS_, please check:

https://beta.bestofjs.org/projects/revezone
