### ISSUE TITLE
Dependency injection libraries

### ISSUE THREAD

**Issue by loganvolkers** [michaelrambeau/bestofjs#771]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Lightweight dependency injection containers for JavaScript/TypeScript

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/microsoft/tsyringe
https://github.com/mgechev/injection-js
https://github.com/inversify/InversifyJS
https://github.com/typestack/typedi

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Dependency injection (DI)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

The `Dependency injection (DI)` tag. Should also apply to: https://github.com/wix-incubator/obsidian

**Comment by michaelrambeau** [comment]
Thank you for the multiple suggestions! @loganvolkers 

A new tag DI was created here: https://bestofjs.org/projects?tags=DI

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/d16ffbf0-5139-4d6f-a2c0-df43cc1bd5a4)
