### ISSUE TITLE
Add Default composer

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#774]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- A tiny (~500B) JavaScript library that allows you to set default values for nested objects

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/aralroca/default-composer

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Data structure
- Utils

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Default Composer` is available on _Best of JS_

https://bestofjs.org/projects/default-composer
