### ISSUE TITLE
Add Biome

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#781]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Toolchain of the web (Rome's successor)

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/biomejs/biome

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Building tool
- Linter
- Rust

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Biome` is available on _Best of JS_.

https://bestofjs.org/projects/biome

I didn't know about the "fail" of Rome project, I thought it would be one of the big projects of the years to come, it's good you told me 😅

**Comment by xeusteerapat** [comment]
Yeah, I am a bit sad that the project was discontinued but also glad that we still have a great community to contribute 😄
