### ISSUE TITLE
Add Open Props to Best of JS

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#785]
**Please briefly describe the project you'd like to add to _Best of JS_?**

- CSS custom properties to help accelerate adaptive and consistent design.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

- https://github.com/argyleink/open-props

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and the project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- CSS Toolkit

**Comment by michaelrambeau** [comment]
Thank you @jacobthesheep `Open Props` is available on _Best of JS_:

https://bestofjs.org/projects/open-props
