### ISSUE TITLE
Add Pack-js

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#788]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- JS version of Pact. Pact is a contract testing framework for HTTP APIs and non-HTTP asynchronous messaging systems.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/pact-foundation/pact-js

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Testing
- Testing framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @xeusteerapat `Pact` was already available on _Best of JS_:

https://bestofjs.org/projects/pact-js

Let me know if there is anything wrong with the new search feature (or with any other features, a lot of things have changed in the Next.js app released this week)

**Comment by xeusteerapat** [comment]
@michaelrambeau I think I may have typed it wrong `Pack` instead of `Pact` 😅
