### ISSUE TITLE
Add `Chalarangelo/mini.css` project

### ISSUE THREAD

**Issue by Chalarangelo** [michaelrambeau/bestofjs#79]
https://github.com/Chalarangelo/mini.css
I developed a CSS framework and it seems to have gathered some attention already.

**Comment by michaelrambeau** [comment]
Hello Angelos @Chalarangelo,

Thank you for the suggestion, `mini.css` will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello Angelos @Chalarangelo 
It's online, check the `CSS Toolkit` tag: http://bestof.js.org/tags/css-lib

I can see that the project is trendy: + 15 stars since yesterday, keep up the good job!

**Comment by michaelrambeau** [comment]
🔥  It looks like mini.css is today's hottest project... congratulations Angelos @Chalarangelo !

![image](https://cloud.githubusercontent.com/assets/5546996/25726749/991f47a8-3160-11e7-87d1-825ef0504925.png)
