### ISSUE TITLE
Farfetched

### ISSUE THREAD

**Issue by igorkamyshev** [michaelrambeau/bestofjs#792]
**Please briefly describe the project you'd like to add to _Best of JS_?**
The advanced data fetching tool for web applications

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/igorkamyshev/farfetched

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- https://bestofjs.org/projects?tags=data
- https://bestofjs.org/projects?tags=reactive
- https://bestofjs.org/projects?tags=universal
- https://bestofjs.org/projects?tags=caching

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
I suggest adding a tag for https://github.com/effector/effector related projects 😇

**Comment by michaelrambeau** [comment]
Thank you @igorkamyshev `farfetched` is available on _Best of JS_.

https://bestofjs.org/projects/farfetched
