### ISSUE TITLE
Add Nuxt UI

### ISSUE THREAD

**Issue by atinux** [michaelrambeau/bestofjs#795]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Adding Nuxt UI: https://ui.nuxt.com

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/nuxt/ui

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- Vue
- Component Toolkit
- TailwindCSS

(Similar to Nuxt uI)

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Thank you for this awesome project!

**Comment by michaelrambeau** [comment]
Hello Sébastien ! `Nuxt UI` is available on _Best of JS_, please check.

https://bestofjs.org/projects/nuxt-ui

Thank you for your kind words!
