### ISSUE TITLE
Add Matteo Collina (Fastify lead maintainer)

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#797]
The JavaScript Hall of Fame gathers the greatest developers, authors and speakers of the JavaScript community.

Before submitting the request to add a new member, check the following points:

- [x] The member has a GitHub profile with more than 500 followers
- [x] The member is renowned for her/his writings, talks or projects

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat Matteo Collina is now a member of the Hall of Fame!

https://bestofjs.org/hall-of-fame
