### ISSUE TITLE
Add `sapegin/react-styleguidist` project

### ISSUE THREAD

**Issue by sapegin** [michaelrambeau/bestofjs#8]
https://github.com/sapegin/react-styleguidist
React style guide generator

**Comment by michaelrambeau** [comment]
It will be online in 48 hours (because the application needs at least 2 daily snapshots of Github daily stars to display trends), be patient!

**Comment by michaelrambeau** [comment]
Hello @sapegin  it's there => http://bestof.js.org/tags/styleguide
I created a new tag `styleguide` and your project is the leading project, good job!
