### ISSUE TITLE
Add Serverless AWS Secrets

### ISSUE THREAD

**Issue by robin-thomas** [michaelrambeau/bestofjs#804]
**Please briefly describe the project you'd like to add to _Best of JS_?**

* A Serverless Plugin for the [Serverless Framework](https://www.serverless.com/), which can replace environment variables with secrets from AWS Secrets Manager.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

* [https://github.com/robin-thomas/serverless-aws-secrets](https://github.com/robin-thomas/serverless-aws-secrets)

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

* nodejs-framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

* serverless

**Comment by michaelrambeau** [comment]
Hello Robin @robin-thomas thank you for the recommendation, `Serverless AWS Secrets` is available on _Best of JS_, please check:

https://bestofjs.org/projects/serverless-aws-secrets
