### ISSUE TITLE
Add Hwy

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#809]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Hwy is a lightweight, flexible, and powerful alternative to NextJS, based on HTMX instead of React.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/hwy-js/hwy

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [ ] The source code is on GitHub and project has more than 100 stars on GitHub (16 to go 🙂)
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Full-stack framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Hwy` (how do you pronounce that? 😅 ) is available on _Best of JS_.

https://bestofjs.org/projects/hwy

**Comment by xeusteerapat** [comment]
@michaelrambeau It pronounces like "highway" 😄
