### ISSUE TITLE
Add Queryx

### ISSUE THREAD

**Issue by wangzuo** [michaelrambeau/bestofjs#814]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Queryx is schema-first and type-safe ORM for TypeScript and Go.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

http://github.com/swiftcarrot/queryx

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- ORM
- SQL
- Database

Thank you for making bestofjs!

**Comment by michaelrambeau** [comment]
Thank you @wangzuo for the suggestion!

I wonder if there is a NPM package to install when using `Querix`, I cannot find it?

**Comment by wangzuo** [comment]
@michaelrambeau Queryx binary is not published on NPM yet (we do have a pending issue for it https://github.com/swiftcarrot/queryx/issues/28). Queryx works a bit like prisma. The executable is written in go but it generates typescript ORM codes based on schema.

**Comment by michaelrambeau** [comment]
Thank you @wangzuo `Queryx` is available on _Best of JS_.

https://bestofjs.org/projects/queryx

**Comment by wangzuo** [comment]
Thanks!
