### ISSUE TITLE
Add Bruno, Insomnia, Newman, to Best of JS

### ISSUE THREAD

**Issue by BBlackwo** [michaelrambeau/bestofjs#816]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Fast, Git Friendly API Client. Alternative to Postman and Insomnia.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/usebruno/bruno

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The source code is on GitHub and project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- `test`
- Possibly `http`?

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

- Something like `API-Client`? Not sure if it warrants a new category though.

**Comment by BBlackwo** [comment]
Might be worth adding https://github.com/Kong/insomnia too as it's very similar.

**Comment by BBlackwo** [comment]
Could potentially add https://github.com/postmanlabs/newman too. Looks like the main postman client isn't open source.

**Comment by michaelrambeau** [comment]
I'm a user of Insomnia desktop app, I'm curious about what changed recently? (The https://www.usebruno.com/ home page mentions people leaving Insomnia)

**Comment by michaelrambeau** [comment]
About the tagging, we have already a tag called `Desktop App`, used for tools to **build** desktop apps (E.g. Electron, Tauri), not for desktop apps themselves. I suggest:
- rename it `Desktop app framework` 
- add a new tag `Desktop apps` to be used for any desktop app we track in _Best of JS_. Markdown editors, IDEs...

**Comment by michaelrambeau** [comment]
Hello Benjamin @BBlackwo 
`Bruno` and `Insomnia` are available in _Best of JS_, under the tags `Desktop app` and `HTTP client`:

https://bestofjs.org/projects?tags=desktop-app&tags=http

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/dc5900e5-b9df-4c06-a5ca-1dabafc8067e)

**Comment by BBlackwo** [comment]
>I'm a user of Insomnia desktop app, I'm curious about what changed recently?

I'm not sure :sweat_smile: I haven't actually used Insomnia before. Just Postman

The tagging you suggested sounds good :+1: 

Thanks for adding that! Looks like Bruno was number 1 today! 

![image](https://github.com/michaelrambeau/bestofjs/assets/7598058/60b90416-a3ea-4617-b2e0-ab7d5053d1ab)
