### ISSUE TITLE
Add `rill-js/rill` project

### ISSUE THREAD

**Issue by DylanPiercey** [michaelrambeau/bestofjs#82]
https://github.com/rill-js/rill
Expressive HTTP middleware for nodejs and the browser.

**Comment by michaelrambeau** [comment]
Hello @DylanPiercey,
Thank you for the suggestion, the project will be online very soon.
Building a web application as if it was an Express app in the browser, it's a very interesting approach, I wonder why nobody did that before.

It will be tagged under `Isomorphic`and `Routing` at least.
`Frameworks` tag is about UI frameworks in the browser (Angular, React, Vue...) so I think `Full-stack framework` would be more appropriate (even if other contender in this category are quite different: http://bestof.js.org/tags/fullstack). 

Does it make sense?

**Comment by DylanPiercey** [comment]
@michaelrambeau awesome. Those suggestions sound good, also looking through the framework section I do agree.

I would think that it would also fit in with the 'node.js frameworks' though since it competes directly with Koa and Express.

Also this site is 🔥, super handy for me today.

**Comment by michaelrambeau** [comment]
OK Dylan @DylanPiercey, it will be under `node.js frameworks` tag too.
It takes 48 hours to be online because the application automatically takes "snapshots" of Github stars every day and we need at least 2 snapshots to be able to display daily trends.
So I will tell you when it's "live".

Thank you for your feedback about the app!

**Comment by DylanPiercey** [comment]
@michaelrambeau thanks for your prompt response!

**Comment by michaelrambeau** [comment]
Hello @DylanPiercey it's online, check the `isomorphic` tag, for example:

http://bestof.js.org/tags/isomorphic

**Comment by DylanPiercey** [comment]
Awesome thanks. I'll close the issue for you.
