### ISSUE TITLE
Add emojis

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#823]
**Please briefly describe the project you'd like to add to _Best of JS_?**

AI-generated emojis in seconds

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/pondorasti/emojis

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and the project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

emoji

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

AI

**Comment by michaelrambeau** [comment]
Hello @jacobthesheep thank you for the recommendation, `AI Emojis` is available on _Best of JS_, please check:

https://bestofjs.org/projects/ai-emojis
