### ISSUE TITLE
Add Mocks Server

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#826]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Node.js mock server running live, interactive mocks in place of real APIs

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/mocks-server

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Testing

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Mocks Server` is available on _Best of JS_.

https://bestofjs.org/projects/mocks-server

The 2 most recent projects have a similar icon, is it a coincidence 😄 🦎 ?

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/7251b2db-8606-4bdf-aa8f-38330ef3f5dd)
