### ISSUE TITLE
Add `ice-services/moleculer` project

### ISSUE THREAD

**Issue by icebob** [michaelrambeau/bestofjs#83]
https://github.com/ice-services/moleculer
a new Microservices framework for NodeJS

**Comment by michaelrambeau** [comment]
Hello @icebob 
Thank you for the recommendation, `Moleculer` project will be available on bestof.js.org very soon.

FYI, there is already a project from you: `vue-form-generator`, good job!

**Comment by icebob** [comment]
Yes, thank you!

**Comment by michaelrambeau** [comment]
Hello @icebob it's online, check the `Microservice` tag:

http://bestof.js.org/tags/microservice

**Comment by icebob** [comment]
Great! Thank you!

**Comment by icebob** [comment]
Hi @michaelrambeau,
could you add `Node.js framework` tag for Moleculer, as well?

**Comment by michaelrambeau** [comment]
Hello @icebob 
OK, it's done, please check here: https://bestofjs.org/projects/moleculer

Thank you and feel free to suggest anything!

**Comment by icebob** [comment]
Great, thank you very much!
