### ISSUE TITLE
Add next-safe-action

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#830]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Typesafe Server Actions in your Next.js 13 app.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/TheEdoRan/next-safe-action

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Data fetching
- React Server Components
- Next.js
- React

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat it's nice that you noticed I added a new tag "React Server Components" a few days ago, you pay attention to everything ;)

**Comment by michaelrambeau** [comment]
@xeusteerapat `next-safe-action` is available on _Best of JS_.

https://bestofjs.org/projects/next-safe-action
