### ISSUE TITLE
Add Suspensive

### ISSUE THREAD

**Issue by manudeli** [michaelrambeau/bestofjs#848]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Suspensive is packages to use React Suspense easily
- @suspensive/react
- https://suspensive.org

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/suspensive/react

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- React
- Async flow / Promises
- Error handling

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
- Suspense

**Comment by michaelrambeau** [comment]
Hello @manudeli thank you for the suggestion!

`Suspensive` is available on _Best of JS_, please check: https://bestofjs.org/projects/suspensive

**Comment by manudeli** [comment]
@michaelrambeau I checked page. Could you replace Server Component tag to Suspense or Async flow / Promises. Suspensive is not for Server component

**Comment by michaelrambeau** [comment]
Hello @manudeli sorry for my misunderstanding!

The tagging has been fixed, please check again.

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/05408d81-b346-4eda-80bb-e0e3e4e4fe25)

**Comment by manudeli** [comment]
Thanks!
