### ISSUE TITLE
Add Alpine AJAX

### ISSUE THREAD

**Issue by imacrayon** [michaelrambeau/bestofjs#852]
**Please briefly describe the project you'd like to add to _Best of JS_?**

An Alpine.js plugin that enables your HTML elements to request remote content from your server. Use it to build progressively-enhanced, robust, interactive websites.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

[https://github.com/imacrayon/alpine-ajax](https://github.com/imacrayon/alpine-ajax)

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
UI Framework, Utils

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by imacrayon** [comment]
Here's a logo that should work on dark and light background:
![Alpine AJAX](https://github.com/michaelrambeau/bestofjs/assets/3410149/4c06fd88-eebb-41bf-ad05-406ac2d36b4d)

**Comment by michaelrambeau** [comment]
Hello Christian @imacrayon thank you for the suggestion.

Regarding the logo, if we customize to avoid showing the GitHub owner avatar (your avatar for that project 😄) we need a SVG file. We can handle light mode and dark modes if you provide 2 different files (I upload 2 files by project anyway, even if the logos are the same).

Because of the size displayed in the app (the smallest being 32x32px, in the search modal) and for performance reason, a simple shape is better... such as the `img/favicon.svg` file ( 📻 ) that I can use maybe?

**Comment by imacrayon** [comment]
Sure, here's the radio:

![radio](https://github.com/michaelrambeau/bestofjs/assets/3410149/3b7f492c-798c-4ede-a632-070ad3396958)

I'm alright with scaling the logo down to 32px too, but whatever you think is best for your website is good with me 😄

**Comment by michaelrambeau** [comment]
Thank you @imacrayon I'm preparing that.

I need your help about the tagging. We already have `Alpine`, `HTMX` and `Unpoly` projects in _Best of JS_ but there is no specific tag for this category of projects.

Is there a tag that would make sense, the only one that comes to my mind is "HTML over the wire", can you see something better?

Tagging is difficult, almost as difficult as naming things 😄

**Comment by imacrayon** [comment]
Yeah that's tricky, everyone has their own word for it. Some ideas I might recommend: `hypermedia`, `hateoas`, `server-rendered` or `SSR`.

**Comment by michaelrambeau** [comment]
Hello @imacrayon `Alpine AJAX` is now available on _Best of JS_, please check.

I created a tag called `HTML tagging`, let me know what you think

https://bestofjs.org/projects?tags=html-tagging

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/16e9a36a-269d-495a-b42a-a2e7ce2d6665)

The two custom logos can be adjusted (see [this commit in the monorepo](https://github.com/bestofjs/bestofjs/commit/ca0183799907cc856519efa2ae46a19b51d3ff66)).

**Comment by imacrayon** [comment]
Awesome! Looks good to me. Thank you 🙌 

It might be worth adding Turbo (https://bestofjs.org/projects/turbo) to that group as well.

**Comment by michaelrambeau** [comment]
Thank you for your help @imacrayon `Turbo` was added to the list.
