### ISSUE TITLE
Add HyperExpress

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#857]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- High performance Node.js webserver with a simple-to-use API powered by uWebsockets.js under the hood.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/kartikk221/hyper-express

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Node.js framework
- Express
- Websocket

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat Note: I'm not sure if `Express` tag is correct, according to: https://nodeweekly.com/issues/510

> Despite the name, it’s nothing to do with Express.js, though it does have some limited API compatibility

But it's just a detail, you know like me that tagging is difficult 😄

**Comment by xeusteerapat** [comment]
@michaelrambeau ahh, you're right, I think we can remove `Express` tag 🙂

**Comment by michaelrambeau** [comment]
_HyperExpress_ is available on _Best of JS_.

https://bestofjs.org/projects/hyperexpress
