### ISSUE TITLE
Add Dprint

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#860]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Pluggable and configurable code formatting platform written in Rust.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/dprint/dprint

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Linter
- Rust

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
- I'm not sure we should change the tag's name from `Linter` to `Linter / Formatter` since they are different thing. Some package we can use for both linting and formatting, but some of them we can't.

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat Good point, the separation between linters and formatter is clearer now than ESLint is removing the styling rules.

I think the best would be a new tag `Formatters` applied to tools like Prettier, Dprint and Biome.

Some projects would have both, like `ESLint Stylistic` that would be available on _Best of JS_ tomorrow.

**Comment by michaelrambeau** [comment]
@xeusteerapat `dprint` is available on _Best of JS_ and we have 2 distinct tags:

- Formatters: https://bestofjs.org/projects?tags=formatter
- Linters: https://bestofjs.org/projects?tags=lint

Let me know if it makes sense, thank you!
