### ISSUE TITLE
Add authkit

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#862]
**Please briefly describe the project you'd like to add to _Best of JS_?**

The world’s best login box,
powered by WorkOS + Radix.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/workos/authkit

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Authentication / Authorization

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @jacobthesheep `AuthKit` is now available on _Best of JS_, please check!

https://bestofjs.org/projects/authkit

For an unknow reason, the first image included in the README does not show up in _Best of JS_, it seems there is a kind of authentication mechanism (the URL starts with `https://private-user-images.githubusercontent.com/` and there is kind of token in the URL) 🤔 

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/bbb98e21-1ce6-442f-b4f3-0f5b2eb50900)
