### ISSUE TITLE
Remove Rome

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#863]
https://github.com/rome/tools now deprecated.
https://bestofjs.org/projects/rome

**Comment by michaelrambeau** [comment]
Thank you @jacobthesheep , it looks like the fall of the Roman Empire 😄 

I thought about removing it indeed but then I asked myself what to do if just want to look up the project information (as I use _Best of JS_ all day long to look up project's homepage and GitHub repo!)
For big projects like that, I wonder if it would be better to have a kind of "deprecated" status to show clearly that the project is not maintained, it's not a valid option, but we keep it "for reference"?

JFYI: when projects don't have any commit during one year, there are automatically "filtered out", unless they are very popular (they keep getting new stars, which is not the case of Rome, it losing stars at a high speed!).
