### ISSUE TITLE
Add CASE.Js

### ISSUE THREAD

**Issue by ismaelguerrib** [michaelrambeau/bestofjs#867]
**Please briefly describe the project you'd like to add to _Best of JS_?**

CASE is a Backend-as-a-Service for developers. It provides a complete backend to your client app without the hassle that comes with it. It offers a fully Self-Hosted and Open Source backend with a Local-First Approach.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/casejs

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- Utils
- Component toolkit
- UI Framework

**Comment by michaelrambeau** [comment]
Thank you @ismaelguerrib for the suggestion!

`CASE` is available on _Best of JS_ and a new tag called `Backend-as-a-Service` was introduced:

https://bestofjs.org/projects?tags=baas

Let me know if there are others projects from _Best of JS_ that should be tagged under this new tag, thank you for your help!
