### ISSUE TITLE
Add Triplit

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#869]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- A full-stack, syncing database that runs on both server and client

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/aspen-cloud/triplit

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [ ] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Full-stack framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat I was checking the docs to understand the concept, do you know if you can deploy that Triplit DB anywhere? Or it works only with their own cloud solution?

The docs say:

> Although you can connect directly to a managed or self hosted instance of a remote Triplit Database...

but I can't find any explanation.

**Comment by xeusteerapat** [comment]
@michaelrambeau I joined their discord server and found someone asked for self-deployment. As the maintainer said, there is no guide just yet, but they gave the example of deployment to fly.io [here](https://github.com/aspen-cloud/triplit/tree/main/packages/server)

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Triplit` is available on _Best of JS_.

https://bestofjs.org/projects/triplit
