### ISSUE TITLE
Add `handsontable/handsontable` project

### ISSUE THREAD

**Issue by Sharlaan** [michaelrambeau/bestofjs#87]
https://github.com/handsontable/handsontable
Despite being commercial, it seems far superior to other alternatives presented in bestof.js.org

**Comment by michaelrambeau** [comment]
Hello Raphaël @Sharlaan 
Thank you for the recommendation, `handsontable` project will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello Raphaël @Sharlaan,
The project is online and it's number 1 on its category, thank you for the advice!

Check here: http://bestof.js.org/tags/table
