### ISSUE TITLE
Budibase

### ISSUE THREAD

**Issue by joebudi** [michaelrambeau/bestofjs#870]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Budibase is an open-source low-code platform that saves IT teams 100s of hours building apps and transforming workflows.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
[budibase/budibase](https://github.com/budibase/budibase)

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The source code is on GitHub and project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Svelte, SQL, Form, Table, Database

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
Low-code

**Comment by michaelrambeau** [comment]
Hello @joebudi thank you for the suggestion.

A new tag `Low-code` makes sense. We have already a tag [Visual Programming](https://bestofjs.org/projects?tags=visual-programming) but the concepts are not the same.


From that list (or from anywhere in _Best of JS_, including [CMS](https://bestofjs.org/projects?tags=cms&sort=total)), can you see other projects that should be tagged "Low-code"?

Thank you for helping me tagging projects correctly!

**Comment by joebudi** [comment]
Directus maybe

**Comment by michaelrambeau** [comment]
Hello @joebudi `Budybase` is available on _Best of JS_, please check.

https://bestofjs.org/projects/budibase
