### ISSUE TITLE
Add tsdoc

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#878]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Browse type documentation for JS libraries

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/pastelsky/tsdocs

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Types or Documentation

**Comment by michaelrambeau** [comment]
Thank you @jacobdalamb `TSDocs.dev` was added a few days ago, let me know if you can find it 😄
