### ISSUE TITLE
SpiceDB, Open Source, Google Zanzibar-inspired fine-grained permissions database

### ISSUE THREAD

**Issue by pmacni** [michaelrambeau/bestofjs#880]
**SpiceDB Open Source, Google Zanzibar-inspired fine-grained permissions database**

**[What is the GitHub repository of the project you'd like to add to _Best of JS_?](https://github.com/authzed/spicedb)**

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? Authentication / Authorization, authz, auth **

**Authorization, Permissions, RBAC, ReBAC, ABAC, PBAC**

**Comment by michaelrambeau** [comment]
Hello @pmacni thank you for the suggestion.

I'm not sure the project matches the scope of _Best of JS_ as it seems to be a backend written in Golang?

Or maybe the project to track is the Node.js client: https://github.com/authzed/authzed-node ?
