### ISSUE TITLE
Add Dong Yoon Kang

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#883]
The JavaScript Hall of Fame gathers the greatest developers, authors and speakers of the JavaScript community.

Before submitting the request to add a new member, check the following points:

- [x] The member has a GitHub profile with more than 500 followers
- [x] The member is renowned for her/his writings, talks or projects

Note: Dong Yoon Kang is the creator of [SWC](https://swc.rs/)

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat is `Dong Yoon Kang` the right name to display?

On GitHub and Twittter, the name that shows up is "Donny/강동윤".

- https://github.com/kdy1
- https://twitter.com/kdy1dev

**Comment by xeusteerapat** [comment]
@michaelrambeau Yes, I think so. Based on his name display in the Next.js blog [here](https://nextjs.org/blog/next-12-3)

**Comment by michaelrambeau** [comment]
@xeusteerapat Dong Yoon Kang was inducted to the Hall of Fame.

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/4ff34e67-de89-4b5b-b8f7-eacfa739dbdb)
