### ISSUE TITLE
Add tokenami to Best of JS

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#885]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Atomic CSS in the style attribute. Type-safe static styles with theming, responsive variant support, and no bundler integration.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/tokenami/tokenami

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Atomic CSS + CSS-in-JS

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @jacobdalamb `Tokenami` is available on _Best of JS_.

https://bestofjs.org/projects/tokenami

**Comment by michaelrambeau** [comment]
...but there is an issue about the first image in the README that does not show up in _Best of JS_, I'm investigating:

https://github.com/bestofjs/bestofjs/issues/260#issuecomment-1877910735

**Comment by michaelrambeau** [comment]
The issue about the image should be fixed by https://github.com/bestofjs/bestofjs/pull/261 but please let me know if you find any broken image anywhere, thank you again for your precious help!
