### ISSUE TITLE
Adding simple-data-analysis

### ISSUE THREAD

**Issue by nshiab** [michaelrambeau/bestofjs#888]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Hi! I am the maintainer of simple-data-analysis, an easy-to-use and high-performance JavaScript library for data analysis.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/nshiab/simple-data-analysis

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Data analysis, math, statistics.

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @nshiab thank you for the suggestion, `simple-data-analysis` is available on _Best of JS_, please check!

https://bestofjs.org/projects/simple-data-analysis

**Comment by nshiab** [comment]
Wonderful! Thanks a lot, @michaelrambeau !
