### ISSUE TITLE
Add `DIYgod/APlayer` project

### ISSUE THREAD

**Issue by cloudyan** [michaelrambeau/bestofjs#89]
https://github.com/DIYgod/APlayer
a beautiful HTML5 music player http://aplayer.js.org

**Comment by michaelrambeau** [comment]
Thank you @cloudyan for that suggestion, too.
It will be available on bestof.js.org very soon.

**Comment by michaelrambeau** [comment]
Hello @cloudyan
It's online, check here: http://bestof.js.org/tags/audio
