### ISSUE TITLE
Add FormBuilder

### ISSUE THREAD

**Issue by KryptXBSA** [michaelrambeau/bestofjs#890]
**Please briefly describe the project you'd like to add to _Best of JS_?**

UI based codegen tool to easily create Beautiful and Type safe @shadcn/ui forms.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

[https://github.com/AlandSleman/FormBuilder](https://github.com/AlandSleman/FormBuilder)

**Before submitting the request to add a new project, please check the following points:**

- [x ] The project is related to the web platform or Node.js
- [ ] The source code is on GitHub and project has more than 100 stars on GitHub
- [ x] The project has thorough documentation in English
- [ x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Dev tool, Playground, Next.js, Form.

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Code Gen and shadcn/ui, there are a lot of cool libraries/tools which are being built around shadcn/ui.

**Comment by michaelrambeau** [comment]
Hello @AlandSleman thank you for the suggestion, `FormBuilder for @shadcn/ui` is available on _Best of JS_.

https://bestofjs.org/projects/formbuilder
