### ISSUE TITLE
Add PhotoSwipe

### ISSUE THREAD

**Issue by markfinst** [michaelrambeau/bestofjs#891]
**Please briefly describe the project you'd like to add to _Best of JS_?**

PhotoSwipe is a JS image viewer with zoom support.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/dimsemenov/photoswipe

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- [Image viewer](https://bestofjs.org/projects?tags=viewer)
- Utils

**Comment by michaelrambeau** [comment]
Hello @markfinst thank you for the suggestion, `PhotoSwipe` is available on _Best of JS_:

https://bestofjs.org/projects/photoswipe
