### ISSUE TITLE
LemonadeJS

### ISSUE THREAD

**Issue by hodeware** [michaelrambeau/bestofjs#892]
**Please briefly describe the project you'd like to add to _Best of JS_?**
LemonadeJS is a compact, reactive JavaScript micro-library, weighing in at just 4KB when compressed. It facilitates two-way data binding and is designed to assist in creating modern, reusable components. The library is dependency-free and does not require transpiling streamlining development.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/lemonadejs/lemonadejs

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
reactive

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
two-way-data-binding

** Official website **
https://lemonadejs.net

**Comment by michaelrambeau** [comment]
Hello @hodeware `LemondadeJS` is already on Best of JS:

https://bestofjs.org/projects/lemonadejs

Let me know if there is something wrong with the search feature, thank you!

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/02c40188-7c68-4af3-b4aa-66ec6362a517)
