### ISSUE TITLE
Add `typicode/lowdb` project

### ISSUE THREAD

**Issue by typicode** [michaelrambeau/bestofjs#9]
https://github.com/typicode/lowdb
Small database built on Lodash, useful for small servers, CLI, etc...

**Comment by michaelrambeau** [comment]
Hello @typicode !
Thank you for having starred the project.
Did you know that json-server was the leader of this category http://bestof.js.org/tags/api ?
Good job!
I have added lowdb to the project, it will be available in 48 hours, be patient!

**Comment by typicode** [comment]
You're welcome, thanks for adding it.
No I didn't :)

You did a great job too. My favourite feature on bestofjs is the "timeline", being able to quickly see trends by weeks/months 👍

**Comment by michaelrambeau** [comment]
Hello @typicode , lowdb is now on bestof.js.org, check the `database` tag => http://bestof.js.org/tags/db

![image](https://cloud.githubusercontent.com/assets/5546996/19174263/7532ac6a-8c68-11e6-9f59-8834ad2c3c5f.png)
