### ISSUE TITLE
Add `DIYgod/DPlayer` project

### ISSUE THREAD

**Issue by cloudyan** [michaelrambeau/bestofjs#90]
https://github.com/DIYgod/DPlayer
a lovely HTML5 danmaku video player http://dplayer.js.org

**Comment by michaelrambeau** [comment]
Hello @cloudyan 
Thank you for the suggestion, `dplayer` will be available on bestof.js.org very soon.

Maybe It would be nice to explain in the documentation what is "danmaku" (something like "live comments displayed while a video is running") ?

**Comment by michaelrambeau** [comment]
Hello @cloudyan 
It's online, check here: http://bestof.js.org/tags/video
... but I still don't know what is a "danmaku video player" 😄

**Comment by cloudyan** [comment]
danmaku video player = support comments on screen
