### ISSUE TITLE
Add Fuse (not Fuse.js)

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#900]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Fuse: The fastest way to build and query great APIs with TypeScript

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/StellateHQ/fuse

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Data fetching
- GraphQL

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

_I know it's a bit confusing since they have the same name_

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `Fuse` is available on _Best of JS_.

https://bestofjs.org/projects/fuse
