### ISSUE TITLE
Add Expressive Code

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#901]
**Please briefly describe the project you'd like to add to _Best of JS_?**

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Syntax highlighting

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by BBlackwo** [comment]
Just confirming, is this the project @jacobdalamb? https://github.com/expressive-code/expressive-code

**Comment by ghost** [comment]
> Just confirming, is this the project @jacobdalamb? [expressive-code/expressive-code](https://github.com/expressive-code/expressive-code)

Yes.

**Comment by michaelrambeau** [comment]
Thank you @jacobdalamb `Expressive Code` is available on _Best of JS_.

https://bestofjs.org/projects/expressive-code
