### ISSUE TITLE
Update tags for virtua

### ISSUE THREAD

**Issue by inokawa** [michaelrambeau/bestofjs#904]
I'm author of https://bestofjs.org/projects/virtua . Thank you for listing my library!

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Virtual list (current)
React (current)
Scrolling (current)
Vue (new)
Solid (new)

**Comment by michaelrambeau** [comment]
Hello @inokawa thank you for the feedback, please check if the tagging is correct now.

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/bbfbfb95-e513-41bf-898a-89da511954c8)

**Comment by inokawa** [comment]
@michaelrambeau 
It's correct. Thank you!
