### ISSUE TITLE
Add asciidoc

### ISSUE THREAD

**Issue by ghost** [michaelrambeau/bestofjs#913]
**Please briefly describe the project you'd like to add to _Best of JS_?**

A JavaScript port of Asciidoctor, a modern implementation of AsciiDoc

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/asciidoctor/asciidoctor.js

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Markdown doesn't seem right but might be the best tag for people to notice this project

**Comment by michaelrambeau** [comment]
Hello @jacobdalamb I didn't know what was Asciidoc, thank you for the suggestion.

So it's a kind of alternative to Markdown language maybe the generic "Text processing" tag would make sense? (to ensure nobody will never find this project 😅 )

https://bestofjs.org/projects?tags=text-processing

**Comment by ghost** [comment]
> Hello @jacobdalamb I didn't know what was Asciidoc, thank you for the suggestion.
> 
> So it's a kind of alternative to Markdown language maybe the generic "Text processing" tag would make sense? (to ensure nobody will never find this project 😅 )
> 
> [bestofjs.org/projects?tags=text-processing](https://bestofjs.org/projects?tags=text-processing)

It doesn't seem to fit with the projects tagged as "Text processing"

**Comment by michaelrambeau** [comment]
OK Jacob @jacobdalamb thinking more... what about a new tag `Text to HTML processor` (I'm not sure about the best wording) that would include Asciidoc and markdown processors projects such as `Marked`, `remarkable` and `markdown-it`?

- name on the screen: `Text to HTML`
- slug: `text-to-html`
- description: `Text (markdown, asciidoc) to HTML processor`

Thank you again for your help, tagging things properly is challenging 🙏

**Comment by ghost** [comment]
What about `markup-language` or `markup`?

**Comment by michaelrambeau** [comment]
That could work but it makes me think about `templating` languages such as Handlebars, Pug, Nunjucks that we have under the `templating` tag:

https://bestofjs.org/projects?tags=template

...but maybe I'm wrong as a markup language and a templating languages are 2 different things.

**Comment by ghost** [comment]
They're similar but not the same thing.

**Comment by michaelrambeau** [comment]
Hello @jacobdalamb thank you for your patience!

I have introduced a new tag `Markup language`, please check:

https://bestofjs.org/projects?tags=markup

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/efca74bc-d82e-4f41-b44e-985312c553fb)
