### ISSUE TITLE
Add `MichaReiser/speedy.js` project

### ISSUE THREAD

**Issue by andyVanVeen** [michaelrambeau/bestofjs#92]
https://github.com/MichaReiser/speedy.js
Compiling TO WASM FROM JavaScript

**Comment by michaelrambeau** [comment]
Hello @andyVanVeen 
Thank you for the recommendation.
I'm going to check (I have never heard about LLVM before, sorry for my ignorance), I think I will create a `Web Assembly` tag in bestof.js.org.
Let me know if you know other great projects related to Web Assembly.

**Comment by michaelrambeau** [comment]
Hello again @andyVanVeen, 
The project you submitted will be available very soon on bestof.js.org.

Also I'm adding this project: https://github.com/mbasso/awesome-wasm

**Comment by michaelrambeau** [comment]
Hello @andyVanVeen ,
`speedy.js` is available on bestof.js.org
Check here: http://bestof.js.org/tags/webassembly

![image](https://user-images.githubusercontent.com/5546996/27500504-b1c37bc0-58a3-11e7-8191-3dff6fcc0c6c.png)

Thank you for your feedback!
