### ISSUE TITLE
Add NOCC A free modern bootstrap theme

### ISSUE THREAD

**Issue by carlesloriente** [michaelrambeau/bestofjs#929]
**Please briefly describe the project you'd like to add to _Best of JS_?**
NOCC is a responsive Bootstrap 5 dual Theme. Featuring a beautifully designed homepage, dynamic tag cloud, image gallery, and more.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/carlesloriente/nocc-bootstrap-theme/

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [ ] The source code is on GitHub and project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- Bootstrap
- Theme
- HTML Template

**Comment by michaelrambeau** [comment]
Thank you @carlesloriente for the suggestion.

For now there is this requirement about the number of stars but we will keep an eye on your project.

Thank you for your understanding and good luck for the promotion of the project, I know it's hard!

**Comment by carlesloriente** [comment]
Thank you for the quick answer; I'm closing as not completed for now until all the requirements are met :dancing_men:
