### ISSUE TITLE
Add `NaturalIntelligence/fast-xml-parser` project

### ISSUE THREAD

**Issue by amitguptagwl** [michaelrambeau/bestofjs#93]
https://github.com/NaturalIntelligence/fast-xml-parser
Fast XML Parser parse a xml string to json/js object or intermediatory traversal xml object. It is very fast in comparison of other available xml parsers. It can validate the xml. It can also be used from CLI

**Comment by michaelrambeau** [comment]
@amitguptagwl Hello Amit,
Thank you for the recommendation.
`fast-xml-parser` will be available on bestof.js.org very soon.

**Comment by amitguptagwl** [comment]
Thanks Michael for your quick response.

**Comment by michaelrambeau** [comment]
Hello Amit @amitguptagwl ,
It's online, check the `XML` tag:
http://bestof.js.org/tags/xml

**Comment by amitguptagwl** [comment]
Thanks a lot Michael.
