### ISSUE TITLE
Rename "React Storybook" to "Storybook" and add vue tag

### ISSUE THREAD

**Issue by ndelangen** [michaelrambeau/bestofjs#94]
React Storybook will support multiple UI libraries soon, starting with Vue!

For this we changed the project name to "Storybook"

Could you change the url + Title?
https://bestof.js.org/projects/react-storybook
https://bestof.js.org/projects/storybook

Could you add the "Vue" tag also?

♥️ Storybook team

**Comment by michaelrambeau** [comment]
Hello @ndelangen ,

OK, it's done.
https://bestof.js.org/tags/vue

Thank you very much for having checked bestof.js.org, any feedback is always welcome!

Thank you for the Storybook project too, it's really nice to be able to check components in isolation with Storybook.

![image](https://user-images.githubusercontent.com/5546996/28041078-01b25180-6603-11e7-8a9a-3c08ebde3cac.png)

**Comment by ndelangen** [comment]
Super awesome, thanks!

**Comment by ndelangen** [comment]
@michaelrambeau Can you change the link to the npms reference too?

https://bestof.js.org/projects/storybook/
<img width="1003" alt="screen shot 2017-09-19 at 11 33 07" src="https://user-images.githubusercontent.com/3070389/30585831-55c8ff5a-9d2e-11e7-8a0a-a7aa78e83937.png">

I would like that to go to: https://www.npmjs.com/package/storybook

**Comment by michaelrambeau** [comment]
Hello Norbert @ndelangen 
OK it's have been fixed.

By the way what do you think of the "heatmap", introduced yesterday by the last release of bestof.js.org?
This is the heatmap for "storybook":

![image](https://user-images.githubusercontent.com/5546996/30615763-e5b4a550-9dca-11e7-979f-f17ea6e568f8.png)

Don't be afraid of telling me the truth if you think it makes non-sense or it does not provide any value for users.

**Comment by ndelangen** [comment]
Yes I noticed, and I'd like to be able to embed it on our website, I like it so much.
I actually have an idea to pull data from git log during docs build and generate some images to demonstrate the projects health.

I'm already generating a list of all contributors in this phase 😄

**Comment by ndelangen** [comment]
Maybe the git stars isn't the most valuable metric to show, I would like this chart to be a sign of activity. commits, issues, PRs..

I still like the stars added averages!

**Comment by michaelrambeau** [comment]
@ndelangen Thank you very much for your feedback！
Popularity and Activity (or "health") are 2 different things even if they correlate somehow.
I focused on popularity because, at least for me, if a project gets 20 stars a day, every day over the last 12 months, it means a lot, even if there not a single contribution over the last 12 months.
(but I don't think such a combination actually exists)

On the other hand, if a project is super active but loses stars, it's not a good sign, it means that there are a lot of users who "migrate" to something else, the project is not as "relevant" as it was before.

Anyway I agree that more data about project health should be added.
Let me know about what you are doing with the list of all contributors, I'm curious to see if it could inspire me, and I'm really open to any suggestion.

**Comment by ndelangen** [comment]
I think most 'stargazers' never unstar a project.. but maybe something like: installs per month + (commits per month * number of contributors).

Anyway, I think if you could answer the question:
> **should I use package-a or package-b**
>
> -*every npm user at some point*

or provide valuable insight to make a more informed decision, I think that would help a lot of people!

**Comment by michaelrambeau** [comment]
@ndelangen Actually I can see projects that lose stars, it happens, sometimes.
I'm going to add a "TOP 10 Coldest Projects", just for fun 😄 

But you're right, usually people don't remove the star they added previously.

About the metrics you mentioned, it could great to see those numbers, indeed.

I tried to address this problem by adding data from https://npms.io/ site (it's the package "score" displayed after the npm package name) but I don't think this score makes sense for people.

Thank you again for your ideas and your feedback, I will let you know as soon I have something to show!

**Comment by michaelrambeau** [comment]
Hello Norbert @ndelangen 
Just to let you know I added new data:
* The number of commit
* The number of contributor
* The number of dependency, with links to the package page on npm (and the project page on bestof.js.org, if available)

![image](https://user-images.githubusercontent.com/5546996/31054657-b15c91c4-a6f2-11e7-85f9-0ebf52de3a1d.png)

I know it's not everything you requested but it's only the first step... let me know if I move to the right direction 😄 .
