### ISSUE TITLE
Add `voodootikigod` user to the Hall of Fame

### ISSUE THREAD

**Issue by tealtail** [michaelrambeau/bestofjs#95]
https://github.com/voodootikigod
The Godfather of Nodebots; Creator of [JSConf](http://jsconf.com/) and RobotsConf. 
A JS community hero.

**Comment by michaelrambeau** [comment]
Hello @tealtail 
Thank you very much for the suggestion.

"A JS community hero" that sounds great, I want to catch them all 😄  !

I am adding voodootikigod to the the Hall of Fame.
I will let you know when it's online, in 24 hours (when the page is rebuilt).

**Comment by michaelrambeau** [comment]
@tealtail Chris Williams has been inducted to the JavaScript Hall of Fame, as you can see here: https://bestof.js.org/hof

![image](https://user-images.githubusercontent.com/5546996/28483347-b4f7d8d0-6ea7-11e7-9c11-71dc0b991405.png)

Thank you for having checked, any feedback about the application is welcome!
