### ISSUE TITLE
Add Freeter

### ISSUE THREAD

**Issue by alexk111** [michaelrambeau/bestofjs#950]
**Please briefly describe the project you'd like to add to _Best of JS_?**

A productivity app enabling a smarter way to work on the computer.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/FreeterApp/Freeter

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

React, Desktop App, Dashboard

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Productivity

**Comment by michaelrambeau** [comment]
Hello @alexk111 thank you for the recommendation!

`Freeter` is available on _Best of JS_: https://bestofjs.org/projects/freeter

**Comment by alexk111** [comment]
Thanks!
