### ISSUE TITLE
Hono also runs on Node.js and should be tagged as a Node.js framework, not only as Deno or Bun Framework

### ISSUE THREAD

**Issue by sfinotto** [michaelrambeau/bestofjs#958]
Please add the "Node.js framework" tag to Hono https://bestofjs.org/projects/hono  because it does run in Node.js https://hono.dev/

**Comment by michaelrambeau** [comment]
Hello Sergio @sfinotto thank you for the feedback, it will be fixed in 24 hours.

Note: at the time I added Hono to _Best of JS_, the project's description was:

> Ultrafast web framework for Cloudflare Workers, Deno, and Bun. Fast, but not only fast.

But things change 😅

**Comment by michaelrambeau** [comment]
OK @sfinotto please check again, thank you!

Let me know if you have any idea about the tagging.
When I started the projects in 2015, the landscape was simpler in the server-side: by "Node.js server" I meant a "backend server written in JS" but now we have a lot of different runtimes, and we have meta-frameworks too.

So maybe I should rename the tag [Node.js frameworks](https://bestofjs.org/projects?tags=nodejs-framework) => "Web servers", what do you think?

https://bestofjs.org/projects/hono

![image](https://github.com/michaelrambeau/bestofjs/assets/5546996/1a9252dc-8d08-450e-a47c-4933a7ae54a4)

**Comment by sfinotto** [comment]
Thanks for adding the tag

It's complex.
I find it useful to know if it's an ""API framework", if it "generates html
in the backend" or not, or of it's  like next and nuxt and I don't know how
to call next and nuxt because they are not meant to build complex apis.

 I'm not qualified to suggest the ideal tags. Maybe you can ask on hacker
news or Reddit.

Maybe just "backend framework" for all. And keeping also the runtime tags
node bun deno. I'm not sure.
