### ISSUE TITLE
Add yamada-ui

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#959]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- A React UI component library that streamlines the development of cutting-edge web applications and websites.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/yamada-ui/yamada-ui

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Component set
- React

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat for the suggestion.

I like the description:

> React UI components of the Yamada, by the Yamada, for the Yamada...

as Yamada is one of the most popular family names here in Japan 😄

**Comment by michaelrambeau** [comment]
The real Yamada is on on _Best of JS_  🥁 

https://bestofjs.org/projects/yamada-ui
