### ISSUE TITLE
Add Vue Clerk

### ISSUE THREAD

**Issue by wobsoriano** [michaelrambeau/bestofjs#966]
**Please briefly describe the project you'd like to add to _Best of JS_?**

Easiest way to add authentication and user management to your Vue application.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/wobsoriano/vue-clerk

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- Vue
- Authentication

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello Robert, thank you for the suggestion, `vue-cleck` will be available on _Best of JS_ very soon.

Do you think we should add https://github.com/clerk/javascript too, since we already have https://bestofjs.org/projects/auth0js ?

**Comment by wobsoriano** [comment]
Thanks Michael and yes I think we should add that!

**Comment by michaelrambeau** [comment]
Thank you for your patience Robert @wobsoriano , `vue-clerk` is available on _Best of JS_:

https://bestofjs.org/projects/vue-clerk
