### ISSUE TITLE
Add es-toolkit

### ISSUE THREAD

**Issue by raon0211** [michaelrambeau/bestofjs#969]
**Please briefly describe the project you'd like to add to _Best of JS_?**

- `es-toolkit` is a modern JavaScript utility library that's 2-3 times faster and up to 97% smaller, a major upgrade to lodash.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

- [https://github.com/toss/es-toolkit](https://github.com/toss/es-toolkit)

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

- Utils

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Hello @raon0211 thank you for the suggestion, `es-toolkit` is available on _Best of JS_, please check:

https://bestofjs.org/projects/es-toolkit
