### ISSUE TITLE
Add `Ezelia/eureca.io` project

### ISSUE THREAD

**Issue by alaa-eddine** [michaelrambeau/bestofjs#98]
https://github.com/Ezelia/eureca.io

eureca.io is a nodejs transparent bidirectional RPC framework .
it's transport agnostic, it can use one of the many available transport layers :  engine.io, sockjs, WebRTC, Faye, raw websocket ...etc

the goal of this framework is to make client <=> server calls transparent, the user don't have to handle all the messaging stuff, he just declare functions in both sides, and cal call them like any local function.

Documentation and tutorials are available here : http://eureca.io/

**Comment by michaelrambeau** [comment]
Hello @alaa-eddine ,
Thank you for the recommendation, the project will be online very soon, under the `realtime` tag.

**Comment by michaelrambeau** [comment]
Hello @alaa-eddine 
It's online, check here: https://bestof.js.org/tags/realtime

**Comment by alaa-eddine** [comment]
Hi @michaelrambeau ,

Thank you for the addition :)
