### ISSUE TITLE
Add immich to Best of JS

### ISSUE THREAD

**Issue by BBlackwo** [michaelrambeau/bestofjs#980]
**Please briefly describe the project you'd like to add to _Best of JS_?**

High performance self-hosted photo and video management solution (think Google Photos, just self hosted)

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/immich-app/immich

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The source code is on GitHub and project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Maybe `image`, `viewer`, `ml`, `ai`?

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

`self-hosted`? Or `open-source-alternative`?

## Additional info

I guess this request is similar to #964. The main difference being it's mostly written in TS/Svelte so it's more likely to qualify? 😁 

<img width="399" alt="image" src="https://github.com/michaelrambeau/bestofjs/assets/7598058/1fe9ddce-b529-4120-b4a8-e3322c482e74">

**Comment by michaelrambeau** [comment]
Thank you Benjamin, `Immich` is available on _Best of JS_, under the new tag "Self-hosted":

https://bestofjs.org/projects/immich
