### ISSUE TITLE
Add webview-bridge

### ISSUE THREAD

**Issue by gronxb** [michaelrambeau/bestofjs#981]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Type-safe integration for React Native WebView and web enables shared state and seamless communication between React Native and web platforms.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/gronxb/webview-bridge

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
`React Native`, `State management`

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
`WebView`,

**Comment by michaelrambeau** [comment]
Hello @gronxb thank you for the suggestion.

`webview-bridge` is available on _Best of JS_, please check: https://bestofjs.org/projects/webview-bridge

I have also added `react-native-webview` as it seems to be a very popular project that `webview-bridge` relies on.
