### ISSUE TITLE
We need Leptos! Plz!

### ISSUE THREAD

**Issue by zhiyanzhaijie** [michaelrambeau/bestofjs#983]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Leptos is a full-stack, isomorphic Rust web framework leveraging fine-grained reactivity to build declarative user interfaces.
**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/leptos-rs/leptos

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
`Web assembly`, `UI framework`, `Rust`
**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
`Signals`

**Comment by michaelrambeau** [comment]
Hello @zhiyanzhaijie thank you for the suggestion, `Leptos` is available on _Best of JS_:

https://bestofjs.org/projects/leptos
