### ISSUE TITLE
Add Zenstack

### ISSUE THREAD

**Issue by xeusteerapat** [michaelrambeau/bestofjs#994]
**Please briefly describe the project you'd like to add to _Best of JS_?**
- Fullstack TypeScript toolkit enhances Prisma ORM with flexible Authorization layer for RBAC/ABAC/PBAC/ReBAC, offering auto-generated type-safe APIs and frontend hooks.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
- https://github.com/zenstackhq/zenstack

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
- Full-stack framework

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you @xeusteerapat `ZenStack` is available on _Best of JS_:

https://bestofjs.org/projects/zenstack

I didn't apply the tag "Full-stack framework" as it's not really a framework by itself, it's more a solution to add auth features to frameworks like Next.js or Nuxt, let me know it it makes sense.
