### ISSUE TITLE
Add Remix Project

### ISSUE THREAD

**Issue by Aniket-Engg** [michaelrambeau/bestofjs#997]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Remix Project is a rich toolset including Remix IDE, a comprehensive smart contract development tool. Remix IDE is used for the entire journey of contract development by users of any knowledge level. It fosters a fast development cycle and has a rich set of plugins with intuitive GUIs. 

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/ethereum/remix-project

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
REACT, Node.js framework, AI

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
Browser based

**Comment by michaelrambeau** [comment]
Hello @Aniket-Engg thank you for the suggestion.

The name of the project is a bit unfortunate because [Remix](https://remix.run/) is one of the most popular full stack frameworks 😅 .

Is it OK to name it `Ethereum Remix Project` to avoid any confusion?

**Comment by michaelrambeau** [comment]
Hello @Aniket-Engg `Ethereum Remix Project` is available on _Best of JS_, please check.


https://bestofjs.org/projects/ethereum-remix-project

**Comment by Aniket-Engg** [comment]
Thanks @michaelrambeau !!!
