### ISSUE TITLE
Add Sailboat UI

### ISSUE THREAD

**Issue by BlazerYoo** [michaelrambeau/bestofjs#998]
**Please briefly describe the project you'd like to add to _Best of JS_?**
Sailboat UI is a modern UI component library for Tailwind CSS with 150+ open-source Tailwind CSS components, making it easy to build products.

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**
https://github.com/sailboatui/sailboatui

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**
Component set, TailwindCSS

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**
Maybe rename `Component set` to `Component library`?

**Comment by michaelrambeau** [comment]
Hello @BlazerYoo thank you for the suggestion.

I'm not sure the project is actively maintained as a dark mode feature was promised in January 2023 (https://github.com/sailboatui/sailboatui/issues/53) but I can add the project to _Best of JS_, OK.

And thank you for the suggestion about the tagging, `Component library` makes more sense than `Component set` 👍 .

**Comment by michaelrambeau** [comment]
Hello @BlazerYoo `Sailboat UI` is available on _Best of JS_, please check:

https://bestofjs.org/projects/sailboat-ui

**Comment by BlazerYoo** [comment]
Hi @michaelrambeau! When I directly go to [https://bestofjs.org/projects/sailboat-ui](https://bestofjs.org/projects/sailboat-ui), I see the following:

<img width="700" alt="image" src="https://github.com/user-attachments/assets/fe15693f-8a1e-4eb0-9af0-46581bb2547b">

But when I search for `Sailboat UI `and navigate to the page through the search results, I see the following:

<img width="700" alt="image" src="https://github.com/user-attachments/assets/28f7a553-b97e-4c77-8c7b-89bdb18d9d9c">

**Comment by michaelrambeau** [comment]
Hello @BlazerYoo I think it was a caching issue as I had the same issue before I made  a change, could you try again?

**Comment by BlazerYoo** [comment]
Thank you @michaelrambeau. Looks good now!
